import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.*;
public class Fruits100SearchNoBoostTester {public static void main(String[] args) throws Exception{
ProjectTester tester = new ProjectTesterImp(); //Instantiate your own ProjectTester instance here
tester.initialize();
tester.crawl("https://people.scs.carleton.ca/~avamckenney/fruits100/N-0.html");
runTest(tester);}public static void runTest(ProjectTester tester) throws Exception{
PrintWriter failOut = new PrintWriter(new FileWriter("Fruits100-SearchNoBoost-failed.txt"));
PrintWriter passOut = new PrintWriter(new FileWriter("Fruits100-SearchNoBoost-passed.txt"));
List<SearchResult> yourResult; 
//Test #409 checking search results for fig lime banana with boost=true
yourResult = tester.search("fig lime banana", false, 100);
TestingTools.checkSearch(yourResult, "fig lime banana",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #409 checking search results for fig lime banana with boost=true");
//Test #410 checking search results for fig with boost=true
yourResult = tester.search("fig", false, 100);
TestingTools.checkSearch(yourResult, "fig",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #410 checking search results for fig with boost=true");
//Test #411 checking search results for fig cherry with boost=true
yourResult = tester.search("fig cherry", false, 100);
TestingTools.checkSearch(yourResult, "fig cherry",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #411 checking search results for fig cherry with boost=true");
//Test #412 checking search results for strawberry with boost=true
yourResult = tester.search("strawberry", false, 100);
TestingTools.checkSearch(yourResult, "strawberry",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #412 checking search results for strawberry with boost=true");
//Test #413 checking search results for apple apricot with boost=true
yourResult = tester.search("apple apricot", false, 100);
TestingTools.checkSearch(yourResult, "apple apricot",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #413 checking search results for apple apricot with boost=true");
//Test #414 checking search results for apricot banana with boost=true
yourResult = tester.search("apricot banana", false, 100);
TestingTools.checkSearch(yourResult, "apricot banana",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #414 checking search results for apricot banana with boost=true");
//Test #415 checking search results for coconut banana apple pear fig with boost=true
yourResult = tester.search("coconut banana apple pear fig", false, 100);
TestingTools.checkSearch(yourResult, "coconut banana apple pear fig",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #415 checking search results for coconut banana apple pear fig with boost=true");
//Test #416 checking search results for coconut papaya kiwi tomato lime with boost=true
yourResult = tester.search("coconut papaya kiwi tomato lime", false, 100);
TestingTools.checkSearch(yourResult, "coconut papaya kiwi tomato lime",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #416 checking search results for coconut papaya kiwi tomato lime with boost=true");
//Test #417 checking search results for tomato banana strawberry strawberry blueberry with boost=true
yourResult = tester.search("tomato banana strawberry strawberry blueberry", false, 100);
TestingTools.checkSearch(yourResult, "tomato banana strawberry strawberry blueberry",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #417 checking search results for tomato banana strawberry strawberry blueberry with boost=true");
//Test #418 checking search results for cherry fig with boost=true
yourResult = tester.search("cherry fig", false, 100);
TestingTools.checkSearch(yourResult, "cherry fig",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #418 checking search results for cherry fig with boost=true");
//Test #419 checking search results for fig peach papaya cherry with boost=true
yourResult = tester.search("fig peach papaya cherry", false, 100);
TestingTools.checkSearch(yourResult, "fig peach papaya cherry",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #419 checking search results for fig peach papaya cherry with boost=true");
//Test #420 checking search results for coconut banana tomato with boost=true
yourResult = tester.search("coconut banana tomato", false, 100);
TestingTools.checkSearch(yourResult, "coconut banana tomato",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #420 checking search results for coconut banana tomato with boost=true");
//Test #421 checking search results for blueberry pear coconut with boost=true
yourResult = tester.search("blueberry pear coconut", false, 100);
TestingTools.checkSearch(yourResult, "blueberry pear coconut",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #421 checking search results for blueberry pear coconut with boost=true");
//Test #422 checking search results for coconut kiwi apricot tomato with boost=true
yourResult = tester.search("coconut kiwi apricot tomato", false, 100);
TestingTools.checkSearch(yourResult, "coconut kiwi apricot tomato",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #422 checking search results for coconut kiwi apricot tomato with boost=true");
//Test #423 checking search results for coconut peach fig with boost=true
yourResult = tester.search("coconut peach fig", false, 100);
TestingTools.checkSearch(yourResult, "coconut peach fig",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #423 checking search results for coconut peach fig with boost=true");
//Test #424 checking search results for cherry banana cherry banana with boost=true
yourResult = tester.search("cherry banana cherry banana", false, 100);
TestingTools.checkSearch(yourResult, "cherry banana cherry banana",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #424 checking search results for cherry banana cherry banana with boost=true");
//Test #425 checking search results for banana lime peach with boost=true
yourResult = tester.search("banana lime peach", false, 100);
TestingTools.checkSearch(yourResult, "banana lime peach",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #425 checking search results for banana lime peach with boost=true");
//Test #426 checking search results for peach with boost=true
yourResult = tester.search("peach", false, 100);
TestingTools.checkSearch(yourResult, "peach",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #426 checking search results for peach with boost=true");
//Test #427 checking search results for apricot apricot coconut pear lime with boost=true
yourResult = tester.search("apricot apricot coconut pear lime", false, 100);
TestingTools.checkSearch(yourResult, "apricot apricot coconut pear lime",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #427 checking search results for apricot apricot coconut pear lime with boost=true");
//Test #428 checking search results for cherry peach peach with boost=true
yourResult = tester.search("cherry peach peach", false, 100);
TestingTools.checkSearch(yourResult, "cherry peach peach",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #428 checking search results for cherry peach peach with boost=true");
//Test #429 checking search results for cherry apricot lime peach with boost=true
yourResult = tester.search("cherry apricot lime peach", false, 100);
TestingTools.checkSearch(yourResult, "cherry apricot lime peach",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #429 checking search results for cherry apricot lime peach with boost=true");
//Test #430 checking search results for banana papaya kiwi lime kiwi with boost=true
yourResult = tester.search("banana papaya kiwi lime kiwi", false, 100);
TestingTools.checkSearch(yourResult, "banana papaya kiwi lime kiwi",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #430 checking search results for banana papaya kiwi lime kiwi with boost=true");
//Test #431 checking search results for cherry kiwi with boost=true
yourResult = tester.search("cherry kiwi", false, 100);
TestingTools.checkSearch(yourResult, "cherry kiwi",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #431 checking search results for cherry kiwi with boost=true");
//Test #432 checking search results for pear with boost=true
yourResult = tester.search("pear", false, 100);
TestingTools.checkSearch(yourResult, "pear",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #432 checking search results for pear with boost=true");
//Test #433 checking search results for banana papaya papaya lime lime with boost=true
yourResult = tester.search("banana papaya papaya lime lime", false, 100);
TestingTools.checkSearch(yourResult, "banana papaya papaya lime lime",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #433 checking search results for banana papaya papaya lime lime with boost=true");
//Test #434 checking search results for pear with boost=true
yourResult = tester.search("pear", false, 100);
TestingTools.checkSearch(yourResult, "pear",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #434 checking search results for pear with boost=true");
//Test #435 checking search results for apricot cherry lime fig papaya with boost=true
yourResult = tester.search("apricot cherry lime fig papaya", false, 100);
TestingTools.checkSearch(yourResult, "apricot cherry lime fig papaya",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #435 checking search results for apricot cherry lime fig papaya with boost=true");
//Test #436 checking search results for lime tomato peach banana tomato with boost=true
yourResult = tester.search("lime tomato peach banana tomato", false, 100);
TestingTools.checkSearch(yourResult, "lime tomato peach banana tomato",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #436 checking search results for lime tomato peach banana tomato with boost=true");
//Test #437 checking search results for pear apricot peach with boost=true
yourResult = tester.search("pear apricot peach", false, 100);
TestingTools.checkSearch(yourResult, "pear apricot peach",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #437 checking search results for pear apricot peach with boost=true");
//Test #438 checking search results for lime fig banana apricot peach with boost=true
yourResult = tester.search("lime fig banana apricot peach", false, 100);
TestingTools.checkSearch(yourResult, "lime fig banana apricot peach",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #438 checking search results for lime fig banana apricot peach with boost=true");
//Test #439 checking search results for lime with boost=true
yourResult = tester.search("lime", false, 100);
TestingTools.checkSearch(yourResult, "lime",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #439 checking search results for lime with boost=true");
//Test #440 checking search results for apricot strawberry with boost=true
yourResult = tester.search("apricot strawberry", false, 100);
TestingTools.checkSearch(yourResult, "apricot strawberry",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #440 checking search results for apricot strawberry with boost=true");
//Test #441 checking search results for apple coconut lime with boost=true
yourResult = tester.search("apple coconut lime", false, 100);
TestingTools.checkSearch(yourResult, "apple coconut lime",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #441 checking search results for apple coconut lime with boost=true");
//Test #442 checking search results for pear kiwi lime peach with boost=true
yourResult = tester.search("pear kiwi lime peach", false, 100);
TestingTools.checkSearch(yourResult, "pear kiwi lime peach",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #442 checking search results for pear kiwi lime peach with boost=true");
//Test #443 checking search results for blueberry strawberry apple kiwi papaya with boost=true
yourResult = tester.search("blueberry strawberry apple kiwi papaya", false, 100);
TestingTools.checkSearch(yourResult, "blueberry strawberry apple kiwi papaya",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #443 checking search results for blueberry strawberry apple kiwi papaya with boost=true");
//Test #444 checking search results for fig with boost=true
yourResult = tester.search("fig", false, 100);
TestingTools.checkSearch(yourResult, "fig",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #444 checking search results for fig with boost=true");
//Test #445 checking search results for banana papaya kiwi apricot apple with boost=true
yourResult = tester.search("banana papaya kiwi apricot apple", false, 100);
TestingTools.checkSearch(yourResult, "banana papaya kiwi apricot apple",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #445 checking search results for banana papaya kiwi apricot apple with boost=true");
//Test #446 checking search results for strawberry blueberry with boost=true
yourResult = tester.search("strawberry blueberry", false, 100);
TestingTools.checkSearch(yourResult, "strawberry blueberry",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #446 checking search results for strawberry blueberry with boost=true");
//Test #447 checking search results for peach with boost=true
yourResult = tester.search("peach", false, 100);
TestingTools.checkSearch(yourResult, "peach",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #447 checking search results for peach with boost=true");
//Test #448 checking search results for lime kiwi with boost=true
yourResult = tester.search("lime kiwi", false, 100);
TestingTools.checkSearch(yourResult, "lime kiwi",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #448 checking search results for lime kiwi with boost=true");
//Test #449 checking search results for banana tomato tomato with boost=true
yourResult = tester.search("banana tomato tomato", false, 100);
TestingTools.checkSearch(yourResult, "banana tomato tomato",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #449 checking search results for banana tomato tomato with boost=true");
//Test #450 checking search results for lime strawberry with boost=true
yourResult = tester.search("lime strawberry", false, 100);
TestingTools.checkSearch(yourResult, "lime strawberry",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #450 checking search results for lime strawberry with boost=true");
//Test #451 checking search results for lime with boost=true
yourResult = tester.search("lime", false, 100);
TestingTools.checkSearch(yourResult, "lime",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #451 checking search results for lime with boost=true");
//Test #452 checking search results for strawberry tomato with boost=true
yourResult = tester.search("strawberry tomato", false, 100);
TestingTools.checkSearch(yourResult, "strawberry tomato",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #452 checking search results for strawberry tomato with boost=true");
//Test #453 checking search results for banana fig banana papaya apple with boost=true
yourResult = tester.search("banana fig banana papaya apple", false, 100);
TestingTools.checkSearch(yourResult, "banana fig banana papaya apple",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #453 checking search results for banana fig banana papaya apple with boost=true");
//Test #454 checking search results for coconut peach strawberry kiwi cherry with boost=true
yourResult = tester.search("coconut peach strawberry kiwi cherry", false, 100);
TestingTools.checkSearch(yourResult, "coconut peach strawberry kiwi cherry",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #454 checking search results for coconut peach strawberry kiwi cherry with boost=true");
//Test #455 checking search results for pear lime tomato banana with boost=true
yourResult = tester.search("pear lime tomato banana", false, 100);
TestingTools.checkSearch(yourResult, "pear lime tomato banana",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #455 checking search results for pear lime tomato banana with boost=true");
//Test #456 checking search results for apricot kiwi lime with boost=true
yourResult = tester.search("apricot kiwi lime", false, 100);
TestingTools.checkSearch(yourResult, "apricot kiwi lime",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #456 checking search results for apricot kiwi lime with boost=true");
//Test #457 checking search results for strawberry lime apricot lime fig with boost=true
yourResult = tester.search("strawberry lime apricot lime fig", false, 100);
TestingTools.checkSearch(yourResult, "strawberry lime apricot lime fig",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #457 checking search results for strawberry lime apricot lime fig with boost=true");
//Test #458 checking search results for apple cherry pear kiwi with boost=true
yourResult = tester.search("apple cherry pear kiwi", false, 100);
TestingTools.checkSearch(yourResult, "apple cherry pear kiwi",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #458 checking search results for apple cherry pear kiwi with boost=true");
//Test #459 checking search results for pear kiwi with boost=true
yourResult = tester.search("pear kiwi", false, 100);
TestingTools.checkSearch(yourResult, "pear kiwi",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #459 checking search results for pear kiwi with boost=true");
//Test #460 checking search results for lime blueberry papaya with boost=true
yourResult = tester.search("lime blueberry papaya", false, 100);
TestingTools.checkSearch(yourResult, "lime blueberry papaya",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #460 checking search results for lime blueberry papaya with boost=true");
//Test #461 checking search results for cherry with boost=true
yourResult = tester.search("cherry", false, 100);
TestingTools.checkSearch(yourResult, "cherry",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #461 checking search results for cherry with boost=true");
//Test #462 checking search results for kiwi tomato cherry kiwi cherry with boost=true
yourResult = tester.search("kiwi tomato cherry kiwi cherry", false, 100);
TestingTools.checkSearch(yourResult, "kiwi tomato cherry kiwi cherry",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #462 checking search results for kiwi tomato cherry kiwi cherry with boost=true");
//Test #463 checking search results for fig strawberry cherry with boost=true
yourResult = tester.search("fig strawberry cherry", false, 100);
TestingTools.checkSearch(yourResult, "fig strawberry cherry",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #463 checking search results for fig strawberry cherry with boost=true");
//Test #464 checking search results for peach apricot apricot papaya with boost=true
yourResult = tester.search("peach apricot apricot papaya", false, 100);
TestingTools.checkSearch(yourResult, "peach apricot apricot papaya",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #464 checking search results for peach apricot apricot papaya with boost=true");
//Test #465 checking search results for banana apple apple pear with boost=true
yourResult = tester.search("banana apple apple pear", false, 100);
TestingTools.checkSearch(yourResult, "banana apple apple pear",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #465 checking search results for banana apple apple pear with boost=true");
//Test #466 checking search results for apple fig with boost=true
yourResult = tester.search("apple fig", false, 100);
TestingTools.checkSearch(yourResult, "apple fig",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #466 checking search results for apple fig with boost=true");
//Test #467 checking search results for strawberry cherry with boost=true
yourResult = tester.search("strawberry cherry", false, 100);
TestingTools.checkSearch(yourResult, "strawberry cherry",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #467 checking search results for strawberry cherry with boost=true");
//Test #468 checking search results for papaya blueberry blueberry with boost=true
yourResult = tester.search("papaya blueberry blueberry", false, 100);
TestingTools.checkSearch(yourResult, "papaya blueberry blueberry",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #468 checking search results for papaya blueberry blueberry with boost=true");
//Test #469 checking search results for cherry with boost=true
yourResult = tester.search("cherry", false, 100);
TestingTools.checkSearch(yourResult, "cherry",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #469 checking search results for cherry with boost=true");
//Test #470 checking search results for kiwi blueberry cherry tomato with boost=true
yourResult = tester.search("kiwi blueberry cherry tomato", false, 100);
TestingTools.checkSearch(yourResult, "kiwi blueberry cherry tomato",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #470 checking search results for kiwi blueberry cherry tomato with boost=true");
//Test #471 checking search results for fig kiwi kiwi papaya with boost=true
yourResult = tester.search("fig kiwi kiwi papaya", false, 100);
TestingTools.checkSearch(yourResult, "fig kiwi kiwi papaya",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #471 checking search results for fig kiwi kiwi papaya with boost=true");
//Test #472 checking search results for kiwi apple tomato with boost=true
yourResult = tester.search("kiwi apple tomato", false, 100);
TestingTools.checkSearch(yourResult, "kiwi apple tomato",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #472 checking search results for kiwi apple tomato with boost=true");
//Test #473 checking search results for banana peach kiwi with boost=true
yourResult = tester.search("banana peach kiwi", false, 100);
TestingTools.checkSearch(yourResult, "banana peach kiwi",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #473 checking search results for banana peach kiwi with boost=true");
//Test #474 checking search results for apple pear coconut apple with boost=true
yourResult = tester.search("apple pear coconut apple", false, 100);
TestingTools.checkSearch(yourResult, "apple pear coconut apple",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #474 checking search results for apple pear coconut apple with boost=true");
//Test #475 checking search results for coconut pear pear banana with boost=true
yourResult = tester.search("coconut pear pear banana", false, 100);
TestingTools.checkSearch(yourResult, "coconut pear pear banana",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #475 checking search results for coconut pear pear banana with boost=true");
//Test #476 checking search results for coconut papaya coconut with boost=true
yourResult = tester.search("coconut papaya coconut", false, 100);
TestingTools.checkSearch(yourResult, "coconut papaya coconut",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #476 checking search results for coconut papaya coconut with boost=true");
//Test #477 checking search results for pear kiwi blueberry with boost=true
yourResult = tester.search("pear kiwi blueberry", false, 100);
TestingTools.checkSearch(yourResult, "pear kiwi blueberry",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #477 checking search results for pear kiwi blueberry with boost=true");
//Test #478 checking search results for blueberry cherry with boost=true
yourResult = tester.search("blueberry cherry", false, 100);
TestingTools.checkSearch(yourResult, "blueberry cherry",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #478 checking search results for blueberry cherry with boost=true");
//Test #479 checking search results for apricot blueberry coconut with boost=true
yourResult = tester.search("apricot blueberry coconut", false, 100);
TestingTools.checkSearch(yourResult, "apricot blueberry coconut",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #479 checking search results for apricot blueberry coconut with boost=true");
//Test #480 checking search results for papaya peach papaya fig with boost=true
yourResult = tester.search("papaya peach papaya fig", false, 100);
TestingTools.checkSearch(yourResult, "papaya peach papaya fig",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #480 checking search results for papaya peach papaya fig with boost=true");
//Test #481 checking search results for apple tomato cherry with boost=true
yourResult = tester.search("apple tomato cherry", false, 100);
TestingTools.checkSearch(yourResult, "apple tomato cherry",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #481 checking search results for apple tomato cherry with boost=true");
//Test #482 checking search results for banana blueberry lime coconut lime with boost=true
yourResult = tester.search("banana blueberry lime coconut lime", false, 100);
TestingTools.checkSearch(yourResult, "banana blueberry lime coconut lime",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #482 checking search results for banana blueberry lime coconut lime with boost=true");
//Test #483 checking search results for banana apricot banana with boost=true
yourResult = tester.search("banana apricot banana", false, 100);
TestingTools.checkSearch(yourResult, "banana apricot banana",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #483 checking search results for banana apricot banana with boost=true");
//Test #484 checking search results for coconut apple with boost=true
yourResult = tester.search("coconut apple", false, 100);
TestingTools.checkSearch(yourResult, "coconut apple",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #484 checking search results for coconut apple with boost=true");
//Test #485 checking search results for apricot with boost=true
yourResult = tester.search("apricot", false, 100);
TestingTools.checkSearch(yourResult, "apricot",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #485 checking search results for apricot with boost=true");
//Test #486 checking search results for apricot apricot with boost=true
yourResult = tester.search("apricot apricot", false, 100);
TestingTools.checkSearch(yourResult, "apricot apricot",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #486 checking search results for apricot apricot with boost=true");
//Test #487 checking search results for apricot with boost=true
yourResult = tester.search("apricot", false, 100);
TestingTools.checkSearch(yourResult, "apricot",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #487 checking search results for apricot with boost=true");
//Test #488 checking search results for strawberry with boost=true
yourResult = tester.search("strawberry", false, 100);
TestingTools.checkSearch(yourResult, "strawberry",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #488 checking search results for strawberry with boost=true");
//Test #489 checking search results for tomato lime apricot banana with boost=true
yourResult = tester.search("tomato lime apricot banana", false, 100);
TestingTools.checkSearch(yourResult, "tomato lime apricot banana",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #489 checking search results for tomato lime apricot banana with boost=true");
//Test #490 checking search results for apricot apricot papaya with boost=true
yourResult = tester.search("apricot apricot papaya", false, 100);
TestingTools.checkSearch(yourResult, "apricot apricot papaya",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #490 checking search results for apricot apricot papaya with boost=true");
//Test #491 checking search results for banana peach kiwi strawberry with boost=true
yourResult = tester.search("banana peach kiwi strawberry", false, 100);
TestingTools.checkSearch(yourResult, "banana peach kiwi strawberry",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #491 checking search results for banana peach kiwi strawberry with boost=true");
//Test #492 checking search results for cherry pear with boost=true
yourResult = tester.search("cherry pear", false, 100);
TestingTools.checkSearch(yourResult, "cherry pear",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #492 checking search results for cherry pear with boost=true");
//Test #493 checking search results for apricot apricot apricot peach strawberry with boost=true
yourResult = tester.search("apricot apricot apricot peach strawberry", false, 100);
TestingTools.checkSearch(yourResult, "apricot apricot apricot peach strawberry",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #493 checking search results for apricot apricot apricot peach strawberry with boost=true");
//Test #494 checking search results for blueberry peach tomato lime apple with boost=true
yourResult = tester.search("blueberry peach tomato lime apple", false, 100);
TestingTools.checkSearch(yourResult, "blueberry peach tomato lime apple",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #494 checking search results for blueberry peach tomato lime apple with boost=true");
//Test #495 checking search results for papaya banana with boost=true
yourResult = tester.search("papaya banana", false, 100);
TestingTools.checkSearch(yourResult, "papaya banana",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #495 checking search results for papaya banana with boost=true");
//Test #496 checking search results for fig apricot coconut banana with boost=true
yourResult = tester.search("fig apricot coconut banana", false, 100);
TestingTools.checkSearch(yourResult, "fig apricot coconut banana",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #496 checking search results for fig apricot coconut banana with boost=true");
//Test #497 checking search results for kiwi tomato lime apple with boost=true
yourResult = tester.search("kiwi tomato lime apple", false, 100);
TestingTools.checkSearch(yourResult, "kiwi tomato lime apple",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #497 checking search results for kiwi tomato lime apple with boost=true");
//Test #498 checking search results for peach with boost=true
yourResult = tester.search("peach", false, 100);
TestingTools.checkSearch(yourResult, "peach",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #498 checking search results for peach with boost=true");
//Test #499 checking search results for blueberry lime lime apricot coconut with boost=true
yourResult = tester.search("blueberry lime lime apricot coconut", false, 100);
TestingTools.checkSearch(yourResult, "blueberry lime lime apricot coconut",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #499 checking search results for blueberry lime lime apricot coconut with boost=true");
//Test #500 checking search results for kiwi with boost=true
yourResult = tester.search("kiwi", false, 100);
TestingTools.checkSearch(yourResult, "kiwi",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #500 checking search results for kiwi with boost=true");
//Test #501 checking search results for tomato coconut strawberry with boost=true
yourResult = tester.search("tomato coconut strawberry", false, 100);
TestingTools.checkSearch(yourResult, "tomato coconut strawberry",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #501 checking search results for tomato coconut strawberry with boost=true");
//Test #502 checking search results for banana apricot blueberry with boost=true
yourResult = tester.search("banana apricot blueberry", false, 100);
TestingTools.checkSearch(yourResult, "banana apricot blueberry",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #502 checking search results for banana apricot blueberry with boost=true");
//Test #503 checking search results for coconut cherry with boost=true
yourResult = tester.search("coconut cherry", false, 100);
TestingTools.checkSearch(yourResult, "coconut cherry",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #503 checking search results for coconut cherry with boost=true");
//Test #504 checking search results for lime with boost=true
yourResult = tester.search("lime", false, 100);
TestingTools.checkSearch(yourResult, "lime",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #504 checking search results for lime with boost=true");
//Test #505 checking search results for tomato cherry peach with boost=true
yourResult = tester.search("tomato cherry peach", false, 100);
TestingTools.checkSearch(yourResult, "tomato cherry peach",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #505 checking search results for tomato cherry peach with boost=true");
//Test #506 checking search results for papaya coconut with boost=true
yourResult = tester.search("papaya coconut", false, 100);
TestingTools.checkSearch(yourResult, "papaya coconut",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #506 checking search results for papaya coconut with boost=true");
//Test #507 checking search results for strawberry blueberry pear with boost=true
yourResult = tester.search("strawberry blueberry pear", false, 100);
TestingTools.checkSearch(yourResult, "strawberry blueberry pear",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #507 checking search results for strawberry blueberry pear with boost=true");
//Test #508 checking search results for papaya pear with boost=true
yourResult = tester.search("papaya pear", false, 100);
TestingTools.checkSearch(yourResult, "papaya pear",false, passOut, failOut, "Fruits100SearchNoBoostTester", "Test #508 checking search results for papaya pear with boost=true");
failOut.close();
passOut.close();
}
}
