import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.*;
public class Fruits25SearchBoostTester {public static void main(String[] args) throws Exception{
ProjectTester tester = new ProjectTesterImp(); //Instantiate your own ProjectTester instance here
tester.initialize();
tester.crawl("https://people.scs.carleton.ca/~avamckenney/fruits25/N-0.html");
runTest(tester);}public static void runTest(ProjectTester tester) throws Exception{
PrintWriter failOut = new PrintWriter(new FileWriter("Fruits25-SearchBoost-failed.txt"));
PrintWriter passOut = new PrintWriter(new FileWriter("Fruits25-SearchBoost-passed.txt"));
List<SearchResult> yourResult; 
//Test #434 checking search results for pear with boost=true
yourResult = tester.search("pear", true, 25);
TestingTools.checkSearch(yourResult, "pear",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #434 checking search results for pear with boost=true");
//Test #435 checking search results for fig pear fig apricot with boost=true
yourResult = tester.search("fig pear fig apricot", true, 25);
TestingTools.checkSearch(yourResult, "fig pear fig apricot",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #435 checking search results for fig pear fig apricot with boost=true");
//Test #436 checking search results for banana strawberry apple with boost=true
yourResult = tester.search("banana strawberry apple", true, 25);
TestingTools.checkSearch(yourResult, "banana strawberry apple",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #436 checking search results for banana strawberry apple with boost=true");
//Test #437 checking search results for coconut blueberry lime with boost=true
yourResult = tester.search("coconut blueberry lime", true, 25);
TestingTools.checkSearch(yourResult, "coconut blueberry lime",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #437 checking search results for coconut blueberry lime with boost=true");
//Test #438 checking search results for kiwi apricot tomato with boost=true
yourResult = tester.search("kiwi apricot tomato", true, 25);
TestingTools.checkSearch(yourResult, "kiwi apricot tomato",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #438 checking search results for kiwi apricot tomato with boost=true");
//Test #439 checking search results for blueberry coconut lime banana blueberry with boost=true
yourResult = tester.search("blueberry coconut lime banana blueberry", true, 25);
TestingTools.checkSearch(yourResult, "blueberry coconut lime banana blueberry",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #439 checking search results for blueberry coconut lime banana blueberry with boost=true");
//Test #440 checking search results for banana pear blueberry with boost=true
yourResult = tester.search("banana pear blueberry", true, 25);
TestingTools.checkSearch(yourResult, "banana pear blueberry",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #440 checking search results for banana pear blueberry with boost=true");
//Test #441 checking search results for strawberry kiwi coconut fig with boost=true
yourResult = tester.search("strawberry kiwi coconut fig", true, 25);
TestingTools.checkSearch(yourResult, "strawberry kiwi coconut fig",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #441 checking search results for strawberry kiwi coconut fig with boost=true");
//Test #442 checking search results for blueberry kiwi banana banana pear with boost=true
yourResult = tester.search("blueberry kiwi banana banana pear", true, 25);
TestingTools.checkSearch(yourResult, "blueberry kiwi banana banana pear",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #442 checking search results for blueberry kiwi banana banana pear with boost=true");
//Test #443 checking search results for tomato apricot coconut apricot lime with boost=true
yourResult = tester.search("tomato apricot coconut apricot lime", true, 25);
TestingTools.checkSearch(yourResult, "tomato apricot coconut apricot lime",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #443 checking search results for tomato apricot coconut apricot lime with boost=true");
//Test #444 checking search results for apricot coconut with boost=true
yourResult = tester.search("apricot coconut", true, 25);
TestingTools.checkSearch(yourResult, "apricot coconut",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #444 checking search results for apricot coconut with boost=true");
//Test #445 checking search results for apricot apricot tomato cherry apricot with boost=true
yourResult = tester.search("apricot apricot tomato cherry apricot", true, 25);
TestingTools.checkSearch(yourResult, "apricot apricot tomato cherry apricot",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #445 checking search results for apricot apricot tomato cherry apricot with boost=true");
//Test #446 checking search results for coconut banana with boost=true
yourResult = tester.search("coconut banana", true, 25);
TestingTools.checkSearch(yourResult, "coconut banana",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #446 checking search results for coconut banana with boost=true");
//Test #447 checking search results for blueberry blueberry with boost=true
yourResult = tester.search("blueberry blueberry", true, 25);
TestingTools.checkSearch(yourResult, "blueberry blueberry",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #447 checking search results for blueberry blueberry with boost=true");
//Test #448 checking search results for apricot blueberry blueberry kiwi pear with boost=true
yourResult = tester.search("apricot blueberry blueberry kiwi pear", true, 25);
TestingTools.checkSearch(yourResult, "apricot blueberry blueberry kiwi pear",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #448 checking search results for apricot blueberry blueberry kiwi pear with boost=true");
//Test #449 checking search results for apple coconut pear blueberry blueberry with boost=true
yourResult = tester.search("apple coconut pear blueberry blueberry", true, 25);
TestingTools.checkSearch(yourResult, "apple coconut pear blueberry blueberry",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #449 checking search results for apple coconut pear blueberry blueberry with boost=true");
//Test #450 checking search results for cherry tomato fig with boost=true
yourResult = tester.search("cherry tomato fig", true, 25);
TestingTools.checkSearch(yourResult, "cherry tomato fig",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #450 checking search results for cherry tomato fig with boost=true");
//Test #451 checking search results for coconut lime with boost=true
yourResult = tester.search("coconut lime", true, 25);
TestingTools.checkSearch(yourResult, "coconut lime",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #451 checking search results for coconut lime with boost=true");
//Test #452 checking search results for coconut with boost=true
yourResult = tester.search("coconut", true, 25);
TestingTools.checkSearch(yourResult, "coconut",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #452 checking search results for coconut with boost=true");
//Test #453 checking search results for apricot papaya papaya with boost=true
yourResult = tester.search("apricot papaya papaya", true, 25);
TestingTools.checkSearch(yourResult, "apricot papaya papaya",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #453 checking search results for apricot papaya papaya with boost=true");
//Test #454 checking search results for lime coconut pear with boost=true
yourResult = tester.search("lime coconut pear", true, 25);
TestingTools.checkSearch(yourResult, "lime coconut pear",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #454 checking search results for lime coconut pear with boost=true");
//Test #455 checking search results for blueberry with boost=true
yourResult = tester.search("blueberry", true, 25);
TestingTools.checkSearch(yourResult, "blueberry",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #455 checking search results for blueberry with boost=true");
//Test #456 checking search results for strawberry apricot with boost=true
yourResult = tester.search("strawberry apricot", true, 25);
TestingTools.checkSearch(yourResult, "strawberry apricot",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #456 checking search results for strawberry apricot with boost=true");
//Test #457 checking search results for tomato banana cherry fig with boost=true
yourResult = tester.search("tomato banana cherry fig", true, 25);
TestingTools.checkSearch(yourResult, "tomato banana cherry fig",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #457 checking search results for tomato banana cherry fig with boost=true");
//Test #458 checking search results for pear with boost=true
yourResult = tester.search("pear", true, 25);
TestingTools.checkSearch(yourResult, "pear",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #458 checking search results for pear with boost=true");
//Test #459 checking search results for kiwi blueberry banana with boost=true
yourResult = tester.search("kiwi blueberry banana", true, 25);
TestingTools.checkSearch(yourResult, "kiwi blueberry banana",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #459 checking search results for kiwi blueberry banana with boost=true");
//Test #460 checking search results for fig apricot banana apple with boost=true
yourResult = tester.search("fig apricot banana apple", true, 25);
TestingTools.checkSearch(yourResult, "fig apricot banana apple",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #460 checking search results for fig apricot banana apple with boost=true");
//Test #461 checking search results for apple fig banana with boost=true
yourResult = tester.search("apple fig banana", true, 25);
TestingTools.checkSearch(yourResult, "apple fig banana",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #461 checking search results for apple fig banana with boost=true");
//Test #462 checking search results for cherry peach apricot with boost=true
yourResult = tester.search("cherry peach apricot", true, 25);
TestingTools.checkSearch(yourResult, "cherry peach apricot",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #462 checking search results for cherry peach apricot with boost=true");
//Test #463 checking search results for lime tomato banana with boost=true
yourResult = tester.search("lime tomato banana", true, 25);
TestingTools.checkSearch(yourResult, "lime tomato banana",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #463 checking search results for lime tomato banana with boost=true");
//Test #464 checking search results for coconut with boost=true
yourResult = tester.search("coconut", true, 25);
TestingTools.checkSearch(yourResult, "coconut",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #464 checking search results for coconut with boost=true");
//Test #465 checking search results for coconut apricot apple apple with boost=true
yourResult = tester.search("coconut apricot apple apple", true, 25);
TestingTools.checkSearch(yourResult, "coconut apricot apple apple",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #465 checking search results for coconut apricot apple apple with boost=true");
//Test #466 checking search results for apple peach tomato lime with boost=true
yourResult = tester.search("apple peach tomato lime", true, 25);
TestingTools.checkSearch(yourResult, "apple peach tomato lime",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #466 checking search results for apple peach tomato lime with boost=true");
//Test #467 checking search results for blueberry fig coconut fig with boost=true
yourResult = tester.search("blueberry fig coconut fig", true, 25);
TestingTools.checkSearch(yourResult, "blueberry fig coconut fig",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #467 checking search results for blueberry fig coconut fig with boost=true");
//Test #468 checking search results for peach blueberry coconut fig with boost=true
yourResult = tester.search("peach blueberry coconut fig", true, 25);
TestingTools.checkSearch(yourResult, "peach blueberry coconut fig",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #468 checking search results for peach blueberry coconut fig with boost=true");
//Test #469 checking search results for coconut fig with boost=true
yourResult = tester.search("coconut fig", true, 25);
TestingTools.checkSearch(yourResult, "coconut fig",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #469 checking search results for coconut fig with boost=true");
//Test #470 checking search results for blueberry with boost=true
yourResult = tester.search("blueberry", true, 25);
TestingTools.checkSearch(yourResult, "blueberry",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #470 checking search results for blueberry with boost=true");
//Test #471 checking search results for coconut coconut coconut papaya with boost=true
yourResult = tester.search("coconut coconut coconut papaya", true, 25);
TestingTools.checkSearch(yourResult, "coconut coconut coconut papaya",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #471 checking search results for coconut coconut coconut papaya with boost=true");
//Test #472 checking search results for lime fig lime with boost=true
yourResult = tester.search("lime fig lime", true, 25);
TestingTools.checkSearch(yourResult, "lime fig lime",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #472 checking search results for lime fig lime with boost=true");
//Test #473 checking search results for pear peach pear peach pear with boost=true
yourResult = tester.search("pear peach pear peach pear", true, 25);
TestingTools.checkSearch(yourResult, "pear peach pear peach pear",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #473 checking search results for pear peach pear peach pear with boost=true");
//Test #474 checking search results for apricot blueberry cherry with boost=true
yourResult = tester.search("apricot blueberry cherry", true, 25);
TestingTools.checkSearch(yourResult, "apricot blueberry cherry",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #474 checking search results for apricot blueberry cherry with boost=true");
//Test #475 checking search results for peach lime apricot with boost=true
yourResult = tester.search("peach lime apricot", true, 25);
TestingTools.checkSearch(yourResult, "peach lime apricot",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #475 checking search results for peach lime apricot with boost=true");
//Test #476 checking search results for coconut with boost=true
yourResult = tester.search("coconut", true, 25);
TestingTools.checkSearch(yourResult, "coconut",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #476 checking search results for coconut with boost=true");
//Test #477 checking search results for lime peach blueberry papaya papaya with boost=true
yourResult = tester.search("lime peach blueberry papaya papaya", true, 25);
TestingTools.checkSearch(yourResult, "lime peach blueberry papaya papaya",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #477 checking search results for lime peach blueberry papaya papaya with boost=true");
//Test #478 checking search results for lime tomato coconut cherry blueberry with boost=true
yourResult = tester.search("lime tomato coconut cherry blueberry", true, 25);
TestingTools.checkSearch(yourResult, "lime tomato coconut cherry blueberry",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #478 checking search results for lime tomato coconut cherry blueberry with boost=true");
//Test #479 checking search results for apple kiwi peach coconut pear with boost=true
yourResult = tester.search("apple kiwi peach coconut pear", true, 25);
TestingTools.checkSearch(yourResult, "apple kiwi peach coconut pear",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #479 checking search results for apple kiwi peach coconut pear with boost=true");
//Test #480 checking search results for blueberry cherry tomato banana blueberry with boost=true
yourResult = tester.search("blueberry cherry tomato banana blueberry", true, 25);
TestingTools.checkSearch(yourResult, "blueberry cherry tomato banana blueberry",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #480 checking search results for blueberry cherry tomato banana blueberry with boost=true");
//Test #481 checking search results for kiwi kiwi peach apple with boost=true
yourResult = tester.search("kiwi kiwi peach apple", true, 25);
TestingTools.checkSearch(yourResult, "kiwi kiwi peach apple",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #481 checking search results for kiwi kiwi peach apple with boost=true");
//Test #482 checking search results for apricot coconut apricot kiwi with boost=true
yourResult = tester.search("apricot coconut apricot kiwi", true, 25);
TestingTools.checkSearch(yourResult, "apricot coconut apricot kiwi",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #482 checking search results for apricot coconut apricot kiwi with boost=true");
//Test #483 checking search results for pear with boost=true
yourResult = tester.search("pear", true, 25);
TestingTools.checkSearch(yourResult, "pear",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #483 checking search results for pear with boost=true");
//Test #484 checking search results for fig tomato with boost=true
yourResult = tester.search("fig tomato", true, 25);
TestingTools.checkSearch(yourResult, "fig tomato",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #484 checking search results for fig tomato with boost=true");
//Test #485 checking search results for apricot papaya tomato tomato with boost=true
yourResult = tester.search("apricot papaya tomato tomato", true, 25);
TestingTools.checkSearch(yourResult, "apricot papaya tomato tomato",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #485 checking search results for apricot papaya tomato tomato with boost=true");
//Test #486 checking search results for blueberry banana papaya papaya apple with boost=true
yourResult = tester.search("blueberry banana papaya papaya apple", true, 25);
TestingTools.checkSearch(yourResult, "blueberry banana papaya papaya apple",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #486 checking search results for blueberry banana papaya papaya apple with boost=true");
//Test #487 checking search results for banana blueberry strawberry with boost=true
yourResult = tester.search("banana blueberry strawberry", true, 25);
TestingTools.checkSearch(yourResult, "banana blueberry strawberry",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #487 checking search results for banana blueberry strawberry with boost=true");
//Test #488 checking search results for apple with boost=true
yourResult = tester.search("apple", true, 25);
TestingTools.checkSearch(yourResult, "apple",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #488 checking search results for apple with boost=true");
//Test #489 checking search results for coconut peach strawberry with boost=true
yourResult = tester.search("coconut peach strawberry", true, 25);
TestingTools.checkSearch(yourResult, "coconut peach strawberry",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #489 checking search results for coconut peach strawberry with boost=true");
//Test #490 checking search results for banana papaya with boost=true
yourResult = tester.search("banana papaya", true, 25);
TestingTools.checkSearch(yourResult, "banana papaya",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #490 checking search results for banana papaya with boost=true");
//Test #491 checking search results for coconut coconut papaya apple kiwi with boost=true
yourResult = tester.search("coconut coconut papaya apple kiwi", true, 25);
TestingTools.checkSearch(yourResult, "coconut coconut papaya apple kiwi",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #491 checking search results for coconut coconut papaya apple kiwi with boost=true");
//Test #492 checking search results for lime apricot coconut with boost=true
yourResult = tester.search("lime apricot coconut", true, 25);
TestingTools.checkSearch(yourResult, "lime apricot coconut",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #492 checking search results for lime apricot coconut with boost=true");
//Test #493 checking search results for blueberry blueberry blueberry strawberry coconut with boost=true
yourResult = tester.search("blueberry blueberry blueberry strawberry coconut", true, 25);
TestingTools.checkSearch(yourResult, "blueberry blueberry blueberry strawberry coconut",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #493 checking search results for blueberry blueberry blueberry strawberry coconut with boost=true");
//Test #494 checking search results for apple fig kiwi cherry tomato with boost=true
yourResult = tester.search("apple fig kiwi cherry tomato", true, 25);
TestingTools.checkSearch(yourResult, "apple fig kiwi cherry tomato",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #494 checking search results for apple fig kiwi cherry tomato with boost=true");
//Test #495 checking search results for pear strawberry lime with boost=true
yourResult = tester.search("pear strawberry lime", true, 25);
TestingTools.checkSearch(yourResult, "pear strawberry lime",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #495 checking search results for pear strawberry lime with boost=true");
//Test #496 checking search results for tomato pear with boost=true
yourResult = tester.search("tomato pear", true, 25);
TestingTools.checkSearch(yourResult, "tomato pear",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #496 checking search results for tomato pear with boost=true");
//Test #497 checking search results for strawberry apricot kiwi with boost=true
yourResult = tester.search("strawberry apricot kiwi", true, 25);
TestingTools.checkSearch(yourResult, "strawberry apricot kiwi",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #497 checking search results for strawberry apricot kiwi with boost=true");
//Test #498 checking search results for pear papaya with boost=true
yourResult = tester.search("pear papaya", true, 25);
TestingTools.checkSearch(yourResult, "pear papaya",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #498 checking search results for pear papaya with boost=true");
//Test #499 checking search results for pear coconut coconut tomato with boost=true
yourResult = tester.search("pear coconut coconut tomato", true, 25);
TestingTools.checkSearch(yourResult, "pear coconut coconut tomato",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #499 checking search results for pear coconut coconut tomato with boost=true");
//Test #500 checking search results for kiwi cherry strawberry cherry with boost=true
yourResult = tester.search("kiwi cherry strawberry cherry", true, 25);
TestingTools.checkSearch(yourResult, "kiwi cherry strawberry cherry",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #500 checking search results for kiwi cherry strawberry cherry with boost=true");
//Test #501 checking search results for coconut with boost=true
yourResult = tester.search("coconut", true, 25);
TestingTools.checkSearch(yourResult, "coconut",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #501 checking search results for coconut with boost=true");
//Test #502 checking search results for fig kiwi fig with boost=true
yourResult = tester.search("fig kiwi fig", true, 25);
TestingTools.checkSearch(yourResult, "fig kiwi fig",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #502 checking search results for fig kiwi fig with boost=true");
//Test #503 checking search results for blueberry pear apricot with boost=true
yourResult = tester.search("blueberry pear apricot", true, 25);
TestingTools.checkSearch(yourResult, "blueberry pear apricot",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #503 checking search results for blueberry pear apricot with boost=true");
//Test #504 checking search results for tomato apple with boost=true
yourResult = tester.search("tomato apple", true, 25);
TestingTools.checkSearch(yourResult, "tomato apple",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #504 checking search results for tomato apple with boost=true");
//Test #505 checking search results for apricot with boost=true
yourResult = tester.search("apricot", true, 25);
TestingTools.checkSearch(yourResult, "apricot",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #505 checking search results for apricot with boost=true");
//Test #506 checking search results for apple lime kiwi with boost=true
yourResult = tester.search("apple lime kiwi", true, 25);
TestingTools.checkSearch(yourResult, "apple lime kiwi",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #506 checking search results for apple lime kiwi with boost=true");
//Test #507 checking search results for banana with boost=true
yourResult = tester.search("banana", true, 25);
TestingTools.checkSearch(yourResult, "banana",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #507 checking search results for banana with boost=true");
//Test #508 checking search results for fig papaya coconut banana with boost=true
yourResult = tester.search("fig papaya coconut banana", true, 25);
TestingTools.checkSearch(yourResult, "fig papaya coconut banana",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #508 checking search results for fig papaya coconut banana with boost=true");
//Test #509 checking search results for coconut peach tomato apple peach with boost=true
yourResult = tester.search("coconut peach tomato apple peach", true, 25);
TestingTools.checkSearch(yourResult, "coconut peach tomato apple peach",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #509 checking search results for coconut peach tomato apple peach with boost=true");
//Test #510 checking search results for lime kiwi cherry apple with boost=true
yourResult = tester.search("lime kiwi cherry apple", true, 25);
TestingTools.checkSearch(yourResult, "lime kiwi cherry apple",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #510 checking search results for lime kiwi cherry apple with boost=true");
//Test #511 checking search results for kiwi tomato blueberry with boost=true
yourResult = tester.search("kiwi tomato blueberry", true, 25);
TestingTools.checkSearch(yourResult, "kiwi tomato blueberry",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #511 checking search results for kiwi tomato blueberry with boost=true");
//Test #512 checking search results for strawberry fig strawberry tomato with boost=true
yourResult = tester.search("strawberry fig strawberry tomato", true, 25);
TestingTools.checkSearch(yourResult, "strawberry fig strawberry tomato",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #512 checking search results for strawberry fig strawberry tomato with boost=true");
//Test #513 checking search results for lime banana apple lime with boost=true
yourResult = tester.search("lime banana apple lime", true, 25);
TestingTools.checkSearch(yourResult, "lime banana apple lime",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #513 checking search results for lime banana apple lime with boost=true");
//Test #514 checking search results for pear fig with boost=true
yourResult = tester.search("pear fig", true, 25);
TestingTools.checkSearch(yourResult, "pear fig",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #514 checking search results for pear fig with boost=true");
//Test #515 checking search results for kiwi apricot apple with boost=true
yourResult = tester.search("kiwi apricot apple", true, 25);
TestingTools.checkSearch(yourResult, "kiwi apricot apple",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #515 checking search results for kiwi apricot apple with boost=true");
//Test #516 checking search results for tomato kiwi with boost=true
yourResult = tester.search("tomato kiwi", true, 25);
TestingTools.checkSearch(yourResult, "tomato kiwi",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #516 checking search results for tomato kiwi with boost=true");
//Test #517 checking search results for lime banana pear pear with boost=true
yourResult = tester.search("lime banana pear pear", true, 25);
TestingTools.checkSearch(yourResult, "lime banana pear pear",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #517 checking search results for lime banana pear pear with boost=true");
//Test #518 checking search results for fig banana fig fig banana with boost=true
yourResult = tester.search("fig banana fig fig banana", true, 25);
TestingTools.checkSearch(yourResult, "fig banana fig fig banana",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #518 checking search results for fig banana fig fig banana with boost=true");
//Test #519 checking search results for lime coconut with boost=true
yourResult = tester.search("lime coconut", true, 25);
TestingTools.checkSearch(yourResult, "lime coconut",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #519 checking search results for lime coconut with boost=true");
//Test #520 checking search results for blueberry with boost=true
yourResult = tester.search("blueberry", true, 25);
TestingTools.checkSearch(yourResult, "blueberry",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #520 checking search results for blueberry with boost=true");
//Test #521 checking search results for strawberry banana with boost=true
yourResult = tester.search("strawberry banana", true, 25);
TestingTools.checkSearch(yourResult, "strawberry banana",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #521 checking search results for strawberry banana with boost=true");
//Test #522 checking search results for blueberry coconut cherry blueberry apple with boost=true
yourResult = tester.search("blueberry coconut cherry blueberry apple", true, 25);
TestingTools.checkSearch(yourResult, "blueberry coconut cherry blueberry apple",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #522 checking search results for blueberry coconut cherry blueberry apple with boost=true");
//Test #523 checking search results for strawberry fig with boost=true
yourResult = tester.search("strawberry fig", true, 25);
TestingTools.checkSearch(yourResult, "strawberry fig",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #523 checking search results for strawberry fig with boost=true");
//Test #524 checking search results for fig apricot fig strawberry strawberry with boost=true
yourResult = tester.search("fig apricot fig strawberry strawberry", true, 25);
TestingTools.checkSearch(yourResult, "fig apricot fig strawberry strawberry",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #524 checking search results for fig apricot fig strawberry strawberry with boost=true");
//Test #525 checking search results for banana apricot with boost=true
yourResult = tester.search("banana apricot", true, 25);
TestingTools.checkSearch(yourResult, "banana apricot",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #525 checking search results for banana apricot with boost=true");
//Test #526 checking search results for apple lime pear with boost=true
yourResult = tester.search("apple lime pear", true, 25);
TestingTools.checkSearch(yourResult, "apple lime pear",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #526 checking search results for apple lime pear with boost=true");
//Test #527 checking search results for papaya cherry kiwi with boost=true
yourResult = tester.search("papaya cherry kiwi", true, 25);
TestingTools.checkSearch(yourResult, "papaya cherry kiwi",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #527 checking search results for papaya cherry kiwi with boost=true");
//Test #528 checking search results for apple tomato with boost=true
yourResult = tester.search("apple tomato", true, 25);
TestingTools.checkSearch(yourResult, "apple tomato",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #528 checking search results for apple tomato with boost=true");
//Test #529 checking search results for papaya papaya apple with boost=true
yourResult = tester.search("papaya papaya apple", true, 25);
TestingTools.checkSearch(yourResult, "papaya papaya apple",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #529 checking search results for papaya papaya apple with boost=true");
//Test #530 checking search results for peach strawberry peach coconut with boost=true
yourResult = tester.search("peach strawberry peach coconut", true, 25);
TestingTools.checkSearch(yourResult, "peach strawberry peach coconut",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #530 checking search results for peach strawberry peach coconut with boost=true");
//Test #531 checking search results for banana strawberry papaya with boost=true
yourResult = tester.search("banana strawberry papaya", true, 25);
TestingTools.checkSearch(yourResult, "banana strawberry papaya",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #531 checking search results for banana strawberry papaya with boost=true");
//Test #532 checking search results for pear apricot pear with boost=true
yourResult = tester.search("pear apricot pear", true, 25);
TestingTools.checkSearch(yourResult, "pear apricot pear",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #532 checking search results for pear apricot pear with boost=true");
//Test #533 checking search results for apricot pear kiwi kiwi with boost=true
yourResult = tester.search("apricot pear kiwi kiwi", true, 25);
TestingTools.checkSearch(yourResult, "apricot pear kiwi kiwi",true, passOut, failOut, "Fruits25SearchBoostTester", "Test #533 checking search results for apricot pear kiwi kiwi with boost=true");
failOut.close();
passOut.close();
}
}
