import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.*;
public class Fruits25SearchNoBoostTester {public static void main(String[] args) throws Exception{
ProjectTester tester = new ProjectTesterImp(); //Instantiate your own ProjectTester instance here
tester.initialize();
tester.crawl("https://people.scs.carleton.ca/~avamckenney/fruits25/N-0.html");
runTest(tester);}public static void runTest(ProjectTester tester) throws Exception{
PrintWriter failOut = new PrintWriter(new FileWriter("Fruits25-SearchNoBoost-failed.txt"));
PrintWriter passOut = new PrintWriter(new FileWriter("Fruits25-SearchNoBoost-passed.txt"));
List<SearchResult> yourResult; 
//Test #334 checking search results for papaya blueberry cherry with boost=true
yourResult = tester.search("papaya blueberry cherry", false, 25);
TestingTools.checkSearch(yourResult, "papaya blueberry cherry",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #334 checking search results for papaya blueberry cherry with boost=true");
//Test #335 checking search results for pear tomato with boost=true
yourResult = tester.search("pear tomato", false, 25);
TestingTools.checkSearch(yourResult, "pear tomato",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #335 checking search results for pear tomato with boost=true");
//Test #336 checking search results for blueberry apricot apple blueberry tomato with boost=true
yourResult = tester.search("blueberry apricot apple blueberry tomato", false, 25);
TestingTools.checkSearch(yourResult, "blueberry apricot apple blueberry tomato",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #336 checking search results for blueberry apricot apple blueberry tomato with boost=true");
//Test #337 checking search results for lime kiwi tomato pear with boost=true
yourResult = tester.search("lime kiwi tomato pear", false, 25);
TestingTools.checkSearch(yourResult, "lime kiwi tomato pear",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #337 checking search results for lime kiwi tomato pear with boost=true");
//Test #338 checking search results for strawberry blueberry apple papaya apricot with boost=true
yourResult = tester.search("strawberry blueberry apple papaya apricot", false, 25);
TestingTools.checkSearch(yourResult, "strawberry blueberry apple papaya apricot",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #338 checking search results for strawberry blueberry apple papaya apricot with boost=true");
//Test #339 checking search results for coconut tomato lime peach with boost=true
yourResult = tester.search("coconut tomato lime peach", false, 25);
TestingTools.checkSearch(yourResult, "coconut tomato lime peach",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #339 checking search results for coconut tomato lime peach with boost=true");
//Test #340 checking search results for apricot banana apple tomato papaya with boost=true
yourResult = tester.search("apricot banana apple tomato papaya", false, 25);
TestingTools.checkSearch(yourResult, "apricot banana apple tomato papaya",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #340 checking search results for apricot banana apple tomato papaya with boost=true");
//Test #341 checking search results for banana apricot peach lime with boost=true
yourResult = tester.search("banana apricot peach lime", false, 25);
TestingTools.checkSearch(yourResult, "banana apricot peach lime",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #341 checking search results for banana apricot peach lime with boost=true");
//Test #342 checking search results for lime blueberry peach with boost=true
yourResult = tester.search("lime blueberry peach", false, 25);
TestingTools.checkSearch(yourResult, "lime blueberry peach",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #342 checking search results for lime blueberry peach with boost=true");
//Test #343 checking search results for peach kiwi with boost=true
yourResult = tester.search("peach kiwi", false, 25);
TestingTools.checkSearch(yourResult, "peach kiwi",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #343 checking search results for peach kiwi with boost=true");
//Test #344 checking search results for coconut with boost=true
yourResult = tester.search("coconut", false, 25);
TestingTools.checkSearch(yourResult, "coconut",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #344 checking search results for coconut with boost=true");
//Test #345 checking search results for kiwi strawberry apricot pear kiwi with boost=true
yourResult = tester.search("kiwi strawberry apricot pear kiwi", false, 25);
TestingTools.checkSearch(yourResult, "kiwi strawberry apricot pear kiwi",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #345 checking search results for kiwi strawberry apricot pear kiwi with boost=true");
//Test #346 checking search results for apple blueberry strawberry kiwi with boost=true
yourResult = tester.search("apple blueberry strawberry kiwi", false, 25);
TestingTools.checkSearch(yourResult, "apple blueberry strawberry kiwi",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #346 checking search results for apple blueberry strawberry kiwi with boost=true");
//Test #347 checking search results for papaya blueberry papaya kiwi with boost=true
yourResult = tester.search("papaya blueberry papaya kiwi", false, 25);
TestingTools.checkSearch(yourResult, "papaya blueberry papaya kiwi",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #347 checking search results for papaya blueberry papaya kiwi with boost=true");
//Test #348 checking search results for banana papaya apricot with boost=true
yourResult = tester.search("banana papaya apricot", false, 25);
TestingTools.checkSearch(yourResult, "banana papaya apricot",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #348 checking search results for banana papaya apricot with boost=true");
//Test #349 checking search results for fig fig kiwi peach with boost=true
yourResult = tester.search("fig fig kiwi peach", false, 25);
TestingTools.checkSearch(yourResult, "fig fig kiwi peach",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #349 checking search results for fig fig kiwi peach with boost=true");
//Test #350 checking search results for apple strawberry with boost=true
yourResult = tester.search("apple strawberry", false, 25);
TestingTools.checkSearch(yourResult, "apple strawberry",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #350 checking search results for apple strawberry with boost=true");
//Test #351 checking search results for blueberry with boost=true
yourResult = tester.search("blueberry", false, 25);
TestingTools.checkSearch(yourResult, "blueberry",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #351 checking search results for blueberry with boost=true");
//Test #352 checking search results for blueberry pear tomato tomato strawberry with boost=true
yourResult = tester.search("blueberry pear tomato tomato strawberry", false, 25);
TestingTools.checkSearch(yourResult, "blueberry pear tomato tomato strawberry",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #352 checking search results for blueberry pear tomato tomato strawberry with boost=true");
//Test #353 checking search results for blueberry kiwi fig pear blueberry with boost=true
yourResult = tester.search("blueberry kiwi fig pear blueberry", false, 25);
TestingTools.checkSearch(yourResult, "blueberry kiwi fig pear blueberry",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #353 checking search results for blueberry kiwi fig pear blueberry with boost=true");
//Test #354 checking search results for blueberry strawberry tomato coconut kiwi with boost=true
yourResult = tester.search("blueberry strawberry tomato coconut kiwi", false, 25);
TestingTools.checkSearch(yourResult, "blueberry strawberry tomato coconut kiwi",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #354 checking search results for blueberry strawberry tomato coconut kiwi with boost=true");
//Test #355 checking search results for blueberry with boost=true
yourResult = tester.search("blueberry", false, 25);
TestingTools.checkSearch(yourResult, "blueberry",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #355 checking search results for blueberry with boost=true");
//Test #356 checking search results for fig fig papaya cherry with boost=true
yourResult = tester.search("fig fig papaya cherry", false, 25);
TestingTools.checkSearch(yourResult, "fig fig papaya cherry",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #356 checking search results for fig fig papaya cherry with boost=true");
//Test #357 checking search results for peach apricot with boost=true
yourResult = tester.search("peach apricot", false, 25);
TestingTools.checkSearch(yourResult, "peach apricot",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #357 checking search results for peach apricot with boost=true");
//Test #358 checking search results for blueberry cherry apricot kiwi with boost=true
yourResult = tester.search("blueberry cherry apricot kiwi", false, 25);
TestingTools.checkSearch(yourResult, "blueberry cherry apricot kiwi",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #358 checking search results for blueberry cherry apricot kiwi with boost=true");
//Test #359 checking search results for blueberry lime with boost=true
yourResult = tester.search("blueberry lime", false, 25);
TestingTools.checkSearch(yourResult, "blueberry lime",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #359 checking search results for blueberry lime with boost=true");
//Test #360 checking search results for apple lime with boost=true
yourResult = tester.search("apple lime", false, 25);
TestingTools.checkSearch(yourResult, "apple lime",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #360 checking search results for apple lime with boost=true");
//Test #361 checking search results for pear with boost=true
yourResult = tester.search("pear", false, 25);
TestingTools.checkSearch(yourResult, "pear",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #361 checking search results for pear with boost=true");
//Test #362 checking search results for apricot pear with boost=true
yourResult = tester.search("apricot pear", false, 25);
TestingTools.checkSearch(yourResult, "apricot pear",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #362 checking search results for apricot pear with boost=true");
//Test #363 checking search results for cherry pear with boost=true
yourResult = tester.search("cherry pear", false, 25);
TestingTools.checkSearch(yourResult, "cherry pear",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #363 checking search results for cherry pear with boost=true");
//Test #364 checking search results for blueberry peach lime with boost=true
yourResult = tester.search("blueberry peach lime", false, 25);
TestingTools.checkSearch(yourResult, "blueberry peach lime",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #364 checking search results for blueberry peach lime with boost=true");
//Test #365 checking search results for apple apple fig with boost=true
yourResult = tester.search("apple apple fig", false, 25);
TestingTools.checkSearch(yourResult, "apple apple fig",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #365 checking search results for apple apple fig with boost=true");
//Test #366 checking search results for pear papaya strawberry pear with boost=true
yourResult = tester.search("pear papaya strawberry pear", false, 25);
TestingTools.checkSearch(yourResult, "pear papaya strawberry pear",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #366 checking search results for pear papaya strawberry pear with boost=true");
//Test #367 checking search results for kiwi lime strawberry fig pear with boost=true
yourResult = tester.search("kiwi lime strawberry fig pear", false, 25);
TestingTools.checkSearch(yourResult, "kiwi lime strawberry fig pear",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #367 checking search results for kiwi lime strawberry fig pear with boost=true");
//Test #368 checking search results for papaya papaya apricot tomato kiwi with boost=true
yourResult = tester.search("papaya papaya apricot tomato kiwi", false, 25);
TestingTools.checkSearch(yourResult, "papaya papaya apricot tomato kiwi",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #368 checking search results for papaya papaya apricot tomato kiwi with boost=true");
//Test #369 checking search results for peach coconut tomato with boost=true
yourResult = tester.search("peach coconut tomato", false, 25);
TestingTools.checkSearch(yourResult, "peach coconut tomato",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #369 checking search results for peach coconut tomato with boost=true");
//Test #370 checking search results for apple with boost=true
yourResult = tester.search("apple", false, 25);
TestingTools.checkSearch(yourResult, "apple",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #370 checking search results for apple with boost=true");
//Test #371 checking search results for strawberry apricot with boost=true
yourResult = tester.search("strawberry apricot", false, 25);
TestingTools.checkSearch(yourResult, "strawberry apricot",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #371 checking search results for strawberry apricot with boost=true");
//Test #372 checking search results for blueberry lime banana cherry with boost=true
yourResult = tester.search("blueberry lime banana cherry", false, 25);
TestingTools.checkSearch(yourResult, "blueberry lime banana cherry",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #372 checking search results for blueberry lime banana cherry with boost=true");
//Test #373 checking search results for strawberry coconut lime lime papaya with boost=true
yourResult = tester.search("strawberry coconut lime lime papaya", false, 25);
TestingTools.checkSearch(yourResult, "strawberry coconut lime lime papaya",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #373 checking search results for strawberry coconut lime lime papaya with boost=true");
//Test #374 checking search results for cherry papaya pear with boost=true
yourResult = tester.search("cherry papaya pear", false, 25);
TestingTools.checkSearch(yourResult, "cherry papaya pear",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #374 checking search results for cherry papaya pear with boost=true");
//Test #375 checking search results for tomato apricot with boost=true
yourResult = tester.search("tomato apricot", false, 25);
TestingTools.checkSearch(yourResult, "tomato apricot",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #375 checking search results for tomato apricot with boost=true");
//Test #376 checking search results for coconut with boost=true
yourResult = tester.search("coconut", false, 25);
TestingTools.checkSearch(yourResult, "coconut",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #376 checking search results for coconut with boost=true");
//Test #377 checking search results for papaya strawberry kiwi apple apple with boost=true
yourResult = tester.search("papaya strawberry kiwi apple apple", false, 25);
TestingTools.checkSearch(yourResult, "papaya strawberry kiwi apple apple",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #377 checking search results for papaya strawberry kiwi apple apple with boost=true");
//Test #378 checking search results for banana with boost=true
yourResult = tester.search("banana", false, 25);
TestingTools.checkSearch(yourResult, "banana",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #378 checking search results for banana with boost=true");
//Test #379 checking search results for banana coconut kiwi with boost=true
yourResult = tester.search("banana coconut kiwi", false, 25);
TestingTools.checkSearch(yourResult, "banana coconut kiwi",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #379 checking search results for banana coconut kiwi with boost=true");
//Test #380 checking search results for papaya blueberry with boost=true
yourResult = tester.search("papaya blueberry", false, 25);
TestingTools.checkSearch(yourResult, "papaya blueberry",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #380 checking search results for papaya blueberry with boost=true");
//Test #381 checking search results for apricot banana strawberry lime with boost=true
yourResult = tester.search("apricot banana strawberry lime", false, 25);
TestingTools.checkSearch(yourResult, "apricot banana strawberry lime",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #381 checking search results for apricot banana strawberry lime with boost=true");
//Test #382 checking search results for pear with boost=true
yourResult = tester.search("pear", false, 25);
TestingTools.checkSearch(yourResult, "pear",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #382 checking search results for pear with boost=true");
//Test #383 checking search results for fig with boost=true
yourResult = tester.search("fig", false, 25);
TestingTools.checkSearch(yourResult, "fig",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #383 checking search results for fig with boost=true");
//Test #384 checking search results for banana banana peach fig kiwi with boost=true
yourResult = tester.search("banana banana peach fig kiwi", false, 25);
TestingTools.checkSearch(yourResult, "banana banana peach fig kiwi",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #384 checking search results for banana banana peach fig kiwi with boost=true");
//Test #385 checking search results for tomato coconut cherry apricot with boost=true
yourResult = tester.search("tomato coconut cherry apricot", false, 25);
TestingTools.checkSearch(yourResult, "tomato coconut cherry apricot",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #385 checking search results for tomato coconut cherry apricot with boost=true");
//Test #386 checking search results for tomato banana tomato with boost=true
yourResult = tester.search("tomato banana tomato", false, 25);
TestingTools.checkSearch(yourResult, "tomato banana tomato",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #386 checking search results for tomato banana tomato with boost=true");
//Test #387 checking search results for fig lime with boost=true
yourResult = tester.search("fig lime", false, 25);
TestingTools.checkSearch(yourResult, "fig lime",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #387 checking search results for fig lime with boost=true");
//Test #388 checking search results for papaya peach coconut with boost=true
yourResult = tester.search("papaya peach coconut", false, 25);
TestingTools.checkSearch(yourResult, "papaya peach coconut",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #388 checking search results for papaya peach coconut with boost=true");
//Test #389 checking search results for kiwi lime blueberry with boost=true
yourResult = tester.search("kiwi lime blueberry", false, 25);
TestingTools.checkSearch(yourResult, "kiwi lime blueberry",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #389 checking search results for kiwi lime blueberry with boost=true");
//Test #390 checking search results for blueberry strawberry apple with boost=true
yourResult = tester.search("blueberry strawberry apple", false, 25);
TestingTools.checkSearch(yourResult, "blueberry strawberry apple",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #390 checking search results for blueberry strawberry apple with boost=true");
//Test #391 checking search results for banana with boost=true
yourResult = tester.search("banana", false, 25);
TestingTools.checkSearch(yourResult, "banana",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #391 checking search results for banana with boost=true");
//Test #392 checking search results for lime coconut with boost=true
yourResult = tester.search("lime coconut", false, 25);
TestingTools.checkSearch(yourResult, "lime coconut",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #392 checking search results for lime coconut with boost=true");
//Test #393 checking search results for papaya lime kiwi apricot with boost=true
yourResult = tester.search("papaya lime kiwi apricot", false, 25);
TestingTools.checkSearch(yourResult, "papaya lime kiwi apricot",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #393 checking search results for papaya lime kiwi apricot with boost=true");
//Test #394 checking search results for apple peach coconut with boost=true
yourResult = tester.search("apple peach coconut", false, 25);
TestingTools.checkSearch(yourResult, "apple peach coconut",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #394 checking search results for apple peach coconut with boost=true");
//Test #395 checking search results for papaya pear with boost=true
yourResult = tester.search("papaya pear", false, 25);
TestingTools.checkSearch(yourResult, "papaya pear",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #395 checking search results for papaya pear with boost=true");
//Test #396 checking search results for cherry apple lime fig with boost=true
yourResult = tester.search("cherry apple lime fig", false, 25);
TestingTools.checkSearch(yourResult, "cherry apple lime fig",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #396 checking search results for cherry apple lime fig with boost=true");
//Test #397 checking search results for peach apricot cherry with boost=true
yourResult = tester.search("peach apricot cherry", false, 25);
TestingTools.checkSearch(yourResult, "peach apricot cherry",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #397 checking search results for peach apricot cherry with boost=true");
//Test #398 checking search results for kiwi peach peach strawberry with boost=true
yourResult = tester.search("kiwi peach peach strawberry", false, 25);
TestingTools.checkSearch(yourResult, "kiwi peach peach strawberry",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #398 checking search results for kiwi peach peach strawberry with boost=true");
//Test #399 checking search results for pear cherry fig with boost=true
yourResult = tester.search("pear cherry fig", false, 25);
TestingTools.checkSearch(yourResult, "pear cherry fig",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #399 checking search results for pear cherry fig with boost=true");
//Test #400 checking search results for blueberry lime tomato with boost=true
yourResult = tester.search("blueberry lime tomato", false, 25);
TestingTools.checkSearch(yourResult, "blueberry lime tomato",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #400 checking search results for blueberry lime tomato with boost=true");
//Test #401 checking search results for blueberry banana pear with boost=true
yourResult = tester.search("blueberry banana pear", false, 25);
TestingTools.checkSearch(yourResult, "blueberry banana pear",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #401 checking search results for blueberry banana pear with boost=true");
//Test #402 checking search results for blueberry with boost=true
yourResult = tester.search("blueberry", false, 25);
TestingTools.checkSearch(yourResult, "blueberry",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #402 checking search results for blueberry with boost=true");
//Test #403 checking search results for blueberry with boost=true
yourResult = tester.search("blueberry", false, 25);
TestingTools.checkSearch(yourResult, "blueberry",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #403 checking search results for blueberry with boost=true");
//Test #404 checking search results for pear pear peach tomato apricot with boost=true
yourResult = tester.search("pear pear peach tomato apricot", false, 25);
TestingTools.checkSearch(yourResult, "pear pear peach tomato apricot",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #404 checking search results for pear pear peach tomato apricot with boost=true");
//Test #405 checking search results for coconut peach lime banana with boost=true
yourResult = tester.search("coconut peach lime banana", false, 25);
TestingTools.checkSearch(yourResult, "coconut peach lime banana",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #405 checking search results for coconut peach lime banana with boost=true");
//Test #406 checking search results for apple peach fig banana kiwi with boost=true
yourResult = tester.search("apple peach fig banana kiwi", false, 25);
TestingTools.checkSearch(yourResult, "apple peach fig banana kiwi",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #406 checking search results for apple peach fig banana kiwi with boost=true");
//Test #407 checking search results for papaya apricot papaya tomato lime with boost=true
yourResult = tester.search("papaya apricot papaya tomato lime", false, 25);
TestingTools.checkSearch(yourResult, "papaya apricot papaya tomato lime",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #407 checking search results for papaya apricot papaya tomato lime with boost=true");
//Test #408 checking search results for apricot strawberry with boost=true
yourResult = tester.search("apricot strawberry", false, 25);
TestingTools.checkSearch(yourResult, "apricot strawberry",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #408 checking search results for apricot strawberry with boost=true");
//Test #409 checking search results for blueberry peach apricot coconut apple with boost=true
yourResult = tester.search("blueberry peach apricot coconut apple", false, 25);
TestingTools.checkSearch(yourResult, "blueberry peach apricot coconut apple",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #409 checking search results for blueberry peach apricot coconut apple with boost=true");
//Test #410 checking search results for fig with boost=true
yourResult = tester.search("fig", false, 25);
TestingTools.checkSearch(yourResult, "fig",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #410 checking search results for fig with boost=true");
//Test #411 checking search results for kiwi coconut peach apple coconut with boost=true
yourResult = tester.search("kiwi coconut peach apple coconut", false, 25);
TestingTools.checkSearch(yourResult, "kiwi coconut peach apple coconut",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #411 checking search results for kiwi coconut peach apple coconut with boost=true");
//Test #412 checking search results for apple coconut blueberry tomato strawberry with boost=true
yourResult = tester.search("apple coconut blueberry tomato strawberry", false, 25);
TestingTools.checkSearch(yourResult, "apple coconut blueberry tomato strawberry",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #412 checking search results for apple coconut blueberry tomato strawberry with boost=true");
//Test #413 checking search results for fig lime cherry with boost=true
yourResult = tester.search("fig lime cherry", false, 25);
TestingTools.checkSearch(yourResult, "fig lime cherry",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #413 checking search results for fig lime cherry with boost=true");
//Test #414 checking search results for kiwi banana strawberry fig with boost=true
yourResult = tester.search("kiwi banana strawberry fig", false, 25);
TestingTools.checkSearch(yourResult, "kiwi banana strawberry fig",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #414 checking search results for kiwi banana strawberry fig with boost=true");
//Test #415 checking search results for cherry fig with boost=true
yourResult = tester.search("cherry fig", false, 25);
TestingTools.checkSearch(yourResult, "cherry fig",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #415 checking search results for cherry fig with boost=true");
//Test #416 checking search results for pear kiwi cherry with boost=true
yourResult = tester.search("pear kiwi cherry", false, 25);
TestingTools.checkSearch(yourResult, "pear kiwi cherry",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #416 checking search results for pear kiwi cherry with boost=true");
//Test #417 checking search results for tomato apricot papaya lime with boost=true
yourResult = tester.search("tomato apricot papaya lime", false, 25);
TestingTools.checkSearch(yourResult, "tomato apricot papaya lime",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #417 checking search results for tomato apricot papaya lime with boost=true");
//Test #418 checking search results for kiwi kiwi banana with boost=true
yourResult = tester.search("kiwi kiwi banana", false, 25);
TestingTools.checkSearch(yourResult, "kiwi kiwi banana",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #418 checking search results for kiwi kiwi banana with boost=true");
//Test #419 checking search results for apple apricot pear papaya apple with boost=true
yourResult = tester.search("apple apricot pear papaya apple", false, 25);
TestingTools.checkSearch(yourResult, "apple apricot pear papaya apple",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #419 checking search results for apple apricot pear papaya apple with boost=true");
//Test #420 checking search results for fig blueberry cherry coconut with boost=true
yourResult = tester.search("fig blueberry cherry coconut", false, 25);
TestingTools.checkSearch(yourResult, "fig blueberry cherry coconut",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #420 checking search results for fig blueberry cherry coconut with boost=true");
//Test #421 checking search results for strawberry coconut blueberry cherry with boost=true
yourResult = tester.search("strawberry coconut blueberry cherry", false, 25);
TestingTools.checkSearch(yourResult, "strawberry coconut blueberry cherry",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #421 checking search results for strawberry coconut blueberry cherry with boost=true");
//Test #422 checking search results for coconut coconut papaya with boost=true
yourResult = tester.search("coconut coconut papaya", false, 25);
TestingTools.checkSearch(yourResult, "coconut coconut papaya",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #422 checking search results for coconut coconut papaya with boost=true");
//Test #423 checking search results for kiwi with boost=true
yourResult = tester.search("kiwi", false, 25);
TestingTools.checkSearch(yourResult, "kiwi",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #423 checking search results for kiwi with boost=true");
//Test #424 checking search results for peach fig apricot with boost=true
yourResult = tester.search("peach fig apricot", false, 25);
TestingTools.checkSearch(yourResult, "peach fig apricot",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #424 checking search results for peach fig apricot with boost=true");
//Test #425 checking search results for apple with boost=true
yourResult = tester.search("apple", false, 25);
TestingTools.checkSearch(yourResult, "apple",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #425 checking search results for apple with boost=true");
//Test #426 checking search results for apricot strawberry apricot fig with boost=true
yourResult = tester.search("apricot strawberry apricot fig", false, 25);
TestingTools.checkSearch(yourResult, "apricot strawberry apricot fig",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #426 checking search results for apricot strawberry apricot fig with boost=true");
//Test #427 checking search results for cherry coconut banana blueberry cherry with boost=true
yourResult = tester.search("cherry coconut banana blueberry cherry", false, 25);
TestingTools.checkSearch(yourResult, "cherry coconut banana blueberry cherry",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #427 checking search results for cherry coconut banana blueberry cherry with boost=true");
//Test #428 checking search results for strawberry banana with boost=true
yourResult = tester.search("strawberry banana", false, 25);
TestingTools.checkSearch(yourResult, "strawberry banana",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #428 checking search results for strawberry banana with boost=true");
//Test #429 checking search results for blueberry blueberry papaya papaya pear with boost=true
yourResult = tester.search("blueberry blueberry papaya papaya pear", false, 25);
TestingTools.checkSearch(yourResult, "blueberry blueberry papaya papaya pear",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #429 checking search results for blueberry blueberry papaya papaya pear with boost=true");
//Test #430 checking search results for banana tomato banana apricot fig with boost=true
yourResult = tester.search("banana tomato banana apricot fig", false, 25);
TestingTools.checkSearch(yourResult, "banana tomato banana apricot fig",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #430 checking search results for banana tomato banana apricot fig with boost=true");
//Test #431 checking search results for lime pear tomato fig papaya with boost=true
yourResult = tester.search("lime pear tomato fig papaya", false, 25);
TestingTools.checkSearch(yourResult, "lime pear tomato fig papaya",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #431 checking search results for lime pear tomato fig papaya with boost=true");
//Test #432 checking search results for pear cherry cherry lime with boost=true
yourResult = tester.search("pear cherry cherry lime", false, 25);
TestingTools.checkSearch(yourResult, "pear cherry cherry lime",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #432 checking search results for pear cherry cherry lime with boost=true");
//Test #433 checking search results for lime kiwi apple strawberry with boost=true
yourResult = tester.search("lime kiwi apple strawberry", false, 25);
TestingTools.checkSearch(yourResult, "lime kiwi apple strawberry",false, passOut, failOut, "Fruits25SearchNoBoostTester", "Test #433 checking search results for lime kiwi apple strawberry with boost=true");
failOut.close();
passOut.close();
}
}
