import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.*;
public class Fruits100SearchBoostTester {public static void main(String[] args) throws Exception{
ProjectTester tester = new ProjectTesterImp(); //Instantiate your own ProjectTester instance here
tester.initialize();
tester.crawl("https://people.scs.carleton.ca/~avamckenney/fruits100/N-0.html");
runTest(tester);}public static void runTest(ProjectTester tester) throws Exception{
PrintWriter failOut = new PrintWriter(new FileWriter("Fruits100-SearchBoost-failed.txt"));
PrintWriter passOut = new PrintWriter(new FileWriter("Fruits100-SearchBoost-passed.txt"));
List<SearchResult> yourResult; 
//Test #509 checking search results for apricot with boost=true
yourResult = tester.search("apricot", true, 100);
TestingTools.checkSearch(yourResult, "apricot",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #509 checking search results for apricot with boost=true");
//Test #510 checking search results for blueberry cherry with boost=true
yourResult = tester.search("blueberry cherry", true, 100);
TestingTools.checkSearch(yourResult, "blueberry cherry",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #510 checking search results for blueberry cherry with boost=true");
//Test #511 checking search results for apricot blueberry kiwi fig with boost=true
yourResult = tester.search("apricot blueberry kiwi fig", true, 100);
TestingTools.checkSearch(yourResult, "apricot blueberry kiwi fig",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #511 checking search results for apricot blueberry kiwi fig with boost=true");
//Test #512 checking search results for apple blueberry with boost=true
yourResult = tester.search("apple blueberry", true, 100);
TestingTools.checkSearch(yourResult, "apple blueberry",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #512 checking search results for apple blueberry with boost=true");
//Test #513 checking search results for fig with boost=true
yourResult = tester.search("fig", true, 100);
TestingTools.checkSearch(yourResult, "fig",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #513 checking search results for fig with boost=true");
//Test #514 checking search results for tomato apple cherry lime with boost=true
yourResult = tester.search("tomato apple cherry lime", true, 100);
TestingTools.checkSearch(yourResult, "tomato apple cherry lime",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #514 checking search results for tomato apple cherry lime with boost=true");
//Test #515 checking search results for pear lime fig fig papaya with boost=true
yourResult = tester.search("pear lime fig fig papaya", true, 100);
TestingTools.checkSearch(yourResult, "pear lime fig fig papaya",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #515 checking search results for pear lime fig fig papaya with boost=true");
//Test #516 checking search results for fig tomato apricot cherry with boost=true
yourResult = tester.search("fig tomato apricot cherry", true, 100);
TestingTools.checkSearch(yourResult, "fig tomato apricot cherry",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #516 checking search results for fig tomato apricot cherry with boost=true");
//Test #517 checking search results for apricot fig with boost=true
yourResult = tester.search("apricot fig", true, 100);
TestingTools.checkSearch(yourResult, "apricot fig",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #517 checking search results for apricot fig with boost=true");
//Test #518 checking search results for cherry papaya kiwi tomato with boost=true
yourResult = tester.search("cherry papaya kiwi tomato", true, 100);
TestingTools.checkSearch(yourResult, "cherry papaya kiwi tomato",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #518 checking search results for cherry papaya kiwi tomato with boost=true");
//Test #519 checking search results for blueberry cherry strawberry with boost=true
yourResult = tester.search("blueberry cherry strawberry", true, 100);
TestingTools.checkSearch(yourResult, "blueberry cherry strawberry",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #519 checking search results for blueberry cherry strawberry with boost=true");
//Test #520 checking search results for peach coconut peach fig papaya with boost=true
yourResult = tester.search("peach coconut peach fig papaya", true, 100);
TestingTools.checkSearch(yourResult, "peach coconut peach fig papaya",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #520 checking search results for peach coconut peach fig papaya with boost=true");
//Test #521 checking search results for peach lime apricot blueberry fig with boost=true
yourResult = tester.search("peach lime apricot blueberry fig", true, 100);
TestingTools.checkSearch(yourResult, "peach lime apricot blueberry fig",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #521 checking search results for peach lime apricot blueberry fig with boost=true");
//Test #522 checking search results for lime peach with boost=true
yourResult = tester.search("lime peach", true, 100);
TestingTools.checkSearch(yourResult, "lime peach",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #522 checking search results for lime peach with boost=true");
//Test #523 checking search results for blueberry with boost=true
yourResult = tester.search("blueberry", true, 100);
TestingTools.checkSearch(yourResult, "blueberry",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #523 checking search results for blueberry with boost=true");
//Test #524 checking search results for strawberry pear tomato cherry with boost=true
yourResult = tester.search("strawberry pear tomato cherry", true, 100);
TestingTools.checkSearch(yourResult, "strawberry pear tomato cherry",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #524 checking search results for strawberry pear tomato cherry with boost=true");
//Test #525 checking search results for cherry banana papaya kiwi with boost=true
yourResult = tester.search("cherry banana papaya kiwi", true, 100);
TestingTools.checkSearch(yourResult, "cherry banana papaya kiwi",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #525 checking search results for cherry banana papaya kiwi with boost=true");
//Test #526 checking search results for banana with boost=true
yourResult = tester.search("banana", true, 100);
TestingTools.checkSearch(yourResult, "banana",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #526 checking search results for banana with boost=true");
//Test #527 checking search results for apricot pear banana kiwi coconut with boost=true
yourResult = tester.search("apricot pear banana kiwi coconut", true, 100);
TestingTools.checkSearch(yourResult, "apricot pear banana kiwi coconut",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #527 checking search results for apricot pear banana kiwi coconut with boost=true");
//Test #528 checking search results for banana kiwi with boost=true
yourResult = tester.search("banana kiwi", true, 100);
TestingTools.checkSearch(yourResult, "banana kiwi",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #528 checking search results for banana kiwi with boost=true");
//Test #529 checking search results for peach fig apricot strawberry with boost=true
yourResult = tester.search("peach fig apricot strawberry", true, 100);
TestingTools.checkSearch(yourResult, "peach fig apricot strawberry",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #529 checking search results for peach fig apricot strawberry with boost=true");
//Test #530 checking search results for apricot kiwi with boost=true
yourResult = tester.search("apricot kiwi", true, 100);
TestingTools.checkSearch(yourResult, "apricot kiwi",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #530 checking search results for apricot kiwi with boost=true");
//Test #531 checking search results for papaya blueberry lime with boost=true
yourResult = tester.search("papaya blueberry lime", true, 100);
TestingTools.checkSearch(yourResult, "papaya blueberry lime",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #531 checking search results for papaya blueberry lime with boost=true");
//Test #532 checking search results for papaya cherry with boost=true
yourResult = tester.search("papaya cherry", true, 100);
TestingTools.checkSearch(yourResult, "papaya cherry",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #532 checking search results for papaya cherry with boost=true");
//Test #533 checking search results for tomato peach pear tomato pear with boost=true
yourResult = tester.search("tomato peach pear tomato pear", true, 100);
TestingTools.checkSearch(yourResult, "tomato peach pear tomato pear",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #533 checking search results for tomato peach pear tomato pear with boost=true");
//Test #534 checking search results for apple papaya papaya with boost=true
yourResult = tester.search("apple papaya papaya", true, 100);
TestingTools.checkSearch(yourResult, "apple papaya papaya",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #534 checking search results for apple papaya papaya with boost=true");
//Test #535 checking search results for papaya with boost=true
yourResult = tester.search("papaya", true, 100);
TestingTools.checkSearch(yourResult, "papaya",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #535 checking search results for papaya with boost=true");
//Test #536 checking search results for banana apricot pear pear fig with boost=true
yourResult = tester.search("banana apricot pear pear fig", true, 100);
TestingTools.checkSearch(yourResult, "banana apricot pear pear fig",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #536 checking search results for banana apricot pear pear fig with boost=true");
//Test #537 checking search results for fig apple with boost=true
yourResult = tester.search("fig apple", true, 100);
TestingTools.checkSearch(yourResult, "fig apple",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #537 checking search results for fig apple with boost=true");
//Test #538 checking search results for pear with boost=true
yourResult = tester.search("pear", true, 100);
TestingTools.checkSearch(yourResult, "pear",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #538 checking search results for pear with boost=true");
//Test #539 checking search results for cherry banana kiwi fig with boost=true
yourResult = tester.search("cherry banana kiwi fig", true, 100);
TestingTools.checkSearch(yourResult, "cherry banana kiwi fig",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #539 checking search results for cherry banana kiwi fig with boost=true");
//Test #540 checking search results for peach papaya apple with boost=true
yourResult = tester.search("peach papaya apple", true, 100);
TestingTools.checkSearch(yourResult, "peach papaya apple",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #540 checking search results for peach papaya apple with boost=true");
//Test #541 checking search results for cherry papaya tomato with boost=true
yourResult = tester.search("cherry papaya tomato", true, 100);
TestingTools.checkSearch(yourResult, "cherry papaya tomato",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #541 checking search results for cherry papaya tomato with boost=true");
//Test #542 checking search results for cherry apricot with boost=true
yourResult = tester.search("cherry apricot", true, 100);
TestingTools.checkSearch(yourResult, "cherry apricot",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #542 checking search results for cherry apricot with boost=true");
//Test #543 checking search results for apricot lime strawberry with boost=true
yourResult = tester.search("apricot lime strawberry", true, 100);
TestingTools.checkSearch(yourResult, "apricot lime strawberry",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #543 checking search results for apricot lime strawberry with boost=true");
//Test #544 checking search results for fig kiwi pear peach blueberry with boost=true
yourResult = tester.search("fig kiwi pear peach blueberry", true, 100);
TestingTools.checkSearch(yourResult, "fig kiwi pear peach blueberry",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #544 checking search results for fig kiwi pear peach blueberry with boost=true");
//Test #545 checking search results for lime with boost=true
yourResult = tester.search("lime", true, 100);
TestingTools.checkSearch(yourResult, "lime",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #545 checking search results for lime with boost=true");
//Test #546 checking search results for lime with boost=true
yourResult = tester.search("lime", true, 100);
TestingTools.checkSearch(yourResult, "lime",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #546 checking search results for lime with boost=true");
//Test #547 checking search results for fig strawberry pear lime with boost=true
yourResult = tester.search("fig strawberry pear lime", true, 100);
TestingTools.checkSearch(yourResult, "fig strawberry pear lime",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #547 checking search results for fig strawberry pear lime with boost=true");
//Test #548 checking search results for apricot cherry blueberry with boost=true
yourResult = tester.search("apricot cherry blueberry", true, 100);
TestingTools.checkSearch(yourResult, "apricot cherry blueberry",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #548 checking search results for apricot cherry blueberry with boost=true");
//Test #549 checking search results for tomato apple cherry strawberry with boost=true
yourResult = tester.search("tomato apple cherry strawberry", true, 100);
TestingTools.checkSearch(yourResult, "tomato apple cherry strawberry",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #549 checking search results for tomato apple cherry strawberry with boost=true");
//Test #550 checking search results for tomato apricot kiwi tomato with boost=true
yourResult = tester.search("tomato apricot kiwi tomato", true, 100);
TestingTools.checkSearch(yourResult, "tomato apricot kiwi tomato",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #550 checking search results for tomato apricot kiwi tomato with boost=true");
//Test #551 checking search results for coconut pear with boost=true
yourResult = tester.search("coconut pear", true, 100);
TestingTools.checkSearch(yourResult, "coconut pear",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #551 checking search results for coconut pear with boost=true");
//Test #552 checking search results for blueberry blueberry banana coconut with boost=true
yourResult = tester.search("blueberry blueberry banana coconut", true, 100);
TestingTools.checkSearch(yourResult, "blueberry blueberry banana coconut",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #552 checking search results for blueberry blueberry banana coconut with boost=true");
//Test #553 checking search results for strawberry peach apricot pear banana with boost=true
yourResult = tester.search("strawberry peach apricot pear banana", true, 100);
TestingTools.checkSearch(yourResult, "strawberry peach apricot pear banana",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #553 checking search results for strawberry peach apricot pear banana with boost=true");
//Test #554 checking search results for blueberry apricot with boost=true
yourResult = tester.search("blueberry apricot", true, 100);
TestingTools.checkSearch(yourResult, "blueberry apricot",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #554 checking search results for blueberry apricot with boost=true");
//Test #555 checking search results for tomato strawberry fig banana papaya with boost=true
yourResult = tester.search("tomato strawberry fig banana papaya", true, 100);
TestingTools.checkSearch(yourResult, "tomato strawberry fig banana papaya",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #555 checking search results for tomato strawberry fig banana papaya with boost=true");
//Test #556 checking search results for fig tomato fig kiwi peach with boost=true
yourResult = tester.search("fig tomato fig kiwi peach", true, 100);
TestingTools.checkSearch(yourResult, "fig tomato fig kiwi peach",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #556 checking search results for fig tomato fig kiwi peach with boost=true");
//Test #557 checking search results for apricot apple cherry cherry strawberry with boost=true
yourResult = tester.search("apricot apple cherry cherry strawberry", true, 100);
TestingTools.checkSearch(yourResult, "apricot apple cherry cherry strawberry",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #557 checking search results for apricot apple cherry cherry strawberry with boost=true");
//Test #558 checking search results for blueberry with boost=true
yourResult = tester.search("blueberry", true, 100);
TestingTools.checkSearch(yourResult, "blueberry",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #558 checking search results for blueberry with boost=true");
//Test #559 checking search results for coconut banana with boost=true
yourResult = tester.search("coconut banana", true, 100);
TestingTools.checkSearch(yourResult, "coconut banana",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #559 checking search results for coconut banana with boost=true");
//Test #560 checking search results for strawberry lime lime fig apricot with boost=true
yourResult = tester.search("strawberry lime lime fig apricot", true, 100);
TestingTools.checkSearch(yourResult, "strawberry lime lime fig apricot",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #560 checking search results for strawberry lime lime fig apricot with boost=true");
//Test #561 checking search results for blueberry coconut cherry kiwi with boost=true
yourResult = tester.search("blueberry coconut cherry kiwi", true, 100);
TestingTools.checkSearch(yourResult, "blueberry coconut cherry kiwi",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #561 checking search results for blueberry coconut cherry kiwi with boost=true");
//Test #562 checking search results for fig with boost=true
yourResult = tester.search("fig", true, 100);
TestingTools.checkSearch(yourResult, "fig",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #562 checking search results for fig with boost=true");
//Test #563 checking search results for apricot coconut kiwi tomato with boost=true
yourResult = tester.search("apricot coconut kiwi tomato", true, 100);
TestingTools.checkSearch(yourResult, "apricot coconut kiwi tomato",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #563 checking search results for apricot coconut kiwi tomato with boost=true");
//Test #564 checking search results for kiwi lime banana apricot coconut with boost=true
yourResult = tester.search("kiwi lime banana apricot coconut", true, 100);
TestingTools.checkSearch(yourResult, "kiwi lime banana apricot coconut",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #564 checking search results for kiwi lime banana apricot coconut with boost=true");
//Test #565 checking search results for apple tomato cherry apple with boost=true
yourResult = tester.search("apple tomato cherry apple", true, 100);
TestingTools.checkSearch(yourResult, "apple tomato cherry apple",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #565 checking search results for apple tomato cherry apple with boost=true");
//Test #566 checking search results for blueberry banana pear banana with boost=true
yourResult = tester.search("blueberry banana pear banana", true, 100);
TestingTools.checkSearch(yourResult, "blueberry banana pear banana",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #566 checking search results for blueberry banana pear banana with boost=true");
//Test #567 checking search results for cherry pear papaya pear peach with boost=true
yourResult = tester.search("cherry pear papaya pear peach", true, 100);
TestingTools.checkSearch(yourResult, "cherry pear papaya pear peach",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #567 checking search results for cherry pear papaya pear peach with boost=true");
//Test #568 checking search results for strawberry lime blueberry fig with boost=true
yourResult = tester.search("strawberry lime blueberry fig", true, 100);
TestingTools.checkSearch(yourResult, "strawberry lime blueberry fig",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #568 checking search results for strawberry lime blueberry fig with boost=true");
//Test #569 checking search results for strawberry apricot with boost=true
yourResult = tester.search("strawberry apricot", true, 100);
TestingTools.checkSearch(yourResult, "strawberry apricot",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #569 checking search results for strawberry apricot with boost=true");
//Test #570 checking search results for strawberry tomato banana with boost=true
yourResult = tester.search("strawberry tomato banana", true, 100);
TestingTools.checkSearch(yourResult, "strawberry tomato banana",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #570 checking search results for strawberry tomato banana with boost=true");
//Test #571 checking search results for coconut strawberry with boost=true
yourResult = tester.search("coconut strawberry", true, 100);
TestingTools.checkSearch(yourResult, "coconut strawberry",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #571 checking search results for coconut strawberry with boost=true");
//Test #572 checking search results for blueberry cherry with boost=true
yourResult = tester.search("blueberry cherry", true, 100);
TestingTools.checkSearch(yourResult, "blueberry cherry",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #572 checking search results for blueberry cherry with boost=true");
//Test #573 checking search results for strawberry with boost=true
yourResult = tester.search("strawberry", true, 100);
TestingTools.checkSearch(yourResult, "strawberry",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #573 checking search results for strawberry with boost=true");
//Test #574 checking search results for blueberry apple lime apricot coconut with boost=true
yourResult = tester.search("blueberry apple lime apricot coconut", true, 100);
TestingTools.checkSearch(yourResult, "blueberry apple lime apricot coconut",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #574 checking search results for blueberry apple lime apricot coconut with boost=true");
//Test #575 checking search results for coconut pear with boost=true
yourResult = tester.search("coconut pear", true, 100);
TestingTools.checkSearch(yourResult, "coconut pear",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #575 checking search results for coconut pear with boost=true");
//Test #576 checking search results for kiwi with boost=true
yourResult = tester.search("kiwi", true, 100);
TestingTools.checkSearch(yourResult, "kiwi",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #576 checking search results for kiwi with boost=true");
//Test #577 checking search results for coconut coconut with boost=true
yourResult = tester.search("coconut coconut", true, 100);
TestingTools.checkSearch(yourResult, "coconut coconut",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #577 checking search results for coconut coconut with boost=true");
//Test #578 checking search results for strawberry banana with boost=true
yourResult = tester.search("strawberry banana", true, 100);
TestingTools.checkSearch(yourResult, "strawberry banana",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #578 checking search results for strawberry banana with boost=true");
//Test #579 checking search results for pear pear tomato coconut with boost=true
yourResult = tester.search("pear pear tomato coconut", true, 100);
TestingTools.checkSearch(yourResult, "pear pear tomato coconut",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #579 checking search results for pear pear tomato coconut with boost=true");
//Test #580 checking search results for peach blueberry kiwi kiwi apricot with boost=true
yourResult = tester.search("peach blueberry kiwi kiwi apricot", true, 100);
TestingTools.checkSearch(yourResult, "peach blueberry kiwi kiwi apricot",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #580 checking search results for peach blueberry kiwi kiwi apricot with boost=true");
//Test #581 checking search results for strawberry apple papaya apricot papaya with boost=true
yourResult = tester.search("strawberry apple papaya apricot papaya", true, 100);
TestingTools.checkSearch(yourResult, "strawberry apple papaya apricot papaya",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #581 checking search results for strawberry apple papaya apricot papaya with boost=true");
//Test #582 checking search results for apricot apple tomato with boost=true
yourResult = tester.search("apricot apple tomato", true, 100);
TestingTools.checkSearch(yourResult, "apricot apple tomato",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #582 checking search results for apricot apple tomato with boost=true");
//Test #583 checking search results for pear apple with boost=true
yourResult = tester.search("pear apple", true, 100);
TestingTools.checkSearch(yourResult, "pear apple",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #583 checking search results for pear apple with boost=true");
//Test #584 checking search results for apple apple with boost=true
yourResult = tester.search("apple apple", true, 100);
TestingTools.checkSearch(yourResult, "apple apple",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #584 checking search results for apple apple with boost=true");
//Test #585 checking search results for papaya with boost=true
yourResult = tester.search("papaya", true, 100);
TestingTools.checkSearch(yourResult, "papaya",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #585 checking search results for papaya with boost=true");
//Test #586 checking search results for lime apricot blueberry with boost=true
yourResult = tester.search("lime apricot blueberry", true, 100);
TestingTools.checkSearch(yourResult, "lime apricot blueberry",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #586 checking search results for lime apricot blueberry with boost=true");
//Test #587 checking search results for apple peach banana with boost=true
yourResult = tester.search("apple peach banana", true, 100);
TestingTools.checkSearch(yourResult, "apple peach banana",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #587 checking search results for apple peach banana with boost=true");
//Test #588 checking search results for peach fig fig banana kiwi with boost=true
yourResult = tester.search("peach fig fig banana kiwi", true, 100);
TestingTools.checkSearch(yourResult, "peach fig fig banana kiwi",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #588 checking search results for peach fig fig banana kiwi with boost=true");
//Test #589 checking search results for blueberry blueberry apricot with boost=true
yourResult = tester.search("blueberry blueberry apricot", true, 100);
TestingTools.checkSearch(yourResult, "blueberry blueberry apricot",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #589 checking search results for blueberry blueberry apricot with boost=true");
//Test #590 checking search results for blueberry strawberry with boost=true
yourResult = tester.search("blueberry strawberry", true, 100);
TestingTools.checkSearch(yourResult, "blueberry strawberry",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #590 checking search results for blueberry strawberry with boost=true");
//Test #591 checking search results for pear with boost=true
yourResult = tester.search("pear", true, 100);
TestingTools.checkSearch(yourResult, "pear",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #591 checking search results for pear with boost=true");
//Test #592 checking search results for pear with boost=true
yourResult = tester.search("pear", true, 100);
TestingTools.checkSearch(yourResult, "pear",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #592 checking search results for pear with boost=true");
//Test #593 checking search results for apricot with boost=true
yourResult = tester.search("apricot", true, 100);
TestingTools.checkSearch(yourResult, "apricot",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #593 checking search results for apricot with boost=true");
//Test #594 checking search results for apricot tomato apple strawberry with boost=true
yourResult = tester.search("apricot tomato apple strawberry", true, 100);
TestingTools.checkSearch(yourResult, "apricot tomato apple strawberry",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #594 checking search results for apricot tomato apple strawberry with boost=true");
//Test #595 checking search results for tomato papaya apple with boost=true
yourResult = tester.search("tomato papaya apple", true, 100);
TestingTools.checkSearch(yourResult, "tomato papaya apple",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #595 checking search results for tomato papaya apple with boost=true");
//Test #596 checking search results for coconut papaya fig peach kiwi with boost=true
yourResult = tester.search("coconut papaya fig peach kiwi", true, 100);
TestingTools.checkSearch(yourResult, "coconut papaya fig peach kiwi",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #596 checking search results for coconut papaya fig peach kiwi with boost=true");
//Test #597 checking search results for strawberry lime peach papaya blueberry with boost=true
yourResult = tester.search("strawberry lime peach papaya blueberry", true, 100);
TestingTools.checkSearch(yourResult, "strawberry lime peach papaya blueberry",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #597 checking search results for strawberry lime peach papaya blueberry with boost=true");
//Test #598 checking search results for apricot with boost=true
yourResult = tester.search("apricot", true, 100);
TestingTools.checkSearch(yourResult, "apricot",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #598 checking search results for apricot with boost=true");
//Test #599 checking search results for kiwi apricot with boost=true
yourResult = tester.search("kiwi apricot", true, 100);
TestingTools.checkSearch(yourResult, "kiwi apricot",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #599 checking search results for kiwi apricot with boost=true");
//Test #600 checking search results for peach peach with boost=true
yourResult = tester.search("peach peach", true, 100);
TestingTools.checkSearch(yourResult, "peach peach",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #600 checking search results for peach peach with boost=true");
//Test #601 checking search results for coconut kiwi blueberry peach banana with boost=true
yourResult = tester.search("coconut kiwi blueberry peach banana", true, 100);
TestingTools.checkSearch(yourResult, "coconut kiwi blueberry peach banana",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #601 checking search results for coconut kiwi blueberry peach banana with boost=true");
//Test #602 checking search results for kiwi with boost=true
yourResult = tester.search("kiwi", true, 100);
TestingTools.checkSearch(yourResult, "kiwi",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #602 checking search results for kiwi with boost=true");
//Test #603 checking search results for tomato peach with boost=true
yourResult = tester.search("tomato peach", true, 100);
TestingTools.checkSearch(yourResult, "tomato peach",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #603 checking search results for tomato peach with boost=true");
//Test #604 checking search results for papaya with boost=true
yourResult = tester.search("papaya", true, 100);
TestingTools.checkSearch(yourResult, "papaya",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #604 checking search results for papaya with boost=true");
//Test #605 checking search results for apricot papaya blueberry peach peach with boost=true
yourResult = tester.search("apricot papaya blueberry peach peach", true, 100);
TestingTools.checkSearch(yourResult, "apricot papaya blueberry peach peach",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #605 checking search results for apricot papaya blueberry peach peach with boost=true");
//Test #606 checking search results for banana blueberry with boost=true
yourResult = tester.search("banana blueberry", true, 100);
TestingTools.checkSearch(yourResult, "banana blueberry",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #606 checking search results for banana blueberry with boost=true");
//Test #607 checking search results for apricot fig apricot coconut with boost=true
yourResult = tester.search("apricot fig apricot coconut", true, 100);
TestingTools.checkSearch(yourResult, "apricot fig apricot coconut",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #607 checking search results for apricot fig apricot coconut with boost=true");
//Test #608 checking search results for strawberry with boost=true
yourResult = tester.search("strawberry", true, 100);
TestingTools.checkSearch(yourResult, "strawberry",true, passOut, failOut, "Fruits100SearchBoostTester", "Test #608 checking search results for strawberry with boost=true");
failOut.close();
passOut.close();
}
}
