import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.*;
public class FruitsASearchNoBoostTester {public static void main(String[] args) throws Exception{
ProjectTester tester = new ProjectTesterImp(); //Instantiate your own ProjectTester instance here
tester.initialize();
tester.crawl("https://people.scs.carleton.ca/~avamckenney/fruitsA/N-0.html");
runTest(tester);}public static void runTest(ProjectTester tester) throws Exception{
PrintWriter failOut = new PrintWriter(new FileWriter("FruitsA-SearchNoBoost-failed.txt"));
PrintWriter passOut = new PrintWriter(new FileWriter("FruitsA-SearchNoBoost-passed.txt"));
List<SearchResult> yourResult; 
//Test #409 checking search results for banana papaya with boost=true
yourResult = tester.search("banana papaya", false, 100);
TestingTools.checkSearch(yourResult, "banana papaya",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #409 checking search results for banana papaya with boost=true");
//Test #410 checking search results for kiwi kiwi apricot apricot with boost=true
yourResult = tester.search("kiwi kiwi apricot apricot", false, 100);
TestingTools.checkSearch(yourResult, "kiwi kiwi apricot apricot",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #410 checking search results for kiwi kiwi apricot apricot with boost=true");
//Test #411 checking search results for lime peach with boost=true
yourResult = tester.search("lime peach", false, 100);
TestingTools.checkSearch(yourResult, "lime peach",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #411 checking search results for lime peach with boost=true");
//Test #412 checking search results for blueberry with boost=true
yourResult = tester.search("blueberry", false, 100);
TestingTools.checkSearch(yourResult, "blueberry",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #412 checking search results for blueberry with boost=true");
//Test #413 checking search results for coconut pear peach with boost=true
yourResult = tester.search("coconut pear peach", false, 100);
TestingTools.checkSearch(yourResult, "coconut pear peach",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #413 checking search results for coconut pear peach with boost=true");
//Test #414 checking search results for coconut apricot pear apricot with boost=true
yourResult = tester.search("coconut apricot pear apricot", false, 100);
TestingTools.checkSearch(yourResult, "coconut apricot pear apricot",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #414 checking search results for coconut apricot pear apricot with boost=true");
//Test #415 checking search results for kiwi lime coconut apple with boost=true
yourResult = tester.search("kiwi lime coconut apple", false, 100);
TestingTools.checkSearch(yourResult, "kiwi lime coconut apple",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #415 checking search results for kiwi lime coconut apple with boost=true");
//Test #416 checking search results for banana kiwi with boost=true
yourResult = tester.search("banana kiwi", false, 100);
TestingTools.checkSearch(yourResult, "banana kiwi",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #416 checking search results for banana kiwi with boost=true");
//Test #417 checking search results for apple apricot with boost=true
yourResult = tester.search("apple apricot", false, 100);
TestingTools.checkSearch(yourResult, "apple apricot",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #417 checking search results for apple apricot with boost=true");
//Test #418 checking search results for peach with boost=true
yourResult = tester.search("peach", false, 100);
TestingTools.checkSearch(yourResult, "peach",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #418 checking search results for peach with boost=true");
//Test #419 checking search results for fig blueberry banana banana with boost=true
yourResult = tester.search("fig blueberry banana banana", false, 100);
TestingTools.checkSearch(yourResult, "fig blueberry banana banana",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #419 checking search results for fig blueberry banana banana with boost=true");
//Test #420 checking search results for lime kiwi peach blueberry with boost=true
yourResult = tester.search("lime kiwi peach blueberry", false, 100);
TestingTools.checkSearch(yourResult, "lime kiwi peach blueberry",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #420 checking search results for lime kiwi peach blueberry with boost=true");
//Test #421 checking search results for fig blueberry tomato coconut pear with boost=true
yourResult = tester.search("fig blueberry tomato coconut pear", false, 100);
TestingTools.checkSearch(yourResult, "fig blueberry tomato coconut pear",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #421 checking search results for fig blueberry tomato coconut pear with boost=true");
//Test #422 checking search results for fig strawberry blueberry tomato pear with boost=true
yourResult = tester.search("fig strawberry blueberry tomato pear", false, 100);
TestingTools.checkSearch(yourResult, "fig strawberry blueberry tomato pear",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #422 checking search results for fig strawberry blueberry tomato pear with boost=true");
//Test #423 checking search results for peach banana tomato kiwi coconut with boost=true
yourResult = tester.search("peach banana tomato kiwi coconut", false, 100);
TestingTools.checkSearch(yourResult, "peach banana tomato kiwi coconut",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #423 checking search results for peach banana tomato kiwi coconut with boost=true");
//Test #424 checking search results for peach cherry banana with boost=true
yourResult = tester.search("peach cherry banana", false, 100);
TestingTools.checkSearch(yourResult, "peach cherry banana",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #424 checking search results for peach cherry banana with boost=true");
//Test #425 checking search results for kiwi kiwi strawberry banana with boost=true
yourResult = tester.search("kiwi kiwi strawberry banana", false, 100);
TestingTools.checkSearch(yourResult, "kiwi kiwi strawberry banana",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #425 checking search results for kiwi kiwi strawberry banana with boost=true");
//Test #426 checking search results for apple apricot banana with boost=true
yourResult = tester.search("apple apricot banana", false, 100);
TestingTools.checkSearch(yourResult, "apple apricot banana",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #426 checking search results for apple apricot banana with boost=true");
//Test #427 checking search results for lime coconut fig with boost=true
yourResult = tester.search("lime coconut fig", false, 100);
TestingTools.checkSearch(yourResult, "lime coconut fig",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #427 checking search results for lime coconut fig with boost=true");
//Test #428 checking search results for apple kiwi peach apple cherry with boost=true
yourResult = tester.search("apple kiwi peach apple cherry", false, 100);
TestingTools.checkSearch(yourResult, "apple kiwi peach apple cherry",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #428 checking search results for apple kiwi peach apple cherry with boost=true");
//Test #429 checking search results for papaya banana kiwi with boost=true
yourResult = tester.search("papaya banana kiwi", false, 100);
TestingTools.checkSearch(yourResult, "papaya banana kiwi",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #429 checking search results for papaya banana kiwi with boost=true");
//Test #430 checking search results for tomato pear coconut with boost=true
yourResult = tester.search("tomato pear coconut", false, 100);
TestingTools.checkSearch(yourResult, "tomato pear coconut",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #430 checking search results for tomato pear coconut with boost=true");
//Test #431 checking search results for cherry peach pear pear with boost=true
yourResult = tester.search("cherry peach pear pear", false, 100);
TestingTools.checkSearch(yourResult, "cherry peach pear pear",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #431 checking search results for cherry peach pear pear with boost=true");
//Test #432 checking search results for papaya papaya with boost=true
yourResult = tester.search("papaya papaya", false, 100);
TestingTools.checkSearch(yourResult, "papaya papaya",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #432 checking search results for papaya papaya with boost=true");
//Test #433 checking search results for fig peach coconut kiwi with boost=true
yourResult = tester.search("fig peach coconut kiwi", false, 100);
TestingTools.checkSearch(yourResult, "fig peach coconut kiwi",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #433 checking search results for fig peach coconut kiwi with boost=true");
//Test #434 checking search results for papaya lime papaya pear fig with boost=true
yourResult = tester.search("papaya lime papaya pear fig", false, 100);
TestingTools.checkSearch(yourResult, "papaya lime papaya pear fig",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #434 checking search results for papaya lime papaya pear fig with boost=true");
//Test #435 checking search results for apricot with boost=true
yourResult = tester.search("apricot", false, 100);
TestingTools.checkSearch(yourResult, "apricot",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #435 checking search results for apricot with boost=true");
//Test #436 checking search results for lime kiwi with boost=true
yourResult = tester.search("lime kiwi", false, 100);
TestingTools.checkSearch(yourResult, "lime kiwi",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #436 checking search results for lime kiwi with boost=true");
//Test #437 checking search results for apple with boost=true
yourResult = tester.search("apple", false, 100);
TestingTools.checkSearch(yourResult, "apple",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #437 checking search results for apple with boost=true");
//Test #438 checking search results for blueberry with boost=true
yourResult = tester.search("blueberry", false, 100);
TestingTools.checkSearch(yourResult, "blueberry",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #438 checking search results for blueberry with boost=true");
//Test #439 checking search results for pear fig cherry with boost=true
yourResult = tester.search("pear fig cherry", false, 100);
TestingTools.checkSearch(yourResult, "pear fig cherry",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #439 checking search results for pear fig cherry with boost=true");
//Test #440 checking search results for apple banana apricot lime cherry with boost=true
yourResult = tester.search("apple banana apricot lime cherry", false, 100);
TestingTools.checkSearch(yourResult, "apple banana apricot lime cherry",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #440 checking search results for apple banana apricot lime cherry with boost=true");
//Test #441 checking search results for cherry kiwi pear cherry with boost=true
yourResult = tester.search("cherry kiwi pear cherry", false, 100);
TestingTools.checkSearch(yourResult, "cherry kiwi pear cherry",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #441 checking search results for cherry kiwi pear cherry with boost=true");
//Test #442 checking search results for pear cherry strawberry papaya papaya with boost=true
yourResult = tester.search("pear cherry strawberry papaya papaya", false, 100);
TestingTools.checkSearch(yourResult, "pear cherry strawberry papaya papaya",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #442 checking search results for pear cherry strawberry papaya papaya with boost=true");
//Test #443 checking search results for fig strawberry cherry banana tomato with boost=true
yourResult = tester.search("fig strawberry cherry banana tomato", false, 100);
TestingTools.checkSearch(yourResult, "fig strawberry cherry banana tomato",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #443 checking search results for fig strawberry cherry banana tomato with boost=true");
//Test #444 checking search results for lime kiwi with boost=true
yourResult = tester.search("lime kiwi", false, 100);
TestingTools.checkSearch(yourResult, "lime kiwi",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #444 checking search results for lime kiwi with boost=true");
//Test #445 checking search results for banana tomato with boost=true
yourResult = tester.search("banana tomato", false, 100);
TestingTools.checkSearch(yourResult, "banana tomato",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #445 checking search results for banana tomato with boost=true");
//Test #446 checking search results for apple tomato with boost=true
yourResult = tester.search("apple tomato", false, 100);
TestingTools.checkSearch(yourResult, "apple tomato",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #446 checking search results for apple tomato with boost=true");
//Test #447 checking search results for apple apple pear banana with boost=true
yourResult = tester.search("apple apple pear banana", false, 100);
TestingTools.checkSearch(yourResult, "apple apple pear banana",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #447 checking search results for apple apple pear banana with boost=true");
//Test #448 checking search results for peach lime lime apricot coconut with boost=true
yourResult = tester.search("peach lime lime apricot coconut", false, 100);
TestingTools.checkSearch(yourResult, "peach lime lime apricot coconut",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #448 checking search results for peach lime lime apricot coconut with boost=true");
//Test #449 checking search results for cherry kiwi with boost=true
yourResult = tester.search("cherry kiwi", false, 100);
TestingTools.checkSearch(yourResult, "cherry kiwi",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #449 checking search results for cherry kiwi with boost=true");
//Test #450 checking search results for lime with boost=true
yourResult = tester.search("lime", false, 100);
TestingTools.checkSearch(yourResult, "lime",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #450 checking search results for lime with boost=true");
//Test #451 checking search results for apricot with boost=true
yourResult = tester.search("apricot", false, 100);
TestingTools.checkSearch(yourResult, "apricot",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #451 checking search results for apricot with boost=true");
//Test #452 checking search results for banana coconut apricot coconut lime with boost=true
yourResult = tester.search("banana coconut apricot coconut lime", false, 100);
TestingTools.checkSearch(yourResult, "banana coconut apricot coconut lime",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #452 checking search results for banana coconut apricot coconut lime with boost=true");
//Test #453 checking search results for kiwi papaya kiwi with boost=true
yourResult = tester.search("kiwi papaya kiwi", false, 100);
TestingTools.checkSearch(yourResult, "kiwi papaya kiwi",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #453 checking search results for kiwi papaya kiwi with boost=true");
//Test #454 checking search results for lime tomato blueberry peach with boost=true
yourResult = tester.search("lime tomato blueberry peach", false, 100);
TestingTools.checkSearch(yourResult, "lime tomato blueberry peach",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #454 checking search results for lime tomato blueberry peach with boost=true");
//Test #455 checking search results for strawberry strawberry tomato apricot with boost=true
yourResult = tester.search("strawberry strawberry tomato apricot", false, 100);
TestingTools.checkSearch(yourResult, "strawberry strawberry tomato apricot",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #455 checking search results for strawberry strawberry tomato apricot with boost=true");
//Test #456 checking search results for fig with boost=true
yourResult = tester.search("fig", false, 100);
TestingTools.checkSearch(yourResult, "fig",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #456 checking search results for fig with boost=true");
//Test #457 checking search results for apricot peach apple fig papaya with boost=true
yourResult = tester.search("apricot peach apple fig papaya", false, 100);
TestingTools.checkSearch(yourResult, "apricot peach apple fig papaya",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #457 checking search results for apricot peach apple fig papaya with boost=true");
//Test #458 checking search results for apple strawberry with boost=true
yourResult = tester.search("apple strawberry", false, 100);
TestingTools.checkSearch(yourResult, "apple strawberry",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #458 checking search results for apple strawberry with boost=true");
//Test #459 checking search results for fig cherry fig with boost=true
yourResult = tester.search("fig cherry fig", false, 100);
TestingTools.checkSearch(yourResult, "fig cherry fig",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #459 checking search results for fig cherry fig with boost=true");
//Test #460 checking search results for apricot with boost=true
yourResult = tester.search("apricot", false, 100);
TestingTools.checkSearch(yourResult, "apricot",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #460 checking search results for apricot with boost=true");
//Test #461 checking search results for apple peach with boost=true
yourResult = tester.search("apple peach", false, 100);
TestingTools.checkSearch(yourResult, "apple peach",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #461 checking search results for apple peach with boost=true");
//Test #462 checking search results for papaya with boost=true
yourResult = tester.search("papaya", false, 100);
TestingTools.checkSearch(yourResult, "papaya",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #462 checking search results for papaya with boost=true");
//Test #463 checking search results for banana kiwi apple blueberry with boost=true
yourResult = tester.search("banana kiwi apple blueberry", false, 100);
TestingTools.checkSearch(yourResult, "banana kiwi apple blueberry",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #463 checking search results for banana kiwi apple blueberry with boost=true");
//Test #464 checking search results for cherry with boost=true
yourResult = tester.search("cherry", false, 100);
TestingTools.checkSearch(yourResult, "cherry",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #464 checking search results for cherry with boost=true");
//Test #465 checking search results for blueberry with boost=true
yourResult = tester.search("blueberry", false, 100);
TestingTools.checkSearch(yourResult, "blueberry",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #465 checking search results for blueberry with boost=true");
//Test #466 checking search results for blueberry pear with boost=true
yourResult = tester.search("blueberry pear", false, 100);
TestingTools.checkSearch(yourResult, "blueberry pear",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #466 checking search results for blueberry pear with boost=true");
//Test #467 checking search results for apple fig peach peach with boost=true
yourResult = tester.search("apple fig peach peach", false, 100);
TestingTools.checkSearch(yourResult, "apple fig peach peach",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #467 checking search results for apple fig peach peach with boost=true");
//Test #468 checking search results for kiwi papaya with boost=true
yourResult = tester.search("kiwi papaya", false, 100);
TestingTools.checkSearch(yourResult, "kiwi papaya",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #468 checking search results for kiwi papaya with boost=true");
//Test #469 checking search results for coconut coconut with boost=true
yourResult = tester.search("coconut coconut", false, 100);
TestingTools.checkSearch(yourResult, "coconut coconut",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #469 checking search results for coconut coconut with boost=true");
//Test #470 checking search results for tomato coconut strawberry banana with boost=true
yourResult = tester.search("tomato coconut strawberry banana", false, 100);
TestingTools.checkSearch(yourResult, "tomato coconut strawberry banana",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #470 checking search results for tomato coconut strawberry banana with boost=true");
//Test #471 checking search results for banana cherry banana cherry fig with boost=true
yourResult = tester.search("banana cherry banana cherry fig", false, 100);
TestingTools.checkSearch(yourResult, "banana cherry banana cherry fig",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #471 checking search results for banana cherry banana cherry fig with boost=true");
//Test #472 checking search results for pear tomato coconut with boost=true
yourResult = tester.search("pear tomato coconut", false, 100);
TestingTools.checkSearch(yourResult, "pear tomato coconut",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #472 checking search results for pear tomato coconut with boost=true");
//Test #473 checking search results for apple cherry with boost=true
yourResult = tester.search("apple cherry", false, 100);
TestingTools.checkSearch(yourResult, "apple cherry",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #473 checking search results for apple cherry with boost=true");
//Test #474 checking search results for cherry coconut coconut peach with boost=true
yourResult = tester.search("cherry coconut coconut peach", false, 100);
TestingTools.checkSearch(yourResult, "cherry coconut coconut peach",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #474 checking search results for cherry coconut coconut peach with boost=true");
//Test #475 checking search results for banana coconut coconut kiwi with boost=true
yourResult = tester.search("banana coconut coconut kiwi", false, 100);
TestingTools.checkSearch(yourResult, "banana coconut coconut kiwi",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #475 checking search results for banana coconut coconut kiwi with boost=true");
//Test #476 checking search results for tomato cherry fig with boost=true
yourResult = tester.search("tomato cherry fig", false, 100);
TestingTools.checkSearch(yourResult, "tomato cherry fig",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #476 checking search results for tomato cherry fig with boost=true");
//Test #477 checking search results for fig lime pear apple apricot with boost=true
yourResult = tester.search("fig lime pear apple apricot", false, 100);
TestingTools.checkSearch(yourResult, "fig lime pear apple apricot",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #477 checking search results for fig lime pear apple apricot with boost=true");
//Test #478 checking search results for apricot coconut kiwi apple apricot with boost=true
yourResult = tester.search("apricot coconut kiwi apple apricot", false, 100);
TestingTools.checkSearch(yourResult, "apricot coconut kiwi apple apricot",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #478 checking search results for apricot coconut kiwi apple apricot with boost=true");
//Test #479 checking search results for papaya papaya kiwi apricot papaya with boost=true
yourResult = tester.search("papaya papaya kiwi apricot papaya", false, 100);
TestingTools.checkSearch(yourResult, "papaya papaya kiwi apricot papaya",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #479 checking search results for papaya papaya kiwi apricot papaya with boost=true");
//Test #480 checking search results for blueberry tomato pear apple with boost=true
yourResult = tester.search("blueberry tomato pear apple", false, 100);
TestingTools.checkSearch(yourResult, "blueberry tomato pear apple",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #480 checking search results for blueberry tomato pear apple with boost=true");
//Test #481 checking search results for tomato lime with boost=true
yourResult = tester.search("tomato lime", false, 100);
TestingTools.checkSearch(yourResult, "tomato lime",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #481 checking search results for tomato lime with boost=true");
//Test #482 checking search results for papaya papaya apple kiwi coconut with boost=true
yourResult = tester.search("papaya papaya apple kiwi coconut", false, 100);
TestingTools.checkSearch(yourResult, "papaya papaya apple kiwi coconut",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #482 checking search results for papaya papaya apple kiwi coconut with boost=true");
//Test #483 checking search results for banana kiwi peach with boost=true
yourResult = tester.search("banana kiwi peach", false, 100);
TestingTools.checkSearch(yourResult, "banana kiwi peach",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #483 checking search results for banana kiwi peach with boost=true");
//Test #484 checking search results for tomato blueberry kiwi with boost=true
yourResult = tester.search("tomato blueberry kiwi", false, 100);
TestingTools.checkSearch(yourResult, "tomato blueberry kiwi",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #484 checking search results for tomato blueberry kiwi with boost=true");
//Test #485 checking search results for strawberry strawberry strawberry kiwi with boost=true
yourResult = tester.search("strawberry strawberry strawberry kiwi", false, 100);
TestingTools.checkSearch(yourResult, "strawberry strawberry strawberry kiwi",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #485 checking search results for strawberry strawberry strawberry kiwi with boost=true");
//Test #486 checking search results for lime with boost=true
yourResult = tester.search("lime", false, 100);
TestingTools.checkSearch(yourResult, "lime",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #486 checking search results for lime with boost=true");
//Test #487 checking search results for kiwi with boost=true
yourResult = tester.search("kiwi", false, 100);
TestingTools.checkSearch(yourResult, "kiwi",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #487 checking search results for kiwi with boost=true");
//Test #488 checking search results for tomato coconut with boost=true
yourResult = tester.search("tomato coconut", false, 100);
TestingTools.checkSearch(yourResult, "tomato coconut",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #488 checking search results for tomato coconut with boost=true");
//Test #489 checking search results for banana peach kiwi coconut with boost=true
yourResult = tester.search("banana peach kiwi coconut", false, 100);
TestingTools.checkSearch(yourResult, "banana peach kiwi coconut",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #489 checking search results for banana peach kiwi coconut with boost=true");
//Test #490 checking search results for apricot peach with boost=true
yourResult = tester.search("apricot peach", false, 100);
TestingTools.checkSearch(yourResult, "apricot peach",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #490 checking search results for apricot peach with boost=true");
//Test #491 checking search results for blueberry cherry blueberry apple strawberry with boost=true
yourResult = tester.search("blueberry cherry blueberry apple strawberry", false, 100);
TestingTools.checkSearch(yourResult, "blueberry cherry blueberry apple strawberry",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #491 checking search results for blueberry cherry blueberry apple strawberry with boost=true");
//Test #492 checking search results for coconut apricot banana with boost=true
yourResult = tester.search("coconut apricot banana", false, 100);
TestingTools.checkSearch(yourResult, "coconut apricot banana",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #492 checking search results for coconut apricot banana with boost=true");
//Test #493 checking search results for coconut strawberry with boost=true
yourResult = tester.search("coconut strawberry", false, 100);
TestingTools.checkSearch(yourResult, "coconut strawberry",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #493 checking search results for coconut strawberry with boost=true");
//Test #494 checking search results for cherry kiwi with boost=true
yourResult = tester.search("cherry kiwi", false, 100);
TestingTools.checkSearch(yourResult, "cherry kiwi",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #494 checking search results for cherry kiwi with boost=true");
//Test #495 checking search results for fig lime kiwi blueberry with boost=true
yourResult = tester.search("fig lime kiwi blueberry", false, 100);
TestingTools.checkSearch(yourResult, "fig lime kiwi blueberry",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #495 checking search results for fig lime kiwi blueberry with boost=true");
//Test #496 checking search results for strawberry with boost=true
yourResult = tester.search("strawberry", false, 100);
TestingTools.checkSearch(yourResult, "strawberry",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #496 checking search results for strawberry with boost=true");
//Test #497 checking search results for coconut papaya with boost=true
yourResult = tester.search("coconut papaya", false, 100);
TestingTools.checkSearch(yourResult, "coconut papaya",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #497 checking search results for coconut papaya with boost=true");
//Test #498 checking search results for kiwi with boost=true
yourResult = tester.search("kiwi", false, 100);
TestingTools.checkSearch(yourResult, "kiwi",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #498 checking search results for kiwi with boost=true");
//Test #499 checking search results for apricot cherry with boost=true
yourResult = tester.search("apricot cherry", false, 100);
TestingTools.checkSearch(yourResult, "apricot cherry",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #499 checking search results for apricot cherry with boost=true");
//Test #500 checking search results for peach blueberry with boost=true
yourResult = tester.search("peach blueberry", false, 100);
TestingTools.checkSearch(yourResult, "peach blueberry",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #500 checking search results for peach blueberry with boost=true");
//Test #501 checking search results for tomato cherry with boost=true
yourResult = tester.search("tomato cherry", false, 100);
TestingTools.checkSearch(yourResult, "tomato cherry",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #501 checking search results for tomato cherry with boost=true");
//Test #502 checking search results for fig banana fig apricot with boost=true
yourResult = tester.search("fig banana fig apricot", false, 100);
TestingTools.checkSearch(yourResult, "fig banana fig apricot",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #502 checking search results for fig banana fig apricot with boost=true");
//Test #503 checking search results for peach blueberry coconut apple with boost=true
yourResult = tester.search("peach blueberry coconut apple", false, 100);
TestingTools.checkSearch(yourResult, "peach blueberry coconut apple",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #503 checking search results for peach blueberry coconut apple with boost=true");
//Test #504 checking search results for tomato blueberry with boost=true
yourResult = tester.search("tomato blueberry", false, 100);
TestingTools.checkSearch(yourResult, "tomato blueberry",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #504 checking search results for tomato blueberry with boost=true");
//Test #505 checking search results for lime kiwi lime with boost=true
yourResult = tester.search("lime kiwi lime", false, 100);
TestingTools.checkSearch(yourResult, "lime kiwi lime",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #505 checking search results for lime kiwi lime with boost=true");
//Test #506 checking search results for kiwi strawberry cherry kiwi kiwi with boost=true
yourResult = tester.search("kiwi strawberry cherry kiwi kiwi", false, 100);
TestingTools.checkSearch(yourResult, "kiwi strawberry cherry kiwi kiwi",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #506 checking search results for kiwi strawberry cherry kiwi kiwi with boost=true");
//Test #507 checking search results for tomato papaya with boost=true
yourResult = tester.search("tomato papaya", false, 100);
TestingTools.checkSearch(yourResult, "tomato papaya",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #507 checking search results for tomato papaya with boost=true");
//Test #508 checking search results for kiwi fig coconut coconut with boost=true
yourResult = tester.search("kiwi fig coconut coconut", false, 100);
TestingTools.checkSearch(yourResult, "kiwi fig coconut coconut",false, passOut, failOut, "FruitsASearchNoBoostTester", "Test #508 checking search results for kiwi fig coconut coconut with boost=true");
failOut.close();
passOut.close();
}
}
