import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.*;
public class Fruits50SearchNoBoostTester {public static void main(String[] args) throws Exception{
ProjectTester tester = new ProjectTesterImp(); //Instantiate your own ProjectTester instance here
tester.initialize();
tester.crawl("https://people.scs.carleton.ca/~avamckenney/fruits50/N-0.html");
runTest(tester);}public static void runTest(ProjectTester tester) throws Exception{
PrintWriter failOut = new PrintWriter(new FileWriter("Fruits50-SearchNoBoost-failed.txt"));
PrintWriter passOut = new PrintWriter(new FileWriter("Fruits50-SearchNoBoost-passed.txt"));
List<SearchResult> yourResult; 
//Test #409 checking search results for lime apple blueberry coconut with boost=true
yourResult = tester.search("lime apple blueberry coconut", false, 50);
TestingTools.checkSearch(yourResult, "lime apple blueberry coconut",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #409 checking search results for lime apple blueberry coconut with boost=true");
//Test #410 checking search results for banana with boost=true
yourResult = tester.search("banana", false, 50);
TestingTools.checkSearch(yourResult, "banana",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #410 checking search results for banana with boost=true");
//Test #411 checking search results for banana fig kiwi coconut apricot with boost=true
yourResult = tester.search("banana fig kiwi coconut apricot", false, 50);
TestingTools.checkSearch(yourResult, "banana fig kiwi coconut apricot",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #411 checking search results for banana fig kiwi coconut apricot with boost=true");
//Test #412 checking search results for strawberry kiwi fig with boost=true
yourResult = tester.search("strawberry kiwi fig", false, 50);
TestingTools.checkSearch(yourResult, "strawberry kiwi fig",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #412 checking search results for strawberry kiwi fig with boost=true");
//Test #413 checking search results for cherry with boost=true
yourResult = tester.search("cherry", false, 50);
TestingTools.checkSearch(yourResult, "cherry",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #413 checking search results for cherry with boost=true");
//Test #414 checking search results for apricot apricot with boost=true
yourResult = tester.search("apricot apricot", false, 50);
TestingTools.checkSearch(yourResult, "apricot apricot",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #414 checking search results for apricot apricot with boost=true");
//Test #415 checking search results for peach apple apple kiwi with boost=true
yourResult = tester.search("peach apple apple kiwi", false, 50);
TestingTools.checkSearch(yourResult, "peach apple apple kiwi",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #415 checking search results for peach apple apple kiwi with boost=true");
//Test #416 checking search results for fig apricot blueberry fig papaya with boost=true
yourResult = tester.search("fig apricot blueberry fig papaya", false, 50);
TestingTools.checkSearch(yourResult, "fig apricot blueberry fig papaya",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #416 checking search results for fig apricot blueberry fig papaya with boost=true");
//Test #417 checking search results for apricot strawberry strawberry with boost=true
yourResult = tester.search("apricot strawberry strawberry", false, 50);
TestingTools.checkSearch(yourResult, "apricot strawberry strawberry",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #417 checking search results for apricot strawberry strawberry with boost=true");
//Test #418 checking search results for kiwi with boost=true
yourResult = tester.search("kiwi", false, 50);
TestingTools.checkSearch(yourResult, "kiwi",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #418 checking search results for kiwi with boost=true");
//Test #419 checking search results for strawberry with boost=true
yourResult = tester.search("strawberry", false, 50);
TestingTools.checkSearch(yourResult, "strawberry",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #419 checking search results for strawberry with boost=true");
//Test #420 checking search results for pear strawberry fig with boost=true
yourResult = tester.search("pear strawberry fig", false, 50);
TestingTools.checkSearch(yourResult, "pear strawberry fig",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #420 checking search results for pear strawberry fig with boost=true");
//Test #421 checking search results for coconut coconut with boost=true
yourResult = tester.search("coconut coconut", false, 50);
TestingTools.checkSearch(yourResult, "coconut coconut",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #421 checking search results for coconut coconut with boost=true");
//Test #422 checking search results for lime pear apricot with boost=true
yourResult = tester.search("lime pear apricot", false, 50);
TestingTools.checkSearch(yourResult, "lime pear apricot",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #422 checking search results for lime pear apricot with boost=true");
//Test #423 checking search results for tomato banana apricot coconut lime with boost=true
yourResult = tester.search("tomato banana apricot coconut lime", false, 50);
TestingTools.checkSearch(yourResult, "tomato banana apricot coconut lime",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #423 checking search results for tomato banana apricot coconut lime with boost=true");
//Test #424 checking search results for pear apricot kiwi with boost=true
yourResult = tester.search("pear apricot kiwi", false, 50);
TestingTools.checkSearch(yourResult, "pear apricot kiwi",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #424 checking search results for pear apricot kiwi with boost=true");
//Test #425 checking search results for lime coconut with boost=true
yourResult = tester.search("lime coconut", false, 50);
TestingTools.checkSearch(yourResult, "lime coconut",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #425 checking search results for lime coconut with boost=true");
//Test #426 checking search results for strawberry coconut strawberry peach banana with boost=true
yourResult = tester.search("strawberry coconut strawberry peach banana", false, 50);
TestingTools.checkSearch(yourResult, "strawberry coconut strawberry peach banana",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #426 checking search results for strawberry coconut strawberry peach banana with boost=true");
//Test #427 checking search results for tomato strawberry kiwi with boost=true
yourResult = tester.search("tomato strawberry kiwi", false, 50);
TestingTools.checkSearch(yourResult, "tomato strawberry kiwi",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #427 checking search results for tomato strawberry kiwi with boost=true");
//Test #428 checking search results for papaya with boost=true
yourResult = tester.search("papaya", false, 50);
TestingTools.checkSearch(yourResult, "papaya",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #428 checking search results for papaya with boost=true");
//Test #429 checking search results for banana with boost=true
yourResult = tester.search("banana", false, 50);
TestingTools.checkSearch(yourResult, "banana",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #429 checking search results for banana with boost=true");
//Test #430 checking search results for banana with boost=true
yourResult = tester.search("banana", false, 50);
TestingTools.checkSearch(yourResult, "banana",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #430 checking search results for banana with boost=true");
//Test #431 checking search results for apple with boost=true
yourResult = tester.search("apple", false, 50);
TestingTools.checkSearch(yourResult, "apple",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #431 checking search results for apple with boost=true");
//Test #432 checking search results for tomato cherry coconut with boost=true
yourResult = tester.search("tomato cherry coconut", false, 50);
TestingTools.checkSearch(yourResult, "tomato cherry coconut",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #432 checking search results for tomato cherry coconut with boost=true");
//Test #433 checking search results for pear blueberry kiwi banana blueberry with boost=true
yourResult = tester.search("pear blueberry kiwi banana blueberry", false, 50);
TestingTools.checkSearch(yourResult, "pear blueberry kiwi banana blueberry",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #433 checking search results for pear blueberry kiwi banana blueberry with boost=true");
//Test #434 checking search results for banana fig strawberry papaya kiwi with boost=true
yourResult = tester.search("banana fig strawberry papaya kiwi", false, 50);
TestingTools.checkSearch(yourResult, "banana fig strawberry papaya kiwi",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #434 checking search results for banana fig strawberry papaya kiwi with boost=true");
//Test #435 checking search results for coconut peach papaya strawberry with boost=true
yourResult = tester.search("coconut peach papaya strawberry", false, 50);
TestingTools.checkSearch(yourResult, "coconut peach papaya strawberry",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #435 checking search results for coconut peach papaya strawberry with boost=true");
//Test #436 checking search results for pear apricot blueberry apple tomato with boost=true
yourResult = tester.search("pear apricot blueberry apple tomato", false, 50);
TestingTools.checkSearch(yourResult, "pear apricot blueberry apple tomato",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #436 checking search results for pear apricot blueberry apple tomato with boost=true");
//Test #437 checking search results for pear cherry strawberry apricot with boost=true
yourResult = tester.search("pear cherry strawberry apricot", false, 50);
TestingTools.checkSearch(yourResult, "pear cherry strawberry apricot",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #437 checking search results for pear cherry strawberry apricot with boost=true");
//Test #438 checking search results for apple apricot with boost=true
yourResult = tester.search("apple apricot", false, 50);
TestingTools.checkSearch(yourResult, "apple apricot",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #438 checking search results for apple apricot with boost=true");
//Test #439 checking search results for peach cherry pear with boost=true
yourResult = tester.search("peach cherry pear", false, 50);
TestingTools.checkSearch(yourResult, "peach cherry pear",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #439 checking search results for peach cherry pear with boost=true");
//Test #440 checking search results for strawberry with boost=true
yourResult = tester.search("strawberry", false, 50);
TestingTools.checkSearch(yourResult, "strawberry",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #440 checking search results for strawberry with boost=true");
//Test #441 checking search results for apple pear lime kiwi blueberry with boost=true
yourResult = tester.search("apple pear lime kiwi blueberry", false, 50);
TestingTools.checkSearch(yourResult, "apple pear lime kiwi blueberry",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #441 checking search results for apple pear lime kiwi blueberry with boost=true");
//Test #442 checking search results for apple with boost=true
yourResult = tester.search("apple", false, 50);
TestingTools.checkSearch(yourResult, "apple",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #442 checking search results for apple with boost=true");
//Test #443 checking search results for coconut papaya banana with boost=true
yourResult = tester.search("coconut papaya banana", false, 50);
TestingTools.checkSearch(yourResult, "coconut papaya banana",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #443 checking search results for coconut papaya banana with boost=true");
//Test #444 checking search results for coconut peach peach banana with boost=true
yourResult = tester.search("coconut peach peach banana", false, 50);
TestingTools.checkSearch(yourResult, "coconut peach peach banana",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #444 checking search results for coconut peach peach banana with boost=true");
//Test #445 checking search results for apple with boost=true
yourResult = tester.search("apple", false, 50);
TestingTools.checkSearch(yourResult, "apple",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #445 checking search results for apple with boost=true");
//Test #446 checking search results for papaya lime banana kiwi with boost=true
yourResult = tester.search("papaya lime banana kiwi", false, 50);
TestingTools.checkSearch(yourResult, "papaya lime banana kiwi",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #446 checking search results for papaya lime banana kiwi with boost=true");
//Test #447 checking search results for apple apple kiwi with boost=true
yourResult = tester.search("apple apple kiwi", false, 50);
TestingTools.checkSearch(yourResult, "apple apple kiwi",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #447 checking search results for apple apple kiwi with boost=true");
//Test #448 checking search results for kiwi lime coconut apricot apple with boost=true
yourResult = tester.search("kiwi lime coconut apricot apple", false, 50);
TestingTools.checkSearch(yourResult, "kiwi lime coconut apricot apple",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #448 checking search results for kiwi lime coconut apricot apple with boost=true");
//Test #449 checking search results for fig pear tomato coconut with boost=true
yourResult = tester.search("fig pear tomato coconut", false, 50);
TestingTools.checkSearch(yourResult, "fig pear tomato coconut",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #449 checking search results for fig pear tomato coconut with boost=true");
//Test #450 checking search results for tomato tomato papaya strawberry tomato with boost=true
yourResult = tester.search("tomato tomato papaya strawberry tomato", false, 50);
TestingTools.checkSearch(yourResult, "tomato tomato papaya strawberry tomato",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #450 checking search results for tomato tomato papaya strawberry tomato with boost=true");
//Test #451 checking search results for lime with boost=true
yourResult = tester.search("lime", false, 50);
TestingTools.checkSearch(yourResult, "lime",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #451 checking search results for lime with boost=true");
//Test #452 checking search results for kiwi with boost=true
yourResult = tester.search("kiwi", false, 50);
TestingTools.checkSearch(yourResult, "kiwi",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #452 checking search results for kiwi with boost=true");
//Test #453 checking search results for fig with boost=true
yourResult = tester.search("fig", false, 50);
TestingTools.checkSearch(yourResult, "fig",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #453 checking search results for fig with boost=true");
//Test #454 checking search results for peach banana with boost=true
yourResult = tester.search("peach banana", false, 50);
TestingTools.checkSearch(yourResult, "peach banana",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #454 checking search results for peach banana with boost=true");
//Test #455 checking search results for blueberry with boost=true
yourResult = tester.search("blueberry", false, 50);
TestingTools.checkSearch(yourResult, "blueberry",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #455 checking search results for blueberry with boost=true");
//Test #456 checking search results for kiwi pear with boost=true
yourResult = tester.search("kiwi pear", false, 50);
TestingTools.checkSearch(yourResult, "kiwi pear",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #456 checking search results for kiwi pear with boost=true");
//Test #457 checking search results for banana cherry coconut with boost=true
yourResult = tester.search("banana cherry coconut", false, 50);
TestingTools.checkSearch(yourResult, "banana cherry coconut",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #457 checking search results for banana cherry coconut with boost=true");
//Test #458 checking search results for pear apricot lime with boost=true
yourResult = tester.search("pear apricot lime", false, 50);
TestingTools.checkSearch(yourResult, "pear apricot lime",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #458 checking search results for pear apricot lime with boost=true");
//Test #459 checking search results for cherry blueberry apple with boost=true
yourResult = tester.search("cherry blueberry apple", false, 50);
TestingTools.checkSearch(yourResult, "cherry blueberry apple",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #459 checking search results for cherry blueberry apple with boost=true");
//Test #460 checking search results for apricot cherry strawberry strawberry pear with boost=true
yourResult = tester.search("apricot cherry strawberry strawberry pear", false, 50);
TestingTools.checkSearch(yourResult, "apricot cherry strawberry strawberry pear",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #460 checking search results for apricot cherry strawberry strawberry pear with boost=true");
//Test #461 checking search results for peach blueberry papaya blueberry blueberry with boost=true
yourResult = tester.search("peach blueberry papaya blueberry blueberry", false, 50);
TestingTools.checkSearch(yourResult, "peach blueberry papaya blueberry blueberry",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #461 checking search results for peach blueberry papaya blueberry blueberry with boost=true");
//Test #462 checking search results for lime tomato with boost=true
yourResult = tester.search("lime tomato", false, 50);
TestingTools.checkSearch(yourResult, "lime tomato",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #462 checking search results for lime tomato with boost=true");
//Test #463 checking search results for cherry lime with boost=true
yourResult = tester.search("cherry lime", false, 50);
TestingTools.checkSearch(yourResult, "cherry lime",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #463 checking search results for cherry lime with boost=true");
//Test #464 checking search results for strawberry blueberry papaya pear papaya with boost=true
yourResult = tester.search("strawberry blueberry papaya pear papaya", false, 50);
TestingTools.checkSearch(yourResult, "strawberry blueberry papaya pear papaya",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #464 checking search results for strawberry blueberry papaya pear papaya with boost=true");
//Test #465 checking search results for fig peach with boost=true
yourResult = tester.search("fig peach", false, 50);
TestingTools.checkSearch(yourResult, "fig peach",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #465 checking search results for fig peach with boost=true");
//Test #466 checking search results for kiwi papaya peach with boost=true
yourResult = tester.search("kiwi papaya peach", false, 50);
TestingTools.checkSearch(yourResult, "kiwi papaya peach",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #466 checking search results for kiwi papaya peach with boost=true");
//Test #467 checking search results for lime banana banana blueberry with boost=true
yourResult = tester.search("lime banana banana blueberry", false, 50);
TestingTools.checkSearch(yourResult, "lime banana banana blueberry",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #467 checking search results for lime banana banana blueberry with boost=true");
//Test #468 checking search results for fig with boost=true
yourResult = tester.search("fig", false, 50);
TestingTools.checkSearch(yourResult, "fig",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #468 checking search results for fig with boost=true");
//Test #469 checking search results for blueberry fig with boost=true
yourResult = tester.search("blueberry fig", false, 50);
TestingTools.checkSearch(yourResult, "blueberry fig",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #469 checking search results for blueberry fig with boost=true");
//Test #470 checking search results for apple tomato blueberry cherry with boost=true
yourResult = tester.search("apple tomato blueberry cherry", false, 50);
TestingTools.checkSearch(yourResult, "apple tomato blueberry cherry",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #470 checking search results for apple tomato blueberry cherry with boost=true");
//Test #471 checking search results for banana pear tomato fig apple with boost=true
yourResult = tester.search("banana pear tomato fig apple", false, 50);
TestingTools.checkSearch(yourResult, "banana pear tomato fig apple",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #471 checking search results for banana pear tomato fig apple with boost=true");
//Test #472 checking search results for lime coconut with boost=true
yourResult = tester.search("lime coconut", false, 50);
TestingTools.checkSearch(yourResult, "lime coconut",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #472 checking search results for lime coconut with boost=true");
//Test #473 checking search results for kiwi peach kiwi with boost=true
yourResult = tester.search("kiwi peach kiwi", false, 50);
TestingTools.checkSearch(yourResult, "kiwi peach kiwi",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #473 checking search results for kiwi peach kiwi with boost=true");
//Test #474 checking search results for papaya with boost=true
yourResult = tester.search("papaya", false, 50);
TestingTools.checkSearch(yourResult, "papaya",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #474 checking search results for papaya with boost=true");
//Test #475 checking search results for apple lime with boost=true
yourResult = tester.search("apple lime", false, 50);
TestingTools.checkSearch(yourResult, "apple lime",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #475 checking search results for apple lime with boost=true");
//Test #476 checking search results for blueberry with boost=true
yourResult = tester.search("blueberry", false, 50);
TestingTools.checkSearch(yourResult, "blueberry",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #476 checking search results for blueberry with boost=true");
//Test #477 checking search results for papaya strawberry apple with boost=true
yourResult = tester.search("papaya strawberry apple", false, 50);
TestingTools.checkSearch(yourResult, "papaya strawberry apple",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #477 checking search results for papaya strawberry apple with boost=true");
//Test #478 checking search results for coconut coconut blueberry strawberry with boost=true
yourResult = tester.search("coconut coconut blueberry strawberry", false, 50);
TestingTools.checkSearch(yourResult, "coconut coconut blueberry strawberry",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #478 checking search results for coconut coconut blueberry strawberry with boost=true");
//Test #479 checking search results for apple tomato with boost=true
yourResult = tester.search("apple tomato", false, 50);
TestingTools.checkSearch(yourResult, "apple tomato",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #479 checking search results for apple tomato with boost=true");
//Test #480 checking search results for papaya fig with boost=true
yourResult = tester.search("papaya fig", false, 50);
TestingTools.checkSearch(yourResult, "papaya fig",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #480 checking search results for papaya fig with boost=true");
//Test #481 checking search results for apple with boost=true
yourResult = tester.search("apple", false, 50);
TestingTools.checkSearch(yourResult, "apple",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #481 checking search results for apple with boost=true");
//Test #482 checking search results for kiwi apple with boost=true
yourResult = tester.search("kiwi apple", false, 50);
TestingTools.checkSearch(yourResult, "kiwi apple",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #482 checking search results for kiwi apple with boost=true");
//Test #483 checking search results for lime papaya pear pear fig with boost=true
yourResult = tester.search("lime papaya pear pear fig", false, 50);
TestingTools.checkSearch(yourResult, "lime papaya pear pear fig",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #483 checking search results for lime papaya pear pear fig with boost=true");
//Test #484 checking search results for lime with boost=true
yourResult = tester.search("lime", false, 50);
TestingTools.checkSearch(yourResult, "lime",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #484 checking search results for lime with boost=true");
//Test #485 checking search results for strawberry fig coconut coconut kiwi with boost=true
yourResult = tester.search("strawberry fig coconut coconut kiwi", false, 50);
TestingTools.checkSearch(yourResult, "strawberry fig coconut coconut kiwi",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #485 checking search results for strawberry fig coconut coconut kiwi with boost=true");
//Test #486 checking search results for lime banana with boost=true
yourResult = tester.search("lime banana", false, 50);
TestingTools.checkSearch(yourResult, "lime banana",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #486 checking search results for lime banana with boost=true");
//Test #487 checking search results for cherry strawberry fig papaya apple with boost=true
yourResult = tester.search("cherry strawberry fig papaya apple", false, 50);
TestingTools.checkSearch(yourResult, "cherry strawberry fig papaya apple",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #487 checking search results for cherry strawberry fig papaya apple with boost=true");
//Test #488 checking search results for cherry with boost=true
yourResult = tester.search("cherry", false, 50);
TestingTools.checkSearch(yourResult, "cherry",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #488 checking search results for cherry with boost=true");
//Test #489 checking search results for banana lime peach papaya with boost=true
yourResult = tester.search("banana lime peach papaya", false, 50);
TestingTools.checkSearch(yourResult, "banana lime peach papaya",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #489 checking search results for banana lime peach papaya with boost=true");
//Test #490 checking search results for peach fig cherry kiwi tomato with boost=true
yourResult = tester.search("peach fig cherry kiwi tomato", false, 50);
TestingTools.checkSearch(yourResult, "peach fig cherry kiwi tomato",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #490 checking search results for peach fig cherry kiwi tomato with boost=true");
//Test #491 checking search results for banana with boost=true
yourResult = tester.search("banana", false, 50);
TestingTools.checkSearch(yourResult, "banana",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #491 checking search results for banana with boost=true");
//Test #492 checking search results for blueberry peach papaya apricot apricot with boost=true
yourResult = tester.search("blueberry peach papaya apricot apricot", false, 50);
TestingTools.checkSearch(yourResult, "blueberry peach papaya apricot apricot",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #492 checking search results for blueberry peach papaya apricot apricot with boost=true");
//Test #493 checking search results for apricot papaya with boost=true
yourResult = tester.search("apricot papaya", false, 50);
TestingTools.checkSearch(yourResult, "apricot papaya",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #493 checking search results for apricot papaya with boost=true");
//Test #494 checking search results for blueberry tomato with boost=true
yourResult = tester.search("blueberry tomato", false, 50);
TestingTools.checkSearch(yourResult, "blueberry tomato",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #494 checking search results for blueberry tomato with boost=true");
//Test #495 checking search results for coconut fig tomato peach with boost=true
yourResult = tester.search("coconut fig tomato peach", false, 50);
TestingTools.checkSearch(yourResult, "coconut fig tomato peach",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #495 checking search results for coconut fig tomato peach with boost=true");
//Test #496 checking search results for apricot with boost=true
yourResult = tester.search("apricot", false, 50);
TestingTools.checkSearch(yourResult, "apricot",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #496 checking search results for apricot with boost=true");
//Test #497 checking search results for strawberry papaya kiwi with boost=true
yourResult = tester.search("strawberry papaya kiwi", false, 50);
TestingTools.checkSearch(yourResult, "strawberry papaya kiwi",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #497 checking search results for strawberry papaya kiwi with boost=true");
//Test #498 checking search results for apricot tomato apple with boost=true
yourResult = tester.search("apricot tomato apple", false, 50);
TestingTools.checkSearch(yourResult, "apricot tomato apple",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #498 checking search results for apricot tomato apple with boost=true");
//Test #499 checking search results for banana kiwi with boost=true
yourResult = tester.search("banana kiwi", false, 50);
TestingTools.checkSearch(yourResult, "banana kiwi",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #499 checking search results for banana kiwi with boost=true");
//Test #500 checking search results for strawberry with boost=true
yourResult = tester.search("strawberry", false, 50);
TestingTools.checkSearch(yourResult, "strawberry",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #500 checking search results for strawberry with boost=true");
//Test #501 checking search results for lime with boost=true
yourResult = tester.search("lime", false, 50);
TestingTools.checkSearch(yourResult, "lime",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #501 checking search results for lime with boost=true");
//Test #502 checking search results for peach pear with boost=true
yourResult = tester.search("peach pear", false, 50);
TestingTools.checkSearch(yourResult, "peach pear",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #502 checking search results for peach pear with boost=true");
//Test #503 checking search results for tomato pear with boost=true
yourResult = tester.search("tomato pear", false, 50);
TestingTools.checkSearch(yourResult, "tomato pear",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #503 checking search results for tomato pear with boost=true");
//Test #504 checking search results for coconut blueberry banana strawberry with boost=true
yourResult = tester.search("coconut blueberry banana strawberry", false, 50);
TestingTools.checkSearch(yourResult, "coconut blueberry banana strawberry",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #504 checking search results for coconut blueberry banana strawberry with boost=true");
//Test #505 checking search results for peach strawberry papaya with boost=true
yourResult = tester.search("peach strawberry papaya", false, 50);
TestingTools.checkSearch(yourResult, "peach strawberry papaya",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #505 checking search results for peach strawberry papaya with boost=true");
//Test #506 checking search results for peach strawberry blueberry with boost=true
yourResult = tester.search("peach strawberry blueberry", false, 50);
TestingTools.checkSearch(yourResult, "peach strawberry blueberry",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #506 checking search results for peach strawberry blueberry with boost=true");
//Test #507 checking search results for fig kiwi with boost=true
yourResult = tester.search("fig kiwi", false, 50);
TestingTools.checkSearch(yourResult, "fig kiwi",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #507 checking search results for fig kiwi with boost=true");
//Test #508 checking search results for blueberry cherry with boost=true
yourResult = tester.search("blueberry cherry", false, 50);
TestingTools.checkSearch(yourResult, "blueberry cherry",false, passOut, failOut, "Fruits50SearchNoBoostTester", "Test #508 checking search results for blueberry cherry with boost=true");
failOut.close();
passOut.close();
}
}
