import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.*;
public class Fruits50SearchBoostTester {public static void main(String[] args) throws Exception{
ProjectTester tester = new ProjectTesterImp(); //Instantiate your own ProjectTester instance here
tester.initialize();
tester.crawl("https://people.scs.carleton.ca/~avamckenney/fruits50/N-0.html");
runTest(tester);}public static void runTest(ProjectTester tester) throws Exception{
PrintWriter failOut = new PrintWriter(new FileWriter("Fruits50-SearchBoost-failed.txt"));
PrintWriter passOut = new PrintWriter(new FileWriter("Fruits50-SearchBoost-passed.txt"));
List<SearchResult> yourResult; 
//Test #509 checking search results for apricot cherry coconut tomato tomato with boost=true
yourResult = tester.search("apricot cherry coconut tomato tomato", true, 50);
TestingTools.checkSearch(yourResult, "apricot cherry coconut tomato tomato",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #509 checking search results for apricot cherry coconut tomato tomato with boost=true");
//Test #510 checking search results for fig blueberry with boost=true
yourResult = tester.search("fig blueberry", true, 50);
TestingTools.checkSearch(yourResult, "fig blueberry",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #510 checking search results for fig blueberry with boost=true");
//Test #511 checking search results for strawberry strawberry cherry peach banana with boost=true
yourResult = tester.search("strawberry strawberry cherry peach banana", true, 50);
TestingTools.checkSearch(yourResult, "strawberry strawberry cherry peach banana",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #511 checking search results for strawberry strawberry cherry peach banana with boost=true");
//Test #512 checking search results for coconut pear papaya banana with boost=true
yourResult = tester.search("coconut pear papaya banana", true, 50);
TestingTools.checkSearch(yourResult, "coconut pear papaya banana",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #512 checking search results for coconut pear papaya banana with boost=true");
//Test #513 checking search results for kiwi with boost=true
yourResult = tester.search("kiwi", true, 50);
TestingTools.checkSearch(yourResult, "kiwi",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #513 checking search results for kiwi with boost=true");
//Test #514 checking search results for strawberry apricot lime with boost=true
yourResult = tester.search("strawberry apricot lime", true, 50);
TestingTools.checkSearch(yourResult, "strawberry apricot lime",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #514 checking search results for strawberry apricot lime with boost=true");
//Test #515 checking search results for blueberry strawberry blueberry blueberry apricot with boost=true
yourResult = tester.search("blueberry strawberry blueberry blueberry apricot", true, 50);
TestingTools.checkSearch(yourResult, "blueberry strawberry blueberry blueberry apricot",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #515 checking search results for blueberry strawberry blueberry blueberry apricot with boost=true");
//Test #516 checking search results for fig kiwi apple pear fig with boost=true
yourResult = tester.search("fig kiwi apple pear fig", true, 50);
TestingTools.checkSearch(yourResult, "fig kiwi apple pear fig",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #516 checking search results for fig kiwi apple pear fig with boost=true");
//Test #517 checking search results for banana apricot with boost=true
yourResult = tester.search("banana apricot", true, 50);
TestingTools.checkSearch(yourResult, "banana apricot",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #517 checking search results for banana apricot with boost=true");
//Test #518 checking search results for papaya blueberry lime blueberry blueberry with boost=true
yourResult = tester.search("papaya blueberry lime blueberry blueberry", true, 50);
TestingTools.checkSearch(yourResult, "papaya blueberry lime blueberry blueberry",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #518 checking search results for papaya blueberry lime blueberry blueberry with boost=true");
//Test #519 checking search results for fig with boost=true
yourResult = tester.search("fig", true, 50);
TestingTools.checkSearch(yourResult, "fig",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #519 checking search results for fig with boost=true");
//Test #520 checking search results for apple strawberry peach tomato with boost=true
yourResult = tester.search("apple strawberry peach tomato", true, 50);
TestingTools.checkSearch(yourResult, "apple strawberry peach tomato",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #520 checking search results for apple strawberry peach tomato with boost=true");
//Test #521 checking search results for apple fig blueberry with boost=true
yourResult = tester.search("apple fig blueberry", true, 50);
TestingTools.checkSearch(yourResult, "apple fig blueberry",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #521 checking search results for apple fig blueberry with boost=true");
//Test #522 checking search results for banana coconut pear apple with boost=true
yourResult = tester.search("banana coconut pear apple", true, 50);
TestingTools.checkSearch(yourResult, "banana coconut pear apple",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #522 checking search results for banana coconut pear apple with boost=true");
//Test #523 checking search results for kiwi blueberry banana with boost=true
yourResult = tester.search("kiwi blueberry banana", true, 50);
TestingTools.checkSearch(yourResult, "kiwi blueberry banana",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #523 checking search results for kiwi blueberry banana with boost=true");
//Test #524 checking search results for apricot with boost=true
yourResult = tester.search("apricot", true, 50);
TestingTools.checkSearch(yourResult, "apricot",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #524 checking search results for apricot with boost=true");
//Test #525 checking search results for coconut pear with boost=true
yourResult = tester.search("coconut pear", true, 50);
TestingTools.checkSearch(yourResult, "coconut pear",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #525 checking search results for coconut pear with boost=true");
//Test #526 checking search results for kiwi peach papaya blueberry with boost=true
yourResult = tester.search("kiwi peach papaya blueberry", true, 50);
TestingTools.checkSearch(yourResult, "kiwi peach papaya blueberry",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #526 checking search results for kiwi peach papaya blueberry with boost=true");
//Test #527 checking search results for papaya kiwi apricot apple peach with boost=true
yourResult = tester.search("papaya kiwi apricot apple peach", true, 50);
TestingTools.checkSearch(yourResult, "papaya kiwi apricot apple peach",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #527 checking search results for papaya kiwi apricot apple peach with boost=true");
//Test #528 checking search results for lime cherry peach lime kiwi with boost=true
yourResult = tester.search("lime cherry peach lime kiwi", true, 50);
TestingTools.checkSearch(yourResult, "lime cherry peach lime kiwi",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #528 checking search results for lime cherry peach lime kiwi with boost=true");
//Test #529 checking search results for strawberry peach coconut with boost=true
yourResult = tester.search("strawberry peach coconut", true, 50);
TestingTools.checkSearch(yourResult, "strawberry peach coconut",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #529 checking search results for strawberry peach coconut with boost=true");
//Test #530 checking search results for fig tomato kiwi apple pear with boost=true
yourResult = tester.search("fig tomato kiwi apple pear", true, 50);
TestingTools.checkSearch(yourResult, "fig tomato kiwi apple pear",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #530 checking search results for fig tomato kiwi apple pear with boost=true");
//Test #531 checking search results for blueberry peach tomato with boost=true
yourResult = tester.search("blueberry peach tomato", true, 50);
TestingTools.checkSearch(yourResult, "blueberry peach tomato",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #531 checking search results for blueberry peach tomato with boost=true");
//Test #532 checking search results for apple papaya strawberry papaya with boost=true
yourResult = tester.search("apple papaya strawberry papaya", true, 50);
TestingTools.checkSearch(yourResult, "apple papaya strawberry papaya",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #532 checking search results for apple papaya strawberry papaya with boost=true");
//Test #533 checking search results for tomato strawberry with boost=true
yourResult = tester.search("tomato strawberry", true, 50);
TestingTools.checkSearch(yourResult, "tomato strawberry",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #533 checking search results for tomato strawberry with boost=true");
//Test #534 checking search results for fig tomato with boost=true
yourResult = tester.search("fig tomato", true, 50);
TestingTools.checkSearch(yourResult, "fig tomato",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #534 checking search results for fig tomato with boost=true");
//Test #535 checking search results for blueberry blueberry tomato pear with boost=true
yourResult = tester.search("blueberry blueberry tomato pear", true, 50);
TestingTools.checkSearch(yourResult, "blueberry blueberry tomato pear",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #535 checking search results for blueberry blueberry tomato pear with boost=true");
//Test #536 checking search results for papaya cherry strawberry with boost=true
yourResult = tester.search("papaya cherry strawberry", true, 50);
TestingTools.checkSearch(yourResult, "papaya cherry strawberry",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #536 checking search results for papaya cherry strawberry with boost=true");
//Test #537 checking search results for papaya banana peach with boost=true
yourResult = tester.search("papaya banana peach", true, 50);
TestingTools.checkSearch(yourResult, "papaya banana peach",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #537 checking search results for papaya banana peach with boost=true");
//Test #538 checking search results for strawberry cherry coconut with boost=true
yourResult = tester.search("strawberry cherry coconut", true, 50);
TestingTools.checkSearch(yourResult, "strawberry cherry coconut",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #538 checking search results for strawberry cherry coconut with boost=true");
//Test #539 checking search results for apple fig tomato peach with boost=true
yourResult = tester.search("apple fig tomato peach", true, 50);
TestingTools.checkSearch(yourResult, "apple fig tomato peach",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #539 checking search results for apple fig tomato peach with boost=true");
//Test #540 checking search results for strawberry with boost=true
yourResult = tester.search("strawberry", true, 50);
TestingTools.checkSearch(yourResult, "strawberry",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #540 checking search results for strawberry with boost=true");
//Test #541 checking search results for strawberry kiwi with boost=true
yourResult = tester.search("strawberry kiwi", true, 50);
TestingTools.checkSearch(yourResult, "strawberry kiwi",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #541 checking search results for strawberry kiwi with boost=true");
//Test #542 checking search results for kiwi cherry with boost=true
yourResult = tester.search("kiwi cherry", true, 50);
TestingTools.checkSearch(yourResult, "kiwi cherry",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #542 checking search results for kiwi cherry with boost=true");
//Test #543 checking search results for apricot fig with boost=true
yourResult = tester.search("apricot fig", true, 50);
TestingTools.checkSearch(yourResult, "apricot fig",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #543 checking search results for apricot fig with boost=true");
//Test #544 checking search results for lime with boost=true
yourResult = tester.search("lime", true, 50);
TestingTools.checkSearch(yourResult, "lime",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #544 checking search results for lime with boost=true");
//Test #545 checking search results for apple with boost=true
yourResult = tester.search("apple", true, 50);
TestingTools.checkSearch(yourResult, "apple",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #545 checking search results for apple with boost=true");
//Test #546 checking search results for peach strawberry with boost=true
yourResult = tester.search("peach strawberry", true, 50);
TestingTools.checkSearch(yourResult, "peach strawberry",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #546 checking search results for peach strawberry with boost=true");
//Test #547 checking search results for lime apricot tomato with boost=true
yourResult = tester.search("lime apricot tomato", true, 50);
TestingTools.checkSearch(yourResult, "lime apricot tomato",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #547 checking search results for lime apricot tomato with boost=true");
//Test #548 checking search results for papaya papaya with boost=true
yourResult = tester.search("papaya papaya", true, 50);
TestingTools.checkSearch(yourResult, "papaya papaya",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #548 checking search results for papaya papaya with boost=true");
//Test #549 checking search results for fig with boost=true
yourResult = tester.search("fig", true, 50);
TestingTools.checkSearch(yourResult, "fig",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #549 checking search results for fig with boost=true");
//Test #550 checking search results for coconut strawberry with boost=true
yourResult = tester.search("coconut strawberry", true, 50);
TestingTools.checkSearch(yourResult, "coconut strawberry",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #550 checking search results for coconut strawberry with boost=true");
//Test #551 checking search results for papaya tomato lime papaya blueberry with boost=true
yourResult = tester.search("papaya tomato lime papaya blueberry", true, 50);
TestingTools.checkSearch(yourResult, "papaya tomato lime papaya blueberry",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #551 checking search results for papaya tomato lime papaya blueberry with boost=true");
//Test #552 checking search results for papaya apple kiwi peach papaya with boost=true
yourResult = tester.search("papaya apple kiwi peach papaya", true, 50);
TestingTools.checkSearch(yourResult, "papaya apple kiwi peach papaya",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #552 checking search results for papaya apple kiwi peach papaya with boost=true");
//Test #553 checking search results for strawberry papaya apricot apple lime with boost=true
yourResult = tester.search("strawberry papaya apricot apple lime", true, 50);
TestingTools.checkSearch(yourResult, "strawberry papaya apricot apple lime",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #553 checking search results for strawberry papaya apricot apple lime with boost=true");
//Test #554 checking search results for peach lime with boost=true
yourResult = tester.search("peach lime", true, 50);
TestingTools.checkSearch(yourResult, "peach lime",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #554 checking search results for peach lime with boost=true");
//Test #555 checking search results for banana coconut with boost=true
yourResult = tester.search("banana coconut", true, 50);
TestingTools.checkSearch(yourResult, "banana coconut",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #555 checking search results for banana coconut with boost=true");
//Test #556 checking search results for apricot apricot with boost=true
yourResult = tester.search("apricot apricot", true, 50);
TestingTools.checkSearch(yourResult, "apricot apricot",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #556 checking search results for apricot apricot with boost=true");
//Test #557 checking search results for blueberry kiwi lime with boost=true
yourResult = tester.search("blueberry kiwi lime", true, 50);
TestingTools.checkSearch(yourResult, "blueberry kiwi lime",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #557 checking search results for blueberry kiwi lime with boost=true");
//Test #558 checking search results for cherry with boost=true
yourResult = tester.search("cherry", true, 50);
TestingTools.checkSearch(yourResult, "cherry",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #558 checking search results for cherry with boost=true");
//Test #559 checking search results for banana cherry fig apple with boost=true
yourResult = tester.search("banana cherry fig apple", true, 50);
TestingTools.checkSearch(yourResult, "banana cherry fig apple",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #559 checking search results for banana cherry fig apple with boost=true");
//Test #560 checking search results for tomato coconut apricot blueberry banana with boost=true
yourResult = tester.search("tomato coconut apricot blueberry banana", true, 50);
TestingTools.checkSearch(yourResult, "tomato coconut apricot blueberry banana",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #560 checking search results for tomato coconut apricot blueberry banana with boost=true");
//Test #561 checking search results for cherry papaya pear kiwi fig with boost=true
yourResult = tester.search("cherry papaya pear kiwi fig", true, 50);
TestingTools.checkSearch(yourResult, "cherry papaya pear kiwi fig",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #561 checking search results for cherry papaya pear kiwi fig with boost=true");
//Test #562 checking search results for strawberry lime with boost=true
yourResult = tester.search("strawberry lime", true, 50);
TestingTools.checkSearch(yourResult, "strawberry lime",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #562 checking search results for strawberry lime with boost=true");
//Test #563 checking search results for apple fig lime with boost=true
yourResult = tester.search("apple fig lime", true, 50);
TestingTools.checkSearch(yourResult, "apple fig lime",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #563 checking search results for apple fig lime with boost=true");
//Test #564 checking search results for coconut apricot papaya blueberry blueberry with boost=true
yourResult = tester.search("coconut apricot papaya blueberry blueberry", true, 50);
TestingTools.checkSearch(yourResult, "coconut apricot papaya blueberry blueberry",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #564 checking search results for coconut apricot papaya blueberry blueberry with boost=true");
//Test #565 checking search results for cherry pear pear coconut with boost=true
yourResult = tester.search("cherry pear pear coconut", true, 50);
TestingTools.checkSearch(yourResult, "cherry pear pear coconut",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #565 checking search results for cherry pear pear coconut with boost=true");
//Test #566 checking search results for blueberry strawberry coconut fig papaya with boost=true
yourResult = tester.search("blueberry strawberry coconut fig papaya", true, 50);
TestingTools.checkSearch(yourResult, "blueberry strawberry coconut fig papaya",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #566 checking search results for blueberry strawberry coconut fig papaya with boost=true");
//Test #567 checking search results for fig peach with boost=true
yourResult = tester.search("fig peach", true, 50);
TestingTools.checkSearch(yourResult, "fig peach",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #567 checking search results for fig peach with boost=true");
//Test #568 checking search results for peach pear with boost=true
yourResult = tester.search("peach pear", true, 50);
TestingTools.checkSearch(yourResult, "peach pear",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #568 checking search results for peach pear with boost=true");
//Test #569 checking search results for banana with boost=true
yourResult = tester.search("banana", true, 50);
TestingTools.checkSearch(yourResult, "banana",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #569 checking search results for banana with boost=true");
//Test #570 checking search results for cherry pear with boost=true
yourResult = tester.search("cherry pear", true, 50);
TestingTools.checkSearch(yourResult, "cherry pear",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #570 checking search results for cherry pear with boost=true");
//Test #571 checking search results for fig apple papaya with boost=true
yourResult = tester.search("fig apple papaya", true, 50);
TestingTools.checkSearch(yourResult, "fig apple papaya",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #571 checking search results for fig apple papaya with boost=true");
//Test #572 checking search results for coconut apricot tomato banana coconut with boost=true
yourResult = tester.search("coconut apricot tomato banana coconut", true, 50);
TestingTools.checkSearch(yourResult, "coconut apricot tomato banana coconut",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #572 checking search results for coconut apricot tomato banana coconut with boost=true");
//Test #573 checking search results for banana lime peach peach fig with boost=true
yourResult = tester.search("banana lime peach peach fig", true, 50);
TestingTools.checkSearch(yourResult, "banana lime peach peach fig",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #573 checking search results for banana lime peach peach fig with boost=true");
//Test #574 checking search results for apricot cherry papaya strawberry with boost=true
yourResult = tester.search("apricot cherry papaya strawberry", true, 50);
TestingTools.checkSearch(yourResult, "apricot cherry papaya strawberry",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #574 checking search results for apricot cherry papaya strawberry with boost=true");
//Test #575 checking search results for blueberry fig with boost=true
yourResult = tester.search("blueberry fig", true, 50);
TestingTools.checkSearch(yourResult, "blueberry fig",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #575 checking search results for blueberry fig with boost=true");
//Test #576 checking search results for cherry kiwi cherry tomato coconut with boost=true
yourResult = tester.search("cherry kiwi cherry tomato coconut", true, 50);
TestingTools.checkSearch(yourResult, "cherry kiwi cherry tomato coconut",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #576 checking search results for cherry kiwi cherry tomato coconut with boost=true");
//Test #577 checking search results for pear banana with boost=true
yourResult = tester.search("pear banana", true, 50);
TestingTools.checkSearch(yourResult, "pear banana",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #577 checking search results for pear banana with boost=true");
//Test #578 checking search results for blueberry coconut cherry apricot with boost=true
yourResult = tester.search("blueberry coconut cherry apricot", true, 50);
TestingTools.checkSearch(yourResult, "blueberry coconut cherry apricot",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #578 checking search results for blueberry coconut cherry apricot with boost=true");
//Test #579 checking search results for papaya coconut strawberry peach with boost=true
yourResult = tester.search("papaya coconut strawberry peach", true, 50);
TestingTools.checkSearch(yourResult, "papaya coconut strawberry peach",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #579 checking search results for papaya coconut strawberry peach with boost=true");
//Test #580 checking search results for strawberry coconut pear with boost=true
yourResult = tester.search("strawberry coconut pear", true, 50);
TestingTools.checkSearch(yourResult, "strawberry coconut pear",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #580 checking search results for strawberry coconut pear with boost=true");
//Test #581 checking search results for lime with boost=true
yourResult = tester.search("lime", true, 50);
TestingTools.checkSearch(yourResult, "lime",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #581 checking search results for lime with boost=true");
//Test #582 checking search results for banana cherry with boost=true
yourResult = tester.search("banana cherry", true, 50);
TestingTools.checkSearch(yourResult, "banana cherry",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #582 checking search results for banana cherry with boost=true");
//Test #583 checking search results for strawberry tomato with boost=true
yourResult = tester.search("strawberry tomato", true, 50);
TestingTools.checkSearch(yourResult, "strawberry tomato",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #583 checking search results for strawberry tomato with boost=true");
//Test #584 checking search results for apricot strawberry tomato blueberry with boost=true
yourResult = tester.search("apricot strawberry tomato blueberry", true, 50);
TestingTools.checkSearch(yourResult, "apricot strawberry tomato blueberry",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #584 checking search results for apricot strawberry tomato blueberry with boost=true");
//Test #585 checking search results for banana tomato with boost=true
yourResult = tester.search("banana tomato", true, 50);
TestingTools.checkSearch(yourResult, "banana tomato",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #585 checking search results for banana tomato with boost=true");
//Test #586 checking search results for strawberry banana with boost=true
yourResult = tester.search("strawberry banana", true, 50);
TestingTools.checkSearch(yourResult, "strawberry banana",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #586 checking search results for strawberry banana with boost=true");
//Test #587 checking search results for strawberry kiwi coconut coconut tomato with boost=true
yourResult = tester.search("strawberry kiwi coconut coconut tomato", true, 50);
TestingTools.checkSearch(yourResult, "strawberry kiwi coconut coconut tomato",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #587 checking search results for strawberry kiwi coconut coconut tomato with boost=true");
//Test #588 checking search results for strawberry fig apricot with boost=true
yourResult = tester.search("strawberry fig apricot", true, 50);
TestingTools.checkSearch(yourResult, "strawberry fig apricot",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #588 checking search results for strawberry fig apricot with boost=true");
//Test #589 checking search results for coconut apple with boost=true
yourResult = tester.search("coconut apple", true, 50);
TestingTools.checkSearch(yourResult, "coconut apple",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #589 checking search results for coconut apple with boost=true");
//Test #590 checking search results for strawberry with boost=true
yourResult = tester.search("strawberry", true, 50);
TestingTools.checkSearch(yourResult, "strawberry",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #590 checking search results for strawberry with boost=true");
//Test #591 checking search results for banana blueberry apple coconut kiwi with boost=true
yourResult = tester.search("banana blueberry apple coconut kiwi", true, 50);
TestingTools.checkSearch(yourResult, "banana blueberry apple coconut kiwi",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #591 checking search results for banana blueberry apple coconut kiwi with boost=true");
//Test #592 checking search results for kiwi banana with boost=true
yourResult = tester.search("kiwi banana", true, 50);
TestingTools.checkSearch(yourResult, "kiwi banana",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #592 checking search results for kiwi banana with boost=true");
//Test #593 checking search results for blueberry peach apricot blueberry with boost=true
yourResult = tester.search("blueberry peach apricot blueberry", true, 50);
TestingTools.checkSearch(yourResult, "blueberry peach apricot blueberry",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #593 checking search results for blueberry peach apricot blueberry with boost=true");
//Test #594 checking search results for kiwi peach banana peach strawberry with boost=true
yourResult = tester.search("kiwi peach banana peach strawberry", true, 50);
TestingTools.checkSearch(yourResult, "kiwi peach banana peach strawberry",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #594 checking search results for kiwi peach banana peach strawberry with boost=true");
//Test #595 checking search results for peach kiwi with boost=true
yourResult = tester.search("peach kiwi", true, 50);
TestingTools.checkSearch(yourResult, "peach kiwi",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #595 checking search results for peach kiwi with boost=true");
//Test #596 checking search results for lime cherry apricot papaya with boost=true
yourResult = tester.search("lime cherry apricot papaya", true, 50);
TestingTools.checkSearch(yourResult, "lime cherry apricot papaya",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #596 checking search results for lime cherry apricot papaya with boost=true");
//Test #597 checking search results for cherry cherry apricot peach coconut with boost=true
yourResult = tester.search("cherry cherry apricot peach coconut", true, 50);
TestingTools.checkSearch(yourResult, "cherry cherry apricot peach coconut",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #597 checking search results for cherry cherry apricot peach coconut with boost=true");
//Test #598 checking search results for blueberry apricot lime pear banana with boost=true
yourResult = tester.search("blueberry apricot lime pear banana", true, 50);
TestingTools.checkSearch(yourResult, "blueberry apricot lime pear banana",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #598 checking search results for blueberry apricot lime pear banana with boost=true");
//Test #599 checking search results for pear strawberry with boost=true
yourResult = tester.search("pear strawberry", true, 50);
TestingTools.checkSearch(yourResult, "pear strawberry",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #599 checking search results for pear strawberry with boost=true");
//Test #600 checking search results for kiwi apple lime peach with boost=true
yourResult = tester.search("kiwi apple lime peach", true, 50);
TestingTools.checkSearch(yourResult, "kiwi apple lime peach",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #600 checking search results for kiwi apple lime peach with boost=true");
//Test #601 checking search results for fig blueberry apricot coconut with boost=true
yourResult = tester.search("fig blueberry apricot coconut", true, 50);
TestingTools.checkSearch(yourResult, "fig blueberry apricot coconut",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #601 checking search results for fig blueberry apricot coconut with boost=true");
//Test #602 checking search results for lime tomato tomato with boost=true
yourResult = tester.search("lime tomato tomato", true, 50);
TestingTools.checkSearch(yourResult, "lime tomato tomato",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #602 checking search results for lime tomato tomato with boost=true");
//Test #603 checking search results for fig kiwi with boost=true
yourResult = tester.search("fig kiwi", true, 50);
TestingTools.checkSearch(yourResult, "fig kiwi",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #603 checking search results for fig kiwi with boost=true");
//Test #604 checking search results for lime lime with boost=true
yourResult = tester.search("lime lime", true, 50);
TestingTools.checkSearch(yourResult, "lime lime",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #604 checking search results for lime lime with boost=true");
//Test #605 checking search results for papaya with boost=true
yourResult = tester.search("papaya", true, 50);
TestingTools.checkSearch(yourResult, "papaya",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #605 checking search results for papaya with boost=true");
//Test #606 checking search results for tomato pear banana fig fig with boost=true
yourResult = tester.search("tomato pear banana fig fig", true, 50);
TestingTools.checkSearch(yourResult, "tomato pear banana fig fig",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #606 checking search results for tomato pear banana fig fig with boost=true");
//Test #607 checking search results for lime with boost=true
yourResult = tester.search("lime", true, 50);
TestingTools.checkSearch(yourResult, "lime",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #607 checking search results for lime with boost=true");
//Test #608 checking search results for blueberry papaya papaya with boost=true
yourResult = tester.search("blueberry papaya papaya", true, 50);
TestingTools.checkSearch(yourResult, "blueberry papaya papaya",true, passOut, failOut, "Fruits50SearchBoostTester", "Test #608 checking search results for blueberry papaya papaya with boost=true");
failOut.close();
passOut.close();
}
}
