import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.*;
public class FruitsASearchBoostTester {public static void main(String[] args) throws Exception{
ProjectTester tester = new ProjectTesterImp(); //Instantiate your own ProjectTester instance here
tester.initialize();
tester.crawl("https://people.scs.carleton.ca/~avamckenney/fruitsA/N-0.html");
runTest(tester);}public static void runTest(ProjectTester tester) throws Exception{
PrintWriter failOut = new PrintWriter(new FileWriter("FruitsA-SearchBoost-failed.txt"));
PrintWriter passOut = new PrintWriter(new FileWriter("FruitsA-SearchBoost-passed.txt"));
List<SearchResult> yourResult; 
//Test #509 checking search results for tomato coconut lime kiwi strawberry with boost=true
yourResult = tester.search("tomato coconut lime kiwi strawberry", true, 100);
TestingTools.checkSearch(yourResult, "tomato coconut lime kiwi strawberry",true, passOut, failOut, "FruitsASearchBoostTester", "Test #509 checking search results for tomato coconut lime kiwi strawberry with boost=true");
//Test #510 checking search results for coconut apple lime with boost=true
yourResult = tester.search("coconut apple lime", true, 100);
TestingTools.checkSearch(yourResult, "coconut apple lime",true, passOut, failOut, "FruitsASearchBoostTester", "Test #510 checking search results for coconut apple lime with boost=true");
//Test #511 checking search results for blueberry fig fig with boost=true
yourResult = tester.search("blueberry fig fig", true, 100);
TestingTools.checkSearch(yourResult, "blueberry fig fig",true, passOut, failOut, "FruitsASearchBoostTester", "Test #511 checking search results for blueberry fig fig with boost=true");
//Test #512 checking search results for lime pear blueberry peach with boost=true
yourResult = tester.search("lime pear blueberry peach", true, 100);
TestingTools.checkSearch(yourResult, "lime pear blueberry peach",true, passOut, failOut, "FruitsASearchBoostTester", "Test #512 checking search results for lime pear blueberry peach with boost=true");
//Test #513 checking search results for peach with boost=true
yourResult = tester.search("peach", true, 100);
TestingTools.checkSearch(yourResult, "peach",true, passOut, failOut, "FruitsASearchBoostTester", "Test #513 checking search results for peach with boost=true");
//Test #514 checking search results for apple papaya papaya apple with boost=true
yourResult = tester.search("apple papaya papaya apple", true, 100);
TestingTools.checkSearch(yourResult, "apple papaya papaya apple",true, passOut, failOut, "FruitsASearchBoostTester", "Test #514 checking search results for apple papaya papaya apple with boost=true");
//Test #515 checking search results for fig tomato with boost=true
yourResult = tester.search("fig tomato", true, 100);
TestingTools.checkSearch(yourResult, "fig tomato",true, passOut, failOut, "FruitsASearchBoostTester", "Test #515 checking search results for fig tomato with boost=true");
//Test #516 checking search results for papaya pear kiwi with boost=true
yourResult = tester.search("papaya pear kiwi", true, 100);
TestingTools.checkSearch(yourResult, "papaya pear kiwi",true, passOut, failOut, "FruitsASearchBoostTester", "Test #516 checking search results for papaya pear kiwi with boost=true");
//Test #517 checking search results for peach with boost=true
yourResult = tester.search("peach", true, 100);
TestingTools.checkSearch(yourResult, "peach",true, passOut, failOut, "FruitsASearchBoostTester", "Test #517 checking search results for peach with boost=true");
//Test #518 checking search results for lime strawberry lime peach coconut with boost=true
yourResult = tester.search("lime strawberry lime peach coconut", true, 100);
TestingTools.checkSearch(yourResult, "lime strawberry lime peach coconut",true, passOut, failOut, "FruitsASearchBoostTester", "Test #518 checking search results for lime strawberry lime peach coconut with boost=true");
//Test #519 checking search results for lime blueberry with boost=true
yourResult = tester.search("lime blueberry", true, 100);
TestingTools.checkSearch(yourResult, "lime blueberry",true, passOut, failOut, "FruitsASearchBoostTester", "Test #519 checking search results for lime blueberry with boost=true");
//Test #520 checking search results for apricot blueberry apricot strawberry with boost=true
yourResult = tester.search("apricot blueberry apricot strawberry", true, 100);
TestingTools.checkSearch(yourResult, "apricot blueberry apricot strawberry",true, passOut, failOut, "FruitsASearchBoostTester", "Test #520 checking search results for apricot blueberry apricot strawberry with boost=true");
//Test #521 checking search results for apricot peach with boost=true
yourResult = tester.search("apricot peach", true, 100);
TestingTools.checkSearch(yourResult, "apricot peach",true, passOut, failOut, "FruitsASearchBoostTester", "Test #521 checking search results for apricot peach with boost=true");
//Test #522 checking search results for cherry pear kiwi with boost=true
yourResult = tester.search("cherry pear kiwi", true, 100);
TestingTools.checkSearch(yourResult, "cherry pear kiwi",true, passOut, failOut, "FruitsASearchBoostTester", "Test #522 checking search results for cherry pear kiwi with boost=true");
//Test #523 checking search results for tomato coconut strawberry strawberry tomato with boost=true
yourResult = tester.search("tomato coconut strawberry strawberry tomato", true, 100);
TestingTools.checkSearch(yourResult, "tomato coconut strawberry strawberry tomato",true, passOut, failOut, "FruitsASearchBoostTester", "Test #523 checking search results for tomato coconut strawberry strawberry tomato with boost=true");
//Test #524 checking search results for banana with boost=true
yourResult = tester.search("banana", true, 100);
TestingTools.checkSearch(yourResult, "banana",true, passOut, failOut, "FruitsASearchBoostTester", "Test #524 checking search results for banana with boost=true");
//Test #525 checking search results for strawberry with boost=true
yourResult = tester.search("strawberry", true, 100);
TestingTools.checkSearch(yourResult, "strawberry",true, passOut, failOut, "FruitsASearchBoostTester", "Test #525 checking search results for strawberry with boost=true");
//Test #526 checking search results for peach blueberry apricot papaya papaya with boost=true
yourResult = tester.search("peach blueberry apricot papaya papaya", true, 100);
TestingTools.checkSearch(yourResult, "peach blueberry apricot papaya papaya",true, passOut, failOut, "FruitsASearchBoostTester", "Test #526 checking search results for peach blueberry apricot papaya papaya with boost=true");
//Test #527 checking search results for fig peach blueberry papaya coconut with boost=true
yourResult = tester.search("fig peach blueberry papaya coconut", true, 100);
TestingTools.checkSearch(yourResult, "fig peach blueberry papaya coconut",true, passOut, failOut, "FruitsASearchBoostTester", "Test #527 checking search results for fig peach blueberry papaya coconut with boost=true");
//Test #528 checking search results for peach peach lime banana with boost=true
yourResult = tester.search("peach peach lime banana", true, 100);
TestingTools.checkSearch(yourResult, "peach peach lime banana",true, passOut, failOut, "FruitsASearchBoostTester", "Test #528 checking search results for peach peach lime banana with boost=true");
//Test #529 checking search results for fig banana lime with boost=true
yourResult = tester.search("fig banana lime", true, 100);
TestingTools.checkSearch(yourResult, "fig banana lime",true, passOut, failOut, "FruitsASearchBoostTester", "Test #529 checking search results for fig banana lime with boost=true");
//Test #530 checking search results for coconut blueberry fig with boost=true
yourResult = tester.search("coconut blueberry fig", true, 100);
TestingTools.checkSearch(yourResult, "coconut blueberry fig",true, passOut, failOut, "FruitsASearchBoostTester", "Test #530 checking search results for coconut blueberry fig with boost=true");
//Test #531 checking search results for peach lime apple kiwi with boost=true
yourResult = tester.search("peach lime apple kiwi", true, 100);
TestingTools.checkSearch(yourResult, "peach lime apple kiwi",true, passOut, failOut, "FruitsASearchBoostTester", "Test #531 checking search results for peach lime apple kiwi with boost=true");
//Test #532 checking search results for peach apricot papaya kiwi with boost=true
yourResult = tester.search("peach apricot papaya kiwi", true, 100);
TestingTools.checkSearch(yourResult, "peach apricot papaya kiwi",true, passOut, failOut, "FruitsASearchBoostTester", "Test #532 checking search results for peach apricot papaya kiwi with boost=true");
//Test #533 checking search results for strawberry pear pear apricot tomato with boost=true
yourResult = tester.search("strawberry pear pear apricot tomato", true, 100);
TestingTools.checkSearch(yourResult, "strawberry pear pear apricot tomato",true, passOut, failOut, "FruitsASearchBoostTester", "Test #533 checking search results for strawberry pear pear apricot tomato with boost=true");
//Test #534 checking search results for fig blueberry pear with boost=true
yourResult = tester.search("fig blueberry pear", true, 100);
TestingTools.checkSearch(yourResult, "fig blueberry pear",true, passOut, failOut, "FruitsASearchBoostTester", "Test #534 checking search results for fig blueberry pear with boost=true");
//Test #535 checking search results for tomato cherry blueberry with boost=true
yourResult = tester.search("tomato cherry blueberry", true, 100);
TestingTools.checkSearch(yourResult, "tomato cherry blueberry",true, passOut, failOut, "FruitsASearchBoostTester", "Test #535 checking search results for tomato cherry blueberry with boost=true");
//Test #536 checking search results for strawberry with boost=true
yourResult = tester.search("strawberry", true, 100);
TestingTools.checkSearch(yourResult, "strawberry",true, passOut, failOut, "FruitsASearchBoostTester", "Test #536 checking search results for strawberry with boost=true");
//Test #537 checking search results for apple lime with boost=true
yourResult = tester.search("apple lime", true, 100);
TestingTools.checkSearch(yourResult, "apple lime",true, passOut, failOut, "FruitsASearchBoostTester", "Test #537 checking search results for apple lime with boost=true");
//Test #538 checking search results for kiwi kiwi apricot coconut with boost=true
yourResult = tester.search("kiwi kiwi apricot coconut", true, 100);
TestingTools.checkSearch(yourResult, "kiwi kiwi apricot coconut",true, passOut, failOut, "FruitsASearchBoostTester", "Test #538 checking search results for kiwi kiwi apricot coconut with boost=true");
//Test #539 checking search results for banana with boost=true
yourResult = tester.search("banana", true, 100);
TestingTools.checkSearch(yourResult, "banana",true, passOut, failOut, "FruitsASearchBoostTester", "Test #539 checking search results for banana with boost=true");
//Test #540 checking search results for pear apple lime with boost=true
yourResult = tester.search("pear apple lime", true, 100);
TestingTools.checkSearch(yourResult, "pear apple lime",true, passOut, failOut, "FruitsASearchBoostTester", "Test #540 checking search results for pear apple lime with boost=true");
//Test #541 checking search results for kiwi kiwi with boost=true
yourResult = tester.search("kiwi kiwi", true, 100);
TestingTools.checkSearch(yourResult, "kiwi kiwi",true, passOut, failOut, "FruitsASearchBoostTester", "Test #541 checking search results for kiwi kiwi with boost=true");
//Test #542 checking search results for peach with boost=true
yourResult = tester.search("peach", true, 100);
TestingTools.checkSearch(yourResult, "peach",true, passOut, failOut, "FruitsASearchBoostTester", "Test #542 checking search results for peach with boost=true");
//Test #543 checking search results for tomato peach with boost=true
yourResult = tester.search("tomato peach", true, 100);
TestingTools.checkSearch(yourResult, "tomato peach",true, passOut, failOut, "FruitsASearchBoostTester", "Test #543 checking search results for tomato peach with boost=true");
//Test #544 checking search results for apple with boost=true
yourResult = tester.search("apple", true, 100);
TestingTools.checkSearch(yourResult, "apple",true, passOut, failOut, "FruitsASearchBoostTester", "Test #544 checking search results for apple with boost=true");
//Test #545 checking search results for apple cherry papaya with boost=true
yourResult = tester.search("apple cherry papaya", true, 100);
TestingTools.checkSearch(yourResult, "apple cherry papaya",true, passOut, failOut, "FruitsASearchBoostTester", "Test #545 checking search results for apple cherry papaya with boost=true");
//Test #546 checking search results for lime tomato lime with boost=true
yourResult = tester.search("lime tomato lime", true, 100);
TestingTools.checkSearch(yourResult, "lime tomato lime",true, passOut, failOut, "FruitsASearchBoostTester", "Test #546 checking search results for lime tomato lime with boost=true");
//Test #547 checking search results for tomato apricot peach with boost=true
yourResult = tester.search("tomato apricot peach", true, 100);
TestingTools.checkSearch(yourResult, "tomato apricot peach",true, passOut, failOut, "FruitsASearchBoostTester", "Test #547 checking search results for tomato apricot peach with boost=true");
//Test #548 checking search results for peach apple pear with boost=true
yourResult = tester.search("peach apple pear", true, 100);
TestingTools.checkSearch(yourResult, "peach apple pear",true, passOut, failOut, "FruitsASearchBoostTester", "Test #548 checking search results for peach apple pear with boost=true");
//Test #549 checking search results for apricot kiwi cherry coconut tomato with boost=true
yourResult = tester.search("apricot kiwi cherry coconut tomato", true, 100);
TestingTools.checkSearch(yourResult, "apricot kiwi cherry coconut tomato",true, passOut, failOut, "FruitsASearchBoostTester", "Test #549 checking search results for apricot kiwi cherry coconut tomato with boost=true");
//Test #550 checking search results for peach kiwi with boost=true
yourResult = tester.search("peach kiwi", true, 100);
TestingTools.checkSearch(yourResult, "peach kiwi",true, passOut, failOut, "FruitsASearchBoostTester", "Test #550 checking search results for peach kiwi with boost=true");
//Test #551 checking search results for banana banana banana apricot with boost=true
yourResult = tester.search("banana banana banana apricot", true, 100);
TestingTools.checkSearch(yourResult, "banana banana banana apricot",true, passOut, failOut, "FruitsASearchBoostTester", "Test #551 checking search results for banana banana banana apricot with boost=true");
//Test #552 checking search results for fig fig blueberry apricot apple with boost=true
yourResult = tester.search("fig fig blueberry apricot apple", true, 100);
TestingTools.checkSearch(yourResult, "fig fig blueberry apricot apple",true, passOut, failOut, "FruitsASearchBoostTester", "Test #552 checking search results for fig fig blueberry apricot apple with boost=true");
//Test #553 checking search results for apple tomato banana apricot peach with boost=true
yourResult = tester.search("apple tomato banana apricot peach", true, 100);
TestingTools.checkSearch(yourResult, "apple tomato banana apricot peach",true, passOut, failOut, "FruitsASearchBoostTester", "Test #553 checking search results for apple tomato banana apricot peach with boost=true");
//Test #554 checking search results for papaya lime lime kiwi with boost=true
yourResult = tester.search("papaya lime lime kiwi", true, 100);
TestingTools.checkSearch(yourResult, "papaya lime lime kiwi",true, passOut, failOut, "FruitsASearchBoostTester", "Test #554 checking search results for papaya lime lime kiwi with boost=true");
//Test #555 checking search results for coconut peach lime blueberry apricot with boost=true
yourResult = tester.search("coconut peach lime blueberry apricot", true, 100);
TestingTools.checkSearch(yourResult, "coconut peach lime blueberry apricot",true, passOut, failOut, "FruitsASearchBoostTester", "Test #555 checking search results for coconut peach lime blueberry apricot with boost=true");
//Test #556 checking search results for tomato lime apple peach pear with boost=true
yourResult = tester.search("tomato lime apple peach pear", true, 100);
TestingTools.checkSearch(yourResult, "tomato lime apple peach pear",true, passOut, failOut, "FruitsASearchBoostTester", "Test #556 checking search results for tomato lime apple peach pear with boost=true");
//Test #557 checking search results for lime apricot peach peach with boost=true
yourResult = tester.search("lime apricot peach peach", true, 100);
TestingTools.checkSearch(yourResult, "lime apricot peach peach",true, passOut, failOut, "FruitsASearchBoostTester", "Test #557 checking search results for lime apricot peach peach with boost=true");
//Test #558 checking search results for apple peach lime with boost=true
yourResult = tester.search("apple peach lime", true, 100);
TestingTools.checkSearch(yourResult, "apple peach lime",true, passOut, failOut, "FruitsASearchBoostTester", "Test #558 checking search results for apple peach lime with boost=true");
//Test #559 checking search results for strawberry apple cherry papaya with boost=true
yourResult = tester.search("strawberry apple cherry papaya", true, 100);
TestingTools.checkSearch(yourResult, "strawberry apple cherry papaya",true, passOut, failOut, "FruitsASearchBoostTester", "Test #559 checking search results for strawberry apple cherry papaya with boost=true");
//Test #560 checking search results for pear tomato cherry blueberry kiwi with boost=true
yourResult = tester.search("pear tomato cherry blueberry kiwi", true, 100);
TestingTools.checkSearch(yourResult, "pear tomato cherry blueberry kiwi",true, passOut, failOut, "FruitsASearchBoostTester", "Test #560 checking search results for pear tomato cherry blueberry kiwi with boost=true");
//Test #561 checking search results for apricot with boost=true
yourResult = tester.search("apricot", true, 100);
TestingTools.checkSearch(yourResult, "apricot",true, passOut, failOut, "FruitsASearchBoostTester", "Test #561 checking search results for apricot with boost=true");
//Test #562 checking search results for apple tomato kiwi with boost=true
yourResult = tester.search("apple tomato kiwi", true, 100);
TestingTools.checkSearch(yourResult, "apple tomato kiwi",true, passOut, failOut, "FruitsASearchBoostTester", "Test #562 checking search results for apple tomato kiwi with boost=true");
//Test #563 checking search results for coconut tomato apple apple with boost=true
yourResult = tester.search("coconut tomato apple apple", true, 100);
TestingTools.checkSearch(yourResult, "coconut tomato apple apple",true, passOut, failOut, "FruitsASearchBoostTester", "Test #563 checking search results for coconut tomato apple apple with boost=true");
//Test #564 checking search results for banana kiwi blueberry with boost=true
yourResult = tester.search("banana kiwi blueberry", true, 100);
TestingTools.checkSearch(yourResult, "banana kiwi blueberry",true, passOut, failOut, "FruitsASearchBoostTester", "Test #564 checking search results for banana kiwi blueberry with boost=true");
//Test #565 checking search results for pear with boost=true
yourResult = tester.search("pear", true, 100);
TestingTools.checkSearch(yourResult, "pear",true, passOut, failOut, "FruitsASearchBoostTester", "Test #565 checking search results for pear with boost=true");
//Test #566 checking search results for apricot banana kiwi banana with boost=true
yourResult = tester.search("apricot banana kiwi banana", true, 100);
TestingTools.checkSearch(yourResult, "apricot banana kiwi banana",true, passOut, failOut, "FruitsASearchBoostTester", "Test #566 checking search results for apricot banana kiwi banana with boost=true");
//Test #567 checking search results for fig with boost=true
yourResult = tester.search("fig", true, 100);
TestingTools.checkSearch(yourResult, "fig",true, passOut, failOut, "FruitsASearchBoostTester", "Test #567 checking search results for fig with boost=true");
//Test #568 checking search results for pear peach apple tomato blueberry with boost=true
yourResult = tester.search("pear peach apple tomato blueberry", true, 100);
TestingTools.checkSearch(yourResult, "pear peach apple tomato blueberry",true, passOut, failOut, "FruitsASearchBoostTester", "Test #568 checking search results for pear peach apple tomato blueberry with boost=true");
//Test #569 checking search results for coconut strawberry with boost=true
yourResult = tester.search("coconut strawberry", true, 100);
TestingTools.checkSearch(yourResult, "coconut strawberry",true, passOut, failOut, "FruitsASearchBoostTester", "Test #569 checking search results for coconut strawberry with boost=true");
//Test #570 checking search results for strawberry fig with boost=true
yourResult = tester.search("strawberry fig", true, 100);
TestingTools.checkSearch(yourResult, "strawberry fig",true, passOut, failOut, "FruitsASearchBoostTester", "Test #570 checking search results for strawberry fig with boost=true");
//Test #571 checking search results for tomato peach papaya blueberry with boost=true
yourResult = tester.search("tomato peach papaya blueberry", true, 100);
TestingTools.checkSearch(yourResult, "tomato peach papaya blueberry",true, passOut, failOut, "FruitsASearchBoostTester", "Test #571 checking search results for tomato peach papaya blueberry with boost=true");
//Test #572 checking search results for apricot lime with boost=true
yourResult = tester.search("apricot lime", true, 100);
TestingTools.checkSearch(yourResult, "apricot lime",true, passOut, failOut, "FruitsASearchBoostTester", "Test #572 checking search results for apricot lime with boost=true");
//Test #573 checking search results for coconut with boost=true
yourResult = tester.search("coconut", true, 100);
TestingTools.checkSearch(yourResult, "coconut",true, passOut, failOut, "FruitsASearchBoostTester", "Test #573 checking search results for coconut with boost=true");
//Test #574 checking search results for apple fig peach with boost=true
yourResult = tester.search("apple fig peach", true, 100);
TestingTools.checkSearch(yourResult, "apple fig peach",true, passOut, failOut, "FruitsASearchBoostTester", "Test #574 checking search results for apple fig peach with boost=true");
//Test #575 checking search results for coconut fig with boost=true
yourResult = tester.search("coconut fig", true, 100);
TestingTools.checkSearch(yourResult, "coconut fig",true, passOut, failOut, "FruitsASearchBoostTester", "Test #575 checking search results for coconut fig with boost=true");
//Test #576 checking search results for apple with boost=true
yourResult = tester.search("apple", true, 100);
TestingTools.checkSearch(yourResult, "apple",true, passOut, failOut, "FruitsASearchBoostTester", "Test #576 checking search results for apple with boost=true");
//Test #577 checking search results for tomato pear blueberry strawberry blueberry with boost=true
yourResult = tester.search("tomato pear blueberry strawberry blueberry", true, 100);
TestingTools.checkSearch(yourResult, "tomato pear blueberry strawberry blueberry",true, passOut, failOut, "FruitsASearchBoostTester", "Test #577 checking search results for tomato pear blueberry strawberry blueberry with boost=true");
//Test #578 checking search results for banana pear papaya cherry coconut with boost=true
yourResult = tester.search("banana pear papaya cherry coconut", true, 100);
TestingTools.checkSearch(yourResult, "banana pear papaya cherry coconut",true, passOut, failOut, "FruitsASearchBoostTester", "Test #578 checking search results for banana pear papaya cherry coconut with boost=true");
//Test #579 checking search results for apple apricot with boost=true
yourResult = tester.search("apple apricot", true, 100);
TestingTools.checkSearch(yourResult, "apple apricot",true, passOut, failOut, "FruitsASearchBoostTester", "Test #579 checking search results for apple apricot with boost=true");
//Test #580 checking search results for apricot banana with boost=true
yourResult = tester.search("apricot banana", true, 100);
TestingTools.checkSearch(yourResult, "apricot banana",true, passOut, failOut, "FruitsASearchBoostTester", "Test #580 checking search results for apricot banana with boost=true");
//Test #581 checking search results for apple coconut papaya with boost=true
yourResult = tester.search("apple coconut papaya", true, 100);
TestingTools.checkSearch(yourResult, "apple coconut papaya",true, passOut, failOut, "FruitsASearchBoostTester", "Test #581 checking search results for apple coconut papaya with boost=true");
//Test #582 checking search results for fig peach with boost=true
yourResult = tester.search("fig peach", true, 100);
TestingTools.checkSearch(yourResult, "fig peach",true, passOut, failOut, "FruitsASearchBoostTester", "Test #582 checking search results for fig peach with boost=true");
//Test #583 checking search results for kiwi tomato kiwi blueberry papaya with boost=true
yourResult = tester.search("kiwi tomato kiwi blueberry papaya", true, 100);
TestingTools.checkSearch(yourResult, "kiwi tomato kiwi blueberry papaya",true, passOut, failOut, "FruitsASearchBoostTester", "Test #583 checking search results for kiwi tomato kiwi blueberry papaya with boost=true");
//Test #584 checking search results for strawberry apricot peach apple with boost=true
yourResult = tester.search("strawberry apricot peach apple", true, 100);
TestingTools.checkSearch(yourResult, "strawberry apricot peach apple",true, passOut, failOut, "FruitsASearchBoostTester", "Test #584 checking search results for strawberry apricot peach apple with boost=true");
//Test #585 checking search results for fig with boost=true
yourResult = tester.search("fig", true, 100);
TestingTools.checkSearch(yourResult, "fig",true, passOut, failOut, "FruitsASearchBoostTester", "Test #585 checking search results for fig with boost=true");
//Test #586 checking search results for peach peach banana tomato apricot with boost=true
yourResult = tester.search("peach peach banana tomato apricot", true, 100);
TestingTools.checkSearch(yourResult, "peach peach banana tomato apricot",true, passOut, failOut, "FruitsASearchBoostTester", "Test #586 checking search results for peach peach banana tomato apricot with boost=true");
//Test #587 checking search results for blueberry with boost=true
yourResult = tester.search("blueberry", true, 100);
TestingTools.checkSearch(yourResult, "blueberry",true, passOut, failOut, "FruitsASearchBoostTester", "Test #587 checking search results for blueberry with boost=true");
//Test #588 checking search results for peach tomato pear with boost=true
yourResult = tester.search("peach tomato pear", true, 100);
TestingTools.checkSearch(yourResult, "peach tomato pear",true, passOut, failOut, "FruitsASearchBoostTester", "Test #588 checking search results for peach tomato pear with boost=true");
//Test #589 checking search results for coconut lime papaya coconut coconut with boost=true
yourResult = tester.search("coconut lime papaya coconut coconut", true, 100);
TestingTools.checkSearch(yourResult, "coconut lime papaya coconut coconut",true, passOut, failOut, "FruitsASearchBoostTester", "Test #589 checking search results for coconut lime papaya coconut coconut with boost=true");
//Test #590 checking search results for papaya with boost=true
yourResult = tester.search("papaya", true, 100);
TestingTools.checkSearch(yourResult, "papaya",true, passOut, failOut, "FruitsASearchBoostTester", "Test #590 checking search results for papaya with boost=true");
//Test #591 checking search results for apricot peach kiwi with boost=true
yourResult = tester.search("apricot peach kiwi", true, 100);
TestingTools.checkSearch(yourResult, "apricot peach kiwi",true, passOut, failOut, "FruitsASearchBoostTester", "Test #591 checking search results for apricot peach kiwi with boost=true");
//Test #592 checking search results for cherry fig papaya pear peach with boost=true
yourResult = tester.search("cherry fig papaya pear peach", true, 100);
TestingTools.checkSearch(yourResult, "cherry fig papaya pear peach",true, passOut, failOut, "FruitsASearchBoostTester", "Test #592 checking search results for cherry fig papaya pear peach with boost=true");
//Test #593 checking search results for strawberry tomato blueberry coconut with boost=true
yourResult = tester.search("strawberry tomato blueberry coconut", true, 100);
TestingTools.checkSearch(yourResult, "strawberry tomato blueberry coconut",true, passOut, failOut, "FruitsASearchBoostTester", "Test #593 checking search results for strawberry tomato blueberry coconut with boost=true");
//Test #594 checking search results for papaya lime with boost=true
yourResult = tester.search("papaya lime", true, 100);
TestingTools.checkSearch(yourResult, "papaya lime",true, passOut, failOut, "FruitsASearchBoostTester", "Test #594 checking search results for papaya lime with boost=true");
//Test #595 checking search results for kiwi coconut apple cherry lime with boost=true
yourResult = tester.search("kiwi coconut apple cherry lime", true, 100);
TestingTools.checkSearch(yourResult, "kiwi coconut apple cherry lime",true, passOut, failOut, "FruitsASearchBoostTester", "Test #595 checking search results for kiwi coconut apple cherry lime with boost=true");
//Test #596 checking search results for coconut tomato papaya kiwi with boost=true
yourResult = tester.search("coconut tomato papaya kiwi", true, 100);
TestingTools.checkSearch(yourResult, "coconut tomato papaya kiwi",true, passOut, failOut, "FruitsASearchBoostTester", "Test #596 checking search results for coconut tomato papaya kiwi with boost=true");
//Test #597 checking search results for fig kiwi lime tomato tomato with boost=true
yourResult = tester.search("fig kiwi lime tomato tomato", true, 100);
TestingTools.checkSearch(yourResult, "fig kiwi lime tomato tomato",true, passOut, failOut, "FruitsASearchBoostTester", "Test #597 checking search results for fig kiwi lime tomato tomato with boost=true");
//Test #598 checking search results for lime blueberry strawberry with boost=true
yourResult = tester.search("lime blueberry strawberry", true, 100);
TestingTools.checkSearch(yourResult, "lime blueberry strawberry",true, passOut, failOut, "FruitsASearchBoostTester", "Test #598 checking search results for lime blueberry strawberry with boost=true");
//Test #599 checking search results for papaya apple coconut with boost=true
yourResult = tester.search("papaya apple coconut", true, 100);
TestingTools.checkSearch(yourResult, "papaya apple coconut",true, passOut, failOut, "FruitsASearchBoostTester", "Test #599 checking search results for papaya apple coconut with boost=true");
//Test #600 checking search results for lime apricot peach papaya with boost=true
yourResult = tester.search("lime apricot peach papaya", true, 100);
TestingTools.checkSearch(yourResult, "lime apricot peach papaya",true, passOut, failOut, "FruitsASearchBoostTester", "Test #600 checking search results for lime apricot peach papaya with boost=true");
//Test #601 checking search results for pear coconut fig apple lime with boost=true
yourResult = tester.search("pear coconut fig apple lime", true, 100);
TestingTools.checkSearch(yourResult, "pear coconut fig apple lime",true, passOut, failOut, "FruitsASearchBoostTester", "Test #601 checking search results for pear coconut fig apple lime with boost=true");
//Test #602 checking search results for apricot kiwi fig tomato blueberry with boost=true
yourResult = tester.search("apricot kiwi fig tomato blueberry", true, 100);
TestingTools.checkSearch(yourResult, "apricot kiwi fig tomato blueberry",true, passOut, failOut, "FruitsASearchBoostTester", "Test #602 checking search results for apricot kiwi fig tomato blueberry with boost=true");
//Test #603 checking search results for banana fig kiwi pear blueberry with boost=true
yourResult = tester.search("banana fig kiwi pear blueberry", true, 100);
TestingTools.checkSearch(yourResult, "banana fig kiwi pear blueberry",true, passOut, failOut, "FruitsASearchBoostTester", "Test #603 checking search results for banana fig kiwi pear blueberry with boost=true");
//Test #604 checking search results for cherry apricot lime pear with boost=true
yourResult = tester.search("cherry apricot lime pear", true, 100);
TestingTools.checkSearch(yourResult, "cherry apricot lime pear",true, passOut, failOut, "FruitsASearchBoostTester", "Test #604 checking search results for cherry apricot lime pear with boost=true");
//Test #605 checking search results for coconut kiwi banana fig coconut with boost=true
yourResult = tester.search("coconut kiwi banana fig coconut", true, 100);
TestingTools.checkSearch(yourResult, "coconut kiwi banana fig coconut",true, passOut, failOut, "FruitsASearchBoostTester", "Test #605 checking search results for coconut kiwi banana fig coconut with boost=true");
//Test #606 checking search results for kiwi blueberry pear with boost=true
yourResult = tester.search("kiwi blueberry pear", true, 100);
TestingTools.checkSearch(yourResult, "kiwi blueberry pear",true, passOut, failOut, "FruitsASearchBoostTester", "Test #606 checking search results for kiwi blueberry pear with boost=true");
//Test #607 checking search results for coconut blueberry apple tomato blueberry with boost=true
yourResult = tester.search("coconut blueberry apple tomato blueberry", true, 100);
TestingTools.checkSearch(yourResult, "coconut blueberry apple tomato blueberry",true, passOut, failOut, "FruitsASearchBoostTester", "Test #607 checking search results for coconut blueberry apple tomato blueberry with boost=true");
//Test #608 checking search results for apricot banana fig strawberry with boost=true
yourResult = tester.search("apricot banana fig strawberry", true, 100);
TestingTools.checkSearch(yourResult, "apricot banana fig strawberry",true, passOut, failOut, "FruitsASearchBoostTester", "Test #608 checking search results for apricot banana fig strawberry with boost=true");
failOut.close();
passOut.close();
}
}
