import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.*;
public class TinyFruitsASearchBoostTester {public static void main(String[] args) throws Exception{
ProjectTester tester = new ProjectTesterImp(); //Instantiate your own ProjectTester instance here
tester.initialize();
tester.crawl("https://people.scs.carleton.ca/~avamckenney/tinyfruitsA/N-0.html");
runTest(tester);}public static void runTest(ProjectTester tester) throws Exception{
PrintWriter failOut = new PrintWriter(new FileWriter("TinyFruitsA-SearchBoost-failed.txt"));
PrintWriter passOut = new PrintWriter(new FileWriter("TinyFruitsA-SearchBoost-passed.txt"));
List<SearchResult> yourResult; 
//Test #389 checking search results for fig apple banana apricot with boost=true
yourResult = tester.search("fig apple banana apricot", true, 10);
TestingTools.checkSearch(yourResult, "fig apple banana apricot",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #389 checking search results for fig apple banana apricot with boost=true");
//Test #390 checking search results for fig fig strawberry apple banana with boost=true
yourResult = tester.search("fig fig strawberry apple banana", true, 10);
TestingTools.checkSearch(yourResult, "fig fig strawberry apple banana",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #390 checking search results for fig fig strawberry apple banana with boost=true");
//Test #391 checking search results for peach fig with boost=true
yourResult = tester.search("peach fig", true, 10);
TestingTools.checkSearch(yourResult, "peach fig",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #391 checking search results for peach fig with boost=true");
//Test #392 checking search results for tomato papaya apricot apple with boost=true
yourResult = tester.search("tomato papaya apricot apple", true, 10);
TestingTools.checkSearch(yourResult, "tomato papaya apricot apple",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #392 checking search results for tomato papaya apricot apple with boost=true");
//Test #393 checking search results for pear with boost=true
yourResult = tester.search("pear", true, 10);
TestingTools.checkSearch(yourResult, "pear",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #393 checking search results for pear with boost=true");
//Test #394 checking search results for pear tomato with boost=true
yourResult = tester.search("pear tomato", true, 10);
TestingTools.checkSearch(yourResult, "pear tomato",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #394 checking search results for pear tomato with boost=true");
//Test #395 checking search results for pear apple apricot with boost=true
yourResult = tester.search("pear apple apricot", true, 10);
TestingTools.checkSearch(yourResult, "pear apple apricot",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #395 checking search results for pear apple apricot with boost=true");
//Test #396 checking search results for apricot pear banana tomato with boost=true
yourResult = tester.search("apricot pear banana tomato", true, 10);
TestingTools.checkSearch(yourResult, "apricot pear banana tomato",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #396 checking search results for apricot pear banana tomato with boost=true");
//Test #397 checking search results for kiwi blueberry apricot pear with boost=true
yourResult = tester.search("kiwi blueberry apricot pear", true, 10);
TestingTools.checkSearch(yourResult, "kiwi blueberry apricot pear",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #397 checking search results for kiwi blueberry apricot pear with boost=true");
//Test #398 checking search results for coconut apricot pear papaya cherry with boost=true
yourResult = tester.search("coconut apricot pear papaya cherry", true, 10);
TestingTools.checkSearch(yourResult, "coconut apricot pear papaya cherry",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #398 checking search results for coconut apricot pear papaya cherry with boost=true");
//Test #399 checking search results for fig kiwi pear tomato with boost=true
yourResult = tester.search("fig kiwi pear tomato", true, 10);
TestingTools.checkSearch(yourResult, "fig kiwi pear tomato",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #399 checking search results for fig kiwi pear tomato with boost=true");
//Test #400 checking search results for banana lime peach cherry cherry with boost=true
yourResult = tester.search("banana lime peach cherry cherry", true, 10);
TestingTools.checkSearch(yourResult, "banana lime peach cherry cherry",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #400 checking search results for banana lime peach cherry cherry with boost=true");
//Test #401 checking search results for peach coconut with boost=true
yourResult = tester.search("peach coconut", true, 10);
TestingTools.checkSearch(yourResult, "peach coconut",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #401 checking search results for peach coconut with boost=true");
//Test #402 checking search results for strawberry papaya strawberry with boost=true
yourResult = tester.search("strawberry papaya strawberry", true, 10);
TestingTools.checkSearch(yourResult, "strawberry papaya strawberry",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #402 checking search results for strawberry papaya strawberry with boost=true");
//Test #403 checking search results for blueberry strawberry cherry apricot with boost=true
yourResult = tester.search("blueberry strawberry cherry apricot", true, 10);
TestingTools.checkSearch(yourResult, "blueberry strawberry cherry apricot",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #403 checking search results for blueberry strawberry cherry apricot with boost=true");
//Test #404 checking search results for coconut papaya peach blueberry tomato with boost=true
yourResult = tester.search("coconut papaya peach blueberry tomato", true, 10);
TestingTools.checkSearch(yourResult, "coconut papaya peach blueberry tomato",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #404 checking search results for coconut papaya peach blueberry tomato with boost=true");
//Test #405 checking search results for apricot lime apricot pear with boost=true
yourResult = tester.search("apricot lime apricot pear", true, 10);
TestingTools.checkSearch(yourResult, "apricot lime apricot pear",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #405 checking search results for apricot lime apricot pear with boost=true");
//Test #406 checking search results for banana with boost=true
yourResult = tester.search("banana", true, 10);
TestingTools.checkSearch(yourResult, "banana",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #406 checking search results for banana with boost=true");
//Test #407 checking search results for banana fig banana with boost=true
yourResult = tester.search("banana fig banana", true, 10);
TestingTools.checkSearch(yourResult, "banana fig banana",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #407 checking search results for banana fig banana with boost=true");
//Test #408 checking search results for papaya with boost=true
yourResult = tester.search("papaya", true, 10);
TestingTools.checkSearch(yourResult, "papaya",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #408 checking search results for papaya with boost=true");
//Test #409 checking search results for apple banana apple apple with boost=true
yourResult = tester.search("apple banana apple apple", true, 10);
TestingTools.checkSearch(yourResult, "apple banana apple apple",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #409 checking search results for apple banana apple apple with boost=true");
//Test #410 checking search results for coconut with boost=true
yourResult = tester.search("coconut", true, 10);
TestingTools.checkSearch(yourResult, "coconut",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #410 checking search results for coconut with boost=true");
//Test #411 checking search results for coconut blueberry banana banana with boost=true
yourResult = tester.search("coconut blueberry banana banana", true, 10);
TestingTools.checkSearch(yourResult, "coconut blueberry banana banana",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #411 checking search results for coconut blueberry banana banana with boost=true");
//Test #412 checking search results for papaya tomato blueberry banana with boost=true
yourResult = tester.search("papaya tomato blueberry banana", true, 10);
TestingTools.checkSearch(yourResult, "papaya tomato blueberry banana",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #412 checking search results for papaya tomato blueberry banana with boost=true");
//Test #413 checking search results for papaya tomato pear strawberry coconut with boost=true
yourResult = tester.search("papaya tomato pear strawberry coconut", true, 10);
TestingTools.checkSearch(yourResult, "papaya tomato pear strawberry coconut",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #413 checking search results for papaya tomato pear strawberry coconut with boost=true");
//Test #414 checking search results for coconut coconut strawberry fig peach with boost=true
yourResult = tester.search("coconut coconut strawberry fig peach", true, 10);
TestingTools.checkSearch(yourResult, "coconut coconut strawberry fig peach",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #414 checking search results for coconut coconut strawberry fig peach with boost=true");
//Test #415 checking search results for banana with boost=true
yourResult = tester.search("banana", true, 10);
TestingTools.checkSearch(yourResult, "banana",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #415 checking search results for banana with boost=true");
//Test #416 checking search results for coconut tomato kiwi coconut with boost=true
yourResult = tester.search("coconut tomato kiwi coconut", true, 10);
TestingTools.checkSearch(yourResult, "coconut tomato kiwi coconut",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #416 checking search results for coconut tomato kiwi coconut with boost=true");
//Test #417 checking search results for strawberry strawberry peach kiwi pear with boost=true
yourResult = tester.search("strawberry strawberry peach kiwi pear", true, 10);
TestingTools.checkSearch(yourResult, "strawberry strawberry peach kiwi pear",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #417 checking search results for strawberry strawberry peach kiwi pear with boost=true");
//Test #418 checking search results for peach with boost=true
yourResult = tester.search("peach", true, 10);
TestingTools.checkSearch(yourResult, "peach",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #418 checking search results for peach with boost=true");
//Test #419 checking search results for apricot apricot lime apple papaya with boost=true
yourResult = tester.search("apricot apricot lime apple papaya", true, 10);
TestingTools.checkSearch(yourResult, "apricot apricot lime apple papaya",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #419 checking search results for apricot apricot lime apple papaya with boost=true");
//Test #420 checking search results for blueberry kiwi coconut with boost=true
yourResult = tester.search("blueberry kiwi coconut", true, 10);
TestingTools.checkSearch(yourResult, "blueberry kiwi coconut",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #420 checking search results for blueberry kiwi coconut with boost=true");
//Test #421 checking search results for apple cherry pear strawberry with boost=true
yourResult = tester.search("apple cherry pear strawberry", true, 10);
TestingTools.checkSearch(yourResult, "apple cherry pear strawberry",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #421 checking search results for apple cherry pear strawberry with boost=true");
//Test #422 checking search results for banana lime kiwi tomato tomato with boost=true
yourResult = tester.search("banana lime kiwi tomato tomato", true, 10);
TestingTools.checkSearch(yourResult, "banana lime kiwi tomato tomato",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #422 checking search results for banana lime kiwi tomato tomato with boost=true");
//Test #423 checking search results for apricot lime with boost=true
yourResult = tester.search("apricot lime", true, 10);
TestingTools.checkSearch(yourResult, "apricot lime",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #423 checking search results for apricot lime with boost=true");
//Test #424 checking search results for pear with boost=true
yourResult = tester.search("pear", true, 10);
TestingTools.checkSearch(yourResult, "pear",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #424 checking search results for pear with boost=true");
//Test #425 checking search results for peach peach lime with boost=true
yourResult = tester.search("peach peach lime", true, 10);
TestingTools.checkSearch(yourResult, "peach peach lime",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #425 checking search results for peach peach lime with boost=true");
//Test #426 checking search results for fig lime kiwi coconut with boost=true
yourResult = tester.search("fig lime kiwi coconut", true, 10);
TestingTools.checkSearch(yourResult, "fig lime kiwi coconut",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #426 checking search results for fig lime kiwi coconut with boost=true");
//Test #427 checking search results for pear banana with boost=true
yourResult = tester.search("pear banana", true, 10);
TestingTools.checkSearch(yourResult, "pear banana",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #427 checking search results for pear banana with boost=true");
//Test #428 checking search results for tomato papaya tomato with boost=true
yourResult = tester.search("tomato papaya tomato", true, 10);
TestingTools.checkSearch(yourResult, "tomato papaya tomato",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #428 checking search results for tomato papaya tomato with boost=true");
//Test #429 checking search results for pear tomato with boost=true
yourResult = tester.search("pear tomato", true, 10);
TestingTools.checkSearch(yourResult, "pear tomato",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #429 checking search results for pear tomato with boost=true");
//Test #430 checking search results for pear coconut strawberry apricot with boost=true
yourResult = tester.search("pear coconut strawberry apricot", true, 10);
TestingTools.checkSearch(yourResult, "pear coconut strawberry apricot",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #430 checking search results for pear coconut strawberry apricot with boost=true");
//Test #431 checking search results for pear with boost=true
yourResult = tester.search("pear", true, 10);
TestingTools.checkSearch(yourResult, "pear",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #431 checking search results for pear with boost=true");
//Test #432 checking search results for coconut with boost=true
yourResult = tester.search("coconut", true, 10);
TestingTools.checkSearch(yourResult, "coconut",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #432 checking search results for coconut with boost=true");
//Test #433 checking search results for papaya strawberry tomato with boost=true
yourResult = tester.search("papaya strawberry tomato", true, 10);
TestingTools.checkSearch(yourResult, "papaya strawberry tomato",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #433 checking search results for papaya strawberry tomato with boost=true");
//Test #434 checking search results for tomato pear lime cherry lime with boost=true
yourResult = tester.search("tomato pear lime cherry lime", true, 10);
TestingTools.checkSearch(yourResult, "tomato pear lime cherry lime",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #434 checking search results for tomato pear lime cherry lime with boost=true");
//Test #435 checking search results for peach pear with boost=true
yourResult = tester.search("peach pear", true, 10);
TestingTools.checkSearch(yourResult, "peach pear",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #435 checking search results for peach pear with boost=true");
//Test #436 checking search results for apple blueberry peach pear banana with boost=true
yourResult = tester.search("apple blueberry peach pear banana", true, 10);
TestingTools.checkSearch(yourResult, "apple blueberry peach pear banana",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #436 checking search results for apple blueberry peach pear banana with boost=true");
//Test #437 checking search results for tomato papaya papaya coconut peach with boost=true
yourResult = tester.search("tomato papaya papaya coconut peach", true, 10);
TestingTools.checkSearch(yourResult, "tomato papaya papaya coconut peach",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #437 checking search results for tomato papaya papaya coconut peach with boost=true");
//Test #438 checking search results for apple lime tomato coconut pear with boost=true
yourResult = tester.search("apple lime tomato coconut pear", true, 10);
TestingTools.checkSearch(yourResult, "apple lime tomato coconut pear",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #438 checking search results for apple lime tomato coconut pear with boost=true");
//Test #439 checking search results for coconut strawberry fig apple peach with boost=true
yourResult = tester.search("coconut strawberry fig apple peach", true, 10);
TestingTools.checkSearch(yourResult, "coconut strawberry fig apple peach",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #439 checking search results for coconut strawberry fig apple peach with boost=true");
//Test #440 checking search results for kiwi lime pear with boost=true
yourResult = tester.search("kiwi lime pear", true, 10);
TestingTools.checkSearch(yourResult, "kiwi lime pear",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #440 checking search results for kiwi lime pear with boost=true");
//Test #441 checking search results for apricot lime with boost=true
yourResult = tester.search("apricot lime", true, 10);
TestingTools.checkSearch(yourResult, "apricot lime",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #441 checking search results for apricot lime with boost=true");
//Test #442 checking search results for papaya cherry cherry tomato with boost=true
yourResult = tester.search("papaya cherry cherry tomato", true, 10);
TestingTools.checkSearch(yourResult, "papaya cherry cherry tomato",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #442 checking search results for papaya cherry cherry tomato with boost=true");
//Test #443 checking search results for apple peach with boost=true
yourResult = tester.search("apple peach", true, 10);
TestingTools.checkSearch(yourResult, "apple peach",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #443 checking search results for apple peach with boost=true");
//Test #444 checking search results for coconut peach pear papaya lime with boost=true
yourResult = tester.search("coconut peach pear papaya lime", true, 10);
TestingTools.checkSearch(yourResult, "coconut peach pear papaya lime",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #444 checking search results for coconut peach pear papaya lime with boost=true");
//Test #445 checking search results for pear with boost=true
yourResult = tester.search("pear", true, 10);
TestingTools.checkSearch(yourResult, "pear",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #445 checking search results for pear with boost=true");
//Test #446 checking search results for blueberry apricot kiwi with boost=true
yourResult = tester.search("blueberry apricot kiwi", true, 10);
TestingTools.checkSearch(yourResult, "blueberry apricot kiwi",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #446 checking search results for blueberry apricot kiwi with boost=true");
//Test #447 checking search results for papaya apple banana apple tomato with boost=true
yourResult = tester.search("papaya apple banana apple tomato", true, 10);
TestingTools.checkSearch(yourResult, "papaya apple banana apple tomato",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #447 checking search results for papaya apple banana apple tomato with boost=true");
//Test #448 checking search results for kiwi pear pear with boost=true
yourResult = tester.search("kiwi pear pear", true, 10);
TestingTools.checkSearch(yourResult, "kiwi pear pear",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #448 checking search results for kiwi pear pear with boost=true");
//Test #449 checking search results for apricot banana papaya banana with boost=true
yourResult = tester.search("apricot banana papaya banana", true, 10);
TestingTools.checkSearch(yourResult, "apricot banana papaya banana",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #449 checking search results for apricot banana papaya banana with boost=true");
//Test #450 checking search results for papaya with boost=true
yourResult = tester.search("papaya", true, 10);
TestingTools.checkSearch(yourResult, "papaya",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #450 checking search results for papaya with boost=true");
//Test #451 checking search results for fig fig pear fig coconut with boost=true
yourResult = tester.search("fig fig pear fig coconut", true, 10);
TestingTools.checkSearch(yourResult, "fig fig pear fig coconut",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #451 checking search results for fig fig pear fig coconut with boost=true");
//Test #452 checking search results for blueberry banana kiwi cherry with boost=true
yourResult = tester.search("blueberry banana kiwi cherry", true, 10);
TestingTools.checkSearch(yourResult, "blueberry banana kiwi cherry",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #452 checking search results for blueberry banana kiwi cherry with boost=true");
//Test #453 checking search results for coconut blueberry with boost=true
yourResult = tester.search("coconut blueberry", true, 10);
TestingTools.checkSearch(yourResult, "coconut blueberry",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #453 checking search results for coconut blueberry with boost=true");
//Test #454 checking search results for strawberry peach with boost=true
yourResult = tester.search("strawberry peach", true, 10);
TestingTools.checkSearch(yourResult, "strawberry peach",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #454 checking search results for strawberry peach with boost=true");
//Test #455 checking search results for cherry pear with boost=true
yourResult = tester.search("cherry pear", true, 10);
TestingTools.checkSearch(yourResult, "cherry pear",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #455 checking search results for cherry pear with boost=true");
//Test #456 checking search results for pear with boost=true
yourResult = tester.search("pear", true, 10);
TestingTools.checkSearch(yourResult, "pear",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #456 checking search results for pear with boost=true");
//Test #457 checking search results for banana apricot apricot with boost=true
yourResult = tester.search("banana apricot apricot", true, 10);
TestingTools.checkSearch(yourResult, "banana apricot apricot",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #457 checking search results for banana apricot apricot with boost=true");
//Test #458 checking search results for strawberry cherry papaya with boost=true
yourResult = tester.search("strawberry cherry papaya", true, 10);
TestingTools.checkSearch(yourResult, "strawberry cherry papaya",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #458 checking search results for strawberry cherry papaya with boost=true");
//Test #459 checking search results for coconut banana peach blueberry papaya with boost=true
yourResult = tester.search("coconut banana peach blueberry papaya", true, 10);
TestingTools.checkSearch(yourResult, "coconut banana peach blueberry papaya",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #459 checking search results for coconut banana peach blueberry papaya with boost=true");
//Test #460 checking search results for papaya apricot tomato with boost=true
yourResult = tester.search("papaya apricot tomato", true, 10);
TestingTools.checkSearch(yourResult, "papaya apricot tomato",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #460 checking search results for papaya apricot tomato with boost=true");
//Test #461 checking search results for pear cherry with boost=true
yourResult = tester.search("pear cherry", true, 10);
TestingTools.checkSearch(yourResult, "pear cherry",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #461 checking search results for pear cherry with boost=true");
//Test #462 checking search results for papaya cherry lime with boost=true
yourResult = tester.search("papaya cherry lime", true, 10);
TestingTools.checkSearch(yourResult, "papaya cherry lime",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #462 checking search results for papaya cherry lime with boost=true");
//Test #463 checking search results for peach with boost=true
yourResult = tester.search("peach", true, 10);
TestingTools.checkSearch(yourResult, "peach",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #463 checking search results for peach with boost=true");
//Test #464 checking search results for apricot coconut with boost=true
yourResult = tester.search("apricot coconut", true, 10);
TestingTools.checkSearch(yourResult, "apricot coconut",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #464 checking search results for apricot coconut with boost=true");
//Test #465 checking search results for blueberry fig lime apricot with boost=true
yourResult = tester.search("blueberry fig lime apricot", true, 10);
TestingTools.checkSearch(yourResult, "blueberry fig lime apricot",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #465 checking search results for blueberry fig lime apricot with boost=true");
//Test #466 checking search results for papaya apple papaya kiwi apricot with boost=true
yourResult = tester.search("papaya apple papaya kiwi apricot", true, 10);
TestingTools.checkSearch(yourResult, "papaya apple papaya kiwi apricot",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #466 checking search results for papaya apple papaya kiwi apricot with boost=true");
//Test #467 checking search results for papaya with boost=true
yourResult = tester.search("papaya", true, 10);
TestingTools.checkSearch(yourResult, "papaya",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #467 checking search results for papaya with boost=true");
//Test #468 checking search results for apricot kiwi peach coconut banana with boost=true
yourResult = tester.search("apricot kiwi peach coconut banana", true, 10);
TestingTools.checkSearch(yourResult, "apricot kiwi peach coconut banana",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #468 checking search results for apricot kiwi peach coconut banana with boost=true");
//Test #469 checking search results for fig kiwi papaya with boost=true
yourResult = tester.search("fig kiwi papaya", true, 10);
TestingTools.checkSearch(yourResult, "fig kiwi papaya",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #469 checking search results for fig kiwi papaya with boost=true");
//Test #470 checking search results for lime apricot lime lime with boost=true
yourResult = tester.search("lime apricot lime lime", true, 10);
TestingTools.checkSearch(yourResult, "lime apricot lime lime",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #470 checking search results for lime apricot lime lime with boost=true");
//Test #471 checking search results for coconut fig with boost=true
yourResult = tester.search("coconut fig", true, 10);
TestingTools.checkSearch(yourResult, "coconut fig",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #471 checking search results for coconut fig with boost=true");
//Test #472 checking search results for pear tomato tomato blueberry with boost=true
yourResult = tester.search("pear tomato tomato blueberry", true, 10);
TestingTools.checkSearch(yourResult, "pear tomato tomato blueberry",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #472 checking search results for pear tomato tomato blueberry with boost=true");
//Test #473 checking search results for apricot with boost=true
yourResult = tester.search("apricot", true, 10);
TestingTools.checkSearch(yourResult, "apricot",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #473 checking search results for apricot with boost=true");
//Test #474 checking search results for strawberry coconut banana tomato with boost=true
yourResult = tester.search("strawberry coconut banana tomato", true, 10);
TestingTools.checkSearch(yourResult, "strawberry coconut banana tomato",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #474 checking search results for strawberry coconut banana tomato with boost=true");
//Test #475 checking search results for apricot strawberry tomato banana with boost=true
yourResult = tester.search("apricot strawberry tomato banana", true, 10);
TestingTools.checkSearch(yourResult, "apricot strawberry tomato banana",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #475 checking search results for apricot strawberry tomato banana with boost=true");
//Test #476 checking search results for blueberry strawberry pear with boost=true
yourResult = tester.search("blueberry strawberry pear", true, 10);
TestingTools.checkSearch(yourResult, "blueberry strawberry pear",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #476 checking search results for blueberry strawberry pear with boost=true");
//Test #477 checking search results for pear with boost=true
yourResult = tester.search("pear", true, 10);
TestingTools.checkSearch(yourResult, "pear",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #477 checking search results for pear with boost=true");
//Test #478 checking search results for coconut tomato strawberry with boost=true
yourResult = tester.search("coconut tomato strawberry", true, 10);
TestingTools.checkSearch(yourResult, "coconut tomato strawberry",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #478 checking search results for coconut tomato strawberry with boost=true");
//Test #479 checking search results for pear strawberry peach coconut fig with boost=true
yourResult = tester.search("pear strawberry peach coconut fig", true, 10);
TestingTools.checkSearch(yourResult, "pear strawberry peach coconut fig",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #479 checking search results for pear strawberry peach coconut fig with boost=true");
//Test #480 checking search results for blueberry pear with boost=true
yourResult = tester.search("blueberry pear", true, 10);
TestingTools.checkSearch(yourResult, "blueberry pear",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #480 checking search results for blueberry pear with boost=true");
//Test #481 checking search results for apple coconut tomato with boost=true
yourResult = tester.search("apple coconut tomato", true, 10);
TestingTools.checkSearch(yourResult, "apple coconut tomato",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #481 checking search results for apple coconut tomato with boost=true");
//Test #482 checking search results for cherry cherry pear tomato pear with boost=true
yourResult = tester.search("cherry cherry pear tomato pear", true, 10);
TestingTools.checkSearch(yourResult, "cherry cherry pear tomato pear",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #482 checking search results for cherry cherry pear tomato pear with boost=true");
//Test #483 checking search results for tomato cherry kiwi banana with boost=true
yourResult = tester.search("tomato cherry kiwi banana", true, 10);
TestingTools.checkSearch(yourResult, "tomato cherry kiwi banana",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #483 checking search results for tomato cherry kiwi banana with boost=true");
//Test #484 checking search results for pear apricot with boost=true
yourResult = tester.search("pear apricot", true, 10);
TestingTools.checkSearch(yourResult, "pear apricot",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #484 checking search results for pear apricot with boost=true");
//Test #485 checking search results for apricot with boost=true
yourResult = tester.search("apricot", true, 10);
TestingTools.checkSearch(yourResult, "apricot",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #485 checking search results for apricot with boost=true");
//Test #486 checking search results for fig strawberry peach with boost=true
yourResult = tester.search("fig strawberry peach", true, 10);
TestingTools.checkSearch(yourResult, "fig strawberry peach",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #486 checking search results for fig strawberry peach with boost=true");
//Test #487 checking search results for kiwi coconut strawberry with boost=true
yourResult = tester.search("kiwi coconut strawberry", true, 10);
TestingTools.checkSearch(yourResult, "kiwi coconut strawberry",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #487 checking search results for kiwi coconut strawberry with boost=true");
//Test #488 checking search results for blueberry papaya peach with boost=true
yourResult = tester.search("blueberry papaya peach", true, 10);
TestingTools.checkSearch(yourResult, "blueberry papaya peach",true, passOut, failOut, "TinyFruitsASearchBoostTester", "Test #488 checking search results for blueberry papaya peach with boost=true");
failOut.close();
passOut.close();
}
}
