import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.*;
public class TinyFruitsASearchNoBoostTester {public static void main(String[] args) throws Exception{
ProjectTester tester = new ProjectTesterImp(); //Instantiate your own ProjectTester instance here
tester.initialize();
tester.crawl("https://people.scs.carleton.ca/~avamckenney/tinyfruitsA/N-0.html");
runTest(tester);}public static void runTest(ProjectTester tester) throws Exception{
PrintWriter failOut = new PrintWriter(new FileWriter("TinyFruitsA-SearchNoBoost-failed.txt"));
PrintWriter passOut = new PrintWriter(new FileWriter("TinyFruitsA-SearchNoBoost-passed.txt"));
List<SearchResult> yourResult; 
//Test #289 checking search results for banana strawberry apricot blueberry with boost=true
yourResult = tester.search("banana strawberry apricot blueberry", false, 10);
TestingTools.checkSearch(yourResult, "banana strawberry apricot blueberry",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #289 checking search results for banana strawberry apricot blueberry with boost=true");
//Test #290 checking search results for apricot blueberry apple cherry with boost=true
yourResult = tester.search("apricot blueberry apple cherry", false, 10);
TestingTools.checkSearch(yourResult, "apricot blueberry apple cherry",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #290 checking search results for apricot blueberry apple cherry with boost=true");
//Test #291 checking search results for papaya with boost=true
yourResult = tester.search("papaya", false, 10);
TestingTools.checkSearch(yourResult, "papaya",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #291 checking search results for papaya with boost=true");
//Test #292 checking search results for apricot peach apricot cherry strawberry with boost=true
yourResult = tester.search("apricot peach apricot cherry strawberry", false, 10);
TestingTools.checkSearch(yourResult, "apricot peach apricot cherry strawberry",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #292 checking search results for apricot peach apricot cherry strawberry with boost=true");
//Test #293 checking search results for lime blueberry banana with boost=true
yourResult = tester.search("lime blueberry banana", false, 10);
TestingTools.checkSearch(yourResult, "lime blueberry banana",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #293 checking search results for lime blueberry banana with boost=true");
//Test #294 checking search results for blueberry peach papaya apricot strawberry with boost=true
yourResult = tester.search("blueberry peach papaya apricot strawberry", false, 10);
TestingTools.checkSearch(yourResult, "blueberry peach papaya apricot strawberry",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #294 checking search results for blueberry peach papaya apricot strawberry with boost=true");
//Test #295 checking search results for apple kiwi coconut tomato blueberry with boost=true
yourResult = tester.search("apple kiwi coconut tomato blueberry", false, 10);
TestingTools.checkSearch(yourResult, "apple kiwi coconut tomato blueberry",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #295 checking search results for apple kiwi coconut tomato blueberry with boost=true");
//Test #296 checking search results for papaya banana cherry with boost=true
yourResult = tester.search("papaya banana cherry", false, 10);
TestingTools.checkSearch(yourResult, "papaya banana cherry",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #296 checking search results for papaya banana cherry with boost=true");
//Test #297 checking search results for apricot with boost=true
yourResult = tester.search("apricot", false, 10);
TestingTools.checkSearch(yourResult, "apricot",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #297 checking search results for apricot with boost=true");
//Test #298 checking search results for fig papaya with boost=true
yourResult = tester.search("fig papaya", false, 10);
TestingTools.checkSearch(yourResult, "fig papaya",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #298 checking search results for fig papaya with boost=true");
//Test #299 checking search results for apricot with boost=true
yourResult = tester.search("apricot", false, 10);
TestingTools.checkSearch(yourResult, "apricot",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #299 checking search results for apricot with boost=true");
//Test #300 checking search results for banana papaya papaya fig with boost=true
yourResult = tester.search("banana papaya papaya fig", false, 10);
TestingTools.checkSearch(yourResult, "banana papaya papaya fig",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #300 checking search results for banana papaya papaya fig with boost=true");
//Test #301 checking search results for banana kiwi papaya banana cherry with boost=true
yourResult = tester.search("banana kiwi papaya banana cherry", false, 10);
TestingTools.checkSearch(yourResult, "banana kiwi papaya banana cherry",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #301 checking search results for banana kiwi papaya banana cherry with boost=true");
//Test #302 checking search results for banana tomato lime banana blueberry with boost=true
yourResult = tester.search("banana tomato lime banana blueberry", false, 10);
TestingTools.checkSearch(yourResult, "banana tomato lime banana blueberry",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #302 checking search results for banana tomato lime banana blueberry with boost=true");
//Test #303 checking search results for apricot with boost=true
yourResult = tester.search("apricot", false, 10);
TestingTools.checkSearch(yourResult, "apricot",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #303 checking search results for apricot with boost=true");
//Test #304 checking search results for banana with boost=true
yourResult = tester.search("banana", false, 10);
TestingTools.checkSearch(yourResult, "banana",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #304 checking search results for banana with boost=true");
//Test #305 checking search results for kiwi fig pear kiwi banana with boost=true
yourResult = tester.search("kiwi fig pear kiwi banana", false, 10);
TestingTools.checkSearch(yourResult, "kiwi fig pear kiwi banana",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #305 checking search results for kiwi fig pear kiwi banana with boost=true");
//Test #306 checking search results for fig lime coconut with boost=true
yourResult = tester.search("fig lime coconut", false, 10);
TestingTools.checkSearch(yourResult, "fig lime coconut",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #306 checking search results for fig lime coconut with boost=true");
//Test #307 checking search results for tomato strawberry peach coconut blueberry with boost=true
yourResult = tester.search("tomato strawberry peach coconut blueberry", false, 10);
TestingTools.checkSearch(yourResult, "tomato strawberry peach coconut blueberry",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #307 checking search results for tomato strawberry peach coconut blueberry with boost=true");
//Test #308 checking search results for fig cherry fig papaya cherry with boost=true
yourResult = tester.search("fig cherry fig papaya cherry", false, 10);
TestingTools.checkSearch(yourResult, "fig cherry fig papaya cherry",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #308 checking search results for fig cherry fig papaya cherry with boost=true");
//Test #309 checking search results for blueberry apricot lime kiwi with boost=true
yourResult = tester.search("blueberry apricot lime kiwi", false, 10);
TestingTools.checkSearch(yourResult, "blueberry apricot lime kiwi",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #309 checking search results for blueberry apricot lime kiwi with boost=true");
//Test #310 checking search results for peach cherry apple peach pear with boost=true
yourResult = tester.search("peach cherry apple peach pear", false, 10);
TestingTools.checkSearch(yourResult, "peach cherry apple peach pear",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #310 checking search results for peach cherry apple peach pear with boost=true");
//Test #311 checking search results for apricot cherry tomato kiwi with boost=true
yourResult = tester.search("apricot cherry tomato kiwi", false, 10);
TestingTools.checkSearch(yourResult, "apricot cherry tomato kiwi",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #311 checking search results for apricot cherry tomato kiwi with boost=true");
//Test #312 checking search results for apricot with boost=true
yourResult = tester.search("apricot", false, 10);
TestingTools.checkSearch(yourResult, "apricot",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #312 checking search results for apricot with boost=true");
//Test #313 checking search results for peach lime peach coconut with boost=true
yourResult = tester.search("peach lime peach coconut", false, 10);
TestingTools.checkSearch(yourResult, "peach lime peach coconut",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #313 checking search results for peach lime peach coconut with boost=true");
//Test #314 checking search results for fig cherry blueberry coconut with boost=true
yourResult = tester.search("fig cherry blueberry coconut", false, 10);
TestingTools.checkSearch(yourResult, "fig cherry blueberry coconut",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #314 checking search results for fig cherry blueberry coconut with boost=true");
//Test #315 checking search results for banana blueberry with boost=true
yourResult = tester.search("banana blueberry", false, 10);
TestingTools.checkSearch(yourResult, "banana blueberry",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #315 checking search results for banana blueberry with boost=true");
//Test #316 checking search results for apple fig coconut banana strawberry with boost=true
yourResult = tester.search("apple fig coconut banana strawberry", false, 10);
TestingTools.checkSearch(yourResult, "apple fig coconut banana strawberry",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #316 checking search results for apple fig coconut banana strawberry with boost=true");
//Test #317 checking search results for coconut with boost=true
yourResult = tester.search("coconut", false, 10);
TestingTools.checkSearch(yourResult, "coconut",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #317 checking search results for coconut with boost=true");
//Test #318 checking search results for papaya pear with boost=true
yourResult = tester.search("papaya pear", false, 10);
TestingTools.checkSearch(yourResult, "papaya pear",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #318 checking search results for papaya pear with boost=true");
//Test #319 checking search results for cherry tomato lime peach with boost=true
yourResult = tester.search("cherry tomato lime peach", false, 10);
TestingTools.checkSearch(yourResult, "cherry tomato lime peach",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #319 checking search results for cherry tomato lime peach with boost=true");
//Test #320 checking search results for papaya blueberry strawberry peach fig with boost=true
yourResult = tester.search("papaya blueberry strawberry peach fig", false, 10);
TestingTools.checkSearch(yourResult, "papaya blueberry strawberry peach fig",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #320 checking search results for papaya blueberry strawberry peach fig with boost=true");
//Test #321 checking search results for apple papaya tomato pear kiwi with boost=true
yourResult = tester.search("apple papaya tomato pear kiwi", false, 10);
TestingTools.checkSearch(yourResult, "apple papaya tomato pear kiwi",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #321 checking search results for apple papaya tomato pear kiwi with boost=true");
//Test #322 checking search results for apple papaya papaya with boost=true
yourResult = tester.search("apple papaya papaya", false, 10);
TestingTools.checkSearch(yourResult, "apple papaya papaya",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #322 checking search results for apple papaya papaya with boost=true");
//Test #323 checking search results for banana pear lime banana with boost=true
yourResult = tester.search("banana pear lime banana", false, 10);
TestingTools.checkSearch(yourResult, "banana pear lime banana",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #323 checking search results for banana pear lime banana with boost=true");
//Test #324 checking search results for strawberry apricot papaya apple with boost=true
yourResult = tester.search("strawberry apricot papaya apple", false, 10);
TestingTools.checkSearch(yourResult, "strawberry apricot papaya apple",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #324 checking search results for strawberry apricot papaya apple with boost=true");
//Test #325 checking search results for blueberry kiwi pear peach with boost=true
yourResult = tester.search("blueberry kiwi pear peach", false, 10);
TestingTools.checkSearch(yourResult, "blueberry kiwi pear peach",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #325 checking search results for blueberry kiwi pear peach with boost=true");
//Test #326 checking search results for apple coconut coconut coconut pear with boost=true
yourResult = tester.search("apple coconut coconut coconut pear", false, 10);
TestingTools.checkSearch(yourResult, "apple coconut coconut coconut pear",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #326 checking search results for apple coconut coconut coconut pear with boost=true");
//Test #327 checking search results for apricot peach papaya apple with boost=true
yourResult = tester.search("apricot peach papaya apple", false, 10);
TestingTools.checkSearch(yourResult, "apricot peach papaya apple",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #327 checking search results for apricot peach papaya apple with boost=true");
//Test #328 checking search results for pear with boost=true
yourResult = tester.search("pear", false, 10);
TestingTools.checkSearch(yourResult, "pear",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #328 checking search results for pear with boost=true");
//Test #329 checking search results for lime strawberry apricot with boost=true
yourResult = tester.search("lime strawberry apricot", false, 10);
TestingTools.checkSearch(yourResult, "lime strawberry apricot",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #329 checking search results for lime strawberry apricot with boost=true");
//Test #330 checking search results for cherry apple tomato apricot with boost=true
yourResult = tester.search("cherry apple tomato apricot", false, 10);
TestingTools.checkSearch(yourResult, "cherry apple tomato apricot",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #330 checking search results for cherry apple tomato apricot with boost=true");
//Test #331 checking search results for banana tomato with boost=true
yourResult = tester.search("banana tomato", false, 10);
TestingTools.checkSearch(yourResult, "banana tomato",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #331 checking search results for banana tomato with boost=true");
//Test #332 checking search results for peach with boost=true
yourResult = tester.search("peach", false, 10);
TestingTools.checkSearch(yourResult, "peach",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #332 checking search results for peach with boost=true");
//Test #333 checking search results for coconut papaya cherry pear apple with boost=true
yourResult = tester.search("coconut papaya cherry pear apple", false, 10);
TestingTools.checkSearch(yourResult, "coconut papaya cherry pear apple",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #333 checking search results for coconut papaya cherry pear apple with boost=true");
//Test #334 checking search results for banana banana with boost=true
yourResult = tester.search("banana banana", false, 10);
TestingTools.checkSearch(yourResult, "banana banana",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #334 checking search results for banana banana with boost=true");
//Test #335 checking search results for kiwi apple pear banana with boost=true
yourResult = tester.search("kiwi apple pear banana", false, 10);
TestingTools.checkSearch(yourResult, "kiwi apple pear banana",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #335 checking search results for kiwi apple pear banana with boost=true");
//Test #336 checking search results for papaya coconut apricot kiwi with boost=true
yourResult = tester.search("papaya coconut apricot kiwi", false, 10);
TestingTools.checkSearch(yourResult, "papaya coconut apricot kiwi",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #336 checking search results for papaya coconut apricot kiwi with boost=true");
//Test #337 checking search results for kiwi peach blueberry apple with boost=true
yourResult = tester.search("kiwi peach blueberry apple", false, 10);
TestingTools.checkSearch(yourResult, "kiwi peach blueberry apple",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #337 checking search results for kiwi peach blueberry apple with boost=true");
//Test #338 checking search results for pear fig with boost=true
yourResult = tester.search("pear fig", false, 10);
TestingTools.checkSearch(yourResult, "pear fig",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #338 checking search results for pear fig with boost=true");
//Test #339 checking search results for coconut apple with boost=true
yourResult = tester.search("coconut apple", false, 10);
TestingTools.checkSearch(yourResult, "coconut apple",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #339 checking search results for coconut apple with boost=true");
//Test #340 checking search results for pear pear strawberry apple kiwi with boost=true
yourResult = tester.search("pear pear strawberry apple kiwi", false, 10);
TestingTools.checkSearch(yourResult, "pear pear strawberry apple kiwi",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #340 checking search results for pear pear strawberry apple kiwi with boost=true");
//Test #341 checking search results for banana apricot with boost=true
yourResult = tester.search("banana apricot", false, 10);
TestingTools.checkSearch(yourResult, "banana apricot",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #341 checking search results for banana apricot with boost=true");
//Test #342 checking search results for peach with boost=true
yourResult = tester.search("peach", false, 10);
TestingTools.checkSearch(yourResult, "peach",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #342 checking search results for peach with boost=true");
//Test #343 checking search results for apricot with boost=true
yourResult = tester.search("apricot", false, 10);
TestingTools.checkSearch(yourResult, "apricot",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #343 checking search results for apricot with boost=true");
//Test #344 checking search results for apricot lime papaya with boost=true
yourResult = tester.search("apricot lime papaya", false, 10);
TestingTools.checkSearch(yourResult, "apricot lime papaya",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #344 checking search results for apricot lime papaya with boost=true");
//Test #345 checking search results for apricot blueberry fig cherry kiwi with boost=true
yourResult = tester.search("apricot blueberry fig cherry kiwi", false, 10);
TestingTools.checkSearch(yourResult, "apricot blueberry fig cherry kiwi",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #345 checking search results for apricot blueberry fig cherry kiwi with boost=true");
//Test #346 checking search results for coconut blueberry strawberry papaya papaya with boost=true
yourResult = tester.search("coconut blueberry strawberry papaya papaya", false, 10);
TestingTools.checkSearch(yourResult, "coconut blueberry strawberry papaya papaya",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #346 checking search results for coconut blueberry strawberry papaya papaya with boost=true");
//Test #347 checking search results for banana kiwi banana pear strawberry with boost=true
yourResult = tester.search("banana kiwi banana pear strawberry", false, 10);
TestingTools.checkSearch(yourResult, "banana kiwi banana pear strawberry",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #347 checking search results for banana kiwi banana pear strawberry with boost=true");
//Test #348 checking search results for blueberry coconut lime apple lime with boost=true
yourResult = tester.search("blueberry coconut lime apple lime", false, 10);
TestingTools.checkSearch(yourResult, "blueberry coconut lime apple lime",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #348 checking search results for blueberry coconut lime apple lime with boost=true");
//Test #349 checking search results for apricot with boost=true
yourResult = tester.search("apricot", false, 10);
TestingTools.checkSearch(yourResult, "apricot",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #349 checking search results for apricot with boost=true");
//Test #350 checking search results for coconut kiwi banana with boost=true
yourResult = tester.search("coconut kiwi banana", false, 10);
TestingTools.checkSearch(yourResult, "coconut kiwi banana",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #350 checking search results for coconut kiwi banana with boost=true");
//Test #351 checking search results for apricot with boost=true
yourResult = tester.search("apricot", false, 10);
TestingTools.checkSearch(yourResult, "apricot",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #351 checking search results for apricot with boost=true");
//Test #352 checking search results for cherry cherry peach with boost=true
yourResult = tester.search("cherry cherry peach", false, 10);
TestingTools.checkSearch(yourResult, "cherry cherry peach",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #352 checking search results for cherry cherry peach with boost=true");
//Test #353 checking search results for banana peach with boost=true
yourResult = tester.search("banana peach", false, 10);
TestingTools.checkSearch(yourResult, "banana peach",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #353 checking search results for banana peach with boost=true");
//Test #354 checking search results for apple banana coconut tomato apricot with boost=true
yourResult = tester.search("apple banana coconut tomato apricot", false, 10);
TestingTools.checkSearch(yourResult, "apple banana coconut tomato apricot",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #354 checking search results for apple banana coconut tomato apricot with boost=true");
//Test #355 checking search results for cherry cherry papaya blueberry with boost=true
yourResult = tester.search("cherry cherry papaya blueberry", false, 10);
TestingTools.checkSearch(yourResult, "cherry cherry papaya blueberry",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #355 checking search results for cherry cherry papaya blueberry with boost=true");
//Test #356 checking search results for strawberry pear tomato peach with boost=true
yourResult = tester.search("strawberry pear tomato peach", false, 10);
TestingTools.checkSearch(yourResult, "strawberry pear tomato peach",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #356 checking search results for strawberry pear tomato peach with boost=true");
//Test #357 checking search results for coconut pear apricot coconut with boost=true
yourResult = tester.search("coconut pear apricot coconut", false, 10);
TestingTools.checkSearch(yourResult, "coconut pear apricot coconut",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #357 checking search results for coconut pear apricot coconut with boost=true");
//Test #358 checking search results for pear lime tomato with boost=true
yourResult = tester.search("pear lime tomato", false, 10);
TestingTools.checkSearch(yourResult, "pear lime tomato",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #358 checking search results for pear lime tomato with boost=true");
//Test #359 checking search results for apricot coconut papaya strawberry with boost=true
yourResult = tester.search("apricot coconut papaya strawberry", false, 10);
TestingTools.checkSearch(yourResult, "apricot coconut papaya strawberry",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #359 checking search results for apricot coconut papaya strawberry with boost=true");
//Test #360 checking search results for coconut cherry strawberry with boost=true
yourResult = tester.search("coconut cherry strawberry", false, 10);
TestingTools.checkSearch(yourResult, "coconut cherry strawberry",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #360 checking search results for coconut cherry strawberry with boost=true");
//Test #361 checking search results for pear coconut with boost=true
yourResult = tester.search("pear coconut", false, 10);
TestingTools.checkSearch(yourResult, "pear coconut",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #361 checking search results for pear coconut with boost=true");
//Test #362 checking search results for strawberry apricot banana with boost=true
yourResult = tester.search("strawberry apricot banana", false, 10);
TestingTools.checkSearch(yourResult, "strawberry apricot banana",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #362 checking search results for strawberry apricot banana with boost=true");
//Test #363 checking search results for blueberry fig coconut papaya lime with boost=true
yourResult = tester.search("blueberry fig coconut papaya lime", false, 10);
TestingTools.checkSearch(yourResult, "blueberry fig coconut papaya lime",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #363 checking search results for blueberry fig coconut papaya lime with boost=true");
//Test #364 checking search results for lime peach banana with boost=true
yourResult = tester.search("lime peach banana", false, 10);
TestingTools.checkSearch(yourResult, "lime peach banana",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #364 checking search results for lime peach banana with boost=true");
//Test #365 checking search results for apricot tomato with boost=true
yourResult = tester.search("apricot tomato", false, 10);
TestingTools.checkSearch(yourResult, "apricot tomato",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #365 checking search results for apricot tomato with boost=true");
//Test #366 checking search results for cherry peach tomato with boost=true
yourResult = tester.search("cherry peach tomato", false, 10);
TestingTools.checkSearch(yourResult, "cherry peach tomato",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #366 checking search results for cherry peach tomato with boost=true");
//Test #367 checking search results for coconut tomato fig peach blueberry with boost=true
yourResult = tester.search("coconut tomato fig peach blueberry", false, 10);
TestingTools.checkSearch(yourResult, "coconut tomato fig peach blueberry",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #367 checking search results for coconut tomato fig peach blueberry with boost=true");
//Test #368 checking search results for peach with boost=true
yourResult = tester.search("peach", false, 10);
TestingTools.checkSearch(yourResult, "peach",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #368 checking search results for peach with boost=true");
//Test #369 checking search results for peach strawberry coconut strawberry apricot with boost=true
yourResult = tester.search("peach strawberry coconut strawberry apricot", false, 10);
TestingTools.checkSearch(yourResult, "peach strawberry coconut strawberry apricot",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #369 checking search results for peach strawberry coconut strawberry apricot with boost=true");
//Test #370 checking search results for coconut strawberry peach banana apricot with boost=true
yourResult = tester.search("coconut strawberry peach banana apricot", false, 10);
TestingTools.checkSearch(yourResult, "coconut strawberry peach banana apricot",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #370 checking search results for coconut strawberry peach banana apricot with boost=true");
//Test #371 checking search results for pear blueberry with boost=true
yourResult = tester.search("pear blueberry", false, 10);
TestingTools.checkSearch(yourResult, "pear blueberry",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #371 checking search results for pear blueberry with boost=true");
//Test #372 checking search results for peach with boost=true
yourResult = tester.search("peach", false, 10);
TestingTools.checkSearch(yourResult, "peach",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #372 checking search results for peach with boost=true");
//Test #373 checking search results for kiwi cherry papaya kiwi with boost=true
yourResult = tester.search("kiwi cherry papaya kiwi", false, 10);
TestingTools.checkSearch(yourResult, "kiwi cherry papaya kiwi",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #373 checking search results for kiwi cherry papaya kiwi with boost=true");
//Test #374 checking search results for tomato kiwi fig pear with boost=true
yourResult = tester.search("tomato kiwi fig pear", false, 10);
TestingTools.checkSearch(yourResult, "tomato kiwi fig pear",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #374 checking search results for tomato kiwi fig pear with boost=true");
//Test #375 checking search results for peach pear coconut coconut with boost=true
yourResult = tester.search("peach pear coconut coconut", false, 10);
TestingTools.checkSearch(yourResult, "peach pear coconut coconut",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #375 checking search results for peach pear coconut coconut with boost=true");
//Test #376 checking search results for tomato blueberry coconut with boost=true
yourResult = tester.search("tomato blueberry coconut", false, 10);
TestingTools.checkSearch(yourResult, "tomato blueberry coconut",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #376 checking search results for tomato blueberry coconut with boost=true");
//Test #377 checking search results for strawberry fig coconut peach kiwi with boost=true
yourResult = tester.search("strawberry fig coconut peach kiwi", false, 10);
TestingTools.checkSearch(yourResult, "strawberry fig coconut peach kiwi",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #377 checking search results for strawberry fig coconut peach kiwi with boost=true");
//Test #378 checking search results for peach papaya with boost=true
yourResult = tester.search("peach papaya", false, 10);
TestingTools.checkSearch(yourResult, "peach papaya",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #378 checking search results for peach papaya with boost=true");
//Test #379 checking search results for peach with boost=true
yourResult = tester.search("peach", false, 10);
TestingTools.checkSearch(yourResult, "peach",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #379 checking search results for peach with boost=true");
//Test #380 checking search results for apricot fig coconut tomato tomato with boost=true
yourResult = tester.search("apricot fig coconut tomato tomato", false, 10);
TestingTools.checkSearch(yourResult, "apricot fig coconut tomato tomato",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #380 checking search results for apricot fig coconut tomato tomato with boost=true");
//Test #381 checking search results for pear with boost=true
yourResult = tester.search("pear", false, 10);
TestingTools.checkSearch(yourResult, "pear",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #381 checking search results for pear with boost=true");
//Test #382 checking search results for strawberry peach with boost=true
yourResult = tester.search("strawberry peach", false, 10);
TestingTools.checkSearch(yourResult, "strawberry peach",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #382 checking search results for strawberry peach with boost=true");
//Test #383 checking search results for apple blueberry papaya fig with boost=true
yourResult = tester.search("apple blueberry papaya fig", false, 10);
TestingTools.checkSearch(yourResult, "apple blueberry papaya fig",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #383 checking search results for apple blueberry papaya fig with boost=true");
//Test #384 checking search results for coconut with boost=true
yourResult = tester.search("coconut", false, 10);
TestingTools.checkSearch(yourResult, "coconut",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #384 checking search results for coconut with boost=true");
//Test #385 checking search results for apricot peach strawberry fig cherry with boost=true
yourResult = tester.search("apricot peach strawberry fig cherry", false, 10);
TestingTools.checkSearch(yourResult, "apricot peach strawberry fig cherry",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #385 checking search results for apricot peach strawberry fig cherry with boost=true");
//Test #386 checking search results for cherry banana blueberry peach with boost=true
yourResult = tester.search("cherry banana blueberry peach", false, 10);
TestingTools.checkSearch(yourResult, "cherry banana blueberry peach",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #386 checking search results for cherry banana blueberry peach with boost=true");
//Test #387 checking search results for coconut fig coconut tomato with boost=true
yourResult = tester.search("coconut fig coconut tomato", false, 10);
TestingTools.checkSearch(yourResult, "coconut fig coconut tomato",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #387 checking search results for coconut fig coconut tomato with boost=true");
//Test #388 checking search results for peach blueberry with boost=true
yourResult = tester.search("peach blueberry", false, 10);
TestingTools.checkSearch(yourResult, "peach blueberry",false, passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #388 checking search results for peach blueberry with boost=true");
failOut.close();
passOut.close();
}
}
