import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.*;
public class TinyFruitsSearchNoBoostTester {public static void main(String[] args) throws Exception{
ProjectTester tester = new ProjectTesterImp(); //Instantiate your own ProjectTester instance here
tester.initialize();
tester.crawl("https://people.scs.carleton.ca/~avamckenney/tinyfruits/N-0.html");
runTest(tester);}public static void runTest(ProjectTester tester) throws Exception{
PrintWriter failOut = new PrintWriter(new FileWriter("TinyFruits-SearchNoBoost-failed.txt"));
PrintWriter passOut = new PrintWriter(new FileWriter("TinyFruits-SearchNoBoost-passed.txt"));
List<SearchResult> yourResult; 
//Test #289 checking search results for orange papaya lime orange with boost=true
yourResult = tester.search("orange papaya lime orange", false, 10);
TestingTools.checkSearch(yourResult, "orange papaya lime orange",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #289 checking search results for orange papaya lime orange with boost=true");
//Test #290 checking search results for cherry banana with boost=true
yourResult = tester.search("cherry banana", false, 10);
TestingTools.checkSearch(yourResult, "cherry banana",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #290 checking search results for cherry banana with boost=true");
//Test #291 checking search results for apple tomato orange with boost=true
yourResult = tester.search("apple tomato orange", false, 10);
TestingTools.checkSearch(yourResult, "apple tomato orange",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #291 checking search results for apple tomato orange with boost=true");
//Test #292 checking search results for lime with boost=true
yourResult = tester.search("lime", false, 10);
TestingTools.checkSearch(yourResult, "lime",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #292 checking search results for lime with boost=true");
//Test #293 checking search results for orange lime with boost=true
yourResult = tester.search("orange lime", false, 10);
TestingTools.checkSearch(yourResult, "orange lime",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #293 checking search results for orange lime with boost=true");
//Test #294 checking search results for blueberry orange cherry apricot apple with boost=true
yourResult = tester.search("blueberry orange cherry apricot apple", false, 10);
TestingTools.checkSearch(yourResult, "blueberry orange cherry apricot apple",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #294 checking search results for blueberry orange cherry apricot apple with boost=true");
//Test #295 checking search results for peach banana blueberry pear lime with boost=true
yourResult = tester.search("peach banana blueberry pear lime", false, 10);
TestingTools.checkSearch(yourResult, "peach banana blueberry pear lime",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #295 checking search results for peach banana blueberry pear lime with boost=true");
//Test #296 checking search results for lime apricot coconut pear with boost=true
yourResult = tester.search("lime apricot coconut pear", false, 10);
TestingTools.checkSearch(yourResult, "lime apricot coconut pear",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #296 checking search results for lime apricot coconut pear with boost=true");
//Test #297 checking search results for apple tomato peach with boost=true
yourResult = tester.search("apple tomato peach", false, 10);
TestingTools.checkSearch(yourResult, "apple tomato peach",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #297 checking search results for apple tomato peach with boost=true");
//Test #298 checking search results for pear with boost=true
yourResult = tester.search("pear", false, 10);
TestingTools.checkSearch(yourResult, "pear",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #298 checking search results for pear with boost=true");
//Test #299 checking search results for peach pear orange orange with boost=true
yourResult = tester.search("peach pear orange orange", false, 10);
TestingTools.checkSearch(yourResult, "peach pear orange orange",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #299 checking search results for peach pear orange orange with boost=true");
//Test #300 checking search results for lime with boost=true
yourResult = tester.search("lime", false, 10);
TestingTools.checkSearch(yourResult, "lime",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #300 checking search results for lime with boost=true");
//Test #301 checking search results for tomato lime peach blueberry with boost=true
yourResult = tester.search("tomato lime peach blueberry", false, 10);
TestingTools.checkSearch(yourResult, "tomato lime peach blueberry",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #301 checking search results for tomato lime peach blueberry with boost=true");
//Test #302 checking search results for apricot peach lime with boost=true
yourResult = tester.search("apricot peach lime", false, 10);
TestingTools.checkSearch(yourResult, "apricot peach lime",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #302 checking search results for apricot peach lime with boost=true");
//Test #303 checking search results for cherry lime peach with boost=true
yourResult = tester.search("cherry lime peach", false, 10);
TestingTools.checkSearch(yourResult, "cherry lime peach",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #303 checking search results for cherry lime peach with boost=true");
//Test #304 checking search results for peach kiwi peach apple with boost=true
yourResult = tester.search("peach kiwi peach apple", false, 10);
TestingTools.checkSearch(yourResult, "peach kiwi peach apple",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #304 checking search results for peach kiwi peach apple with boost=true");
//Test #305 checking search results for pear with boost=true
yourResult = tester.search("pear", false, 10);
TestingTools.checkSearch(yourResult, "pear",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #305 checking search results for pear with boost=true");
//Test #306 checking search results for coconut pear banana pear kiwi with boost=true
yourResult = tester.search("coconut pear banana pear kiwi", false, 10);
TestingTools.checkSearch(yourResult, "coconut pear banana pear kiwi",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #306 checking search results for coconut pear banana pear kiwi with boost=true");
//Test #307 checking search results for blueberry papaya banana fig pear with boost=true
yourResult = tester.search("blueberry papaya banana fig pear", false, 10);
TestingTools.checkSearch(yourResult, "blueberry papaya banana fig pear",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #307 checking search results for blueberry papaya banana fig pear with boost=true");
//Test #308 checking search results for tomato blueberry coconut kiwi with boost=true
yourResult = tester.search("tomato blueberry coconut kiwi", false, 10);
TestingTools.checkSearch(yourResult, "tomato blueberry coconut kiwi",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #308 checking search results for tomato blueberry coconut kiwi with boost=true");
//Test #309 checking search results for banana fig with boost=true
yourResult = tester.search("banana fig", false, 10);
TestingTools.checkSearch(yourResult, "banana fig",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #309 checking search results for banana fig with boost=true");
//Test #310 checking search results for papaya coconut cherry with boost=true
yourResult = tester.search("papaya coconut cherry", false, 10);
TestingTools.checkSearch(yourResult, "papaya coconut cherry",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #310 checking search results for papaya coconut cherry with boost=true");
//Test #311 checking search results for pear lime coconut apricot cherry with boost=true
yourResult = tester.search("pear lime coconut apricot cherry", false, 10);
TestingTools.checkSearch(yourResult, "pear lime coconut apricot cherry",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #311 checking search results for pear lime coconut apricot cherry with boost=true");
//Test #312 checking search results for fig cherry with boost=true
yourResult = tester.search("fig cherry", false, 10);
TestingTools.checkSearch(yourResult, "fig cherry",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #312 checking search results for fig cherry with boost=true");
//Test #313 checking search results for pear kiwi peach with boost=true
yourResult = tester.search("pear kiwi peach", false, 10);
TestingTools.checkSearch(yourResult, "pear kiwi peach",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #313 checking search results for pear kiwi peach with boost=true");
//Test #314 checking search results for papaya tomato blueberry papaya banana with boost=true
yourResult = tester.search("papaya tomato blueberry papaya banana", false, 10);
TestingTools.checkSearch(yourResult, "papaya tomato blueberry papaya banana",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #314 checking search results for papaya tomato blueberry papaya banana with boost=true");
//Test #315 checking search results for papaya orange with boost=true
yourResult = tester.search("papaya orange", false, 10);
TestingTools.checkSearch(yourResult, "papaya orange",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #315 checking search results for papaya orange with boost=true");
//Test #316 checking search results for fig cherry fig kiwi with boost=true
yourResult = tester.search("fig cherry fig kiwi", false, 10);
TestingTools.checkSearch(yourResult, "fig cherry fig kiwi",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #316 checking search results for fig cherry fig kiwi with boost=true");
//Test #317 checking search results for blueberry fig pear banana banana with boost=true
yourResult = tester.search("blueberry fig pear banana banana", false, 10);
TestingTools.checkSearch(yourResult, "blueberry fig pear banana banana",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #317 checking search results for blueberry fig pear banana banana with boost=true");
//Test #318 checking search results for banana apricot coconut with boost=true
yourResult = tester.search("banana apricot coconut", false, 10);
TestingTools.checkSearch(yourResult, "banana apricot coconut",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #318 checking search results for banana apricot coconut with boost=true");
//Test #319 checking search results for lime coconut apple banana with boost=true
yourResult = tester.search("lime coconut apple banana", false, 10);
TestingTools.checkSearch(yourResult, "lime coconut apple banana",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #319 checking search results for lime coconut apple banana with boost=true");
//Test #320 checking search results for apple peach apricot apricot kiwi with boost=true
yourResult = tester.search("apple peach apricot apricot kiwi", false, 10);
TestingTools.checkSearch(yourResult, "apple peach apricot apricot kiwi",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #320 checking search results for apple peach apricot apricot kiwi with boost=true");
//Test #321 checking search results for pear with boost=true
yourResult = tester.search("pear", false, 10);
TestingTools.checkSearch(yourResult, "pear",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #321 checking search results for pear with boost=true");
//Test #322 checking search results for peach kiwi papaya apricot orange with boost=true
yourResult = tester.search("peach kiwi papaya apricot orange", false, 10);
TestingTools.checkSearch(yourResult, "peach kiwi papaya apricot orange",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #322 checking search results for peach kiwi papaya apricot orange with boost=true");
//Test #323 checking search results for papaya orange papaya with boost=true
yourResult = tester.search("papaya orange papaya", false, 10);
TestingTools.checkSearch(yourResult, "papaya orange papaya",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #323 checking search results for papaya orange papaya with boost=true");
//Test #324 checking search results for apple coconut tomato with boost=true
yourResult = tester.search("apple coconut tomato", false, 10);
TestingTools.checkSearch(yourResult, "apple coconut tomato",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #324 checking search results for apple coconut tomato with boost=true");
//Test #325 checking search results for banana apricot blueberry fig tomato with boost=true
yourResult = tester.search("banana apricot blueberry fig tomato", false, 10);
TestingTools.checkSearch(yourResult, "banana apricot blueberry fig tomato",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #325 checking search results for banana apricot blueberry fig tomato with boost=true");
//Test #326 checking search results for coconut blueberry orange with boost=true
yourResult = tester.search("coconut blueberry orange", false, 10);
TestingTools.checkSearch(yourResult, "coconut blueberry orange",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #326 checking search results for coconut blueberry orange with boost=true");
//Test #327 checking search results for cherry with boost=true
yourResult = tester.search("cherry", false, 10);
TestingTools.checkSearch(yourResult, "cherry",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #327 checking search results for cherry with boost=true");
//Test #328 checking search results for orange tomato orange lime with boost=true
yourResult = tester.search("orange tomato orange lime", false, 10);
TestingTools.checkSearch(yourResult, "orange tomato orange lime",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #328 checking search results for orange tomato orange lime with boost=true");
//Test #329 checking search results for apricot peach blueberry kiwi apple with boost=true
yourResult = tester.search("apricot peach blueberry kiwi apple", false, 10);
TestingTools.checkSearch(yourResult, "apricot peach blueberry kiwi apple",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #329 checking search results for apricot peach blueberry kiwi apple with boost=true");
//Test #330 checking search results for fig banana pear orange cherry with boost=true
yourResult = tester.search("fig banana pear orange cherry", false, 10);
TestingTools.checkSearch(yourResult, "fig banana pear orange cherry",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #330 checking search results for fig banana pear orange cherry with boost=true");
//Test #331 checking search results for orange with boost=true
yourResult = tester.search("orange", false, 10);
TestingTools.checkSearch(yourResult, "orange",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #331 checking search results for orange with boost=true");
//Test #332 checking search results for lime papaya with boost=true
yourResult = tester.search("lime papaya", false, 10);
TestingTools.checkSearch(yourResult, "lime papaya",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #332 checking search results for lime papaya with boost=true");
//Test #333 checking search results for papaya apricot with boost=true
yourResult = tester.search("papaya apricot", false, 10);
TestingTools.checkSearch(yourResult, "papaya apricot",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #333 checking search results for papaya apricot with boost=true");
//Test #334 checking search results for pear lime kiwi cherry with boost=true
yourResult = tester.search("pear lime kiwi cherry", false, 10);
TestingTools.checkSearch(yourResult, "pear lime kiwi cherry",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #334 checking search results for pear lime kiwi cherry with boost=true");
//Test #335 checking search results for papaya peach peach banana apple with boost=true
yourResult = tester.search("papaya peach peach banana apple", false, 10);
TestingTools.checkSearch(yourResult, "papaya peach peach banana apple",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #335 checking search results for papaya peach peach banana apple with boost=true");
//Test #336 checking search results for apricot fig apricot lime with boost=true
yourResult = tester.search("apricot fig apricot lime", false, 10);
TestingTools.checkSearch(yourResult, "apricot fig apricot lime",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #336 checking search results for apricot fig apricot lime with boost=true");
//Test #337 checking search results for coconut fig cherry kiwi with boost=true
yourResult = tester.search("coconut fig cherry kiwi", false, 10);
TestingTools.checkSearch(yourResult, "coconut fig cherry kiwi",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #337 checking search results for coconut fig cherry kiwi with boost=true");
//Test #338 checking search results for peach apple blueberry papaya pear with boost=true
yourResult = tester.search("peach apple blueberry papaya pear", false, 10);
TestingTools.checkSearch(yourResult, "peach apple blueberry papaya pear",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #338 checking search results for peach apple blueberry papaya pear with boost=true");
//Test #339 checking search results for papaya kiwi orange papaya with boost=true
yourResult = tester.search("papaya kiwi orange papaya", false, 10);
TestingTools.checkSearch(yourResult, "papaya kiwi orange papaya",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #339 checking search results for papaya kiwi orange papaya with boost=true");
//Test #340 checking search results for kiwi tomato coconut with boost=true
yourResult = tester.search("kiwi tomato coconut", false, 10);
TestingTools.checkSearch(yourResult, "kiwi tomato coconut",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #340 checking search results for kiwi tomato coconut with boost=true");
//Test #341 checking search results for cherry banana with boost=true
yourResult = tester.search("cherry banana", false, 10);
TestingTools.checkSearch(yourResult, "cherry banana",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #341 checking search results for cherry banana with boost=true");
//Test #342 checking search results for banana blueberry with boost=true
yourResult = tester.search("banana blueberry", false, 10);
TestingTools.checkSearch(yourResult, "banana blueberry",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #342 checking search results for banana blueberry with boost=true");
//Test #343 checking search results for apple pear with boost=true
yourResult = tester.search("apple pear", false, 10);
TestingTools.checkSearch(yourResult, "apple pear",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #343 checking search results for apple pear with boost=true");
//Test #344 checking search results for fig peach cherry with boost=true
yourResult = tester.search("fig peach cherry", false, 10);
TestingTools.checkSearch(yourResult, "fig peach cherry",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #344 checking search results for fig peach cherry with boost=true");
//Test #345 checking search results for apple lime peach cherry with boost=true
yourResult = tester.search("apple lime peach cherry", false, 10);
TestingTools.checkSearch(yourResult, "apple lime peach cherry",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #345 checking search results for apple lime peach cherry with boost=true");
//Test #346 checking search results for tomato fig coconut coconut with boost=true
yourResult = tester.search("tomato fig coconut coconut", false, 10);
TestingTools.checkSearch(yourResult, "tomato fig coconut coconut",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #346 checking search results for tomato fig coconut coconut with boost=true");
//Test #347 checking search results for apple kiwi with boost=true
yourResult = tester.search("apple kiwi", false, 10);
TestingTools.checkSearch(yourResult, "apple kiwi",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #347 checking search results for apple kiwi with boost=true");
//Test #348 checking search results for apple with boost=true
yourResult = tester.search("apple", false, 10);
TestingTools.checkSearch(yourResult, "apple",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #348 checking search results for apple with boost=true");
//Test #349 checking search results for kiwi apple with boost=true
yourResult = tester.search("kiwi apple", false, 10);
TestingTools.checkSearch(yourResult, "kiwi apple",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #349 checking search results for kiwi apple with boost=true");
//Test #350 checking search results for fig orange blueberry blueberry kiwi with boost=true
yourResult = tester.search("fig orange blueberry blueberry kiwi", false, 10);
TestingTools.checkSearch(yourResult, "fig orange blueberry blueberry kiwi",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #350 checking search results for fig orange blueberry blueberry kiwi with boost=true");
//Test #351 checking search results for orange lime orange with boost=true
yourResult = tester.search("orange lime orange", false, 10);
TestingTools.checkSearch(yourResult, "orange lime orange",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #351 checking search results for orange lime orange with boost=true");
//Test #352 checking search results for apple papaya tomato orange with boost=true
yourResult = tester.search("apple papaya tomato orange", false, 10);
TestingTools.checkSearch(yourResult, "apple papaya tomato orange",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #352 checking search results for apple papaya tomato orange with boost=true");
//Test #353 checking search results for kiwi pear coconut apricot peach with boost=true
yourResult = tester.search("kiwi pear coconut apricot peach", false, 10);
TestingTools.checkSearch(yourResult, "kiwi pear coconut apricot peach",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #353 checking search results for kiwi pear coconut apricot peach with boost=true");
//Test #354 checking search results for coconut cherry apricot with boost=true
yourResult = tester.search("coconut cherry apricot", false, 10);
TestingTools.checkSearch(yourResult, "coconut cherry apricot",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #354 checking search results for coconut cherry apricot with boost=true");
//Test #355 checking search results for lime blueberry banana papaya with boost=true
yourResult = tester.search("lime blueberry banana papaya", false, 10);
TestingTools.checkSearch(yourResult, "lime blueberry banana papaya",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #355 checking search results for lime blueberry banana papaya with boost=true");
//Test #356 checking search results for pear with boost=true
yourResult = tester.search("pear", false, 10);
TestingTools.checkSearch(yourResult, "pear",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #356 checking search results for pear with boost=true");
//Test #357 checking search results for coconut tomato peach apple apple with boost=true
yourResult = tester.search("coconut tomato peach apple apple", false, 10);
TestingTools.checkSearch(yourResult, "coconut tomato peach apple apple",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #357 checking search results for coconut tomato peach apple apple with boost=true");
//Test #358 checking search results for pear papaya tomato with boost=true
yourResult = tester.search("pear papaya tomato", false, 10);
TestingTools.checkSearch(yourResult, "pear papaya tomato",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #358 checking search results for pear papaya tomato with boost=true");
//Test #359 checking search results for papaya kiwi orange with boost=true
yourResult = tester.search("papaya kiwi orange", false, 10);
TestingTools.checkSearch(yourResult, "papaya kiwi orange",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #359 checking search results for papaya kiwi orange with boost=true");
//Test #360 checking search results for apple cherry cherry kiwi with boost=true
yourResult = tester.search("apple cherry cherry kiwi", false, 10);
TestingTools.checkSearch(yourResult, "apple cherry cherry kiwi",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #360 checking search results for apple cherry cherry kiwi with boost=true");
//Test #361 checking search results for lime pear blueberry with boost=true
yourResult = tester.search("lime pear blueberry", false, 10);
TestingTools.checkSearch(yourResult, "lime pear blueberry",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #361 checking search results for lime pear blueberry with boost=true");
//Test #362 checking search results for orange kiwi with boost=true
yourResult = tester.search("orange kiwi", false, 10);
TestingTools.checkSearch(yourResult, "orange kiwi",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #362 checking search results for orange kiwi with boost=true");
//Test #363 checking search results for banana fig apricot with boost=true
yourResult = tester.search("banana fig apricot", false, 10);
TestingTools.checkSearch(yourResult, "banana fig apricot",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #363 checking search results for banana fig apricot with boost=true");
//Test #364 checking search results for apple orange lime banana with boost=true
yourResult = tester.search("apple orange lime banana", false, 10);
TestingTools.checkSearch(yourResult, "apple orange lime banana",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #364 checking search results for apple orange lime banana with boost=true");
//Test #365 checking search results for coconut orange peach papaya coconut with boost=true
yourResult = tester.search("coconut orange peach papaya coconut", false, 10);
TestingTools.checkSearch(yourResult, "coconut orange peach papaya coconut",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #365 checking search results for coconut orange peach papaya coconut with boost=true");
//Test #366 checking search results for apple with boost=true
yourResult = tester.search("apple", false, 10);
TestingTools.checkSearch(yourResult, "apple",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #366 checking search results for apple with boost=true");
//Test #367 checking search results for peach papaya papaya with boost=true
yourResult = tester.search("peach papaya papaya", false, 10);
TestingTools.checkSearch(yourResult, "peach papaya papaya",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #367 checking search results for peach papaya papaya with boost=true");
//Test #368 checking search results for blueberry with boost=true
yourResult = tester.search("blueberry", false, 10);
TestingTools.checkSearch(yourResult, "blueberry",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #368 checking search results for blueberry with boost=true");
//Test #369 checking search results for cherry orange fig banana papaya with boost=true
yourResult = tester.search("cherry orange fig banana papaya", false, 10);
TestingTools.checkSearch(yourResult, "cherry orange fig banana papaya",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #369 checking search results for cherry orange fig banana papaya with boost=true");
//Test #370 checking search results for papaya apricot fig kiwi banana with boost=true
yourResult = tester.search("papaya apricot fig kiwi banana", false, 10);
TestingTools.checkSearch(yourResult, "papaya apricot fig kiwi banana",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #370 checking search results for papaya apricot fig kiwi banana with boost=true");
//Test #371 checking search results for kiwi cherry with boost=true
yourResult = tester.search("kiwi cherry", false, 10);
TestingTools.checkSearch(yourResult, "kiwi cherry",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #371 checking search results for kiwi cherry with boost=true");
//Test #372 checking search results for cherry cherry blueberry with boost=true
yourResult = tester.search("cherry cherry blueberry", false, 10);
TestingTools.checkSearch(yourResult, "cherry cherry blueberry",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #372 checking search results for cherry cherry blueberry with boost=true");
//Test #373 checking search results for apple peach kiwi papaya with boost=true
yourResult = tester.search("apple peach kiwi papaya", false, 10);
TestingTools.checkSearch(yourResult, "apple peach kiwi papaya",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #373 checking search results for apple peach kiwi papaya with boost=true");
//Test #374 checking search results for orange apple apricot blueberry with boost=true
yourResult = tester.search("orange apple apricot blueberry", false, 10);
TestingTools.checkSearch(yourResult, "orange apple apricot blueberry",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #374 checking search results for orange apple apricot blueberry with boost=true");
//Test #375 checking search results for lime blueberry orange peach with boost=true
yourResult = tester.search("lime blueberry orange peach", false, 10);
TestingTools.checkSearch(yourResult, "lime blueberry orange peach",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #375 checking search results for lime blueberry orange peach with boost=true");
//Test #376 checking search results for lime cherry with boost=true
yourResult = tester.search("lime cherry", false, 10);
TestingTools.checkSearch(yourResult, "lime cherry",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #376 checking search results for lime cherry with boost=true");
//Test #377 checking search results for kiwi cherry blueberry cherry with boost=true
yourResult = tester.search("kiwi cherry blueberry cherry", false, 10);
TestingTools.checkSearch(yourResult, "kiwi cherry blueberry cherry",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #377 checking search results for kiwi cherry blueberry cherry with boost=true");
//Test #378 checking search results for cherry lime tomato apple with boost=true
yourResult = tester.search("cherry lime tomato apple", false, 10);
TestingTools.checkSearch(yourResult, "cherry lime tomato apple",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #378 checking search results for cherry lime tomato apple with boost=true");
//Test #379 checking search results for apricot apple kiwi peach with boost=true
yourResult = tester.search("apricot apple kiwi peach", false, 10);
TestingTools.checkSearch(yourResult, "apricot apple kiwi peach",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #379 checking search results for apricot apple kiwi peach with boost=true");
//Test #380 checking search results for fig papaya with boost=true
yourResult = tester.search("fig papaya", false, 10);
TestingTools.checkSearch(yourResult, "fig papaya",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #380 checking search results for fig papaya with boost=true");
//Test #381 checking search results for pear tomato with boost=true
yourResult = tester.search("pear tomato", false, 10);
TestingTools.checkSearch(yourResult, "pear tomato",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #381 checking search results for pear tomato with boost=true");
//Test #382 checking search results for orange cherry with boost=true
yourResult = tester.search("orange cherry", false, 10);
TestingTools.checkSearch(yourResult, "orange cherry",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #382 checking search results for orange cherry with boost=true");
//Test #383 checking search results for fig peach apricot tomato peach with boost=true
yourResult = tester.search("fig peach apricot tomato peach", false, 10);
TestingTools.checkSearch(yourResult, "fig peach apricot tomato peach",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #383 checking search results for fig peach apricot tomato peach with boost=true");
//Test #384 checking search results for fig with boost=true
yourResult = tester.search("fig", false, 10);
TestingTools.checkSearch(yourResult, "fig",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #384 checking search results for fig with boost=true");
//Test #385 checking search results for papaya fig coconut orange tomato with boost=true
yourResult = tester.search("papaya fig coconut orange tomato", false, 10);
TestingTools.checkSearch(yourResult, "papaya fig coconut orange tomato",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #385 checking search results for papaya fig coconut orange tomato with boost=true");
//Test #386 checking search results for banana banana peach with boost=true
yourResult = tester.search("banana banana peach", false, 10);
TestingTools.checkSearch(yourResult, "banana banana peach",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #386 checking search results for banana banana peach with boost=true");
//Test #387 checking search results for tomato peach kiwi fig apple with boost=true
yourResult = tester.search("tomato peach kiwi fig apple", false, 10);
TestingTools.checkSearch(yourResult, "tomato peach kiwi fig apple",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #387 checking search results for tomato peach kiwi fig apple with boost=true");
//Test #388 checking search results for lime kiwi fig apple lime with boost=true
yourResult = tester.search("lime kiwi fig apple lime", false, 10);
TestingTools.checkSearch(yourResult, "lime kiwi fig apple lime",false, passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #388 checking search results for lime kiwi fig apple lime with boost=true");
failOut.close();
passOut.close();
}
}
