import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.*;
public class TinyFruitsSearchBoostTester {public static void main(String[] args) throws Exception{
ProjectTester tester = new ProjectTesterImp(); //Instantiate your own ProjectTester instance here
tester.initialize();
tester.crawl("https://people.scs.carleton.ca/~avamckenney/tinyfruits/N-0.html");
runTest(tester);}public static void runTest(ProjectTester tester) throws Exception{
PrintWriter failOut = new PrintWriter(new FileWriter("TinyFruits-SearchBoost-failed.txt"));
PrintWriter passOut = new PrintWriter(new FileWriter("TinyFruits-SearchBoost-passed.txt"));
List<SearchResult> yourResult; 
//Test #389 checking search results for pear pear apple with boost=true
yourResult = tester.search("pear pear apple", true, 10);
TestingTools.checkSearch(yourResult, "pear pear apple",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #389 checking search results for pear pear apple with boost=true");
//Test #390 checking search results for apricot papaya peach with boost=true
yourResult = tester.search("apricot papaya peach", true, 10);
TestingTools.checkSearch(yourResult, "apricot papaya peach",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #390 checking search results for apricot papaya peach with boost=true");
//Test #391 checking search results for fig fig with boost=true
yourResult = tester.search("fig fig", true, 10);
TestingTools.checkSearch(yourResult, "fig fig",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #391 checking search results for fig fig with boost=true");
//Test #392 checking search results for kiwi coconut apple with boost=true
yourResult = tester.search("kiwi coconut apple", true, 10);
TestingTools.checkSearch(yourResult, "kiwi coconut apple",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #392 checking search results for kiwi coconut apple with boost=true");
//Test #393 checking search results for kiwi cherry fig coconut with boost=true
yourResult = tester.search("kiwi cherry fig coconut", true, 10);
TestingTools.checkSearch(yourResult, "kiwi cherry fig coconut",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #393 checking search results for kiwi cherry fig coconut with boost=true");
//Test #394 checking search results for lime blueberry papaya with boost=true
yourResult = tester.search("lime blueberry papaya", true, 10);
TestingTools.checkSearch(yourResult, "lime blueberry papaya",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #394 checking search results for lime blueberry papaya with boost=true");
//Test #395 checking search results for cherry banana kiwi with boost=true
yourResult = tester.search("cherry banana kiwi", true, 10);
TestingTools.checkSearch(yourResult, "cherry banana kiwi",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #395 checking search results for cherry banana kiwi with boost=true");
//Test #396 checking search results for papaya kiwi banana coconut cherry with boost=true
yourResult = tester.search("papaya kiwi banana coconut cherry", true, 10);
TestingTools.checkSearch(yourResult, "papaya kiwi banana coconut cherry",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #396 checking search results for papaya kiwi banana coconut cherry with boost=true");
//Test #397 checking search results for pear apple with boost=true
yourResult = tester.search("pear apple", true, 10);
TestingTools.checkSearch(yourResult, "pear apple",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #397 checking search results for pear apple with boost=true");
//Test #398 checking search results for fig papaya pear apple pear with boost=true
yourResult = tester.search("fig papaya pear apple pear", true, 10);
TestingTools.checkSearch(yourResult, "fig papaya pear apple pear",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #398 checking search results for fig papaya pear apple pear with boost=true");
//Test #399 checking search results for kiwi with boost=true
yourResult = tester.search("kiwi", true, 10);
TestingTools.checkSearch(yourResult, "kiwi",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #399 checking search results for kiwi with boost=true");
//Test #400 checking search results for papaya peach papaya with boost=true
yourResult = tester.search("papaya peach papaya", true, 10);
TestingTools.checkSearch(yourResult, "papaya peach papaya",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #400 checking search results for papaya peach papaya with boost=true");
//Test #401 checking search results for blueberry pear kiwi with boost=true
yourResult = tester.search("blueberry pear kiwi", true, 10);
TestingTools.checkSearch(yourResult, "blueberry pear kiwi",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #401 checking search results for blueberry pear kiwi with boost=true");
//Test #402 checking search results for papaya cherry with boost=true
yourResult = tester.search("papaya cherry", true, 10);
TestingTools.checkSearch(yourResult, "papaya cherry",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #402 checking search results for papaya cherry with boost=true");
//Test #403 checking search results for banana kiwi lime peach with boost=true
yourResult = tester.search("banana kiwi lime peach", true, 10);
TestingTools.checkSearch(yourResult, "banana kiwi lime peach",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #403 checking search results for banana kiwi lime peach with boost=true");
//Test #404 checking search results for cherry apple lime kiwi apple with boost=true
yourResult = tester.search("cherry apple lime kiwi apple", true, 10);
TestingTools.checkSearch(yourResult, "cherry apple lime kiwi apple",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #404 checking search results for cherry apple lime kiwi apple with boost=true");
//Test #405 checking search results for apple orange with boost=true
yourResult = tester.search("apple orange", true, 10);
TestingTools.checkSearch(yourResult, "apple orange",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #405 checking search results for apple orange with boost=true");
//Test #406 checking search results for peach papaya cherry apple coconut with boost=true
yourResult = tester.search("peach papaya cherry apple coconut", true, 10);
TestingTools.checkSearch(yourResult, "peach papaya cherry apple coconut",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #406 checking search results for peach papaya cherry apple coconut with boost=true");
//Test #407 checking search results for apricot fig apple apple with boost=true
yourResult = tester.search("apricot fig apple apple", true, 10);
TestingTools.checkSearch(yourResult, "apricot fig apple apple",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #407 checking search results for apricot fig apple apple with boost=true");
//Test #408 checking search results for banana pear peach with boost=true
yourResult = tester.search("banana pear peach", true, 10);
TestingTools.checkSearch(yourResult, "banana pear peach",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #408 checking search results for banana pear peach with boost=true");
//Test #409 checking search results for papaya blueberry orange fig cherry with boost=true
yourResult = tester.search("papaya blueberry orange fig cherry", true, 10);
TestingTools.checkSearch(yourResult, "papaya blueberry orange fig cherry",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #409 checking search results for papaya blueberry orange fig cherry with boost=true");
//Test #410 checking search results for fig apple pear blueberry with boost=true
yourResult = tester.search("fig apple pear blueberry", true, 10);
TestingTools.checkSearch(yourResult, "fig apple pear blueberry",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #410 checking search results for fig apple pear blueberry with boost=true");
//Test #411 checking search results for peach peach apple coconut with boost=true
yourResult = tester.search("peach peach apple coconut", true, 10);
TestingTools.checkSearch(yourResult, "peach peach apple coconut",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #411 checking search results for peach peach apple coconut with boost=true");
//Test #412 checking search results for banana blueberry orange apple with boost=true
yourResult = tester.search("banana blueberry orange apple", true, 10);
TestingTools.checkSearch(yourResult, "banana blueberry orange apple",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #412 checking search results for banana blueberry orange apple with boost=true");
//Test #413 checking search results for coconut pear kiwi kiwi with boost=true
yourResult = tester.search("coconut pear kiwi kiwi", true, 10);
TestingTools.checkSearch(yourResult, "coconut pear kiwi kiwi",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #413 checking search results for coconut pear kiwi kiwi with boost=true");
//Test #414 checking search results for apricot banana peach apple with boost=true
yourResult = tester.search("apricot banana peach apple", true, 10);
TestingTools.checkSearch(yourResult, "apricot banana peach apple",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #414 checking search results for apricot banana peach apple with boost=true");
//Test #415 checking search results for papaya with boost=true
yourResult = tester.search("papaya", true, 10);
TestingTools.checkSearch(yourResult, "papaya",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #415 checking search results for papaya with boost=true");
//Test #416 checking search results for papaya lime blueberry coconut with boost=true
yourResult = tester.search("papaya lime blueberry coconut", true, 10);
TestingTools.checkSearch(yourResult, "papaya lime blueberry coconut",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #416 checking search results for papaya lime blueberry coconut with boost=true");
//Test #417 checking search results for apple orange apricot orange pear with boost=true
yourResult = tester.search("apple orange apricot orange pear", true, 10);
TestingTools.checkSearch(yourResult, "apple orange apricot orange pear",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #417 checking search results for apple orange apricot orange pear with boost=true");
//Test #418 checking search results for coconut banana with boost=true
yourResult = tester.search("coconut banana", true, 10);
TestingTools.checkSearch(yourResult, "coconut banana",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #418 checking search results for coconut banana with boost=true");
//Test #419 checking search results for orange cherry orange with boost=true
yourResult = tester.search("orange cherry orange", true, 10);
TestingTools.checkSearch(yourResult, "orange cherry orange",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #419 checking search results for orange cherry orange with boost=true");
//Test #420 checking search results for fig lime fig orange coconut with boost=true
yourResult = tester.search("fig lime fig orange coconut", true, 10);
TestingTools.checkSearch(yourResult, "fig lime fig orange coconut",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #420 checking search results for fig lime fig orange coconut with boost=true");
//Test #421 checking search results for banana peach apple lime banana with boost=true
yourResult = tester.search("banana peach apple lime banana", true, 10);
TestingTools.checkSearch(yourResult, "banana peach apple lime banana",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #421 checking search results for banana peach apple lime banana with boost=true");
//Test #422 checking search results for orange coconut with boost=true
yourResult = tester.search("orange coconut", true, 10);
TestingTools.checkSearch(yourResult, "orange coconut",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #422 checking search results for orange coconut with boost=true");
//Test #423 checking search results for blueberry blueberry fig with boost=true
yourResult = tester.search("blueberry blueberry fig", true, 10);
TestingTools.checkSearch(yourResult, "blueberry blueberry fig",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #423 checking search results for blueberry blueberry fig with boost=true");
//Test #424 checking search results for pear fig with boost=true
yourResult = tester.search("pear fig", true, 10);
TestingTools.checkSearch(yourResult, "pear fig",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #424 checking search results for pear fig with boost=true");
//Test #425 checking search results for pear papaya apricot kiwi with boost=true
yourResult = tester.search("pear papaya apricot kiwi", true, 10);
TestingTools.checkSearch(yourResult, "pear papaya apricot kiwi",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #425 checking search results for pear papaya apricot kiwi with boost=true");
//Test #426 checking search results for blueberry papaya coconut with boost=true
yourResult = tester.search("blueberry papaya coconut", true, 10);
TestingTools.checkSearch(yourResult, "blueberry papaya coconut",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #426 checking search results for blueberry papaya coconut with boost=true");
//Test #427 checking search results for apricot coconut blueberry papaya fig with boost=true
yourResult = tester.search("apricot coconut blueberry papaya fig", true, 10);
TestingTools.checkSearch(yourResult, "apricot coconut blueberry papaya fig",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #427 checking search results for apricot coconut blueberry papaya fig with boost=true");
//Test #428 checking search results for orange orange with boost=true
yourResult = tester.search("orange orange", true, 10);
TestingTools.checkSearch(yourResult, "orange orange",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #428 checking search results for orange orange with boost=true");
//Test #429 checking search results for coconut apricot peach with boost=true
yourResult = tester.search("coconut apricot peach", true, 10);
TestingTools.checkSearch(yourResult, "coconut apricot peach",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #429 checking search results for coconut apricot peach with boost=true");
//Test #430 checking search results for lime apple lime orange coconut with boost=true
yourResult = tester.search("lime apple lime orange coconut", true, 10);
TestingTools.checkSearch(yourResult, "lime apple lime orange coconut",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #430 checking search results for lime apple lime orange coconut with boost=true");
//Test #431 checking search results for lime orange with boost=true
yourResult = tester.search("lime orange", true, 10);
TestingTools.checkSearch(yourResult, "lime orange",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #431 checking search results for lime orange with boost=true");
//Test #432 checking search results for papaya with boost=true
yourResult = tester.search("papaya", true, 10);
TestingTools.checkSearch(yourResult, "papaya",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #432 checking search results for papaya with boost=true");
//Test #433 checking search results for lime fig coconut with boost=true
yourResult = tester.search("lime fig coconut", true, 10);
TestingTools.checkSearch(yourResult, "lime fig coconut",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #433 checking search results for lime fig coconut with boost=true");
//Test #434 checking search results for cherry coconut blueberry with boost=true
yourResult = tester.search("cherry coconut blueberry", true, 10);
TestingTools.checkSearch(yourResult, "cherry coconut blueberry",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #434 checking search results for cherry coconut blueberry with boost=true");
//Test #435 checking search results for pear tomato with boost=true
yourResult = tester.search("pear tomato", true, 10);
TestingTools.checkSearch(yourResult, "pear tomato",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #435 checking search results for pear tomato with boost=true");
//Test #436 checking search results for papaya with boost=true
yourResult = tester.search("papaya", true, 10);
TestingTools.checkSearch(yourResult, "papaya",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #436 checking search results for papaya with boost=true");
//Test #437 checking search results for fig papaya apricot kiwi fig with boost=true
yourResult = tester.search("fig papaya apricot kiwi fig", true, 10);
TestingTools.checkSearch(yourResult, "fig papaya apricot kiwi fig",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #437 checking search results for fig papaya apricot kiwi fig with boost=true");
//Test #438 checking search results for pear with boost=true
yourResult = tester.search("pear", true, 10);
TestingTools.checkSearch(yourResult, "pear",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #438 checking search results for pear with boost=true");
//Test #439 checking search results for kiwi orange apricot fig papaya with boost=true
yourResult = tester.search("kiwi orange apricot fig papaya", true, 10);
TestingTools.checkSearch(yourResult, "kiwi orange apricot fig papaya",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #439 checking search results for kiwi orange apricot fig papaya with boost=true");
//Test #440 checking search results for banana kiwi with boost=true
yourResult = tester.search("banana kiwi", true, 10);
TestingTools.checkSearch(yourResult, "banana kiwi",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #440 checking search results for banana kiwi with boost=true");
//Test #441 checking search results for apple orange blueberry fig blueberry with boost=true
yourResult = tester.search("apple orange blueberry fig blueberry", true, 10);
TestingTools.checkSearch(yourResult, "apple orange blueberry fig blueberry",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #441 checking search results for apple orange blueberry fig blueberry with boost=true");
//Test #442 checking search results for fig with boost=true
yourResult = tester.search("fig", true, 10);
TestingTools.checkSearch(yourResult, "fig",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #442 checking search results for fig with boost=true");
//Test #443 checking search results for tomato tomato coconut pear blueberry with boost=true
yourResult = tester.search("tomato tomato coconut pear blueberry", true, 10);
TestingTools.checkSearch(yourResult, "tomato tomato coconut pear blueberry",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #443 checking search results for tomato tomato coconut pear blueberry with boost=true");
//Test #444 checking search results for apple pear papaya with boost=true
yourResult = tester.search("apple pear papaya", true, 10);
TestingTools.checkSearch(yourResult, "apple pear papaya",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #444 checking search results for apple pear papaya with boost=true");
//Test #445 checking search results for kiwi peach fig apple papaya with boost=true
yourResult = tester.search("kiwi peach fig apple papaya", true, 10);
TestingTools.checkSearch(yourResult, "kiwi peach fig apple papaya",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #445 checking search results for kiwi peach fig apple papaya with boost=true");
//Test #446 checking search results for tomato lime tomato cherry with boost=true
yourResult = tester.search("tomato lime tomato cherry", true, 10);
TestingTools.checkSearch(yourResult, "tomato lime tomato cherry",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #446 checking search results for tomato lime tomato cherry with boost=true");
//Test #447 checking search results for lime papaya tomato apple blueberry with boost=true
yourResult = tester.search("lime papaya tomato apple blueberry", true, 10);
TestingTools.checkSearch(yourResult, "lime papaya tomato apple blueberry",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #447 checking search results for lime papaya tomato apple blueberry with boost=true");
//Test #448 checking search results for blueberry peach apricot papaya kiwi with boost=true
yourResult = tester.search("blueberry peach apricot papaya kiwi", true, 10);
TestingTools.checkSearch(yourResult, "blueberry peach apricot papaya kiwi",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #448 checking search results for blueberry peach apricot papaya kiwi with boost=true");
//Test #449 checking search results for orange kiwi blueberry fig with boost=true
yourResult = tester.search("orange kiwi blueberry fig", true, 10);
TestingTools.checkSearch(yourResult, "orange kiwi blueberry fig",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #449 checking search results for orange kiwi blueberry fig with boost=true");
//Test #450 checking search results for fig orange kiwi with boost=true
yourResult = tester.search("fig orange kiwi", true, 10);
TestingTools.checkSearch(yourResult, "fig orange kiwi",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #450 checking search results for fig orange kiwi with boost=true");
//Test #451 checking search results for orange apple tomato peach with boost=true
yourResult = tester.search("orange apple tomato peach", true, 10);
TestingTools.checkSearch(yourResult, "orange apple tomato peach",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #451 checking search results for orange apple tomato peach with boost=true");
//Test #452 checking search results for coconut cherry apricot pear blueberry with boost=true
yourResult = tester.search("coconut cherry apricot pear blueberry", true, 10);
TestingTools.checkSearch(yourResult, "coconut cherry apricot pear blueberry",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #452 checking search results for coconut cherry apricot pear blueberry with boost=true");
//Test #453 checking search results for kiwi pear kiwi peach with boost=true
yourResult = tester.search("kiwi pear kiwi peach", true, 10);
TestingTools.checkSearch(yourResult, "kiwi pear kiwi peach",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #453 checking search results for kiwi pear kiwi peach with boost=true");
//Test #454 checking search results for cherry orange with boost=true
yourResult = tester.search("cherry orange", true, 10);
TestingTools.checkSearch(yourResult, "cherry orange",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #454 checking search results for cherry orange with boost=true");
//Test #455 checking search results for coconut peach with boost=true
yourResult = tester.search("coconut peach", true, 10);
TestingTools.checkSearch(yourResult, "coconut peach",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #455 checking search results for coconut peach with boost=true");
//Test #456 checking search results for coconut kiwi fig with boost=true
yourResult = tester.search("coconut kiwi fig", true, 10);
TestingTools.checkSearch(yourResult, "coconut kiwi fig",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #456 checking search results for coconut kiwi fig with boost=true");
//Test #457 checking search results for pear fig cherry with boost=true
yourResult = tester.search("pear fig cherry", true, 10);
TestingTools.checkSearch(yourResult, "pear fig cherry",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #457 checking search results for pear fig cherry with boost=true");
//Test #458 checking search results for blueberry apple with boost=true
yourResult = tester.search("blueberry apple", true, 10);
TestingTools.checkSearch(yourResult, "blueberry apple",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #458 checking search results for blueberry apple with boost=true");
//Test #459 checking search results for apricot peach lime with boost=true
yourResult = tester.search("apricot peach lime", true, 10);
TestingTools.checkSearch(yourResult, "apricot peach lime",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #459 checking search results for apricot peach lime with boost=true");
//Test #460 checking search results for cherry with boost=true
yourResult = tester.search("cherry", true, 10);
TestingTools.checkSearch(yourResult, "cherry",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #460 checking search results for cherry with boost=true");
//Test #461 checking search results for peach with boost=true
yourResult = tester.search("peach", true, 10);
TestingTools.checkSearch(yourResult, "peach",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #461 checking search results for peach with boost=true");
//Test #462 checking search results for lime lime coconut with boost=true
yourResult = tester.search("lime lime coconut", true, 10);
TestingTools.checkSearch(yourResult, "lime lime coconut",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #462 checking search results for lime lime coconut with boost=true");
//Test #463 checking search results for blueberry blueberry orange peach with boost=true
yourResult = tester.search("blueberry blueberry orange peach", true, 10);
TestingTools.checkSearch(yourResult, "blueberry blueberry orange peach",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #463 checking search results for blueberry blueberry orange peach with boost=true");
//Test #464 checking search results for coconut with boost=true
yourResult = tester.search("coconut", true, 10);
TestingTools.checkSearch(yourResult, "coconut",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #464 checking search results for coconut with boost=true");
//Test #465 checking search results for banana pear with boost=true
yourResult = tester.search("banana pear", true, 10);
TestingTools.checkSearch(yourResult, "banana pear",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #465 checking search results for banana pear with boost=true");
//Test #466 checking search results for blueberry apple with boost=true
yourResult = tester.search("blueberry apple", true, 10);
TestingTools.checkSearch(yourResult, "blueberry apple",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #466 checking search results for blueberry apple with boost=true");
//Test #467 checking search results for apricot peach orange with boost=true
yourResult = tester.search("apricot peach orange", true, 10);
TestingTools.checkSearch(yourResult, "apricot peach orange",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #467 checking search results for apricot peach orange with boost=true");
//Test #468 checking search results for blueberry apricot blueberry with boost=true
yourResult = tester.search("blueberry apricot blueberry", true, 10);
TestingTools.checkSearch(yourResult, "blueberry apricot blueberry",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #468 checking search results for blueberry apricot blueberry with boost=true");
//Test #469 checking search results for fig apricot with boost=true
yourResult = tester.search("fig apricot", true, 10);
TestingTools.checkSearch(yourResult, "fig apricot",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #469 checking search results for fig apricot with boost=true");
//Test #470 checking search results for coconut pear with boost=true
yourResult = tester.search("coconut pear", true, 10);
TestingTools.checkSearch(yourResult, "coconut pear",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #470 checking search results for coconut pear with boost=true");
//Test #471 checking search results for blueberry blueberry tomato banana papaya with boost=true
yourResult = tester.search("blueberry blueberry tomato banana papaya", true, 10);
TestingTools.checkSearch(yourResult, "blueberry blueberry tomato banana papaya",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #471 checking search results for blueberry blueberry tomato banana papaya with boost=true");
//Test #472 checking search results for papaya with boost=true
yourResult = tester.search("papaya", true, 10);
TestingTools.checkSearch(yourResult, "papaya",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #472 checking search results for papaya with boost=true");
//Test #473 checking search results for cherry with boost=true
yourResult = tester.search("cherry", true, 10);
TestingTools.checkSearch(yourResult, "cherry",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #473 checking search results for cherry with boost=true");
//Test #474 checking search results for fig banana cherry with boost=true
yourResult = tester.search("fig banana cherry", true, 10);
TestingTools.checkSearch(yourResult, "fig banana cherry",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #474 checking search results for fig banana cherry with boost=true");
//Test #475 checking search results for lime pear with boost=true
yourResult = tester.search("lime pear", true, 10);
TestingTools.checkSearch(yourResult, "lime pear",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #475 checking search results for lime pear with boost=true");
//Test #476 checking search results for fig orange apricot with boost=true
yourResult = tester.search("fig orange apricot", true, 10);
TestingTools.checkSearch(yourResult, "fig orange apricot",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #476 checking search results for fig orange apricot with boost=true");
//Test #477 checking search results for blueberry peach peach papaya papaya with boost=true
yourResult = tester.search("blueberry peach peach papaya papaya", true, 10);
TestingTools.checkSearch(yourResult, "blueberry peach peach papaya papaya",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #477 checking search results for blueberry peach peach papaya papaya with boost=true");
//Test #478 checking search results for papaya orange with boost=true
yourResult = tester.search("papaya orange", true, 10);
TestingTools.checkSearch(yourResult, "papaya orange",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #478 checking search results for papaya orange with boost=true");
//Test #479 checking search results for pear cherry cherry papaya orange with boost=true
yourResult = tester.search("pear cherry cherry papaya orange", true, 10);
TestingTools.checkSearch(yourResult, "pear cherry cherry papaya orange",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #479 checking search results for pear cherry cherry papaya orange with boost=true");
//Test #480 checking search results for apricot fig blueberry papaya with boost=true
yourResult = tester.search("apricot fig blueberry papaya", true, 10);
TestingTools.checkSearch(yourResult, "apricot fig blueberry papaya",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #480 checking search results for apricot fig blueberry papaya with boost=true");
//Test #481 checking search results for kiwi tomato cherry coconut banana with boost=true
yourResult = tester.search("kiwi tomato cherry coconut banana", true, 10);
TestingTools.checkSearch(yourResult, "kiwi tomato cherry coconut banana",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #481 checking search results for kiwi tomato cherry coconut banana with boost=true");
//Test #482 checking search results for coconut tomato pear pear fig with boost=true
yourResult = tester.search("coconut tomato pear pear fig", true, 10);
TestingTools.checkSearch(yourResult, "coconut tomato pear pear fig",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #482 checking search results for coconut tomato pear pear fig with boost=true");
//Test #483 checking search results for lime tomato pear apple kiwi with boost=true
yourResult = tester.search("lime tomato pear apple kiwi", true, 10);
TestingTools.checkSearch(yourResult, "lime tomato pear apple kiwi",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #483 checking search results for lime tomato pear apple kiwi with boost=true");
//Test #484 checking search results for banana fig blueberry kiwi lime with boost=true
yourResult = tester.search("banana fig blueberry kiwi lime", true, 10);
TestingTools.checkSearch(yourResult, "banana fig blueberry kiwi lime",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #484 checking search results for banana fig blueberry kiwi lime with boost=true");
//Test #485 checking search results for apple papaya papaya orange with boost=true
yourResult = tester.search("apple papaya papaya orange", true, 10);
TestingTools.checkSearch(yourResult, "apple papaya papaya orange",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #485 checking search results for apple papaya papaya orange with boost=true");
//Test #486 checking search results for peach tomato blueberry blueberry lime with boost=true
yourResult = tester.search("peach tomato blueberry blueberry lime", true, 10);
TestingTools.checkSearch(yourResult, "peach tomato blueberry blueberry lime",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #486 checking search results for peach tomato blueberry blueberry lime with boost=true");
//Test #487 checking search results for orange coconut peach with boost=true
yourResult = tester.search("orange coconut peach", true, 10);
TestingTools.checkSearch(yourResult, "orange coconut peach",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #487 checking search results for orange coconut peach with boost=true");
//Test #488 checking search results for papaya fig peach with boost=true
yourResult = tester.search("papaya fig peach", true, 10);
TestingTools.checkSearch(yourResult, "papaya fig peach",true, passOut, failOut, "TinyFruitsSearchBoostTester", "Test #488 checking search results for papaya fig peach with boost=true");
failOut.close();
passOut.close();
}
}
