import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.*;
public class FruitsASearchNoBoostTester {public static void main(String[] args) throws Exception{
ProjectTester tester = new ProjectTesterImp(); //Instantiate your own ProjectTester instance here
tester.initialize();
tester.crawl("https://people.scs.carleton.ca/~avamckenney/fruitsA/N-0.html");
runTest(tester);}public static void runTest(ProjectTester tester) throws Exception{
PrintWriter failOut = new PrintWriter(new FileWriter("FruitsA-SearchNoBoost-failed.txt"));
PrintWriter passOut = new PrintWriter(new FileWriter("FruitsA-SearchNoBoost-passed.txt"));
List<SearchResult> yourResult; 
//Test #459 checking search results for kiwi with boost=false
yourResult = tester.search("kiwi", false, 100);
TestingTools.checkSearch(yourResult, "kiwi", passOut, failOut, "FruitsASearchNoBoostTester", "Test #459 checking search results for kiwi with boost=false");
//Test #460 checking search results for fig banana with boost=false
yourResult = tester.search("fig banana", false, 100);
TestingTools.checkSearch(yourResult, "fig banana", passOut, failOut, "FruitsASearchNoBoostTester", "Test #460 checking search results for fig banana with boost=false");
//Test #461 checking search results for papaya strawberry fig with boost=false
yourResult = tester.search("papaya strawberry fig", false, 100);
TestingTools.checkSearch(yourResult, "papaya strawberry fig", passOut, failOut, "FruitsASearchNoBoostTester", "Test #461 checking search results for papaya strawberry fig with boost=false");
//Test #462 checking search results for fig with boost=false
yourResult = tester.search("fig", false, 100);
TestingTools.checkSearch(yourResult, "fig", passOut, failOut, "FruitsASearchNoBoostTester", "Test #462 checking search results for fig with boost=false");
//Test #463 checking search results for blueberry pear with boost=false
yourResult = tester.search("blueberry pear", false, 100);
TestingTools.checkSearch(yourResult, "blueberry pear", passOut, failOut, "FruitsASearchNoBoostTester", "Test #463 checking search results for blueberry pear with boost=false");
//Test #464 checking search results for peach papaya cherry with boost=false
yourResult = tester.search("peach papaya cherry", false, 100);
TestingTools.checkSearch(yourResult, "peach papaya cherry", passOut, failOut, "FruitsASearchNoBoostTester", "Test #464 checking search results for peach papaya cherry with boost=false");
//Test #465 checking search results for papaya papaya apricot with boost=false
yourResult = tester.search("papaya papaya apricot", false, 100);
TestingTools.checkSearch(yourResult, "papaya papaya apricot", passOut, failOut, "FruitsASearchNoBoostTester", "Test #465 checking search results for papaya papaya apricot with boost=false");
//Test #466 checking search results for fig banana with boost=false
yourResult = tester.search("fig banana", false, 100);
TestingTools.checkSearch(yourResult, "fig banana", passOut, failOut, "FruitsASearchNoBoostTester", "Test #466 checking search results for fig banana with boost=false");
//Test #467 checking search results for cherry peach pear blueberry apple with boost=false
yourResult = tester.search("cherry peach pear blueberry apple", false, 100);
TestingTools.checkSearch(yourResult, "cherry peach pear blueberry apple", passOut, failOut, "FruitsASearchNoBoostTester", "Test #467 checking search results for cherry peach pear blueberry apple with boost=false");
//Test #468 checking search results for coconut kiwi with boost=false
yourResult = tester.search("coconut kiwi", false, 100);
TestingTools.checkSearch(yourResult, "coconut kiwi", passOut, failOut, "FruitsASearchNoBoostTester", "Test #468 checking search results for coconut kiwi with boost=false");
//Test #469 checking search results for kiwi with boost=false
yourResult = tester.search("kiwi", false, 100);
TestingTools.checkSearch(yourResult, "kiwi", passOut, failOut, "FruitsASearchNoBoostTester", "Test #469 checking search results for kiwi with boost=false");
//Test #470 checking search results for tomato banana peach with boost=false
yourResult = tester.search("tomato banana peach", false, 100);
TestingTools.checkSearch(yourResult, "tomato banana peach", passOut, failOut, "FruitsASearchNoBoostTester", "Test #470 checking search results for tomato banana peach with boost=false");
//Test #471 checking search results for peach with boost=false
yourResult = tester.search("peach", false, 100);
TestingTools.checkSearch(yourResult, "peach", passOut, failOut, "FruitsASearchNoBoostTester", "Test #471 checking search results for peach with boost=false");
//Test #472 checking search results for blueberry strawberry with boost=false
yourResult = tester.search("blueberry strawberry", false, 100);
TestingTools.checkSearch(yourResult, "blueberry strawberry", passOut, failOut, "FruitsASearchNoBoostTester", "Test #472 checking search results for blueberry strawberry with boost=false");
//Test #473 checking search results for peach with boost=false
yourResult = tester.search("peach", false, 100);
TestingTools.checkSearch(yourResult, "peach", passOut, failOut, "FruitsASearchNoBoostTester", "Test #473 checking search results for peach with boost=false");
//Test #474 checking search results for papaya apricot blueberry papaya with boost=false
yourResult = tester.search("papaya apricot blueberry papaya", false, 100);
TestingTools.checkSearch(yourResult, "papaya apricot blueberry papaya", passOut, failOut, "FruitsASearchNoBoostTester", "Test #474 checking search results for papaya apricot blueberry papaya with boost=false");
//Test #475 checking search results for pear banana pear coconut with boost=false
yourResult = tester.search("pear banana pear coconut", false, 100);
TestingTools.checkSearch(yourResult, "pear banana pear coconut", passOut, failOut, "FruitsASearchNoBoostTester", "Test #475 checking search results for pear banana pear coconut with boost=false");
//Test #476 checking search results for papaya papaya lime papaya strawberry with boost=false
yourResult = tester.search("papaya papaya lime papaya strawberry", false, 100);
TestingTools.checkSearch(yourResult, "papaya papaya lime papaya strawberry", passOut, failOut, "FruitsASearchNoBoostTester", "Test #476 checking search results for papaya papaya lime papaya strawberry with boost=false");
//Test #477 checking search results for peach papaya lime with boost=false
yourResult = tester.search("peach papaya lime", false, 100);
TestingTools.checkSearch(yourResult, "peach papaya lime", passOut, failOut, "FruitsASearchNoBoostTester", "Test #477 checking search results for peach papaya lime with boost=false");
//Test #478 checking search results for pear with boost=false
yourResult = tester.search("pear", false, 100);
TestingTools.checkSearch(yourResult, "pear", passOut, failOut, "FruitsASearchNoBoostTester", "Test #478 checking search results for pear with boost=false");
//Test #479 checking search results for banana lime blueberry cherry with boost=false
yourResult = tester.search("banana lime blueberry cherry", false, 100);
TestingTools.checkSearch(yourResult, "banana lime blueberry cherry", passOut, failOut, "FruitsASearchNoBoostTester", "Test #479 checking search results for banana lime blueberry cherry with boost=false");
//Test #480 checking search results for coconut apricot apricot with boost=false
yourResult = tester.search("coconut apricot apricot", false, 100);
TestingTools.checkSearch(yourResult, "coconut apricot apricot", passOut, failOut, "FruitsASearchNoBoostTester", "Test #480 checking search results for coconut apricot apricot with boost=false");
//Test #481 checking search results for banana with boost=false
yourResult = tester.search("banana", false, 100);
TestingTools.checkSearch(yourResult, "banana", passOut, failOut, "FruitsASearchNoBoostTester", "Test #481 checking search results for banana with boost=false");
//Test #482 checking search results for peach cherry cherry blueberry banana with boost=false
yourResult = tester.search("peach cherry cherry blueberry banana", false, 100);
TestingTools.checkSearch(yourResult, "peach cherry cherry blueberry banana", passOut, failOut, "FruitsASearchNoBoostTester", "Test #482 checking search results for peach cherry cherry blueberry banana with boost=false");
//Test #483 checking search results for papaya blueberry cherry tomato with boost=false
yourResult = tester.search("papaya blueberry cherry tomato", false, 100);
TestingTools.checkSearch(yourResult, "papaya blueberry cherry tomato", passOut, failOut, "FruitsASearchNoBoostTester", "Test #483 checking search results for papaya blueberry cherry tomato with boost=false");
//Test #484 checking search results for strawberry apricot kiwi pear with boost=false
yourResult = tester.search("strawberry apricot kiwi pear", false, 100);
TestingTools.checkSearch(yourResult, "strawberry apricot kiwi pear", passOut, failOut, "FruitsASearchNoBoostTester", "Test #484 checking search results for strawberry apricot kiwi pear with boost=false");
//Test #485 checking search results for banana strawberry with boost=false
yourResult = tester.search("banana strawberry", false, 100);
TestingTools.checkSearch(yourResult, "banana strawberry", passOut, failOut, "FruitsASearchNoBoostTester", "Test #485 checking search results for banana strawberry with boost=false");
//Test #486 checking search results for pear peach strawberry apple with boost=false
yourResult = tester.search("pear peach strawberry apple", false, 100);
TestingTools.checkSearch(yourResult, "pear peach strawberry apple", passOut, failOut, "FruitsASearchNoBoostTester", "Test #486 checking search results for pear peach strawberry apple with boost=false");
//Test #487 checking search results for fig peach with boost=false
yourResult = tester.search("fig peach", false, 100);
TestingTools.checkSearch(yourResult, "fig peach", passOut, failOut, "FruitsASearchNoBoostTester", "Test #487 checking search results for fig peach with boost=false");
//Test #488 checking search results for papaya fig tomato coconut with boost=false
yourResult = tester.search("papaya fig tomato coconut", false, 100);
TestingTools.checkSearch(yourResult, "papaya fig tomato coconut", passOut, failOut, "FruitsASearchNoBoostTester", "Test #488 checking search results for papaya fig tomato coconut with boost=false");
//Test #489 checking search results for strawberry with boost=false
yourResult = tester.search("strawberry", false, 100);
TestingTools.checkSearch(yourResult, "strawberry", passOut, failOut, "FruitsASearchNoBoostTester", "Test #489 checking search results for strawberry with boost=false");
//Test #490 checking search results for papaya with boost=false
yourResult = tester.search("papaya", false, 100);
TestingTools.checkSearch(yourResult, "papaya", passOut, failOut, "FruitsASearchNoBoostTester", "Test #490 checking search results for papaya with boost=false");
//Test #491 checking search results for apple lime tomato with boost=false
yourResult = tester.search("apple lime tomato", false, 100);
TestingTools.checkSearch(yourResult, "apple lime tomato", passOut, failOut, "FruitsASearchNoBoostTester", "Test #491 checking search results for apple lime tomato with boost=false");
//Test #492 checking search results for blueberry apricot papaya peach with boost=false
yourResult = tester.search("blueberry apricot papaya peach", false, 100);
TestingTools.checkSearch(yourResult, "blueberry apricot papaya peach", passOut, failOut, "FruitsASearchNoBoostTester", "Test #492 checking search results for blueberry apricot papaya peach with boost=false");
//Test #493 checking search results for pear strawberry pear lime kiwi with boost=false
yourResult = tester.search("pear strawberry pear lime kiwi", false, 100);
TestingTools.checkSearch(yourResult, "pear strawberry pear lime kiwi", passOut, failOut, "FruitsASearchNoBoostTester", "Test #493 checking search results for pear strawberry pear lime kiwi with boost=false");
//Test #494 checking search results for lime kiwi with boost=false
yourResult = tester.search("lime kiwi", false, 100);
TestingTools.checkSearch(yourResult, "lime kiwi", passOut, failOut, "FruitsASearchNoBoostTester", "Test #494 checking search results for lime kiwi with boost=false");
//Test #495 checking search results for apricot banana peach tomato papaya with boost=false
yourResult = tester.search("apricot banana peach tomato papaya", false, 100);
TestingTools.checkSearch(yourResult, "apricot banana peach tomato papaya", passOut, failOut, "FruitsASearchNoBoostTester", "Test #495 checking search results for apricot banana peach tomato papaya with boost=false");
//Test #496 checking search results for apple peach apricot papaya with boost=false
yourResult = tester.search("apple peach apricot papaya", false, 100);
TestingTools.checkSearch(yourResult, "apple peach apricot papaya", passOut, failOut, "FruitsASearchNoBoostTester", "Test #496 checking search results for apple peach apricot papaya with boost=false");
//Test #497 checking search results for lime with boost=false
yourResult = tester.search("lime", false, 100);
TestingTools.checkSearch(yourResult, "lime", passOut, failOut, "FruitsASearchNoBoostTester", "Test #497 checking search results for lime with boost=false");
//Test #498 checking search results for apple with boost=false
yourResult = tester.search("apple", false, 100);
TestingTools.checkSearch(yourResult, "apple", passOut, failOut, "FruitsASearchNoBoostTester", "Test #498 checking search results for apple with boost=false");
//Test #499 checking search results for pear with boost=false
yourResult = tester.search("pear", false, 100);
TestingTools.checkSearch(yourResult, "pear", passOut, failOut, "FruitsASearchNoBoostTester", "Test #499 checking search results for pear with boost=false");
//Test #500 checking search results for blueberry strawberry blueberry kiwi with boost=false
yourResult = tester.search("blueberry strawberry blueberry kiwi", false, 100);
TestingTools.checkSearch(yourResult, "blueberry strawberry blueberry kiwi", passOut, failOut, "FruitsASearchNoBoostTester", "Test #500 checking search results for blueberry strawberry blueberry kiwi with boost=false");
//Test #501 checking search results for kiwi apple strawberry papaya with boost=false
yourResult = tester.search("kiwi apple strawberry papaya", false, 100);
TestingTools.checkSearch(yourResult, "kiwi apple strawberry papaya", passOut, failOut, "FruitsASearchNoBoostTester", "Test #501 checking search results for kiwi apple strawberry papaya with boost=false");
//Test #502 checking search results for coconut apple with boost=false
yourResult = tester.search("coconut apple", false, 100);
TestingTools.checkSearch(yourResult, "coconut apple", passOut, failOut, "FruitsASearchNoBoostTester", "Test #502 checking search results for coconut apple with boost=false");
//Test #503 checking search results for banana fig with boost=false
yourResult = tester.search("banana fig", false, 100);
TestingTools.checkSearch(yourResult, "banana fig", passOut, failOut, "FruitsASearchNoBoostTester", "Test #503 checking search results for banana fig with boost=false");
//Test #504 checking search results for strawberry blueberry fig apricot coconut with boost=false
yourResult = tester.search("strawberry blueberry fig apricot coconut", false, 100);
TestingTools.checkSearch(yourResult, "strawberry blueberry fig apricot coconut", passOut, failOut, "FruitsASearchNoBoostTester", "Test #504 checking search results for strawberry blueberry fig apricot coconut with boost=false");
//Test #505 checking search results for coconut fig with boost=false
yourResult = tester.search("coconut fig", false, 100);
TestingTools.checkSearch(yourResult, "coconut fig", passOut, failOut, "FruitsASearchNoBoostTester", "Test #505 checking search results for coconut fig with boost=false");
//Test #506 checking search results for banana papaya papaya with boost=false
yourResult = tester.search("banana papaya papaya", false, 100);
TestingTools.checkSearch(yourResult, "banana papaya papaya", passOut, failOut, "FruitsASearchNoBoostTester", "Test #506 checking search results for banana papaya papaya with boost=false");
//Test #507 checking search results for blueberry with boost=false
yourResult = tester.search("blueberry", false, 100);
TestingTools.checkSearch(yourResult, "blueberry", passOut, failOut, "FruitsASearchNoBoostTester", "Test #507 checking search results for blueberry with boost=false");
//Test #508 checking search results for cherry apple kiwi with boost=false
yourResult = tester.search("cherry apple kiwi", false, 100);
TestingTools.checkSearch(yourResult, "cherry apple kiwi", passOut, failOut, "FruitsASearchNoBoostTester", "Test #508 checking search results for cherry apple kiwi with boost=false");
//Test #509 checking search results for kiwi tomato blueberry peach cherry with boost=false
yourResult = tester.search("kiwi tomato blueberry peach cherry", false, 100);
TestingTools.checkSearch(yourResult, "kiwi tomato blueberry peach cherry", passOut, failOut, "FruitsASearchNoBoostTester", "Test #509 checking search results for kiwi tomato blueberry peach cherry with boost=false");
//Test #510 checking search results for blueberry with boost=false
yourResult = tester.search("blueberry", false, 100);
TestingTools.checkSearch(yourResult, "blueberry", passOut, failOut, "FruitsASearchNoBoostTester", "Test #510 checking search results for blueberry with boost=false");
//Test #511 checking search results for pear lime blueberry with boost=false
yourResult = tester.search("pear lime blueberry", false, 100);
TestingTools.checkSearch(yourResult, "pear lime blueberry", passOut, failOut, "FruitsASearchNoBoostTester", "Test #511 checking search results for pear lime blueberry with boost=false");
//Test #512 checking search results for blueberry with boost=false
yourResult = tester.search("blueberry", false, 100);
TestingTools.checkSearch(yourResult, "blueberry", passOut, failOut, "FruitsASearchNoBoostTester", "Test #512 checking search results for blueberry with boost=false");
//Test #513 checking search results for pear cherry with boost=false
yourResult = tester.search("pear cherry", false, 100);
TestingTools.checkSearch(yourResult, "pear cherry", passOut, failOut, "FruitsASearchNoBoostTester", "Test #513 checking search results for pear cherry with boost=false");
//Test #514 checking search results for papaya with boost=false
yourResult = tester.search("papaya", false, 100);
TestingTools.checkSearch(yourResult, "papaya", passOut, failOut, "FruitsASearchNoBoostTester", "Test #514 checking search results for papaya with boost=false");
//Test #515 checking search results for kiwi kiwi with boost=false
yourResult = tester.search("kiwi kiwi", false, 100);
TestingTools.checkSearch(yourResult, "kiwi kiwi", passOut, failOut, "FruitsASearchNoBoostTester", "Test #515 checking search results for kiwi kiwi with boost=false");
//Test #516 checking search results for cherry tomato kiwi apricot papaya with boost=false
yourResult = tester.search("cherry tomato kiwi apricot papaya", false, 100);
TestingTools.checkSearch(yourResult, "cherry tomato kiwi apricot papaya", passOut, failOut, "FruitsASearchNoBoostTester", "Test #516 checking search results for cherry tomato kiwi apricot papaya with boost=false");
//Test #517 checking search results for lime apricot banana with boost=false
yourResult = tester.search("lime apricot banana", false, 100);
TestingTools.checkSearch(yourResult, "lime apricot banana", passOut, failOut, "FruitsASearchNoBoostTester", "Test #517 checking search results for lime apricot banana with boost=false");
//Test #518 checking search results for apple with boost=false
yourResult = tester.search("apple", false, 100);
TestingTools.checkSearch(yourResult, "apple", passOut, failOut, "FruitsASearchNoBoostTester", "Test #518 checking search results for apple with boost=false");
//Test #519 checking search results for pear with boost=false
yourResult = tester.search("pear", false, 100);
TestingTools.checkSearch(yourResult, "pear", passOut, failOut, "FruitsASearchNoBoostTester", "Test #519 checking search results for pear with boost=false");
//Test #520 checking search results for peach strawberry fig with boost=false
yourResult = tester.search("peach strawberry fig", false, 100);
TestingTools.checkSearch(yourResult, "peach strawberry fig", passOut, failOut, "FruitsASearchNoBoostTester", "Test #520 checking search results for peach strawberry fig with boost=false");
//Test #521 checking search results for papaya kiwi apple tomato with boost=false
yourResult = tester.search("papaya kiwi apple tomato", false, 100);
TestingTools.checkSearch(yourResult, "papaya kiwi apple tomato", passOut, failOut, "FruitsASearchNoBoostTester", "Test #521 checking search results for papaya kiwi apple tomato with boost=false");
//Test #522 checking search results for banana peach with boost=false
yourResult = tester.search("banana peach", false, 100);
TestingTools.checkSearch(yourResult, "banana peach", passOut, failOut, "FruitsASearchNoBoostTester", "Test #522 checking search results for banana peach with boost=false");
//Test #523 checking search results for peach banana lime strawberry coconut with boost=false
yourResult = tester.search("peach banana lime strawberry coconut", false, 100);
TestingTools.checkSearch(yourResult, "peach banana lime strawberry coconut", passOut, failOut, "FruitsASearchNoBoostTester", "Test #523 checking search results for peach banana lime strawberry coconut with boost=false");
//Test #524 checking search results for apricot cherry blueberry strawberry kiwi with boost=false
yourResult = tester.search("apricot cherry blueberry strawberry kiwi", false, 100);
TestingTools.checkSearch(yourResult, "apricot cherry blueberry strawberry kiwi", passOut, failOut, "FruitsASearchNoBoostTester", "Test #524 checking search results for apricot cherry blueberry strawberry kiwi with boost=false");
//Test #525 checking search results for fig fig apple with boost=false
yourResult = tester.search("fig fig apple", false, 100);
TestingTools.checkSearch(yourResult, "fig fig apple", passOut, failOut, "FruitsASearchNoBoostTester", "Test #525 checking search results for fig fig apple with boost=false");
//Test #526 checking search results for banana apple lime with boost=false
yourResult = tester.search("banana apple lime", false, 100);
TestingTools.checkSearch(yourResult, "banana apple lime", passOut, failOut, "FruitsASearchNoBoostTester", "Test #526 checking search results for banana apple lime with boost=false");
//Test #527 checking search results for fig apple banana cherry peach with boost=false
yourResult = tester.search("fig apple banana cherry peach", false, 100);
TestingTools.checkSearch(yourResult, "fig apple banana cherry peach", passOut, failOut, "FruitsASearchNoBoostTester", "Test #527 checking search results for fig apple banana cherry peach with boost=false");
//Test #528 checking search results for peach tomato apple cherry apricot with boost=false
yourResult = tester.search("peach tomato apple cherry apricot", false, 100);
TestingTools.checkSearch(yourResult, "peach tomato apple cherry apricot", passOut, failOut, "FruitsASearchNoBoostTester", "Test #528 checking search results for peach tomato apple cherry apricot with boost=false");
//Test #529 checking search results for coconut fig with boost=false
yourResult = tester.search("coconut fig", false, 100);
TestingTools.checkSearch(yourResult, "coconut fig", passOut, failOut, "FruitsASearchNoBoostTester", "Test #529 checking search results for coconut fig with boost=false");
//Test #530 checking search results for cherry kiwi coconut apricot coconut with boost=false
yourResult = tester.search("cherry kiwi coconut apricot coconut", false, 100);
TestingTools.checkSearch(yourResult, "cherry kiwi coconut apricot coconut", passOut, failOut, "FruitsASearchNoBoostTester", "Test #530 checking search results for cherry kiwi coconut apricot coconut with boost=false");
//Test #531 checking search results for apple with boost=false
yourResult = tester.search("apple", false, 100);
TestingTools.checkSearch(yourResult, "apple", passOut, failOut, "FruitsASearchNoBoostTester", "Test #531 checking search results for apple with boost=false");
//Test #532 checking search results for coconut fig banana apricot with boost=false
yourResult = tester.search("coconut fig banana apricot", false, 100);
TestingTools.checkSearch(yourResult, "coconut fig banana apricot", passOut, failOut, "FruitsASearchNoBoostTester", "Test #532 checking search results for coconut fig banana apricot with boost=false");
//Test #533 checking search results for blueberry apple lime strawberry coconut with boost=false
yourResult = tester.search("blueberry apple lime strawberry coconut", false, 100);
TestingTools.checkSearch(yourResult, "blueberry apple lime strawberry coconut", passOut, failOut, "FruitsASearchNoBoostTester", "Test #533 checking search results for blueberry apple lime strawberry coconut with boost=false");
//Test #534 checking search results for kiwi pear strawberry with boost=false
yourResult = tester.search("kiwi pear strawberry", false, 100);
TestingTools.checkSearch(yourResult, "kiwi pear strawberry", passOut, failOut, "FruitsASearchNoBoostTester", "Test #534 checking search results for kiwi pear strawberry with boost=false");
//Test #535 checking search results for banana peach cherry coconut apple with boost=false
yourResult = tester.search("banana peach cherry coconut apple", false, 100);
TestingTools.checkSearch(yourResult, "banana peach cherry coconut apple", passOut, failOut, "FruitsASearchNoBoostTester", "Test #535 checking search results for banana peach cherry coconut apple with boost=false");
//Test #536 checking search results for blueberry peach fig tomato kiwi with boost=false
yourResult = tester.search("blueberry peach fig tomato kiwi", false, 100);
TestingTools.checkSearch(yourResult, "blueberry peach fig tomato kiwi", passOut, failOut, "FruitsASearchNoBoostTester", "Test #536 checking search results for blueberry peach fig tomato kiwi with boost=false");
//Test #537 checking search results for apricot pear pear with boost=false
yourResult = tester.search("apricot pear pear", false, 100);
TestingTools.checkSearch(yourResult, "apricot pear pear", passOut, failOut, "FruitsASearchNoBoostTester", "Test #537 checking search results for apricot pear pear with boost=false");
//Test #538 checking search results for peach tomato coconut cherry with boost=false
yourResult = tester.search("peach tomato coconut cherry", false, 100);
TestingTools.checkSearch(yourResult, "peach tomato coconut cherry", passOut, failOut, "FruitsASearchNoBoostTester", "Test #538 checking search results for peach tomato coconut cherry with boost=false");
//Test #539 checking search results for lime with boost=false
yourResult = tester.search("lime", false, 100);
TestingTools.checkSearch(yourResult, "lime", passOut, failOut, "FruitsASearchNoBoostTester", "Test #539 checking search results for lime with boost=false");
//Test #540 checking search results for apple strawberry apricot with boost=false
yourResult = tester.search("apple strawberry apricot", false, 100);
TestingTools.checkSearch(yourResult, "apple strawberry apricot", passOut, failOut, "FruitsASearchNoBoostTester", "Test #540 checking search results for apple strawberry apricot with boost=false");
//Test #541 checking search results for strawberry pear with boost=false
yourResult = tester.search("strawberry pear", false, 100);
TestingTools.checkSearch(yourResult, "strawberry pear", passOut, failOut, "FruitsASearchNoBoostTester", "Test #541 checking search results for strawberry pear with boost=false");
//Test #542 checking search results for apple strawberry coconut banana with boost=false
yourResult = tester.search("apple strawberry coconut banana", false, 100);
TestingTools.checkSearch(yourResult, "apple strawberry coconut banana", passOut, failOut, "FruitsASearchNoBoostTester", "Test #542 checking search results for apple strawberry coconut banana with boost=false");
//Test #543 checking search results for strawberry peach papaya with boost=false
yourResult = tester.search("strawberry peach papaya", false, 100);
TestingTools.checkSearch(yourResult, "strawberry peach papaya", passOut, failOut, "FruitsASearchNoBoostTester", "Test #543 checking search results for strawberry peach papaya with boost=false");
//Test #544 checking search results for lime lime with boost=false
yourResult = tester.search("lime lime", false, 100);
TestingTools.checkSearch(yourResult, "lime lime", passOut, failOut, "FruitsASearchNoBoostTester", "Test #544 checking search results for lime lime with boost=false");
//Test #545 checking search results for apricot strawberry pear pear with boost=false
yourResult = tester.search("apricot strawberry pear pear", false, 100);
TestingTools.checkSearch(yourResult, "apricot strawberry pear pear", passOut, failOut, "FruitsASearchNoBoostTester", "Test #545 checking search results for apricot strawberry pear pear with boost=false");
//Test #546 checking search results for kiwi papaya lime papaya with boost=false
yourResult = tester.search("kiwi papaya lime papaya", false, 100);
TestingTools.checkSearch(yourResult, "kiwi papaya lime papaya", passOut, failOut, "FruitsASearchNoBoostTester", "Test #546 checking search results for kiwi papaya lime papaya with boost=false");
//Test #547 checking search results for lime papaya with boost=false
yourResult = tester.search("lime papaya", false, 100);
TestingTools.checkSearch(yourResult, "lime papaya", passOut, failOut, "FruitsASearchNoBoostTester", "Test #547 checking search results for lime papaya with boost=false");
//Test #548 checking search results for strawberry fig apricot blueberry with boost=false
yourResult = tester.search("strawberry fig apricot blueberry", false, 100);
TestingTools.checkSearch(yourResult, "strawberry fig apricot blueberry", passOut, failOut, "FruitsASearchNoBoostTester", "Test #548 checking search results for strawberry fig apricot blueberry with boost=false");
//Test #549 checking search results for apple pear apricot with boost=false
yourResult = tester.search("apple pear apricot", false, 100);
TestingTools.checkSearch(yourResult, "apple pear apricot", passOut, failOut, "FruitsASearchNoBoostTester", "Test #549 checking search results for apple pear apricot with boost=false");
//Test #550 checking search results for cherry papaya kiwi apple papaya with boost=false
yourResult = tester.search("cherry papaya kiwi apple papaya", false, 100);
TestingTools.checkSearch(yourResult, "cherry papaya kiwi apple papaya", passOut, failOut, "FruitsASearchNoBoostTester", "Test #550 checking search results for cherry papaya kiwi apple papaya with boost=false");
//Test #551 checking search results for kiwi with boost=false
yourResult = tester.search("kiwi", false, 100);
TestingTools.checkSearch(yourResult, "kiwi", passOut, failOut, "FruitsASearchNoBoostTester", "Test #551 checking search results for kiwi with boost=false");
//Test #552 checking search results for kiwi pear banana peach apple with boost=false
yourResult = tester.search("kiwi pear banana peach apple", false, 100);
TestingTools.checkSearch(yourResult, "kiwi pear banana peach apple", passOut, failOut, "FruitsASearchNoBoostTester", "Test #552 checking search results for kiwi pear banana peach apple with boost=false");
//Test #553 checking search results for blueberry strawberry with boost=false
yourResult = tester.search("blueberry strawberry", false, 100);
TestingTools.checkSearch(yourResult, "blueberry strawberry", passOut, failOut, "FruitsASearchNoBoostTester", "Test #553 checking search results for blueberry strawberry with boost=false");
//Test #554 checking search results for coconut lime kiwi with boost=false
yourResult = tester.search("coconut lime kiwi", false, 100);
TestingTools.checkSearch(yourResult, "coconut lime kiwi", passOut, failOut, "FruitsASearchNoBoostTester", "Test #554 checking search results for coconut lime kiwi with boost=false");
//Test #555 checking search results for apple cherry with boost=false
yourResult = tester.search("apple cherry", false, 100);
TestingTools.checkSearch(yourResult, "apple cherry", passOut, failOut, "FruitsASearchNoBoostTester", "Test #555 checking search results for apple cherry with boost=false");
//Test #556 checking search results for blueberry with boost=false
yourResult = tester.search("blueberry", false, 100);
TestingTools.checkSearch(yourResult, "blueberry", passOut, failOut, "FruitsASearchNoBoostTester", "Test #556 checking search results for blueberry with boost=false");
//Test #557 checking search results for peach tomato coconut banana with boost=false
yourResult = tester.search("peach tomato coconut banana", false, 100);
TestingTools.checkSearch(yourResult, "peach tomato coconut banana", passOut, failOut, "FruitsASearchNoBoostTester", "Test #557 checking search results for peach tomato coconut banana with boost=false");
//Test #558 checking search results for banana pear with boost=false
yourResult = tester.search("banana pear", false, 100);
TestingTools.checkSearch(yourResult, "banana pear", passOut, failOut, "FruitsASearchNoBoostTester", "Test #558 checking search results for banana pear with boost=false");
failOut.close();
passOut.close();
}
}
