import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.*;
public class Fruits100SearchNoBoostTester {public static void main(String[] args) throws Exception{
ProjectTester tester = new ProjectTesterImp(); //Instantiate your own ProjectTester instance here
tester.initialize();
tester.crawl("https://people.scs.carleton.ca/~avamckenney/fruits100/N-0.html");
runTest(tester);}public static void runTest(ProjectTester tester) throws Exception{
PrintWriter failOut = new PrintWriter(new FileWriter("Fruits100-SearchNoBoost-failed.txt"));
PrintWriter passOut = new PrintWriter(new FileWriter("Fruits100-SearchNoBoost-passed.txt"));
List<SearchResult> yourResult; 
//Test #459 checking search results for strawberry pear with boost=false
yourResult = tester.search("strawberry pear", false, 100);
TestingTools.checkSearch(yourResult, "strawberry pear", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #459 checking search results for strawberry pear with boost=false");
//Test #460 checking search results for blueberry coconut apple with boost=false
yourResult = tester.search("blueberry coconut apple", false, 100);
TestingTools.checkSearch(yourResult, "blueberry coconut apple", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #460 checking search results for blueberry coconut apple with boost=false");
//Test #461 checking search results for pear blueberry fig kiwi with boost=false
yourResult = tester.search("pear blueberry fig kiwi", false, 100);
TestingTools.checkSearch(yourResult, "pear blueberry fig kiwi", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #461 checking search results for pear blueberry fig kiwi with boost=false");
//Test #462 checking search results for strawberry with boost=false
yourResult = tester.search("strawberry", false, 100);
TestingTools.checkSearch(yourResult, "strawberry", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #462 checking search results for strawberry with boost=false");
//Test #463 checking search results for strawberry strawberry with boost=false
yourResult = tester.search("strawberry strawberry", false, 100);
TestingTools.checkSearch(yourResult, "strawberry strawberry", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #463 checking search results for strawberry strawberry with boost=false");
//Test #464 checking search results for kiwi with boost=false
yourResult = tester.search("kiwi", false, 100);
TestingTools.checkSearch(yourResult, "kiwi", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #464 checking search results for kiwi with boost=false");
//Test #465 checking search results for papaya pear with boost=false
yourResult = tester.search("papaya pear", false, 100);
TestingTools.checkSearch(yourResult, "papaya pear", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #465 checking search results for papaya pear with boost=false");
//Test #466 checking search results for strawberry apricot coconut with boost=false
yourResult = tester.search("strawberry apricot coconut", false, 100);
TestingTools.checkSearch(yourResult, "strawberry apricot coconut", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #466 checking search results for strawberry apricot coconut with boost=false");
//Test #467 checking search results for apricot coconut apricot with boost=false
yourResult = tester.search("apricot coconut apricot", false, 100);
TestingTools.checkSearch(yourResult, "apricot coconut apricot", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #467 checking search results for apricot coconut apricot with boost=false");
//Test #468 checking search results for apricot banana tomato with boost=false
yourResult = tester.search("apricot banana tomato", false, 100);
TestingTools.checkSearch(yourResult, "apricot banana tomato", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #468 checking search results for apricot banana tomato with boost=false");
//Test #469 checking search results for coconut cherry apricot with boost=false
yourResult = tester.search("coconut cherry apricot", false, 100);
TestingTools.checkSearch(yourResult, "coconut cherry apricot", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #469 checking search results for coconut cherry apricot with boost=false");
//Test #470 checking search results for strawberry papaya strawberry banana with boost=false
yourResult = tester.search("strawberry papaya strawberry banana", false, 100);
TestingTools.checkSearch(yourResult, "strawberry papaya strawberry banana", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #470 checking search results for strawberry papaya strawberry banana with boost=false");
//Test #471 checking search results for peach fig with boost=false
yourResult = tester.search("peach fig", false, 100);
TestingTools.checkSearch(yourResult, "peach fig", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #471 checking search results for peach fig with boost=false");
//Test #472 checking search results for blueberry kiwi coconut with boost=false
yourResult = tester.search("blueberry kiwi coconut", false, 100);
TestingTools.checkSearch(yourResult, "blueberry kiwi coconut", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #472 checking search results for blueberry kiwi coconut with boost=false");
//Test #473 checking search results for peach lime banana with boost=false
yourResult = tester.search("peach lime banana", false, 100);
TestingTools.checkSearch(yourResult, "peach lime banana", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #473 checking search results for peach lime banana with boost=false");
//Test #474 checking search results for pear fig kiwi pear blueberry with boost=false
yourResult = tester.search("pear fig kiwi pear blueberry", false, 100);
TestingTools.checkSearch(yourResult, "pear fig kiwi pear blueberry", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #474 checking search results for pear fig kiwi pear blueberry with boost=false");
//Test #475 checking search results for tomato coconut lime with boost=false
yourResult = tester.search("tomato coconut lime", false, 100);
TestingTools.checkSearch(yourResult, "tomato coconut lime", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #475 checking search results for tomato coconut lime with boost=false");
//Test #476 checking search results for kiwi peach with boost=false
yourResult = tester.search("kiwi peach", false, 100);
TestingTools.checkSearch(yourResult, "kiwi peach", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #476 checking search results for kiwi peach with boost=false");
//Test #477 checking search results for strawberry banana cherry blueberry with boost=false
yourResult = tester.search("strawberry banana cherry blueberry", false, 100);
TestingTools.checkSearch(yourResult, "strawberry banana cherry blueberry", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #477 checking search results for strawberry banana cherry blueberry with boost=false");
//Test #478 checking search results for papaya banana banana cherry fig with boost=false
yourResult = tester.search("papaya banana banana cherry fig", false, 100);
TestingTools.checkSearch(yourResult, "papaya banana banana cherry fig", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #478 checking search results for papaya banana banana cherry fig with boost=false");
//Test #479 checking search results for kiwi cherry peach cherry with boost=false
yourResult = tester.search("kiwi cherry peach cherry", false, 100);
TestingTools.checkSearch(yourResult, "kiwi cherry peach cherry", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #479 checking search results for kiwi cherry peach cherry with boost=false");
//Test #480 checking search results for lime with boost=false
yourResult = tester.search("lime", false, 100);
TestingTools.checkSearch(yourResult, "lime", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #480 checking search results for lime with boost=false");
//Test #481 checking search results for fig with boost=false
yourResult = tester.search("fig", false, 100);
TestingTools.checkSearch(yourResult, "fig", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #481 checking search results for fig with boost=false");
//Test #482 checking search results for pear with boost=false
yourResult = tester.search("pear", false, 100);
TestingTools.checkSearch(yourResult, "pear", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #482 checking search results for pear with boost=false");
//Test #483 checking search results for coconut fig strawberry coconut with boost=false
yourResult = tester.search("coconut fig strawberry coconut", false, 100);
TestingTools.checkSearch(yourResult, "coconut fig strawberry coconut", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #483 checking search results for coconut fig strawberry coconut with boost=false");
//Test #484 checking search results for lime with boost=false
yourResult = tester.search("lime", false, 100);
TestingTools.checkSearch(yourResult, "lime", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #484 checking search results for lime with boost=false");
//Test #485 checking search results for apple with boost=false
yourResult = tester.search("apple", false, 100);
TestingTools.checkSearch(yourResult, "apple", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #485 checking search results for apple with boost=false");
//Test #486 checking search results for lime lime kiwi papaya strawberry with boost=false
yourResult = tester.search("lime lime kiwi papaya strawberry", false, 100);
TestingTools.checkSearch(yourResult, "lime lime kiwi papaya strawberry", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #486 checking search results for lime lime kiwi papaya strawberry with boost=false");
//Test #487 checking search results for apricot with boost=false
yourResult = tester.search("apricot", false, 100);
TestingTools.checkSearch(yourResult, "apricot", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #487 checking search results for apricot with boost=false");
//Test #488 checking search results for apple papaya lime cherry papaya with boost=false
yourResult = tester.search("apple papaya lime cherry papaya", false, 100);
TestingTools.checkSearch(yourResult, "apple papaya lime cherry papaya", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #488 checking search results for apple papaya lime cherry papaya with boost=false");
//Test #489 checking search results for strawberry apricot coconut with boost=false
yourResult = tester.search("strawberry apricot coconut", false, 100);
TestingTools.checkSearch(yourResult, "strawberry apricot coconut", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #489 checking search results for strawberry apricot coconut with boost=false");
//Test #490 checking search results for lime lime lime coconut with boost=false
yourResult = tester.search("lime lime lime coconut", false, 100);
TestingTools.checkSearch(yourResult, "lime lime lime coconut", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #490 checking search results for lime lime lime coconut with boost=false");
//Test #491 checking search results for fig fig tomato blueberry apple with boost=false
yourResult = tester.search("fig fig tomato blueberry apple", false, 100);
TestingTools.checkSearch(yourResult, "fig fig tomato blueberry apple", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #491 checking search results for fig fig tomato blueberry apple with boost=false");
//Test #492 checking search results for peach lime with boost=false
yourResult = tester.search("peach lime", false, 100);
TestingTools.checkSearch(yourResult, "peach lime", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #492 checking search results for peach lime with boost=false");
//Test #493 checking search results for apple blueberry tomato fig with boost=false
yourResult = tester.search("apple blueberry tomato fig", false, 100);
TestingTools.checkSearch(yourResult, "apple blueberry tomato fig", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #493 checking search results for apple blueberry tomato fig with boost=false");
//Test #494 checking search results for kiwi with boost=false
yourResult = tester.search("kiwi", false, 100);
TestingTools.checkSearch(yourResult, "kiwi", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #494 checking search results for kiwi with boost=false");
//Test #495 checking search results for kiwi with boost=false
yourResult = tester.search("kiwi", false, 100);
TestingTools.checkSearch(yourResult, "kiwi", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #495 checking search results for kiwi with boost=false");
//Test #496 checking search results for blueberry strawberry tomato apple with boost=false
yourResult = tester.search("blueberry strawberry tomato apple", false, 100);
TestingTools.checkSearch(yourResult, "blueberry strawberry tomato apple", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #496 checking search results for blueberry strawberry tomato apple with boost=false");
//Test #497 checking search results for papaya with boost=false
yourResult = tester.search("papaya", false, 100);
TestingTools.checkSearch(yourResult, "papaya", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #497 checking search results for papaya with boost=false");
//Test #498 checking search results for coconut fig papaya with boost=false
yourResult = tester.search("coconut fig papaya", false, 100);
TestingTools.checkSearch(yourResult, "coconut fig papaya", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #498 checking search results for coconut fig papaya with boost=false");
//Test #499 checking search results for lime banana tomato banana lime with boost=false
yourResult = tester.search("lime banana tomato banana lime", false, 100);
TestingTools.checkSearch(yourResult, "lime banana tomato banana lime", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #499 checking search results for lime banana tomato banana lime with boost=false");
//Test #500 checking search results for cherry strawberry with boost=false
yourResult = tester.search("cherry strawberry", false, 100);
TestingTools.checkSearch(yourResult, "cherry strawberry", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #500 checking search results for cherry strawberry with boost=false");
//Test #501 checking search results for cherry tomato blueberry cherry with boost=false
yourResult = tester.search("cherry tomato blueberry cherry", false, 100);
TestingTools.checkSearch(yourResult, "cherry tomato blueberry cherry", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #501 checking search results for cherry tomato blueberry cherry with boost=false");
//Test #502 checking search results for lime strawberry with boost=false
yourResult = tester.search("lime strawberry", false, 100);
TestingTools.checkSearch(yourResult, "lime strawberry", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #502 checking search results for lime strawberry with boost=false");
//Test #503 checking search results for kiwi lime with boost=false
yourResult = tester.search("kiwi lime", false, 100);
TestingTools.checkSearch(yourResult, "kiwi lime", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #503 checking search results for kiwi lime with boost=false");
//Test #504 checking search results for apricot tomato fig with boost=false
yourResult = tester.search("apricot tomato fig", false, 100);
TestingTools.checkSearch(yourResult, "apricot tomato fig", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #504 checking search results for apricot tomato fig with boost=false");
//Test #505 checking search results for lime strawberry kiwi kiwi papaya with boost=false
yourResult = tester.search("lime strawberry kiwi kiwi papaya", false, 100);
TestingTools.checkSearch(yourResult, "lime strawberry kiwi kiwi papaya", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #505 checking search results for lime strawberry kiwi kiwi papaya with boost=false");
//Test #506 checking search results for blueberry with boost=false
yourResult = tester.search("blueberry", false, 100);
TestingTools.checkSearch(yourResult, "blueberry", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #506 checking search results for blueberry with boost=false");
//Test #507 checking search results for coconut peach cherry with boost=false
yourResult = tester.search("coconut peach cherry", false, 100);
TestingTools.checkSearch(yourResult, "coconut peach cherry", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #507 checking search results for coconut peach cherry with boost=false");
//Test #508 checking search results for coconut with boost=false
yourResult = tester.search("coconut", false, 100);
TestingTools.checkSearch(yourResult, "coconut", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #508 checking search results for coconut with boost=false");
//Test #509 checking search results for blueberry blueberry cherry banana with boost=false
yourResult = tester.search("blueberry blueberry cherry banana", false, 100);
TestingTools.checkSearch(yourResult, "blueberry blueberry cherry banana", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #509 checking search results for blueberry blueberry cherry banana with boost=false");
//Test #510 checking search results for kiwi with boost=false
yourResult = tester.search("kiwi", false, 100);
TestingTools.checkSearch(yourResult, "kiwi", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #510 checking search results for kiwi with boost=false");
//Test #511 checking search results for apple tomato with boost=false
yourResult = tester.search("apple tomato", false, 100);
TestingTools.checkSearch(yourResult, "apple tomato", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #511 checking search results for apple tomato with boost=false");
//Test #512 checking search results for apple coconut kiwi with boost=false
yourResult = tester.search("apple coconut kiwi", false, 100);
TestingTools.checkSearch(yourResult, "apple coconut kiwi", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #512 checking search results for apple coconut kiwi with boost=false");
//Test #513 checking search results for peach strawberry with boost=false
yourResult = tester.search("peach strawberry", false, 100);
TestingTools.checkSearch(yourResult, "peach strawberry", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #513 checking search results for peach strawberry with boost=false");
//Test #514 checking search results for apricot with boost=false
yourResult = tester.search("apricot", false, 100);
TestingTools.checkSearch(yourResult, "apricot", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #514 checking search results for apricot with boost=false");
//Test #515 checking search results for apple peach fig with boost=false
yourResult = tester.search("apple peach fig", false, 100);
TestingTools.checkSearch(yourResult, "apple peach fig", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #515 checking search results for apple peach fig with boost=false");
//Test #516 checking search results for lime papaya cherry lime with boost=false
yourResult = tester.search("lime papaya cherry lime", false, 100);
TestingTools.checkSearch(yourResult, "lime papaya cherry lime", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #516 checking search results for lime papaya cherry lime with boost=false");
//Test #517 checking search results for pear coconut lime blueberry with boost=false
yourResult = tester.search("pear coconut lime blueberry", false, 100);
TestingTools.checkSearch(yourResult, "pear coconut lime blueberry", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #517 checking search results for pear coconut lime blueberry with boost=false");
//Test #518 checking search results for apple banana banana kiwi strawberry with boost=false
yourResult = tester.search("apple banana banana kiwi strawberry", false, 100);
TestingTools.checkSearch(yourResult, "apple banana banana kiwi strawberry", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #518 checking search results for apple banana banana kiwi strawberry with boost=false");
//Test #519 checking search results for apple apricot with boost=false
yourResult = tester.search("apple apricot", false, 100);
TestingTools.checkSearch(yourResult, "apple apricot", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #519 checking search results for apple apricot with boost=false");
//Test #520 checking search results for kiwi kiwi kiwi with boost=false
yourResult = tester.search("kiwi kiwi kiwi", false, 100);
TestingTools.checkSearch(yourResult, "kiwi kiwi kiwi", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #520 checking search results for kiwi kiwi kiwi with boost=false");
//Test #521 checking search results for lime cherry with boost=false
yourResult = tester.search("lime cherry", false, 100);
TestingTools.checkSearch(yourResult, "lime cherry", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #521 checking search results for lime cherry with boost=false");
//Test #522 checking search results for tomato apricot with boost=false
yourResult = tester.search("tomato apricot", false, 100);
TestingTools.checkSearch(yourResult, "tomato apricot", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #522 checking search results for tomato apricot with boost=false");
//Test #523 checking search results for coconut with boost=false
yourResult = tester.search("coconut", false, 100);
TestingTools.checkSearch(yourResult, "coconut", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #523 checking search results for coconut with boost=false");
//Test #524 checking search results for banana with boost=false
yourResult = tester.search("banana", false, 100);
TestingTools.checkSearch(yourResult, "banana", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #524 checking search results for banana with boost=false");
//Test #525 checking search results for fig fig with boost=false
yourResult = tester.search("fig fig", false, 100);
TestingTools.checkSearch(yourResult, "fig fig", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #525 checking search results for fig fig with boost=false");
//Test #526 checking search results for pear coconut with boost=false
yourResult = tester.search("pear coconut", false, 100);
TestingTools.checkSearch(yourResult, "pear coconut", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #526 checking search results for pear coconut with boost=false");
//Test #527 checking search results for fig lime coconut kiwi with boost=false
yourResult = tester.search("fig lime coconut kiwi", false, 100);
TestingTools.checkSearch(yourResult, "fig lime coconut kiwi", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #527 checking search results for fig lime coconut kiwi with boost=false");
//Test #528 checking search results for strawberry papaya lime with boost=false
yourResult = tester.search("strawberry papaya lime", false, 100);
TestingTools.checkSearch(yourResult, "strawberry papaya lime", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #528 checking search results for strawberry papaya lime with boost=false");
//Test #529 checking search results for cherry pear banana with boost=false
yourResult = tester.search("cherry pear banana", false, 100);
TestingTools.checkSearch(yourResult, "cherry pear banana", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #529 checking search results for cherry pear banana with boost=false");
//Test #530 checking search results for tomato fig cherry with boost=false
yourResult = tester.search("tomato fig cherry", false, 100);
TestingTools.checkSearch(yourResult, "tomato fig cherry", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #530 checking search results for tomato fig cherry with boost=false");
//Test #531 checking search results for cherry strawberry peach with boost=false
yourResult = tester.search("cherry strawberry peach", false, 100);
TestingTools.checkSearch(yourResult, "cherry strawberry peach", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #531 checking search results for cherry strawberry peach with boost=false");
//Test #532 checking search results for apple coconut strawberry coconut with boost=false
yourResult = tester.search("apple coconut strawberry coconut", false, 100);
TestingTools.checkSearch(yourResult, "apple coconut strawberry coconut", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #532 checking search results for apple coconut strawberry coconut with boost=false");
//Test #533 checking search results for blueberry tomato with boost=false
yourResult = tester.search("blueberry tomato", false, 100);
TestingTools.checkSearch(yourResult, "blueberry tomato", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #533 checking search results for blueberry tomato with boost=false");
//Test #534 checking search results for strawberry cherry coconut fig with boost=false
yourResult = tester.search("strawberry cherry coconut fig", false, 100);
TestingTools.checkSearch(yourResult, "strawberry cherry coconut fig", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #534 checking search results for strawberry cherry coconut fig with boost=false");
//Test #535 checking search results for peach with boost=false
yourResult = tester.search("peach", false, 100);
TestingTools.checkSearch(yourResult, "peach", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #535 checking search results for peach with boost=false");
//Test #536 checking search results for apricot blueberry peach with boost=false
yourResult = tester.search("apricot blueberry peach", false, 100);
TestingTools.checkSearch(yourResult, "apricot blueberry peach", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #536 checking search results for apricot blueberry peach with boost=false");
//Test #537 checking search results for banana papaya fig peach apricot with boost=false
yourResult = tester.search("banana papaya fig peach apricot", false, 100);
TestingTools.checkSearch(yourResult, "banana papaya fig peach apricot", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #537 checking search results for banana papaya fig peach apricot with boost=false");
//Test #538 checking search results for coconut cherry with boost=false
yourResult = tester.search("coconut cherry", false, 100);
TestingTools.checkSearch(yourResult, "coconut cherry", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #538 checking search results for coconut cherry with boost=false");
//Test #539 checking search results for apple strawberry apple fig apple with boost=false
yourResult = tester.search("apple strawberry apple fig apple", false, 100);
TestingTools.checkSearch(yourResult, "apple strawberry apple fig apple", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #539 checking search results for apple strawberry apple fig apple with boost=false");
//Test #540 checking search results for lime blueberry with boost=false
yourResult = tester.search("lime blueberry", false, 100);
TestingTools.checkSearch(yourResult, "lime blueberry", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #540 checking search results for lime blueberry with boost=false");
//Test #541 checking search results for strawberry fig coconut cherry blueberry with boost=false
yourResult = tester.search("strawberry fig coconut cherry blueberry", false, 100);
TestingTools.checkSearch(yourResult, "strawberry fig coconut cherry blueberry", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #541 checking search results for strawberry fig coconut cherry blueberry with boost=false");
//Test #542 checking search results for pear with boost=false
yourResult = tester.search("pear", false, 100);
TestingTools.checkSearch(yourResult, "pear", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #542 checking search results for pear with boost=false");
//Test #543 checking search results for peach apricot peach with boost=false
yourResult = tester.search("peach apricot peach", false, 100);
TestingTools.checkSearch(yourResult, "peach apricot peach", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #543 checking search results for peach apricot peach with boost=false");
//Test #544 checking search results for kiwi papaya peach apricot coconut with boost=false
yourResult = tester.search("kiwi papaya peach apricot coconut", false, 100);
TestingTools.checkSearch(yourResult, "kiwi papaya peach apricot coconut", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #544 checking search results for kiwi papaya peach apricot coconut with boost=false");
//Test #545 checking search results for coconut strawberry pear lime with boost=false
yourResult = tester.search("coconut strawberry pear lime", false, 100);
TestingTools.checkSearch(yourResult, "coconut strawberry pear lime", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #545 checking search results for coconut strawberry pear lime with boost=false");
//Test #546 checking search results for lime papaya apple apple papaya with boost=false
yourResult = tester.search("lime papaya apple apple papaya", false, 100);
TestingTools.checkSearch(yourResult, "lime papaya apple apple papaya", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #546 checking search results for lime papaya apple apple papaya with boost=false");
//Test #547 checking search results for peach with boost=false
yourResult = tester.search("peach", false, 100);
TestingTools.checkSearch(yourResult, "peach", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #547 checking search results for peach with boost=false");
//Test #548 checking search results for lime apple apricot apricot cherry with boost=false
yourResult = tester.search("lime apple apricot apricot cherry", false, 100);
TestingTools.checkSearch(yourResult, "lime apple apricot apricot cherry", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #548 checking search results for lime apple apricot apricot cherry with boost=false");
//Test #549 checking search results for fig strawberry banana strawberry peach with boost=false
yourResult = tester.search("fig strawberry banana strawberry peach", false, 100);
TestingTools.checkSearch(yourResult, "fig strawberry banana strawberry peach", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #549 checking search results for fig strawberry banana strawberry peach with boost=false");
//Test #550 checking search results for coconut cherry with boost=false
yourResult = tester.search("coconut cherry", false, 100);
TestingTools.checkSearch(yourResult, "coconut cherry", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #550 checking search results for coconut cherry with boost=false");
//Test #551 checking search results for papaya with boost=false
yourResult = tester.search("papaya", false, 100);
TestingTools.checkSearch(yourResult, "papaya", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #551 checking search results for papaya with boost=false");
//Test #552 checking search results for coconut fig blueberry apricot apple with boost=false
yourResult = tester.search("coconut fig blueberry apricot apple", false, 100);
TestingTools.checkSearch(yourResult, "coconut fig blueberry apricot apple", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #552 checking search results for coconut fig blueberry apricot apple with boost=false");
//Test #553 checking search results for kiwi pear banana peach cherry with boost=false
yourResult = tester.search("kiwi pear banana peach cherry", false, 100);
TestingTools.checkSearch(yourResult, "kiwi pear banana peach cherry", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #553 checking search results for kiwi pear banana peach cherry with boost=false");
//Test #554 checking search results for cherry kiwi pear with boost=false
yourResult = tester.search("cherry kiwi pear", false, 100);
TestingTools.checkSearch(yourResult, "cherry kiwi pear", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #554 checking search results for cherry kiwi pear with boost=false");
//Test #555 checking search results for pear pear with boost=false
yourResult = tester.search("pear pear", false, 100);
TestingTools.checkSearch(yourResult, "pear pear", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #555 checking search results for pear pear with boost=false");
//Test #556 checking search results for banana papaya pear with boost=false
yourResult = tester.search("banana papaya pear", false, 100);
TestingTools.checkSearch(yourResult, "banana papaya pear", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #556 checking search results for banana papaya pear with boost=false");
//Test #557 checking search results for fig with boost=false
yourResult = tester.search("fig", false, 100);
TestingTools.checkSearch(yourResult, "fig", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #557 checking search results for fig with boost=false");
//Test #558 checking search results for pear tomato strawberry blueberry fig with boost=false
yourResult = tester.search("pear tomato strawberry blueberry fig", false, 100);
TestingTools.checkSearch(yourResult, "pear tomato strawberry blueberry fig", passOut, failOut, "Fruits100SearchNoBoostTester", "Test #558 checking search results for pear tomato strawberry blueberry fig with boost=false");
failOut.close();
passOut.close();
}
}
