import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.*;
public class Fruits25SearchBoostTester {public static void main(String[] args) throws Exception{
ProjectTester tester = new ProjectTesterImp(); //Instantiate your own ProjectTester instance here
tester.initialize();
tester.crawl("https://people.scs.carleton.ca/~avamckenney/fruits25/N-0.html");
runTest(tester);}public static void runTest(ProjectTester tester) throws Exception{
PrintWriter failOut = new PrintWriter(new FileWriter("Fruits25-SearchBoost-failed.txt"));
PrintWriter passOut = new PrintWriter(new FileWriter("Fruits25-SearchBoost-passed.txt"));
List<SearchResult> yourResult; 
//Test #434 checking search results for kiwi tomato fig banana cherry with boost=true
yourResult = tester.search("kiwi tomato fig banana cherry", true, 25);
TestingTools.checkSearch(yourResult, "kiwi tomato fig banana cherry", passOut, failOut, "Fruits25SearchBoostTester", "Test #434 checking search results for kiwi tomato fig banana cherry with boost=true");
//Test #435 checking search results for fig papaya apple with boost=true
yourResult = tester.search("fig papaya apple", true, 25);
TestingTools.checkSearch(yourResult, "fig papaya apple", passOut, failOut, "Fruits25SearchBoostTester", "Test #435 checking search results for fig papaya apple with boost=true");
//Test #436 checking search results for cherry peach cherry coconut with boost=true
yourResult = tester.search("cherry peach cherry coconut", true, 25);
TestingTools.checkSearch(yourResult, "cherry peach cherry coconut", passOut, failOut, "Fruits25SearchBoostTester", "Test #436 checking search results for cherry peach cherry coconut with boost=true");
//Test #437 checking search results for blueberry apricot kiwi strawberry papaya with boost=true
yourResult = tester.search("blueberry apricot kiwi strawberry papaya", true, 25);
TestingTools.checkSearch(yourResult, "blueberry apricot kiwi strawberry papaya", passOut, failOut, "Fruits25SearchBoostTester", "Test #437 checking search results for blueberry apricot kiwi strawberry papaya with boost=true");
//Test #438 checking search results for blueberry banana peach pear with boost=true
yourResult = tester.search("blueberry banana peach pear", true, 25);
TestingTools.checkSearch(yourResult, "blueberry banana peach pear", passOut, failOut, "Fruits25SearchBoostTester", "Test #438 checking search results for blueberry banana peach pear with boost=true");
//Test #439 checking search results for pear fig strawberry banana with boost=true
yourResult = tester.search("pear fig strawberry banana", true, 25);
TestingTools.checkSearch(yourResult, "pear fig strawberry banana", passOut, failOut, "Fruits25SearchBoostTester", "Test #439 checking search results for pear fig strawberry banana with boost=true");
//Test #440 checking search results for strawberry kiwi kiwi banana peach with boost=true
yourResult = tester.search("strawberry kiwi kiwi banana peach", true, 25);
TestingTools.checkSearch(yourResult, "strawberry kiwi kiwi banana peach", passOut, failOut, "Fruits25SearchBoostTester", "Test #440 checking search results for strawberry kiwi kiwi banana peach with boost=true");
//Test #441 checking search results for lime kiwi pear with boost=true
yourResult = tester.search("lime kiwi pear", true, 25);
TestingTools.checkSearch(yourResult, "lime kiwi pear", passOut, failOut, "Fruits25SearchBoostTester", "Test #441 checking search results for lime kiwi pear with boost=true");
//Test #442 checking search results for fig with boost=true
yourResult = tester.search("fig", true, 25);
TestingTools.checkSearch(yourResult, "fig", passOut, failOut, "Fruits25SearchBoostTester", "Test #442 checking search results for fig with boost=true");
//Test #443 checking search results for coconut lime with boost=true
yourResult = tester.search("coconut lime", true, 25);
TestingTools.checkSearch(yourResult, "coconut lime", passOut, failOut, "Fruits25SearchBoostTester", "Test #443 checking search results for coconut lime with boost=true");
//Test #444 checking search results for papaya blueberry with boost=true
yourResult = tester.search("papaya blueberry", true, 25);
TestingTools.checkSearch(yourResult, "papaya blueberry", passOut, failOut, "Fruits25SearchBoostTester", "Test #444 checking search results for papaya blueberry with boost=true");
//Test #445 checking search results for pear with boost=true
yourResult = tester.search("pear", true, 25);
TestingTools.checkSearch(yourResult, "pear", passOut, failOut, "Fruits25SearchBoostTester", "Test #445 checking search results for pear with boost=true");
//Test #446 checking search results for peach kiwi strawberry with boost=true
yourResult = tester.search("peach kiwi strawberry", true, 25);
TestingTools.checkSearch(yourResult, "peach kiwi strawberry", passOut, failOut, "Fruits25SearchBoostTester", "Test #446 checking search results for peach kiwi strawberry with boost=true");
//Test #447 checking search results for cherry kiwi with boost=true
yourResult = tester.search("cherry kiwi", true, 25);
TestingTools.checkSearch(yourResult, "cherry kiwi", passOut, failOut, "Fruits25SearchBoostTester", "Test #447 checking search results for cherry kiwi with boost=true");
//Test #448 checking search results for banana with boost=true
yourResult = tester.search("banana", true, 25);
TestingTools.checkSearch(yourResult, "banana", passOut, failOut, "Fruits25SearchBoostTester", "Test #448 checking search results for banana with boost=true");
//Test #449 checking search results for apple tomato with boost=true
yourResult = tester.search("apple tomato", true, 25);
TestingTools.checkSearch(yourResult, "apple tomato", passOut, failOut, "Fruits25SearchBoostTester", "Test #449 checking search results for apple tomato with boost=true");
//Test #450 checking search results for apple cherry papaya strawberry coconut with boost=true
yourResult = tester.search("apple cherry papaya strawberry coconut", true, 25);
TestingTools.checkSearch(yourResult, "apple cherry papaya strawberry coconut", passOut, failOut, "Fruits25SearchBoostTester", "Test #450 checking search results for apple cherry papaya strawberry coconut with boost=true");
//Test #451 checking search results for fig with boost=true
yourResult = tester.search("fig", true, 25);
TestingTools.checkSearch(yourResult, "fig", passOut, failOut, "Fruits25SearchBoostTester", "Test #451 checking search results for fig with boost=true");
//Test #452 checking search results for coconut fig tomato with boost=true
yourResult = tester.search("coconut fig tomato", true, 25);
TestingTools.checkSearch(yourResult, "coconut fig tomato", passOut, failOut, "Fruits25SearchBoostTester", "Test #452 checking search results for coconut fig tomato with boost=true");
//Test #453 checking search results for papaya kiwi tomato banana with boost=true
yourResult = tester.search("papaya kiwi tomato banana", true, 25);
TestingTools.checkSearch(yourResult, "papaya kiwi tomato banana", passOut, failOut, "Fruits25SearchBoostTester", "Test #453 checking search results for papaya kiwi tomato banana with boost=true");
//Test #454 checking search results for lime blueberry with boost=true
yourResult = tester.search("lime blueberry", true, 25);
TestingTools.checkSearch(yourResult, "lime blueberry", passOut, failOut, "Fruits25SearchBoostTester", "Test #454 checking search results for lime blueberry with boost=true");
//Test #455 checking search results for pear with boost=true
yourResult = tester.search("pear", true, 25);
TestingTools.checkSearch(yourResult, "pear", passOut, failOut, "Fruits25SearchBoostTester", "Test #455 checking search results for pear with boost=true");
//Test #456 checking search results for kiwi with boost=true
yourResult = tester.search("kiwi", true, 25);
TestingTools.checkSearch(yourResult, "kiwi", passOut, failOut, "Fruits25SearchBoostTester", "Test #456 checking search results for kiwi with boost=true");
//Test #457 checking search results for apricot coconut apricot cherry with boost=true
yourResult = tester.search("apricot coconut apricot cherry", true, 25);
TestingTools.checkSearch(yourResult, "apricot coconut apricot cherry", passOut, failOut, "Fruits25SearchBoostTester", "Test #457 checking search results for apricot coconut apricot cherry with boost=true");
//Test #458 checking search results for kiwi blueberry banana with boost=true
yourResult = tester.search("kiwi blueberry banana", true, 25);
TestingTools.checkSearch(yourResult, "kiwi blueberry banana", passOut, failOut, "Fruits25SearchBoostTester", "Test #458 checking search results for kiwi blueberry banana with boost=true");
//Test #459 checking search results for kiwi banana apple papaya apple with boost=true
yourResult = tester.search("kiwi banana apple papaya apple", true, 25);
TestingTools.checkSearch(yourResult, "kiwi banana apple papaya apple", passOut, failOut, "Fruits25SearchBoostTester", "Test #459 checking search results for kiwi banana apple papaya apple with boost=true");
//Test #460 checking search results for peach pear with boost=true
yourResult = tester.search("peach pear", true, 25);
TestingTools.checkSearch(yourResult, "peach pear", passOut, failOut, "Fruits25SearchBoostTester", "Test #460 checking search results for peach pear with boost=true");
//Test #461 checking search results for blueberry cherry with boost=true
yourResult = tester.search("blueberry cherry", true, 25);
TestingTools.checkSearch(yourResult, "blueberry cherry", passOut, failOut, "Fruits25SearchBoostTester", "Test #461 checking search results for blueberry cherry with boost=true");
//Test #462 checking search results for papaya apple strawberry lime apple with boost=true
yourResult = tester.search("papaya apple strawberry lime apple", true, 25);
TestingTools.checkSearch(yourResult, "papaya apple strawberry lime apple", passOut, failOut, "Fruits25SearchBoostTester", "Test #462 checking search results for papaya apple strawberry lime apple with boost=true");
//Test #463 checking search results for coconut lime papaya strawberry tomato with boost=true
yourResult = tester.search("coconut lime papaya strawberry tomato", true, 25);
TestingTools.checkSearch(yourResult, "coconut lime papaya strawberry tomato", passOut, failOut, "Fruits25SearchBoostTester", "Test #463 checking search results for coconut lime papaya strawberry tomato with boost=true");
//Test #464 checking search results for peach pear kiwi tomato with boost=true
yourResult = tester.search("peach pear kiwi tomato", true, 25);
TestingTools.checkSearch(yourResult, "peach pear kiwi tomato", passOut, failOut, "Fruits25SearchBoostTester", "Test #464 checking search results for peach pear kiwi tomato with boost=true");
//Test #465 checking search results for fig tomato cherry with boost=true
yourResult = tester.search("fig tomato cherry", true, 25);
TestingTools.checkSearch(yourResult, "fig tomato cherry", passOut, failOut, "Fruits25SearchBoostTester", "Test #465 checking search results for fig tomato cherry with boost=true");
//Test #466 checking search results for pear peach tomato with boost=true
yourResult = tester.search("pear peach tomato", true, 25);
TestingTools.checkSearch(yourResult, "pear peach tomato", passOut, failOut, "Fruits25SearchBoostTester", "Test #466 checking search results for pear peach tomato with boost=true");
//Test #467 checking search results for blueberry strawberry coconut with boost=true
yourResult = tester.search("blueberry strawberry coconut", true, 25);
TestingTools.checkSearch(yourResult, "blueberry strawberry coconut", passOut, failOut, "Fruits25SearchBoostTester", "Test #467 checking search results for blueberry strawberry coconut with boost=true");
//Test #468 checking search results for fig lime peach apple with boost=true
yourResult = tester.search("fig lime peach apple", true, 25);
TestingTools.checkSearch(yourResult, "fig lime peach apple", passOut, failOut, "Fruits25SearchBoostTester", "Test #468 checking search results for fig lime peach apple with boost=true");
//Test #469 checking search results for coconut with boost=true
yourResult = tester.search("coconut", true, 25);
TestingTools.checkSearch(yourResult, "coconut", passOut, failOut, "Fruits25SearchBoostTester", "Test #469 checking search results for coconut with boost=true");
//Test #470 checking search results for strawberry pear banana apple apricot with boost=true
yourResult = tester.search("strawberry pear banana apple apricot", true, 25);
TestingTools.checkSearch(yourResult, "strawberry pear banana apple apricot", passOut, failOut, "Fruits25SearchBoostTester", "Test #470 checking search results for strawberry pear banana apple apricot with boost=true");
//Test #471 checking search results for coconut cherry papaya with boost=true
yourResult = tester.search("coconut cherry papaya", true, 25);
TestingTools.checkSearch(yourResult, "coconut cherry papaya", passOut, failOut, "Fruits25SearchBoostTester", "Test #471 checking search results for coconut cherry papaya with boost=true");
//Test #472 checking search results for banana with boost=true
yourResult = tester.search("banana", true, 25);
TestingTools.checkSearch(yourResult, "banana", passOut, failOut, "Fruits25SearchBoostTester", "Test #472 checking search results for banana with boost=true");
//Test #473 checking search results for strawberry pear with boost=true
yourResult = tester.search("strawberry pear", true, 25);
TestingTools.checkSearch(yourResult, "strawberry pear", passOut, failOut, "Fruits25SearchBoostTester", "Test #473 checking search results for strawberry pear with boost=true");
//Test #474 checking search results for coconut apricot with boost=true
yourResult = tester.search("coconut apricot", true, 25);
TestingTools.checkSearch(yourResult, "coconut apricot", passOut, failOut, "Fruits25SearchBoostTester", "Test #474 checking search results for coconut apricot with boost=true");
//Test #475 checking search results for pear peach with boost=true
yourResult = tester.search("pear peach", true, 25);
TestingTools.checkSearch(yourResult, "pear peach", passOut, failOut, "Fruits25SearchBoostTester", "Test #475 checking search results for pear peach with boost=true");
//Test #476 checking search results for fig apple papaya strawberry coconut with boost=true
yourResult = tester.search("fig apple papaya strawberry coconut", true, 25);
TestingTools.checkSearch(yourResult, "fig apple papaya strawberry coconut", passOut, failOut, "Fruits25SearchBoostTester", "Test #476 checking search results for fig apple papaya strawberry coconut with boost=true");
//Test #477 checking search results for cherry apricot pear with boost=true
yourResult = tester.search("cherry apricot pear", true, 25);
TestingTools.checkSearch(yourResult, "cherry apricot pear", passOut, failOut, "Fruits25SearchBoostTester", "Test #477 checking search results for cherry apricot pear with boost=true");
//Test #478 checking search results for apple strawberry with boost=true
yourResult = tester.search("apple strawberry", true, 25);
TestingTools.checkSearch(yourResult, "apple strawberry", passOut, failOut, "Fruits25SearchBoostTester", "Test #478 checking search results for apple strawberry with boost=true");
//Test #479 checking search results for strawberry apple fig with boost=true
yourResult = tester.search("strawberry apple fig", true, 25);
TestingTools.checkSearch(yourResult, "strawberry apple fig", passOut, failOut, "Fruits25SearchBoostTester", "Test #479 checking search results for strawberry apple fig with boost=true");
//Test #480 checking search results for kiwi banana tomato papaya cherry with boost=true
yourResult = tester.search("kiwi banana tomato papaya cherry", true, 25);
TestingTools.checkSearch(yourResult, "kiwi banana tomato papaya cherry", passOut, failOut, "Fruits25SearchBoostTester", "Test #480 checking search results for kiwi banana tomato papaya cherry with boost=true");
//Test #481 checking search results for blueberry cherry coconut with boost=true
yourResult = tester.search("blueberry cherry coconut", true, 25);
TestingTools.checkSearch(yourResult, "blueberry cherry coconut", passOut, failOut, "Fruits25SearchBoostTester", "Test #481 checking search results for blueberry cherry coconut with boost=true");
//Test #482 checking search results for peach pear apricot apple with boost=true
yourResult = tester.search("peach pear apricot apple", true, 25);
TestingTools.checkSearch(yourResult, "peach pear apricot apple", passOut, failOut, "Fruits25SearchBoostTester", "Test #482 checking search results for peach pear apricot apple with boost=true");
//Test #483 checking search results for blueberry peach peach lime with boost=true
yourResult = tester.search("blueberry peach peach lime", true, 25);
TestingTools.checkSearch(yourResult, "blueberry peach peach lime", passOut, failOut, "Fruits25SearchBoostTester", "Test #483 checking search results for blueberry peach peach lime with boost=true");
//Test #484 checking search results for banana tomato pear tomato lime with boost=true
yourResult = tester.search("banana tomato pear tomato lime", true, 25);
TestingTools.checkSearch(yourResult, "banana tomato pear tomato lime", passOut, failOut, "Fruits25SearchBoostTester", "Test #484 checking search results for banana tomato pear tomato lime with boost=true");
//Test #485 checking search results for apple banana apricot with boost=true
yourResult = tester.search("apple banana apricot", true, 25);
TestingTools.checkSearch(yourResult, "apple banana apricot", passOut, failOut, "Fruits25SearchBoostTester", "Test #485 checking search results for apple banana apricot with boost=true");
//Test #486 checking search results for blueberry with boost=true
yourResult = tester.search("blueberry", true, 25);
TestingTools.checkSearch(yourResult, "blueberry", passOut, failOut, "Fruits25SearchBoostTester", "Test #486 checking search results for blueberry with boost=true");
//Test #487 checking search results for papaya banana peach with boost=true
yourResult = tester.search("papaya banana peach", true, 25);
TestingTools.checkSearch(yourResult, "papaya banana peach", passOut, failOut, "Fruits25SearchBoostTester", "Test #487 checking search results for papaya banana peach with boost=true");
//Test #488 checking search results for apple with boost=true
yourResult = tester.search("apple", true, 25);
TestingTools.checkSearch(yourResult, "apple", passOut, failOut, "Fruits25SearchBoostTester", "Test #488 checking search results for apple with boost=true");
//Test #489 checking search results for lime coconut apricot with boost=true
yourResult = tester.search("lime coconut apricot", true, 25);
TestingTools.checkSearch(yourResult, "lime coconut apricot", passOut, failOut, "Fruits25SearchBoostTester", "Test #489 checking search results for lime coconut apricot with boost=true");
//Test #490 checking search results for strawberry coconut pear apple lime with boost=true
yourResult = tester.search("strawberry coconut pear apple lime", true, 25);
TestingTools.checkSearch(yourResult, "strawberry coconut pear apple lime", passOut, failOut, "Fruits25SearchBoostTester", "Test #490 checking search results for strawberry coconut pear apple lime with boost=true");
//Test #491 checking search results for tomato banana apricot banana with boost=true
yourResult = tester.search("tomato banana apricot banana", true, 25);
TestingTools.checkSearch(yourResult, "tomato banana apricot banana", passOut, failOut, "Fruits25SearchBoostTester", "Test #491 checking search results for tomato banana apricot banana with boost=true");
//Test #492 checking search results for banana coconut apricot pear papaya with boost=true
yourResult = tester.search("banana coconut apricot pear papaya", true, 25);
TestingTools.checkSearch(yourResult, "banana coconut apricot pear papaya", passOut, failOut, "Fruits25SearchBoostTester", "Test #492 checking search results for banana coconut apricot pear papaya with boost=true");
//Test #493 checking search results for apple apple kiwi with boost=true
yourResult = tester.search("apple apple kiwi", true, 25);
TestingTools.checkSearch(yourResult, "apple apple kiwi", passOut, failOut, "Fruits25SearchBoostTester", "Test #493 checking search results for apple apple kiwi with boost=true");
//Test #494 checking search results for pear papaya pear apple coconut with boost=true
yourResult = tester.search("pear papaya pear apple coconut", true, 25);
TestingTools.checkSearch(yourResult, "pear papaya pear apple coconut", passOut, failOut, "Fruits25SearchBoostTester", "Test #494 checking search results for pear papaya pear apple coconut with boost=true");
//Test #495 checking search results for coconut with boost=true
yourResult = tester.search("coconut", true, 25);
TestingTools.checkSearch(yourResult, "coconut", passOut, failOut, "Fruits25SearchBoostTester", "Test #495 checking search results for coconut with boost=true");
//Test #496 checking search results for kiwi papaya tomato peach with boost=true
yourResult = tester.search("kiwi papaya tomato peach", true, 25);
TestingTools.checkSearch(yourResult, "kiwi papaya tomato peach", passOut, failOut, "Fruits25SearchBoostTester", "Test #496 checking search results for kiwi papaya tomato peach with boost=true");
//Test #497 checking search results for fig apple with boost=true
yourResult = tester.search("fig apple", true, 25);
TestingTools.checkSearch(yourResult, "fig apple", passOut, failOut, "Fruits25SearchBoostTester", "Test #497 checking search results for fig apple with boost=true");
//Test #498 checking search results for peach kiwi strawberry with boost=true
yourResult = tester.search("peach kiwi strawberry", true, 25);
TestingTools.checkSearch(yourResult, "peach kiwi strawberry", passOut, failOut, "Fruits25SearchBoostTester", "Test #498 checking search results for peach kiwi strawberry with boost=true");
//Test #499 checking search results for banana apricot with boost=true
yourResult = tester.search("banana apricot", true, 25);
TestingTools.checkSearch(yourResult, "banana apricot", passOut, failOut, "Fruits25SearchBoostTester", "Test #499 checking search results for banana apricot with boost=true");
//Test #500 checking search results for kiwi lime banana tomato with boost=true
yourResult = tester.search("kiwi lime banana tomato", true, 25);
TestingTools.checkSearch(yourResult, "kiwi lime banana tomato", passOut, failOut, "Fruits25SearchBoostTester", "Test #500 checking search results for kiwi lime banana tomato with boost=true");
//Test #501 checking search results for kiwi lime with boost=true
yourResult = tester.search("kiwi lime", true, 25);
TestingTools.checkSearch(yourResult, "kiwi lime", passOut, failOut, "Fruits25SearchBoostTester", "Test #501 checking search results for kiwi lime with boost=true");
//Test #502 checking search results for apricot with boost=true
yourResult = tester.search("apricot", true, 25);
TestingTools.checkSearch(yourResult, "apricot", passOut, failOut, "Fruits25SearchBoostTester", "Test #502 checking search results for apricot with boost=true");
//Test #503 checking search results for banana banana with boost=true
yourResult = tester.search("banana banana", true, 25);
TestingTools.checkSearch(yourResult, "banana banana", passOut, failOut, "Fruits25SearchBoostTester", "Test #503 checking search results for banana banana with boost=true");
//Test #504 checking search results for blueberry blueberry fig blueberry cherry with boost=true
yourResult = tester.search("blueberry blueberry fig blueberry cherry", true, 25);
TestingTools.checkSearch(yourResult, "blueberry blueberry fig blueberry cherry", passOut, failOut, "Fruits25SearchBoostTester", "Test #504 checking search results for blueberry blueberry fig blueberry cherry with boost=true");
//Test #505 checking search results for peach blueberry strawberry cherry apple with boost=true
yourResult = tester.search("peach blueberry strawberry cherry apple", true, 25);
TestingTools.checkSearch(yourResult, "peach blueberry strawberry cherry apple", passOut, failOut, "Fruits25SearchBoostTester", "Test #505 checking search results for peach blueberry strawberry cherry apple with boost=true");
//Test #506 checking search results for apricot lime with boost=true
yourResult = tester.search("apricot lime", true, 25);
TestingTools.checkSearch(yourResult, "apricot lime", passOut, failOut, "Fruits25SearchBoostTester", "Test #506 checking search results for apricot lime with boost=true");
//Test #507 checking search results for apricot lime peach fig with boost=true
yourResult = tester.search("apricot lime peach fig", true, 25);
TestingTools.checkSearch(yourResult, "apricot lime peach fig", passOut, failOut, "Fruits25SearchBoostTester", "Test #507 checking search results for apricot lime peach fig with boost=true");
//Test #508 checking search results for strawberry lime strawberry apple kiwi with boost=true
yourResult = tester.search("strawberry lime strawberry apple kiwi", true, 25);
TestingTools.checkSearch(yourResult, "strawberry lime strawberry apple kiwi", passOut, failOut, "Fruits25SearchBoostTester", "Test #508 checking search results for strawberry lime strawberry apple kiwi with boost=true");
//Test #509 checking search results for blueberry fig lime tomato pear with boost=true
yourResult = tester.search("blueberry fig lime tomato pear", true, 25);
TestingTools.checkSearch(yourResult, "blueberry fig lime tomato pear", passOut, failOut, "Fruits25SearchBoostTester", "Test #509 checking search results for blueberry fig lime tomato pear with boost=true");
//Test #510 checking search results for banana kiwi coconut with boost=true
yourResult = tester.search("banana kiwi coconut", true, 25);
TestingTools.checkSearch(yourResult, "banana kiwi coconut", passOut, failOut, "Fruits25SearchBoostTester", "Test #510 checking search results for banana kiwi coconut with boost=true");
//Test #511 checking search results for cherry kiwi banana with boost=true
yourResult = tester.search("cherry kiwi banana", true, 25);
TestingTools.checkSearch(yourResult, "cherry kiwi banana", passOut, failOut, "Fruits25SearchBoostTester", "Test #511 checking search results for cherry kiwi banana with boost=true");
//Test #512 checking search results for strawberry apricot coconut pear with boost=true
yourResult = tester.search("strawberry apricot coconut pear", true, 25);
TestingTools.checkSearch(yourResult, "strawberry apricot coconut pear", passOut, failOut, "Fruits25SearchBoostTester", "Test #512 checking search results for strawberry apricot coconut pear with boost=true");
//Test #513 checking search results for strawberry fig apricot strawberry cherry with boost=true
yourResult = tester.search("strawberry fig apricot strawberry cherry", true, 25);
TestingTools.checkSearch(yourResult, "strawberry fig apricot strawberry cherry", passOut, failOut, "Fruits25SearchBoostTester", "Test #513 checking search results for strawberry fig apricot strawberry cherry with boost=true");
//Test #514 checking search results for tomato cherry banana papaya with boost=true
yourResult = tester.search("tomato cherry banana papaya", true, 25);
TestingTools.checkSearch(yourResult, "tomato cherry banana papaya", passOut, failOut, "Fruits25SearchBoostTester", "Test #514 checking search results for tomato cherry banana papaya with boost=true");
//Test #515 checking search results for banana apple with boost=true
yourResult = tester.search("banana apple", true, 25);
TestingTools.checkSearch(yourResult, "banana apple", passOut, failOut, "Fruits25SearchBoostTester", "Test #515 checking search results for banana apple with boost=true");
//Test #516 checking search results for blueberry apricot pear fig strawberry with boost=true
yourResult = tester.search("blueberry apricot pear fig strawberry", true, 25);
TestingTools.checkSearch(yourResult, "blueberry apricot pear fig strawberry", passOut, failOut, "Fruits25SearchBoostTester", "Test #516 checking search results for blueberry apricot pear fig strawberry with boost=true");
//Test #517 checking search results for fig coconut papaya cherry with boost=true
yourResult = tester.search("fig coconut papaya cherry", true, 25);
TestingTools.checkSearch(yourResult, "fig coconut papaya cherry", passOut, failOut, "Fruits25SearchBoostTester", "Test #517 checking search results for fig coconut papaya cherry with boost=true");
//Test #518 checking search results for apple with boost=true
yourResult = tester.search("apple", true, 25);
TestingTools.checkSearch(yourResult, "apple", passOut, failOut, "Fruits25SearchBoostTester", "Test #518 checking search results for apple with boost=true");
//Test #519 checking search results for peach tomato papaya fig strawberry with boost=true
yourResult = tester.search("peach tomato papaya fig strawberry", true, 25);
TestingTools.checkSearch(yourResult, "peach tomato papaya fig strawberry", passOut, failOut, "Fruits25SearchBoostTester", "Test #519 checking search results for peach tomato papaya fig strawberry with boost=true");
//Test #520 checking search results for tomato blueberry with boost=true
yourResult = tester.search("tomato blueberry", true, 25);
TestingTools.checkSearch(yourResult, "tomato blueberry", passOut, failOut, "Fruits25SearchBoostTester", "Test #520 checking search results for tomato blueberry with boost=true");
//Test #521 checking search results for fig with boost=true
yourResult = tester.search("fig", true, 25);
TestingTools.checkSearch(yourResult, "fig", passOut, failOut, "Fruits25SearchBoostTester", "Test #521 checking search results for fig with boost=true");
//Test #522 checking search results for pear lime apricot with boost=true
yourResult = tester.search("pear lime apricot", true, 25);
TestingTools.checkSearch(yourResult, "pear lime apricot", passOut, failOut, "Fruits25SearchBoostTester", "Test #522 checking search results for pear lime apricot with boost=true");
//Test #523 checking search results for coconut kiwi papaya with boost=true
yourResult = tester.search("coconut kiwi papaya", true, 25);
TestingTools.checkSearch(yourResult, "coconut kiwi papaya", passOut, failOut, "Fruits25SearchBoostTester", "Test #523 checking search results for coconut kiwi papaya with boost=true");
//Test #524 checking search results for apple cherry apricot strawberry with boost=true
yourResult = tester.search("apple cherry apricot strawberry", true, 25);
TestingTools.checkSearch(yourResult, "apple cherry apricot strawberry", passOut, failOut, "Fruits25SearchBoostTester", "Test #524 checking search results for apple cherry apricot strawberry with boost=true");
//Test #525 checking search results for peach apple strawberry tomato with boost=true
yourResult = tester.search("peach apple strawberry tomato", true, 25);
TestingTools.checkSearch(yourResult, "peach apple strawberry tomato", passOut, failOut, "Fruits25SearchBoostTester", "Test #525 checking search results for peach apple strawberry tomato with boost=true");
//Test #526 checking search results for cherry pear papaya apricot with boost=true
yourResult = tester.search("cherry pear papaya apricot", true, 25);
TestingTools.checkSearch(yourResult, "cherry pear papaya apricot", passOut, failOut, "Fruits25SearchBoostTester", "Test #526 checking search results for cherry pear papaya apricot with boost=true");
//Test #527 checking search results for apricot lime apricot tomato apple with boost=true
yourResult = tester.search("apricot lime apricot tomato apple", true, 25);
TestingTools.checkSearch(yourResult, "apricot lime apricot tomato apple", passOut, failOut, "Fruits25SearchBoostTester", "Test #527 checking search results for apricot lime apricot tomato apple with boost=true");
//Test #528 checking search results for pear pear with boost=true
yourResult = tester.search("pear pear", true, 25);
TestingTools.checkSearch(yourResult, "pear pear", passOut, failOut, "Fruits25SearchBoostTester", "Test #528 checking search results for pear pear with boost=true");
//Test #529 checking search results for papaya kiwi fig papaya tomato with boost=true
yourResult = tester.search("papaya kiwi fig papaya tomato", true, 25);
TestingTools.checkSearch(yourResult, "papaya kiwi fig papaya tomato", passOut, failOut, "Fruits25SearchBoostTester", "Test #529 checking search results for papaya kiwi fig papaya tomato with boost=true");
//Test #530 checking search results for apricot tomato peach lime with boost=true
yourResult = tester.search("apricot tomato peach lime", true, 25);
TestingTools.checkSearch(yourResult, "apricot tomato peach lime", passOut, failOut, "Fruits25SearchBoostTester", "Test #530 checking search results for apricot tomato peach lime with boost=true");
//Test #531 checking search results for apricot fig coconut with boost=true
yourResult = tester.search("apricot fig coconut", true, 25);
TestingTools.checkSearch(yourResult, "apricot fig coconut", passOut, failOut, "Fruits25SearchBoostTester", "Test #531 checking search results for apricot fig coconut with boost=true");
//Test #532 checking search results for peach blueberry coconut tomato lime with boost=true
yourResult = tester.search("peach blueberry coconut tomato lime", true, 25);
TestingTools.checkSearch(yourResult, "peach blueberry coconut tomato lime", passOut, failOut, "Fruits25SearchBoostTester", "Test #532 checking search results for peach blueberry coconut tomato lime with boost=true");
//Test #533 checking search results for coconut banana with boost=true
yourResult = tester.search("coconut banana", true, 25);
TestingTools.checkSearch(yourResult, "coconut banana", passOut, failOut, "Fruits25SearchBoostTester", "Test #533 checking search results for coconut banana with boost=true");
failOut.close();
passOut.close();
}
}
