import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.*;
public class Fruits100SearchBoostTester {public static void main(String[] args) throws Exception{
ProjectTester tester = new ProjectTesterImp(); //Instantiate your own ProjectTester instance here
tester.initialize();
tester.crawl("https://people.scs.carleton.ca/~avamckenney/fruits100/N-0.html");
runTest(tester);}public static void runTest(ProjectTester tester) throws Exception{
PrintWriter failOut = new PrintWriter(new FileWriter("Fruits100-SearchBoost-failed.txt"));
PrintWriter passOut = new PrintWriter(new FileWriter("Fruits100-SearchBoost-passed.txt"));
List<SearchResult> yourResult; 
//Test #559 checking search results for apple apricot banana with boost=true
yourResult = tester.search("apple apricot banana", true, 100);
TestingTools.checkSearch(yourResult, "apple apricot banana", passOut, failOut, "Fruits100SearchBoostTester", "Test #559 checking search results for apple apricot banana with boost=true");
//Test #560 checking search results for peach with boost=true
yourResult = tester.search("peach", true, 100);
TestingTools.checkSearch(yourResult, "peach", passOut, failOut, "Fruits100SearchBoostTester", "Test #560 checking search results for peach with boost=true");
//Test #561 checking search results for pear fig with boost=true
yourResult = tester.search("pear fig", true, 100);
TestingTools.checkSearch(yourResult, "pear fig", passOut, failOut, "Fruits100SearchBoostTester", "Test #561 checking search results for pear fig with boost=true");
//Test #562 checking search results for apple kiwi apple blueberry with boost=true
yourResult = tester.search("apple kiwi apple blueberry", true, 100);
TestingTools.checkSearch(yourResult, "apple kiwi apple blueberry", passOut, failOut, "Fruits100SearchBoostTester", "Test #562 checking search results for apple kiwi apple blueberry with boost=true");
//Test #563 checking search results for kiwi peach with boost=true
yourResult = tester.search("kiwi peach", true, 100);
TestingTools.checkSearch(yourResult, "kiwi peach", passOut, failOut, "Fruits100SearchBoostTester", "Test #563 checking search results for kiwi peach with boost=true");
//Test #564 checking search results for banana strawberry with boost=true
yourResult = tester.search("banana strawberry", true, 100);
TestingTools.checkSearch(yourResult, "banana strawberry", passOut, failOut, "Fruits100SearchBoostTester", "Test #564 checking search results for banana strawberry with boost=true");
//Test #565 checking search results for cherry apricot with boost=true
yourResult = tester.search("cherry apricot", true, 100);
TestingTools.checkSearch(yourResult, "cherry apricot", passOut, failOut, "Fruits100SearchBoostTester", "Test #565 checking search results for cherry apricot with boost=true");
//Test #566 checking search results for blueberry kiwi papaya with boost=true
yourResult = tester.search("blueberry kiwi papaya", true, 100);
TestingTools.checkSearch(yourResult, "blueberry kiwi papaya", passOut, failOut, "Fruits100SearchBoostTester", "Test #566 checking search results for blueberry kiwi papaya with boost=true");
//Test #567 checking search results for strawberry fig lime banana lime with boost=true
yourResult = tester.search("strawberry fig lime banana lime", true, 100);
TestingTools.checkSearch(yourResult, "strawberry fig lime banana lime", passOut, failOut, "Fruits100SearchBoostTester", "Test #567 checking search results for strawberry fig lime banana lime with boost=true");
//Test #568 checking search results for blueberry kiwi fig apple with boost=true
yourResult = tester.search("blueberry kiwi fig apple", true, 100);
TestingTools.checkSearch(yourResult, "blueberry kiwi fig apple", passOut, failOut, "Fruits100SearchBoostTester", "Test #568 checking search results for blueberry kiwi fig apple with boost=true");
//Test #569 checking search results for tomato tomato tomato papaya with boost=true
yourResult = tester.search("tomato tomato tomato papaya", true, 100);
TestingTools.checkSearch(yourResult, "tomato tomato tomato papaya", passOut, failOut, "Fruits100SearchBoostTester", "Test #569 checking search results for tomato tomato tomato papaya with boost=true");
//Test #570 checking search results for lime kiwi cherry with boost=true
yourResult = tester.search("lime kiwi cherry", true, 100);
TestingTools.checkSearch(yourResult, "lime kiwi cherry", passOut, failOut, "Fruits100SearchBoostTester", "Test #570 checking search results for lime kiwi cherry with boost=true");
//Test #571 checking search results for blueberry with boost=true
yourResult = tester.search("blueberry", true, 100);
TestingTools.checkSearch(yourResult, "blueberry", passOut, failOut, "Fruits100SearchBoostTester", "Test #571 checking search results for blueberry with boost=true");
//Test #572 checking search results for peach fig banana apricot strawberry with boost=true
yourResult = tester.search("peach fig banana apricot strawberry", true, 100);
TestingTools.checkSearch(yourResult, "peach fig banana apricot strawberry", passOut, failOut, "Fruits100SearchBoostTester", "Test #572 checking search results for peach fig banana apricot strawberry with boost=true");
//Test #573 checking search results for fig blueberry papaya apricot papaya with boost=true
yourResult = tester.search("fig blueberry papaya apricot papaya", true, 100);
TestingTools.checkSearch(yourResult, "fig blueberry papaya apricot papaya", passOut, failOut, "Fruits100SearchBoostTester", "Test #573 checking search results for fig blueberry papaya apricot papaya with boost=true");
//Test #574 checking search results for blueberry kiwi apple with boost=true
yourResult = tester.search("blueberry kiwi apple", true, 100);
TestingTools.checkSearch(yourResult, "blueberry kiwi apple", passOut, failOut, "Fruits100SearchBoostTester", "Test #574 checking search results for blueberry kiwi apple with boost=true");
//Test #575 checking search results for strawberry strawberry with boost=true
yourResult = tester.search("strawberry strawberry", true, 100);
TestingTools.checkSearch(yourResult, "strawberry strawberry", passOut, failOut, "Fruits100SearchBoostTester", "Test #575 checking search results for strawberry strawberry with boost=true");
//Test #576 checking search results for peach fig strawberry with boost=true
yourResult = tester.search("peach fig strawberry", true, 100);
TestingTools.checkSearch(yourResult, "peach fig strawberry", passOut, failOut, "Fruits100SearchBoostTester", "Test #576 checking search results for peach fig strawberry with boost=true");
//Test #577 checking search results for kiwi blueberry fig with boost=true
yourResult = tester.search("kiwi blueberry fig", true, 100);
TestingTools.checkSearch(yourResult, "kiwi blueberry fig", passOut, failOut, "Fruits100SearchBoostTester", "Test #577 checking search results for kiwi blueberry fig with boost=true");
//Test #578 checking search results for fig with boost=true
yourResult = tester.search("fig", true, 100);
TestingTools.checkSearch(yourResult, "fig", passOut, failOut, "Fruits100SearchBoostTester", "Test #578 checking search results for fig with boost=true");
//Test #579 checking search results for pear pear apricot peach with boost=true
yourResult = tester.search("pear pear apricot peach", true, 100);
TestingTools.checkSearch(yourResult, "pear pear apricot peach", passOut, failOut, "Fruits100SearchBoostTester", "Test #579 checking search results for pear pear apricot peach with boost=true");
//Test #580 checking search results for banana coconut coconut with boost=true
yourResult = tester.search("banana coconut coconut", true, 100);
TestingTools.checkSearch(yourResult, "banana coconut coconut", passOut, failOut, "Fruits100SearchBoostTester", "Test #580 checking search results for banana coconut coconut with boost=true");
//Test #581 checking search results for banana banana tomato strawberry with boost=true
yourResult = tester.search("banana banana tomato strawberry", true, 100);
TestingTools.checkSearch(yourResult, "banana banana tomato strawberry", passOut, failOut, "Fruits100SearchBoostTester", "Test #581 checking search results for banana banana tomato strawberry with boost=true");
//Test #582 checking search results for coconut blueberry lime strawberry coconut with boost=true
yourResult = tester.search("coconut blueberry lime strawberry coconut", true, 100);
TestingTools.checkSearch(yourResult, "coconut blueberry lime strawberry coconut", passOut, failOut, "Fruits100SearchBoostTester", "Test #582 checking search results for coconut blueberry lime strawberry coconut with boost=true");
//Test #583 checking search results for apple with boost=true
yourResult = tester.search("apple", true, 100);
TestingTools.checkSearch(yourResult, "apple", passOut, failOut, "Fruits100SearchBoostTester", "Test #583 checking search results for apple with boost=true");
//Test #584 checking search results for strawberry apricot apple peach coconut with boost=true
yourResult = tester.search("strawberry apricot apple peach coconut", true, 100);
TestingTools.checkSearch(yourResult, "strawberry apricot apple peach coconut", passOut, failOut, "Fruits100SearchBoostTester", "Test #584 checking search results for strawberry apricot apple peach coconut with boost=true");
//Test #585 checking search results for banana fig banana with boost=true
yourResult = tester.search("banana fig banana", true, 100);
TestingTools.checkSearch(yourResult, "banana fig banana", passOut, failOut, "Fruits100SearchBoostTester", "Test #585 checking search results for banana fig banana with boost=true");
//Test #586 checking search results for apple apricot apple pear with boost=true
yourResult = tester.search("apple apricot apple pear", true, 100);
TestingTools.checkSearch(yourResult, "apple apricot apple pear", passOut, failOut, "Fruits100SearchBoostTester", "Test #586 checking search results for apple apricot apple pear with boost=true");
//Test #587 checking search results for apricot papaya kiwi kiwi banana with boost=true
yourResult = tester.search("apricot papaya kiwi kiwi banana", true, 100);
TestingTools.checkSearch(yourResult, "apricot papaya kiwi kiwi banana", passOut, failOut, "Fruits100SearchBoostTester", "Test #587 checking search results for apricot papaya kiwi kiwi banana with boost=true");
//Test #588 checking search results for coconut tomato strawberry blueberry with boost=true
yourResult = tester.search("coconut tomato strawberry blueberry", true, 100);
TestingTools.checkSearch(yourResult, "coconut tomato strawberry blueberry", passOut, failOut, "Fruits100SearchBoostTester", "Test #588 checking search results for coconut tomato strawberry blueberry with boost=true");
//Test #589 checking search results for fig blueberry with boost=true
yourResult = tester.search("fig blueberry", true, 100);
TestingTools.checkSearch(yourResult, "fig blueberry", passOut, failOut, "Fruits100SearchBoostTester", "Test #589 checking search results for fig blueberry with boost=true");
//Test #590 checking search results for blueberry lime coconut with boost=true
yourResult = tester.search("blueberry lime coconut", true, 100);
TestingTools.checkSearch(yourResult, "blueberry lime coconut", passOut, failOut, "Fruits100SearchBoostTester", "Test #590 checking search results for blueberry lime coconut with boost=true");
//Test #591 checking search results for apple apple strawberry apple with boost=true
yourResult = tester.search("apple apple strawberry apple", true, 100);
TestingTools.checkSearch(yourResult, "apple apple strawberry apple", passOut, failOut, "Fruits100SearchBoostTester", "Test #591 checking search results for apple apple strawberry apple with boost=true");
//Test #592 checking search results for strawberry papaya apricot with boost=true
yourResult = tester.search("strawberry papaya apricot", true, 100);
TestingTools.checkSearch(yourResult, "strawberry papaya apricot", passOut, failOut, "Fruits100SearchBoostTester", "Test #592 checking search results for strawberry papaya apricot with boost=true");
//Test #593 checking search results for apple fig with boost=true
yourResult = tester.search("apple fig", true, 100);
TestingTools.checkSearch(yourResult, "apple fig", passOut, failOut, "Fruits100SearchBoostTester", "Test #593 checking search results for apple fig with boost=true");
//Test #594 checking search results for papaya kiwi with boost=true
yourResult = tester.search("papaya kiwi", true, 100);
TestingTools.checkSearch(yourResult, "papaya kiwi", passOut, failOut, "Fruits100SearchBoostTester", "Test #594 checking search results for papaya kiwi with boost=true");
//Test #595 checking search results for apple tomato with boost=true
yourResult = tester.search("apple tomato", true, 100);
TestingTools.checkSearch(yourResult, "apple tomato", passOut, failOut, "Fruits100SearchBoostTester", "Test #595 checking search results for apple tomato with boost=true");
//Test #596 checking search results for blueberry lime blueberry with boost=true
yourResult = tester.search("blueberry lime blueberry", true, 100);
TestingTools.checkSearch(yourResult, "blueberry lime blueberry", passOut, failOut, "Fruits100SearchBoostTester", "Test #596 checking search results for blueberry lime blueberry with boost=true");
//Test #597 checking search results for lime with boost=true
yourResult = tester.search("lime", true, 100);
TestingTools.checkSearch(yourResult, "lime", passOut, failOut, "Fruits100SearchBoostTester", "Test #597 checking search results for lime with boost=true");
//Test #598 checking search results for papaya with boost=true
yourResult = tester.search("papaya", true, 100);
TestingTools.checkSearch(yourResult, "papaya", passOut, failOut, "Fruits100SearchBoostTester", "Test #598 checking search results for papaya with boost=true");
//Test #599 checking search results for kiwi fig peach with boost=true
yourResult = tester.search("kiwi fig peach", true, 100);
TestingTools.checkSearch(yourResult, "kiwi fig peach", passOut, failOut, "Fruits100SearchBoostTester", "Test #599 checking search results for kiwi fig peach with boost=true");
//Test #600 checking search results for pear papaya cherry with boost=true
yourResult = tester.search("pear papaya cherry", true, 100);
TestingTools.checkSearch(yourResult, "pear papaya cherry", passOut, failOut, "Fruits100SearchBoostTester", "Test #600 checking search results for pear papaya cherry with boost=true");
//Test #601 checking search results for papaya banana strawberry pear peach with boost=true
yourResult = tester.search("papaya banana strawberry pear peach", true, 100);
TestingTools.checkSearch(yourResult, "papaya banana strawberry pear peach", passOut, failOut, "Fruits100SearchBoostTester", "Test #601 checking search results for papaya banana strawberry pear peach with boost=true");
//Test #602 checking search results for kiwi cherry apple papaya coconut with boost=true
yourResult = tester.search("kiwi cherry apple papaya coconut", true, 100);
TestingTools.checkSearch(yourResult, "kiwi cherry apple papaya coconut", passOut, failOut, "Fruits100SearchBoostTester", "Test #602 checking search results for kiwi cherry apple papaya coconut with boost=true");
//Test #603 checking search results for apple with boost=true
yourResult = tester.search("apple", true, 100);
TestingTools.checkSearch(yourResult, "apple", passOut, failOut, "Fruits100SearchBoostTester", "Test #603 checking search results for apple with boost=true");
//Test #604 checking search results for pear apple papaya banana with boost=true
yourResult = tester.search("pear apple papaya banana", true, 100);
TestingTools.checkSearch(yourResult, "pear apple papaya banana", passOut, failOut, "Fruits100SearchBoostTester", "Test #604 checking search results for pear apple papaya banana with boost=true");
//Test #605 checking search results for fig kiwi tomato with boost=true
yourResult = tester.search("fig kiwi tomato", true, 100);
TestingTools.checkSearch(yourResult, "fig kiwi tomato", passOut, failOut, "Fruits100SearchBoostTester", "Test #605 checking search results for fig kiwi tomato with boost=true");
//Test #606 checking search results for lime with boost=true
yourResult = tester.search("lime", true, 100);
TestingTools.checkSearch(yourResult, "lime", passOut, failOut, "Fruits100SearchBoostTester", "Test #606 checking search results for lime with boost=true");
//Test #607 checking search results for apricot banana blueberry with boost=true
yourResult = tester.search("apricot banana blueberry", true, 100);
TestingTools.checkSearch(yourResult, "apricot banana blueberry", passOut, failOut, "Fruits100SearchBoostTester", "Test #607 checking search results for apricot banana blueberry with boost=true");
//Test #608 checking search results for pear peach kiwi with boost=true
yourResult = tester.search("pear peach kiwi", true, 100);
TestingTools.checkSearch(yourResult, "pear peach kiwi", passOut, failOut, "Fruits100SearchBoostTester", "Test #608 checking search results for pear peach kiwi with boost=true");
//Test #609 checking search results for banana fig lime with boost=true
yourResult = tester.search("banana fig lime", true, 100);
TestingTools.checkSearch(yourResult, "banana fig lime", passOut, failOut, "Fruits100SearchBoostTester", "Test #609 checking search results for banana fig lime with boost=true");
//Test #610 checking search results for coconut apple apricot lime apricot with boost=true
yourResult = tester.search("coconut apple apricot lime apricot", true, 100);
TestingTools.checkSearch(yourResult, "coconut apple apricot lime apricot", passOut, failOut, "Fruits100SearchBoostTester", "Test #610 checking search results for coconut apple apricot lime apricot with boost=true");
//Test #611 checking search results for peach papaya fig kiwi kiwi with boost=true
yourResult = tester.search("peach papaya fig kiwi kiwi", true, 100);
TestingTools.checkSearch(yourResult, "peach papaya fig kiwi kiwi", passOut, failOut, "Fruits100SearchBoostTester", "Test #611 checking search results for peach papaya fig kiwi kiwi with boost=true");
//Test #612 checking search results for apricot pear apricot fig blueberry with boost=true
yourResult = tester.search("apricot pear apricot fig blueberry", true, 100);
TestingTools.checkSearch(yourResult, "apricot pear apricot fig blueberry", passOut, failOut, "Fruits100SearchBoostTester", "Test #612 checking search results for apricot pear apricot fig blueberry with boost=true");
//Test #613 checking search results for fig banana peach banana with boost=true
yourResult = tester.search("fig banana peach banana", true, 100);
TestingTools.checkSearch(yourResult, "fig banana peach banana", passOut, failOut, "Fruits100SearchBoostTester", "Test #613 checking search results for fig banana peach banana with boost=true");
//Test #614 checking search results for cherry apple coconut with boost=true
yourResult = tester.search("cherry apple coconut", true, 100);
TestingTools.checkSearch(yourResult, "cherry apple coconut", passOut, failOut, "Fruits100SearchBoostTester", "Test #614 checking search results for cherry apple coconut with boost=true");
//Test #615 checking search results for fig cherry with boost=true
yourResult = tester.search("fig cherry", true, 100);
TestingTools.checkSearch(yourResult, "fig cherry", passOut, failOut, "Fruits100SearchBoostTester", "Test #615 checking search results for fig cherry with boost=true");
//Test #616 checking search results for cherry strawberry with boost=true
yourResult = tester.search("cherry strawberry", true, 100);
TestingTools.checkSearch(yourResult, "cherry strawberry", passOut, failOut, "Fruits100SearchBoostTester", "Test #616 checking search results for cherry strawberry with boost=true");
//Test #617 checking search results for pear apple lime with boost=true
yourResult = tester.search("pear apple lime", true, 100);
TestingTools.checkSearch(yourResult, "pear apple lime", passOut, failOut, "Fruits100SearchBoostTester", "Test #617 checking search results for pear apple lime with boost=true");
//Test #618 checking search results for papaya cherry peach banana with boost=true
yourResult = tester.search("papaya cherry peach banana", true, 100);
TestingTools.checkSearch(yourResult, "papaya cherry peach banana", passOut, failOut, "Fruits100SearchBoostTester", "Test #618 checking search results for papaya cherry peach banana with boost=true");
//Test #619 checking search results for kiwi banana with boost=true
yourResult = tester.search("kiwi banana", true, 100);
TestingTools.checkSearch(yourResult, "kiwi banana", passOut, failOut, "Fruits100SearchBoostTester", "Test #619 checking search results for kiwi banana with boost=true");
//Test #620 checking search results for peach blueberry kiwi with boost=true
yourResult = tester.search("peach blueberry kiwi", true, 100);
TestingTools.checkSearch(yourResult, "peach blueberry kiwi", passOut, failOut, "Fruits100SearchBoostTester", "Test #620 checking search results for peach blueberry kiwi with boost=true");
//Test #621 checking search results for tomato apricot kiwi peach papaya with boost=true
yourResult = tester.search("tomato apricot kiwi peach papaya", true, 100);
TestingTools.checkSearch(yourResult, "tomato apricot kiwi peach papaya", passOut, failOut, "Fruits100SearchBoostTester", "Test #621 checking search results for tomato apricot kiwi peach papaya with boost=true");
//Test #622 checking search results for apricot peach blueberry apricot pear with boost=true
yourResult = tester.search("apricot peach blueberry apricot pear", true, 100);
TestingTools.checkSearch(yourResult, "apricot peach blueberry apricot pear", passOut, failOut, "Fruits100SearchBoostTester", "Test #622 checking search results for apricot peach blueberry apricot pear with boost=true");
//Test #623 checking search results for banana fig cherry strawberry with boost=true
yourResult = tester.search("banana fig cherry strawberry", true, 100);
TestingTools.checkSearch(yourResult, "banana fig cherry strawberry", passOut, failOut, "Fruits100SearchBoostTester", "Test #623 checking search results for banana fig cherry strawberry with boost=true");
//Test #624 checking search results for peach blueberry kiwi with boost=true
yourResult = tester.search("peach blueberry kiwi", true, 100);
TestingTools.checkSearch(yourResult, "peach blueberry kiwi", passOut, failOut, "Fruits100SearchBoostTester", "Test #624 checking search results for peach blueberry kiwi with boost=true");
//Test #625 checking search results for tomato kiwi peach with boost=true
yourResult = tester.search("tomato kiwi peach", true, 100);
TestingTools.checkSearch(yourResult, "tomato kiwi peach", passOut, failOut, "Fruits100SearchBoostTester", "Test #625 checking search results for tomato kiwi peach with boost=true");
//Test #626 checking search results for lime papaya tomato tomato with boost=true
yourResult = tester.search("lime papaya tomato tomato", true, 100);
TestingTools.checkSearch(yourResult, "lime papaya tomato tomato", passOut, failOut, "Fruits100SearchBoostTester", "Test #626 checking search results for lime papaya tomato tomato with boost=true");
//Test #627 checking search results for coconut lime with boost=true
yourResult = tester.search("coconut lime", true, 100);
TestingTools.checkSearch(yourResult, "coconut lime", passOut, failOut, "Fruits100SearchBoostTester", "Test #627 checking search results for coconut lime with boost=true");
//Test #628 checking search results for banana banana apricot apricot with boost=true
yourResult = tester.search("banana banana apricot apricot", true, 100);
TestingTools.checkSearch(yourResult, "banana banana apricot apricot", passOut, failOut, "Fruits100SearchBoostTester", "Test #628 checking search results for banana banana apricot apricot with boost=true");
//Test #629 checking search results for cherry strawberry with boost=true
yourResult = tester.search("cherry strawberry", true, 100);
TestingTools.checkSearch(yourResult, "cherry strawberry", passOut, failOut, "Fruits100SearchBoostTester", "Test #629 checking search results for cherry strawberry with boost=true");
//Test #630 checking search results for blueberry lime blueberry peach with boost=true
yourResult = tester.search("blueberry lime blueberry peach", true, 100);
TestingTools.checkSearch(yourResult, "blueberry lime blueberry peach", passOut, failOut, "Fruits100SearchBoostTester", "Test #630 checking search results for blueberry lime blueberry peach with boost=true");
//Test #631 checking search results for lime with boost=true
yourResult = tester.search("lime", true, 100);
TestingTools.checkSearch(yourResult, "lime", passOut, failOut, "Fruits100SearchBoostTester", "Test #631 checking search results for lime with boost=true");
//Test #632 checking search results for peach banana strawberry apple coconut with boost=true
yourResult = tester.search("peach banana strawberry apple coconut", true, 100);
TestingTools.checkSearch(yourResult, "peach banana strawberry apple coconut", passOut, failOut, "Fruits100SearchBoostTester", "Test #632 checking search results for peach banana strawberry apple coconut with boost=true");
//Test #633 checking search results for apple apricot pear fig pear with boost=true
yourResult = tester.search("apple apricot pear fig pear", true, 100);
TestingTools.checkSearch(yourResult, "apple apricot pear fig pear", passOut, failOut, "Fruits100SearchBoostTester", "Test #633 checking search results for apple apricot pear fig pear with boost=true");
//Test #634 checking search results for fig pear with boost=true
yourResult = tester.search("fig pear", true, 100);
TestingTools.checkSearch(yourResult, "fig pear", passOut, failOut, "Fruits100SearchBoostTester", "Test #634 checking search results for fig pear with boost=true");
//Test #635 checking search results for strawberry kiwi coconut apple with boost=true
yourResult = tester.search("strawberry kiwi coconut apple", true, 100);
TestingTools.checkSearch(yourResult, "strawberry kiwi coconut apple", passOut, failOut, "Fruits100SearchBoostTester", "Test #635 checking search results for strawberry kiwi coconut apple with boost=true");
//Test #636 checking search results for coconut strawberry cherry kiwi with boost=true
yourResult = tester.search("coconut strawberry cherry kiwi", true, 100);
TestingTools.checkSearch(yourResult, "coconut strawberry cherry kiwi", passOut, failOut, "Fruits100SearchBoostTester", "Test #636 checking search results for coconut strawberry cherry kiwi with boost=true");
//Test #637 checking search results for papaya with boost=true
yourResult = tester.search("papaya", true, 100);
TestingTools.checkSearch(yourResult, "papaya", passOut, failOut, "Fruits100SearchBoostTester", "Test #637 checking search results for papaya with boost=true");
//Test #638 checking search results for peach blueberry with boost=true
yourResult = tester.search("peach blueberry", true, 100);
TestingTools.checkSearch(yourResult, "peach blueberry", passOut, failOut, "Fruits100SearchBoostTester", "Test #638 checking search results for peach blueberry with boost=true");
//Test #639 checking search results for apple coconut with boost=true
yourResult = tester.search("apple coconut", true, 100);
TestingTools.checkSearch(yourResult, "apple coconut", passOut, failOut, "Fruits100SearchBoostTester", "Test #639 checking search results for apple coconut with boost=true");
//Test #640 checking search results for papaya banana apricot tomato apricot with boost=true
yourResult = tester.search("papaya banana apricot tomato apricot", true, 100);
TestingTools.checkSearch(yourResult, "papaya banana apricot tomato apricot", passOut, failOut, "Fruits100SearchBoostTester", "Test #640 checking search results for papaya banana apricot tomato apricot with boost=true");
//Test #641 checking search results for apple lime coconut fig with boost=true
yourResult = tester.search("apple lime coconut fig", true, 100);
TestingTools.checkSearch(yourResult, "apple lime coconut fig", passOut, failOut, "Fruits100SearchBoostTester", "Test #641 checking search results for apple lime coconut fig with boost=true");
//Test #642 checking search results for papaya with boost=true
yourResult = tester.search("papaya", true, 100);
TestingTools.checkSearch(yourResult, "papaya", passOut, failOut, "Fruits100SearchBoostTester", "Test #642 checking search results for papaya with boost=true");
//Test #643 checking search results for pear apricot with boost=true
yourResult = tester.search("pear apricot", true, 100);
TestingTools.checkSearch(yourResult, "pear apricot", passOut, failOut, "Fruits100SearchBoostTester", "Test #643 checking search results for pear apricot with boost=true");
//Test #644 checking search results for tomato lime strawberry with boost=true
yourResult = tester.search("tomato lime strawberry", true, 100);
TestingTools.checkSearch(yourResult, "tomato lime strawberry", passOut, failOut, "Fruits100SearchBoostTester", "Test #644 checking search results for tomato lime strawberry with boost=true");
//Test #645 checking search results for papaya kiwi lime with boost=true
yourResult = tester.search("papaya kiwi lime", true, 100);
TestingTools.checkSearch(yourResult, "papaya kiwi lime", passOut, failOut, "Fruits100SearchBoostTester", "Test #645 checking search results for papaya kiwi lime with boost=true");
//Test #646 checking search results for fig with boost=true
yourResult = tester.search("fig", true, 100);
TestingTools.checkSearch(yourResult, "fig", passOut, failOut, "Fruits100SearchBoostTester", "Test #646 checking search results for fig with boost=true");
//Test #647 checking search results for blueberry cherry with boost=true
yourResult = tester.search("blueberry cherry", true, 100);
TestingTools.checkSearch(yourResult, "blueberry cherry", passOut, failOut, "Fruits100SearchBoostTester", "Test #647 checking search results for blueberry cherry with boost=true");
//Test #648 checking search results for fig fig lime cherry with boost=true
yourResult = tester.search("fig fig lime cherry", true, 100);
TestingTools.checkSearch(yourResult, "fig fig lime cherry", passOut, failOut, "Fruits100SearchBoostTester", "Test #648 checking search results for fig fig lime cherry with boost=true");
//Test #649 checking search results for strawberry kiwi lime fig with boost=true
yourResult = tester.search("strawberry kiwi lime fig", true, 100);
TestingTools.checkSearch(yourResult, "strawberry kiwi lime fig", passOut, failOut, "Fruits100SearchBoostTester", "Test #649 checking search results for strawberry kiwi lime fig with boost=true");
//Test #650 checking search results for cherry cherry pear strawberry with boost=true
yourResult = tester.search("cherry cherry pear strawberry", true, 100);
TestingTools.checkSearch(yourResult, "cherry cherry pear strawberry", passOut, failOut, "Fruits100SearchBoostTester", "Test #650 checking search results for cherry cherry pear strawberry with boost=true");
//Test #651 checking search results for cherry cherry kiwi with boost=true
yourResult = tester.search("cherry cherry kiwi", true, 100);
TestingTools.checkSearch(yourResult, "cherry cherry kiwi", passOut, failOut, "Fruits100SearchBoostTester", "Test #651 checking search results for cherry cherry kiwi with boost=true");
//Test #652 checking search results for lime banana kiwi kiwi cherry with boost=true
yourResult = tester.search("lime banana kiwi kiwi cherry", true, 100);
TestingTools.checkSearch(yourResult, "lime banana kiwi kiwi cherry", passOut, failOut, "Fruits100SearchBoostTester", "Test #652 checking search results for lime banana kiwi kiwi cherry with boost=true");
//Test #653 checking search results for apricot with boost=true
yourResult = tester.search("apricot", true, 100);
TestingTools.checkSearch(yourResult, "apricot", passOut, failOut, "Fruits100SearchBoostTester", "Test #653 checking search results for apricot with boost=true");
//Test #654 checking search results for strawberry with boost=true
yourResult = tester.search("strawberry", true, 100);
TestingTools.checkSearch(yourResult, "strawberry", passOut, failOut, "Fruits100SearchBoostTester", "Test #654 checking search results for strawberry with boost=true");
//Test #655 checking search results for kiwi fig papaya blueberry coconut with boost=true
yourResult = tester.search("kiwi fig papaya blueberry coconut", true, 100);
TestingTools.checkSearch(yourResult, "kiwi fig papaya blueberry coconut", passOut, failOut, "Fruits100SearchBoostTester", "Test #655 checking search results for kiwi fig papaya blueberry coconut with boost=true");
//Test #656 checking search results for pear strawberry papaya cherry papaya with boost=true
yourResult = tester.search("pear strawberry papaya cherry papaya", true, 100);
TestingTools.checkSearch(yourResult, "pear strawberry papaya cherry papaya", passOut, failOut, "Fruits100SearchBoostTester", "Test #656 checking search results for pear strawberry papaya cherry papaya with boost=true");
//Test #657 checking search results for lime apricot blueberry with boost=true
yourResult = tester.search("lime apricot blueberry", true, 100);
TestingTools.checkSearch(yourResult, "lime apricot blueberry", passOut, failOut, "Fruits100SearchBoostTester", "Test #657 checking search results for lime apricot blueberry with boost=true");
//Test #658 checking search results for tomato kiwi apricot apricot with boost=true
yourResult = tester.search("tomato kiwi apricot apricot", true, 100);
TestingTools.checkSearch(yourResult, "tomato kiwi apricot apricot", passOut, failOut, "Fruits100SearchBoostTester", "Test #658 checking search results for tomato kiwi apricot apricot with boost=true");
failOut.close();
passOut.close();
}
}
