import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.*;
public class Fruits50SearchNoBoostTester {public static void main(String[] args) throws Exception{
ProjectTester tester = new ProjectTesterImp(); //Instantiate your own ProjectTester instance here
tester.initialize();
tester.crawl("https://people.scs.carleton.ca/~avamckenney/fruits50/N-0.html");
runTest(tester);}public static void runTest(ProjectTester tester) throws Exception{
PrintWriter failOut = new PrintWriter(new FileWriter("Fruits50-SearchNoBoost-failed.txt"));
PrintWriter passOut = new PrintWriter(new FileWriter("Fruits50-SearchNoBoost-passed.txt"));
List<SearchResult> yourResult; 
//Test #409 checking search results for strawberry with boost=false
yourResult = tester.search("strawberry", false, 50);
TestingTools.checkSearch(yourResult, "strawberry", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #409 checking search results for strawberry with boost=false");
//Test #410 checking search results for peach blueberry lime with boost=false
yourResult = tester.search("peach blueberry lime", false, 50);
TestingTools.checkSearch(yourResult, "peach blueberry lime", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #410 checking search results for peach blueberry lime with boost=false");
//Test #411 checking search results for apple apricot with boost=false
yourResult = tester.search("apple apricot", false, 50);
TestingTools.checkSearch(yourResult, "apple apricot", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #411 checking search results for apple apricot with boost=false");
//Test #412 checking search results for pear apricot with boost=false
yourResult = tester.search("pear apricot", false, 50);
TestingTools.checkSearch(yourResult, "pear apricot", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #412 checking search results for pear apricot with boost=false");
//Test #413 checking search results for coconut coconut tomato apple with boost=false
yourResult = tester.search("coconut coconut tomato apple", false, 50);
TestingTools.checkSearch(yourResult, "coconut coconut tomato apple", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #413 checking search results for coconut coconut tomato apple with boost=false");
//Test #414 checking search results for apricot with boost=false
yourResult = tester.search("apricot", false, 50);
TestingTools.checkSearch(yourResult, "apricot", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #414 checking search results for apricot with boost=false");
//Test #415 checking search results for blueberry apricot banana apricot fig with boost=false
yourResult = tester.search("blueberry apricot banana apricot fig", false, 50);
TestingTools.checkSearch(yourResult, "blueberry apricot banana apricot fig", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #415 checking search results for blueberry apricot banana apricot fig with boost=false");
//Test #416 checking search results for strawberry cherry tomato with boost=false
yourResult = tester.search("strawberry cherry tomato", false, 50);
TestingTools.checkSearch(yourResult, "strawberry cherry tomato", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #416 checking search results for strawberry cherry tomato with boost=false");
//Test #417 checking search results for apricot with boost=false
yourResult = tester.search("apricot", false, 50);
TestingTools.checkSearch(yourResult, "apricot", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #417 checking search results for apricot with boost=false");
//Test #418 checking search results for strawberry banana kiwi apricot apricot with boost=false
yourResult = tester.search("strawberry banana kiwi apricot apricot", false, 50);
TestingTools.checkSearch(yourResult, "strawberry banana kiwi apricot apricot", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #418 checking search results for strawberry banana kiwi apricot apricot with boost=false");
//Test #419 checking search results for papaya pear lime with boost=false
yourResult = tester.search("papaya pear lime", false, 50);
TestingTools.checkSearch(yourResult, "papaya pear lime", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #419 checking search results for papaya pear lime with boost=false");
//Test #420 checking search results for blueberry blueberry apple with boost=false
yourResult = tester.search("blueberry blueberry apple", false, 50);
TestingTools.checkSearch(yourResult, "blueberry blueberry apple", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #420 checking search results for blueberry blueberry apple with boost=false");
//Test #421 checking search results for apricot peach apple lime cherry with boost=false
yourResult = tester.search("apricot peach apple lime cherry", false, 50);
TestingTools.checkSearch(yourResult, "apricot peach apple lime cherry", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #421 checking search results for apricot peach apple lime cherry with boost=false");
//Test #422 checking search results for peach kiwi with boost=false
yourResult = tester.search("peach kiwi", false, 50);
TestingTools.checkSearch(yourResult, "peach kiwi", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #422 checking search results for peach kiwi with boost=false");
//Test #423 checking search results for apple with boost=false
yourResult = tester.search("apple", false, 50);
TestingTools.checkSearch(yourResult, "apple", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #423 checking search results for apple with boost=false");
//Test #424 checking search results for kiwi cherry papaya with boost=false
yourResult = tester.search("kiwi cherry papaya", false, 50);
TestingTools.checkSearch(yourResult, "kiwi cherry papaya", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #424 checking search results for kiwi cherry papaya with boost=false");
//Test #425 checking search results for strawberry cherry banana fig with boost=false
yourResult = tester.search("strawberry cherry banana fig", false, 50);
TestingTools.checkSearch(yourResult, "strawberry cherry banana fig", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #425 checking search results for strawberry cherry banana fig with boost=false");
//Test #426 checking search results for strawberry with boost=false
yourResult = tester.search("strawberry", false, 50);
TestingTools.checkSearch(yourResult, "strawberry", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #426 checking search results for strawberry with boost=false");
//Test #427 checking search results for apple apple papaya cherry peach with boost=false
yourResult = tester.search("apple apple papaya cherry peach", false, 50);
TestingTools.checkSearch(yourResult, "apple apple papaya cherry peach", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #427 checking search results for apple apple papaya cherry peach with boost=false");
//Test #428 checking search results for papaya peach kiwi papaya with boost=false
yourResult = tester.search("papaya peach kiwi papaya", false, 50);
TestingTools.checkSearch(yourResult, "papaya peach kiwi papaya", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #428 checking search results for papaya peach kiwi papaya with boost=false");
//Test #429 checking search results for tomato strawberry peach apple lime with boost=false
yourResult = tester.search("tomato strawberry peach apple lime", false, 50);
TestingTools.checkSearch(yourResult, "tomato strawberry peach apple lime", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #429 checking search results for tomato strawberry peach apple lime with boost=false");
//Test #430 checking search results for kiwi with boost=false
yourResult = tester.search("kiwi", false, 50);
TestingTools.checkSearch(yourResult, "kiwi", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #430 checking search results for kiwi with boost=false");
//Test #431 checking search results for lime peach lime peach tomato with boost=false
yourResult = tester.search("lime peach lime peach tomato", false, 50);
TestingTools.checkSearch(yourResult, "lime peach lime peach tomato", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #431 checking search results for lime peach lime peach tomato with boost=false");
//Test #432 checking search results for kiwi apricot kiwi kiwi blueberry with boost=false
yourResult = tester.search("kiwi apricot kiwi kiwi blueberry", false, 50);
TestingTools.checkSearch(yourResult, "kiwi apricot kiwi kiwi blueberry", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #432 checking search results for kiwi apricot kiwi kiwi blueberry with boost=false");
//Test #433 checking search results for peach strawberry apricot banana with boost=false
yourResult = tester.search("peach strawberry apricot banana", false, 50);
TestingTools.checkSearch(yourResult, "peach strawberry apricot banana", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #433 checking search results for peach strawberry apricot banana with boost=false");
//Test #434 checking search results for fig papaya with boost=false
yourResult = tester.search("fig papaya", false, 50);
TestingTools.checkSearch(yourResult, "fig papaya", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #434 checking search results for fig papaya with boost=false");
//Test #435 checking search results for tomato papaya with boost=false
yourResult = tester.search("tomato papaya", false, 50);
TestingTools.checkSearch(yourResult, "tomato papaya", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #435 checking search results for tomato papaya with boost=false");
//Test #436 checking search results for apricot kiwi fig pear with boost=false
yourResult = tester.search("apricot kiwi fig pear", false, 50);
TestingTools.checkSearch(yourResult, "apricot kiwi fig pear", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #436 checking search results for apricot kiwi fig pear with boost=false");
//Test #437 checking search results for lime banana blueberry with boost=false
yourResult = tester.search("lime banana blueberry", false, 50);
TestingTools.checkSearch(yourResult, "lime banana blueberry", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #437 checking search results for lime banana blueberry with boost=false");
//Test #438 checking search results for blueberry with boost=false
yourResult = tester.search("blueberry", false, 50);
TestingTools.checkSearch(yourResult, "blueberry", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #438 checking search results for blueberry with boost=false");
//Test #439 checking search results for peach banana kiwi pear cherry with boost=false
yourResult = tester.search("peach banana kiwi pear cherry", false, 50);
TestingTools.checkSearch(yourResult, "peach banana kiwi pear cherry", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #439 checking search results for peach banana kiwi pear cherry with boost=false");
//Test #440 checking search results for pear blueberry apricot with boost=false
yourResult = tester.search("pear blueberry apricot", false, 50);
TestingTools.checkSearch(yourResult, "pear blueberry apricot", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #440 checking search results for pear blueberry apricot with boost=false");
//Test #441 checking search results for lime banana apricot with boost=false
yourResult = tester.search("lime banana apricot", false, 50);
TestingTools.checkSearch(yourResult, "lime banana apricot", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #441 checking search results for lime banana apricot with boost=false");
//Test #442 checking search results for blueberry kiwi apple tomato with boost=false
yourResult = tester.search("blueberry kiwi apple tomato", false, 50);
TestingTools.checkSearch(yourResult, "blueberry kiwi apple tomato", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #442 checking search results for blueberry kiwi apple tomato with boost=false");
//Test #443 checking search results for cherry cherry blueberry with boost=false
yourResult = tester.search("cherry cherry blueberry", false, 50);
TestingTools.checkSearch(yourResult, "cherry cherry blueberry", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #443 checking search results for cherry cherry blueberry with boost=false");
//Test #444 checking search results for strawberry tomato coconut with boost=false
yourResult = tester.search("strawberry tomato coconut", false, 50);
TestingTools.checkSearch(yourResult, "strawberry tomato coconut", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #444 checking search results for strawberry tomato coconut with boost=false");
//Test #445 checking search results for cherry apricot blueberry blueberry with boost=false
yourResult = tester.search("cherry apricot blueberry blueberry", false, 50);
TestingTools.checkSearch(yourResult, "cherry apricot blueberry blueberry", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #445 checking search results for cherry apricot blueberry blueberry with boost=false");
//Test #446 checking search results for blueberry kiwi cherry with boost=false
yourResult = tester.search("blueberry kiwi cherry", false, 50);
TestingTools.checkSearch(yourResult, "blueberry kiwi cherry", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #446 checking search results for blueberry kiwi cherry with boost=false");
//Test #447 checking search results for banana cherry coconut with boost=false
yourResult = tester.search("banana cherry coconut", false, 50);
TestingTools.checkSearch(yourResult, "banana cherry coconut", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #447 checking search results for banana cherry coconut with boost=false");
//Test #448 checking search results for apricot lime with boost=false
yourResult = tester.search("apricot lime", false, 50);
TestingTools.checkSearch(yourResult, "apricot lime", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #448 checking search results for apricot lime with boost=false");
//Test #449 checking search results for apricot with boost=false
yourResult = tester.search("apricot", false, 50);
TestingTools.checkSearch(yourResult, "apricot", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #449 checking search results for apricot with boost=false");
//Test #450 checking search results for cherry papaya strawberry with boost=false
yourResult = tester.search("cherry papaya strawberry", false, 50);
TestingTools.checkSearch(yourResult, "cherry papaya strawberry", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #450 checking search results for cherry papaya strawberry with boost=false");
//Test #451 checking search results for apple apricot peach tomato blueberry with boost=false
yourResult = tester.search("apple apricot peach tomato blueberry", false, 50);
TestingTools.checkSearch(yourResult, "apple apricot peach tomato blueberry", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #451 checking search results for apple apricot peach tomato blueberry with boost=false");
//Test #452 checking search results for banana tomato cherry with boost=false
yourResult = tester.search("banana tomato cherry", false, 50);
TestingTools.checkSearch(yourResult, "banana tomato cherry", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #452 checking search results for banana tomato cherry with boost=false");
//Test #453 checking search results for coconut pear fig banana cherry with boost=false
yourResult = tester.search("coconut pear fig banana cherry", false, 50);
TestingTools.checkSearch(yourResult, "coconut pear fig banana cherry", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #453 checking search results for coconut pear fig banana cherry with boost=false");
//Test #454 checking search results for lime tomato apple with boost=false
yourResult = tester.search("lime tomato apple", false, 50);
TestingTools.checkSearch(yourResult, "lime tomato apple", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #454 checking search results for lime tomato apple with boost=false");
//Test #455 checking search results for lime apple banana with boost=false
yourResult = tester.search("lime apple banana", false, 50);
TestingTools.checkSearch(yourResult, "lime apple banana", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #455 checking search results for lime apple banana with boost=false");
//Test #456 checking search results for blueberry apricot lime pear with boost=false
yourResult = tester.search("blueberry apricot lime pear", false, 50);
TestingTools.checkSearch(yourResult, "blueberry apricot lime pear", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #456 checking search results for blueberry apricot lime pear with boost=false");
//Test #457 checking search results for apricot with boost=false
yourResult = tester.search("apricot", false, 50);
TestingTools.checkSearch(yourResult, "apricot", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #457 checking search results for apricot with boost=false");
//Test #458 checking search results for lime lime apple with boost=false
yourResult = tester.search("lime lime apple", false, 50);
TestingTools.checkSearch(yourResult, "lime lime apple", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #458 checking search results for lime lime apple with boost=false");
//Test #459 checking search results for cherry kiwi peach blueberry papaya with boost=false
yourResult = tester.search("cherry kiwi peach blueberry papaya", false, 50);
TestingTools.checkSearch(yourResult, "cherry kiwi peach blueberry papaya", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #459 checking search results for cherry kiwi peach blueberry papaya with boost=false");
//Test #460 checking search results for tomato pear with boost=false
yourResult = tester.search("tomato pear", false, 50);
TestingTools.checkSearch(yourResult, "tomato pear", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #460 checking search results for tomato pear with boost=false");
//Test #461 checking search results for cherry apricot cherry with boost=false
yourResult = tester.search("cherry apricot cherry", false, 50);
TestingTools.checkSearch(yourResult, "cherry apricot cherry", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #461 checking search results for cherry apricot cherry with boost=false");
//Test #462 checking search results for apple with boost=false
yourResult = tester.search("apple", false, 50);
TestingTools.checkSearch(yourResult, "apple", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #462 checking search results for apple with boost=false");
//Test #463 checking search results for peach coconut peach coconut banana with boost=false
yourResult = tester.search("peach coconut peach coconut banana", false, 50);
TestingTools.checkSearch(yourResult, "peach coconut peach coconut banana", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #463 checking search results for peach coconut peach coconut banana with boost=false");
//Test #464 checking search results for cherry cherry peach tomato with boost=false
yourResult = tester.search("cherry cherry peach tomato", false, 50);
TestingTools.checkSearch(yourResult, "cherry cherry peach tomato", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #464 checking search results for cherry cherry peach tomato with boost=false");
//Test #465 checking search results for banana coconut fig with boost=false
yourResult = tester.search("banana coconut fig", false, 50);
TestingTools.checkSearch(yourResult, "banana coconut fig", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #465 checking search results for banana coconut fig with boost=false");
//Test #466 checking search results for coconut banana cherry cherry coconut with boost=false
yourResult = tester.search("coconut banana cherry cherry coconut", false, 50);
TestingTools.checkSearch(yourResult, "coconut banana cherry cherry coconut", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #466 checking search results for coconut banana cherry cherry coconut with boost=false");
//Test #467 checking search results for cherry with boost=false
yourResult = tester.search("cherry", false, 50);
TestingTools.checkSearch(yourResult, "cherry", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #467 checking search results for cherry with boost=false");
//Test #468 checking search results for apple with boost=false
yourResult = tester.search("apple", false, 50);
TestingTools.checkSearch(yourResult, "apple", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #468 checking search results for apple with boost=false");
//Test #469 checking search results for strawberry apple with boost=false
yourResult = tester.search("strawberry apple", false, 50);
TestingTools.checkSearch(yourResult, "strawberry apple", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #469 checking search results for strawberry apple with boost=false");
//Test #470 checking search results for strawberry peach apple papaya apple with boost=false
yourResult = tester.search("strawberry peach apple papaya apple", false, 50);
TestingTools.checkSearch(yourResult, "strawberry peach apple papaya apple", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #470 checking search results for strawberry peach apple papaya apple with boost=false");
//Test #471 checking search results for apricot fig cherry pear with boost=false
yourResult = tester.search("apricot fig cherry pear", false, 50);
TestingTools.checkSearch(yourResult, "apricot fig cherry pear", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #471 checking search results for apricot fig cherry pear with boost=false");
//Test #472 checking search results for strawberry with boost=false
yourResult = tester.search("strawberry", false, 50);
TestingTools.checkSearch(yourResult, "strawberry", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #472 checking search results for strawberry with boost=false");
//Test #473 checking search results for peach apricot kiwi apricot lime with boost=false
yourResult = tester.search("peach apricot kiwi apricot lime", false, 50);
TestingTools.checkSearch(yourResult, "peach apricot kiwi apricot lime", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #473 checking search results for peach apricot kiwi apricot lime with boost=false");
//Test #474 checking search results for kiwi apple with boost=false
yourResult = tester.search("kiwi apple", false, 50);
TestingTools.checkSearch(yourResult, "kiwi apple", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #474 checking search results for kiwi apple with boost=false");
//Test #475 checking search results for fig with boost=false
yourResult = tester.search("fig", false, 50);
TestingTools.checkSearch(yourResult, "fig", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #475 checking search results for fig with boost=false");
//Test #476 checking search results for strawberry banana apricot peach with boost=false
yourResult = tester.search("strawberry banana apricot peach", false, 50);
TestingTools.checkSearch(yourResult, "strawberry banana apricot peach", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #476 checking search results for strawberry banana apricot peach with boost=false");
//Test #477 checking search results for strawberry peach strawberry apricot strawberry with boost=false
yourResult = tester.search("strawberry peach strawberry apricot strawberry", false, 50);
TestingTools.checkSearch(yourResult, "strawberry peach strawberry apricot strawberry", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #477 checking search results for strawberry peach strawberry apricot strawberry with boost=false");
//Test #478 checking search results for blueberry apricot with boost=false
yourResult = tester.search("blueberry apricot", false, 50);
TestingTools.checkSearch(yourResult, "blueberry apricot", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #478 checking search results for blueberry apricot with boost=false");
//Test #479 checking search results for kiwi fig cherry peach pear with boost=false
yourResult = tester.search("kiwi fig cherry peach pear", false, 50);
TestingTools.checkSearch(yourResult, "kiwi fig cherry peach pear", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #479 checking search results for kiwi fig cherry peach pear with boost=false");
//Test #480 checking search results for cherry with boost=false
yourResult = tester.search("cherry", false, 50);
TestingTools.checkSearch(yourResult, "cherry", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #480 checking search results for cherry with boost=false");
//Test #481 checking search results for coconut with boost=false
yourResult = tester.search("coconut", false, 50);
TestingTools.checkSearch(yourResult, "coconut", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #481 checking search results for coconut with boost=false");
//Test #482 checking search results for coconut apple lime with boost=false
yourResult = tester.search("coconut apple lime", false, 50);
TestingTools.checkSearch(yourResult, "coconut apple lime", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #482 checking search results for coconut apple lime with boost=false");
//Test #483 checking search results for cherry apple apple apricot with boost=false
yourResult = tester.search("cherry apple apple apricot", false, 50);
TestingTools.checkSearch(yourResult, "cherry apple apple apricot", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #483 checking search results for cherry apple apple apricot with boost=false");
//Test #484 checking search results for strawberry strawberry apple cherry with boost=false
yourResult = tester.search("strawberry strawberry apple cherry", false, 50);
TestingTools.checkSearch(yourResult, "strawberry strawberry apple cherry", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #484 checking search results for strawberry strawberry apple cherry with boost=false");
//Test #485 checking search results for blueberry banana with boost=false
yourResult = tester.search("blueberry banana", false, 50);
TestingTools.checkSearch(yourResult, "blueberry banana", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #485 checking search results for blueberry banana with boost=false");
//Test #486 checking search results for coconut pear cherry tomato with boost=false
yourResult = tester.search("coconut pear cherry tomato", false, 50);
TestingTools.checkSearch(yourResult, "coconut pear cherry tomato", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #486 checking search results for coconut pear cherry tomato with boost=false");
//Test #487 checking search results for blueberry peach papaya with boost=false
yourResult = tester.search("blueberry peach papaya", false, 50);
TestingTools.checkSearch(yourResult, "blueberry peach papaya", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #487 checking search results for blueberry peach papaya with boost=false");
//Test #488 checking search results for tomato strawberry banana with boost=false
yourResult = tester.search("tomato strawberry banana", false, 50);
TestingTools.checkSearch(yourResult, "tomato strawberry banana", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #488 checking search results for tomato strawberry banana with boost=false");
//Test #489 checking search results for fig strawberry with boost=false
yourResult = tester.search("fig strawberry", false, 50);
TestingTools.checkSearch(yourResult, "fig strawberry", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #489 checking search results for fig strawberry with boost=false");
//Test #490 checking search results for coconut coconut with boost=false
yourResult = tester.search("coconut coconut", false, 50);
TestingTools.checkSearch(yourResult, "coconut coconut", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #490 checking search results for coconut coconut with boost=false");
//Test #491 checking search results for kiwi banana with boost=false
yourResult = tester.search("kiwi banana", false, 50);
TestingTools.checkSearch(yourResult, "kiwi banana", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #491 checking search results for kiwi banana with boost=false");
//Test #492 checking search results for coconut apricot with boost=false
yourResult = tester.search("coconut apricot", false, 50);
TestingTools.checkSearch(yourResult, "coconut apricot", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #492 checking search results for coconut apricot with boost=false");
//Test #493 checking search results for strawberry coconut with boost=false
yourResult = tester.search("strawberry coconut", false, 50);
TestingTools.checkSearch(yourResult, "strawberry coconut", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #493 checking search results for strawberry coconut with boost=false");
//Test #494 checking search results for banana fig with boost=false
yourResult = tester.search("banana fig", false, 50);
TestingTools.checkSearch(yourResult, "banana fig", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #494 checking search results for banana fig with boost=false");
//Test #495 checking search results for banana peach fig lime with boost=false
yourResult = tester.search("banana peach fig lime", false, 50);
TestingTools.checkSearch(yourResult, "banana peach fig lime", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #495 checking search results for banana peach fig lime with boost=false");
//Test #496 checking search results for kiwi with boost=false
yourResult = tester.search("kiwi", false, 50);
TestingTools.checkSearch(yourResult, "kiwi", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #496 checking search results for kiwi with boost=false");
//Test #497 checking search results for strawberry with boost=false
yourResult = tester.search("strawberry", false, 50);
TestingTools.checkSearch(yourResult, "strawberry", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #497 checking search results for strawberry with boost=false");
//Test #498 checking search results for blueberry tomato blueberry pear with boost=false
yourResult = tester.search("blueberry tomato blueberry pear", false, 50);
TestingTools.checkSearch(yourResult, "blueberry tomato blueberry pear", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #498 checking search results for blueberry tomato blueberry pear with boost=false");
//Test #499 checking search results for banana apricot pear with boost=false
yourResult = tester.search("banana apricot pear", false, 50);
TestingTools.checkSearch(yourResult, "banana apricot pear", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #499 checking search results for banana apricot pear with boost=false");
//Test #500 checking search results for blueberry peach tomato apple with boost=false
yourResult = tester.search("blueberry peach tomato apple", false, 50);
TestingTools.checkSearch(yourResult, "blueberry peach tomato apple", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #500 checking search results for blueberry peach tomato apple with boost=false");
//Test #501 checking search results for lime banana kiwi blueberry papaya with boost=false
yourResult = tester.search("lime banana kiwi blueberry papaya", false, 50);
TestingTools.checkSearch(yourResult, "lime banana kiwi blueberry papaya", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #501 checking search results for lime banana kiwi blueberry papaya with boost=false");
//Test #502 checking search results for pear coconut strawberry with boost=false
yourResult = tester.search("pear coconut strawberry", false, 50);
TestingTools.checkSearch(yourResult, "pear coconut strawberry", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #502 checking search results for pear coconut strawberry with boost=false");
//Test #503 checking search results for coconut banana kiwi kiwi with boost=false
yourResult = tester.search("coconut banana kiwi kiwi", false, 50);
TestingTools.checkSearch(yourResult, "coconut banana kiwi kiwi", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #503 checking search results for coconut banana kiwi kiwi with boost=false");
//Test #504 checking search results for banana papaya with boost=false
yourResult = tester.search("banana papaya", false, 50);
TestingTools.checkSearch(yourResult, "banana papaya", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #504 checking search results for banana papaya with boost=false");
//Test #505 checking search results for apricot with boost=false
yourResult = tester.search("apricot", false, 50);
TestingTools.checkSearch(yourResult, "apricot", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #505 checking search results for apricot with boost=false");
//Test #506 checking search results for apple apricot tomato apricot fig with boost=false
yourResult = tester.search("apple apricot tomato apricot fig", false, 50);
TestingTools.checkSearch(yourResult, "apple apricot tomato apricot fig", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #506 checking search results for apple apricot tomato apricot fig with boost=false");
//Test #507 checking search results for apple with boost=false
yourResult = tester.search("apple", false, 50);
TestingTools.checkSearch(yourResult, "apple", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #507 checking search results for apple with boost=false");
//Test #508 checking search results for pear coconut with boost=false
yourResult = tester.search("pear coconut", false, 50);
TestingTools.checkSearch(yourResult, "pear coconut", passOut, failOut, "Fruits50SearchNoBoostTester", "Test #508 checking search results for pear coconut with boost=false");
failOut.close();
passOut.close();
}
}
