import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.*;
public class FruitsASearchBoostTester {public static void main(String[] args) throws Exception{
ProjectTester tester = new ProjectTesterImp(); //Instantiate your own ProjectTester instance here
tester.initialize();
tester.crawl("https://people.scs.carleton.ca/~avamckenney/fruitsA/N-0.html");
runTest(tester);}public static void runTest(ProjectTester tester) throws Exception{
PrintWriter failOut = new PrintWriter(new FileWriter("FruitsA-SearchBoost-failed.txt"));
PrintWriter passOut = new PrintWriter(new FileWriter("FruitsA-SearchBoost-passed.txt"));
List<SearchResult> yourResult; 
//Test #559 checking search results for strawberry blueberry strawberry blueberry cherry with boost=true
yourResult = tester.search("strawberry blueberry strawberry blueberry cherry", true, 100);
TestingTools.checkSearch(yourResult, "strawberry blueberry strawberry blueberry cherry", passOut, failOut, "FruitsASearchBoostTester", "Test #559 checking search results for strawberry blueberry strawberry blueberry cherry with boost=true");
//Test #560 checking search results for apricot fig apricot fig with boost=true
yourResult = tester.search("apricot fig apricot fig", true, 100);
TestingTools.checkSearch(yourResult, "apricot fig apricot fig", passOut, failOut, "FruitsASearchBoostTester", "Test #560 checking search results for apricot fig apricot fig with boost=true");
//Test #561 checking search results for banana banana banana fig peach with boost=true
yourResult = tester.search("banana banana banana fig peach", true, 100);
TestingTools.checkSearch(yourResult, "banana banana banana fig peach", passOut, failOut, "FruitsASearchBoostTester", "Test #561 checking search results for banana banana banana fig peach with boost=true");
//Test #562 checking search results for apple pear lime coconut with boost=true
yourResult = tester.search("apple pear lime coconut", true, 100);
TestingTools.checkSearch(yourResult, "apple pear lime coconut", passOut, failOut, "FruitsASearchBoostTester", "Test #562 checking search results for apple pear lime coconut with boost=true");
//Test #563 checking search results for fig tomato blueberry kiwi with boost=true
yourResult = tester.search("fig tomato blueberry kiwi", true, 100);
TestingTools.checkSearch(yourResult, "fig tomato blueberry kiwi", passOut, failOut, "FruitsASearchBoostTester", "Test #563 checking search results for fig tomato blueberry kiwi with boost=true");
//Test #564 checking search results for fig papaya coconut coconut with boost=true
yourResult = tester.search("fig papaya coconut coconut", true, 100);
TestingTools.checkSearch(yourResult, "fig papaya coconut coconut", passOut, failOut, "FruitsASearchBoostTester", "Test #564 checking search results for fig papaya coconut coconut with boost=true");
//Test #565 checking search results for pear with boost=true
yourResult = tester.search("pear", true, 100);
TestingTools.checkSearch(yourResult, "pear", passOut, failOut, "FruitsASearchBoostTester", "Test #565 checking search results for pear with boost=true");
//Test #566 checking search results for coconut peach with boost=true
yourResult = tester.search("coconut peach", true, 100);
TestingTools.checkSearch(yourResult, "coconut peach", passOut, failOut, "FruitsASearchBoostTester", "Test #566 checking search results for coconut peach with boost=true");
//Test #567 checking search results for fig with boost=true
yourResult = tester.search("fig", true, 100);
TestingTools.checkSearch(yourResult, "fig", passOut, failOut, "FruitsASearchBoostTester", "Test #567 checking search results for fig with boost=true");
//Test #568 checking search results for kiwi cherry with boost=true
yourResult = tester.search("kiwi cherry", true, 100);
TestingTools.checkSearch(yourResult, "kiwi cherry", passOut, failOut, "FruitsASearchBoostTester", "Test #568 checking search results for kiwi cherry with boost=true");
//Test #569 checking search results for kiwi apple kiwi with boost=true
yourResult = tester.search("kiwi apple kiwi", true, 100);
TestingTools.checkSearch(yourResult, "kiwi apple kiwi", passOut, failOut, "FruitsASearchBoostTester", "Test #569 checking search results for kiwi apple kiwi with boost=true");
//Test #570 checking search results for pear blueberry with boost=true
yourResult = tester.search("pear blueberry", true, 100);
TestingTools.checkSearch(yourResult, "pear blueberry", passOut, failOut, "FruitsASearchBoostTester", "Test #570 checking search results for pear blueberry with boost=true");
//Test #571 checking search results for apricot fig fig cherry banana with boost=true
yourResult = tester.search("apricot fig fig cherry banana", true, 100);
TestingTools.checkSearch(yourResult, "apricot fig fig cherry banana", passOut, failOut, "FruitsASearchBoostTester", "Test #571 checking search results for apricot fig fig cherry banana with boost=true");
//Test #572 checking search results for fig tomato with boost=true
yourResult = tester.search("fig tomato", true, 100);
TestingTools.checkSearch(yourResult, "fig tomato", passOut, failOut, "FruitsASearchBoostTester", "Test #572 checking search results for fig tomato with boost=true");
//Test #573 checking search results for peach blueberry tomato apple with boost=true
yourResult = tester.search("peach blueberry tomato apple", true, 100);
TestingTools.checkSearch(yourResult, "peach blueberry tomato apple", passOut, failOut, "FruitsASearchBoostTester", "Test #573 checking search results for peach blueberry tomato apple with boost=true");
//Test #574 checking search results for pear apple with boost=true
yourResult = tester.search("pear apple", true, 100);
TestingTools.checkSearch(yourResult, "pear apple", passOut, failOut, "FruitsASearchBoostTester", "Test #574 checking search results for pear apple with boost=true");
//Test #575 checking search results for banana tomato blueberry apricot with boost=true
yourResult = tester.search("banana tomato blueberry apricot", true, 100);
TestingTools.checkSearch(yourResult, "banana tomato blueberry apricot", passOut, failOut, "FruitsASearchBoostTester", "Test #575 checking search results for banana tomato blueberry apricot with boost=true");
//Test #576 checking search results for blueberry lime apricot papaya with boost=true
yourResult = tester.search("blueberry lime apricot papaya", true, 100);
TestingTools.checkSearch(yourResult, "blueberry lime apricot papaya", passOut, failOut, "FruitsASearchBoostTester", "Test #576 checking search results for blueberry lime apricot papaya with boost=true");
//Test #577 checking search results for banana with boost=true
yourResult = tester.search("banana", true, 100);
TestingTools.checkSearch(yourResult, "banana", passOut, failOut, "FruitsASearchBoostTester", "Test #577 checking search results for banana with boost=true");
//Test #578 checking search results for lime blueberry pear with boost=true
yourResult = tester.search("lime blueberry pear", true, 100);
TestingTools.checkSearch(yourResult, "lime blueberry pear", passOut, failOut, "FruitsASearchBoostTester", "Test #578 checking search results for lime blueberry pear with boost=true");
//Test #579 checking search results for banana blueberry kiwi with boost=true
yourResult = tester.search("banana blueberry kiwi", true, 100);
TestingTools.checkSearch(yourResult, "banana blueberry kiwi", passOut, failOut, "FruitsASearchBoostTester", "Test #579 checking search results for banana blueberry kiwi with boost=true");
//Test #580 checking search results for lime lime apricot kiwi with boost=true
yourResult = tester.search("lime lime apricot kiwi", true, 100);
TestingTools.checkSearch(yourResult, "lime lime apricot kiwi", passOut, failOut, "FruitsASearchBoostTester", "Test #580 checking search results for lime lime apricot kiwi with boost=true");
//Test #581 checking search results for papaya with boost=true
yourResult = tester.search("papaya", true, 100);
TestingTools.checkSearch(yourResult, "papaya", passOut, failOut, "FruitsASearchBoostTester", "Test #581 checking search results for papaya with boost=true");
//Test #582 checking search results for strawberry papaya peach apple coconut with boost=true
yourResult = tester.search("strawberry papaya peach apple coconut", true, 100);
TestingTools.checkSearch(yourResult, "strawberry papaya peach apple coconut", passOut, failOut, "FruitsASearchBoostTester", "Test #582 checking search results for strawberry papaya peach apple coconut with boost=true");
//Test #583 checking search results for coconut peach pear cherry with boost=true
yourResult = tester.search("coconut peach pear cherry", true, 100);
TestingTools.checkSearch(yourResult, "coconut peach pear cherry", passOut, failOut, "FruitsASearchBoostTester", "Test #583 checking search results for coconut peach pear cherry with boost=true");
//Test #584 checking search results for fig pear peach with boost=true
yourResult = tester.search("fig pear peach", true, 100);
TestingTools.checkSearch(yourResult, "fig pear peach", passOut, failOut, "FruitsASearchBoostTester", "Test #584 checking search results for fig pear peach with boost=true");
//Test #585 checking search results for tomato lime with boost=true
yourResult = tester.search("tomato lime", true, 100);
TestingTools.checkSearch(yourResult, "tomato lime", passOut, failOut, "FruitsASearchBoostTester", "Test #585 checking search results for tomato lime with boost=true");
//Test #586 checking search results for papaya coconut strawberry cherry fig with boost=true
yourResult = tester.search("papaya coconut strawberry cherry fig", true, 100);
TestingTools.checkSearch(yourResult, "papaya coconut strawberry cherry fig", passOut, failOut, "FruitsASearchBoostTester", "Test #586 checking search results for papaya coconut strawberry cherry fig with boost=true");
//Test #587 checking search results for kiwi coconut apricot cherry apple with boost=true
yourResult = tester.search("kiwi coconut apricot cherry apple", true, 100);
TestingTools.checkSearch(yourResult, "kiwi coconut apricot cherry apple", passOut, failOut, "FruitsASearchBoostTester", "Test #587 checking search results for kiwi coconut apricot cherry apple with boost=true");
//Test #588 checking search results for kiwi papaya lime papaya coconut with boost=true
yourResult = tester.search("kiwi papaya lime papaya coconut", true, 100);
TestingTools.checkSearch(yourResult, "kiwi papaya lime papaya coconut", passOut, failOut, "FruitsASearchBoostTester", "Test #588 checking search results for kiwi papaya lime papaya coconut with boost=true");
//Test #589 checking search results for blueberry with boost=true
yourResult = tester.search("blueberry", true, 100);
TestingTools.checkSearch(yourResult, "blueberry", passOut, failOut, "FruitsASearchBoostTester", "Test #589 checking search results for blueberry with boost=true");
//Test #590 checking search results for apricot pear lime papaya blueberry with boost=true
yourResult = tester.search("apricot pear lime papaya blueberry", true, 100);
TestingTools.checkSearch(yourResult, "apricot pear lime papaya blueberry", passOut, failOut, "FruitsASearchBoostTester", "Test #590 checking search results for apricot pear lime papaya blueberry with boost=true");
//Test #591 checking search results for cherry fig fig papaya with boost=true
yourResult = tester.search("cherry fig fig papaya", true, 100);
TestingTools.checkSearch(yourResult, "cherry fig fig papaya", passOut, failOut, "FruitsASearchBoostTester", "Test #591 checking search results for cherry fig fig papaya with boost=true");
//Test #592 checking search results for apricot tomato with boost=true
yourResult = tester.search("apricot tomato", true, 100);
TestingTools.checkSearch(yourResult, "apricot tomato", passOut, failOut, "FruitsASearchBoostTester", "Test #592 checking search results for apricot tomato with boost=true");
//Test #593 checking search results for fig kiwi with boost=true
yourResult = tester.search("fig kiwi", true, 100);
TestingTools.checkSearch(yourResult, "fig kiwi", passOut, failOut, "FruitsASearchBoostTester", "Test #593 checking search results for fig kiwi with boost=true");
//Test #594 checking search results for lime tomato banana banana pear with boost=true
yourResult = tester.search("lime tomato banana banana pear", true, 100);
TestingTools.checkSearch(yourResult, "lime tomato banana banana pear", passOut, failOut, "FruitsASearchBoostTester", "Test #594 checking search results for lime tomato banana banana pear with boost=true");
//Test #595 checking search results for banana banana peach blueberry apple with boost=true
yourResult = tester.search("banana banana peach blueberry apple", true, 100);
TestingTools.checkSearch(yourResult, "banana banana peach blueberry apple", passOut, failOut, "FruitsASearchBoostTester", "Test #595 checking search results for banana banana peach blueberry apple with boost=true");
//Test #596 checking search results for coconut kiwi lime apricot coconut with boost=true
yourResult = tester.search("coconut kiwi lime apricot coconut", true, 100);
TestingTools.checkSearch(yourResult, "coconut kiwi lime apricot coconut", passOut, failOut, "FruitsASearchBoostTester", "Test #596 checking search results for coconut kiwi lime apricot coconut with boost=true");
//Test #597 checking search results for peach lime peach lime with boost=true
yourResult = tester.search("peach lime peach lime", true, 100);
TestingTools.checkSearch(yourResult, "peach lime peach lime", passOut, failOut, "FruitsASearchBoostTester", "Test #597 checking search results for peach lime peach lime with boost=true");
//Test #598 checking search results for lime with boost=true
yourResult = tester.search("lime", true, 100);
TestingTools.checkSearch(yourResult, "lime", passOut, failOut, "FruitsASearchBoostTester", "Test #598 checking search results for lime with boost=true");
//Test #599 checking search results for lime apricot papaya with boost=true
yourResult = tester.search("lime apricot papaya", true, 100);
TestingTools.checkSearch(yourResult, "lime apricot papaya", passOut, failOut, "FruitsASearchBoostTester", "Test #599 checking search results for lime apricot papaya with boost=true");
//Test #600 checking search results for apple fig with boost=true
yourResult = tester.search("apple fig", true, 100);
TestingTools.checkSearch(yourResult, "apple fig", passOut, failOut, "FruitsASearchBoostTester", "Test #600 checking search results for apple fig with boost=true");
//Test #601 checking search results for apple with boost=true
yourResult = tester.search("apple", true, 100);
TestingTools.checkSearch(yourResult, "apple", passOut, failOut, "FruitsASearchBoostTester", "Test #601 checking search results for apple with boost=true");
//Test #602 checking search results for apricot banana strawberry peach with boost=true
yourResult = tester.search("apricot banana strawberry peach", true, 100);
TestingTools.checkSearch(yourResult, "apricot banana strawberry peach", passOut, failOut, "FruitsASearchBoostTester", "Test #602 checking search results for apricot banana strawberry peach with boost=true");
//Test #603 checking search results for blueberry kiwi strawberry peach peach with boost=true
yourResult = tester.search("blueberry kiwi strawberry peach peach", true, 100);
TestingTools.checkSearch(yourResult, "blueberry kiwi strawberry peach peach", passOut, failOut, "FruitsASearchBoostTester", "Test #603 checking search results for blueberry kiwi strawberry peach peach with boost=true");
//Test #604 checking search results for banana peach pear lime peach with boost=true
yourResult = tester.search("banana peach pear lime peach", true, 100);
TestingTools.checkSearch(yourResult, "banana peach pear lime peach", passOut, failOut, "FruitsASearchBoostTester", "Test #604 checking search results for banana peach pear lime peach with boost=true");
//Test #605 checking search results for blueberry pear lime with boost=true
yourResult = tester.search("blueberry pear lime", true, 100);
TestingTools.checkSearch(yourResult, "blueberry pear lime", passOut, failOut, "FruitsASearchBoostTester", "Test #605 checking search results for blueberry pear lime with boost=true");
//Test #606 checking search results for tomato coconut strawberry with boost=true
yourResult = tester.search("tomato coconut strawberry", true, 100);
TestingTools.checkSearch(yourResult, "tomato coconut strawberry", passOut, failOut, "FruitsASearchBoostTester", "Test #606 checking search results for tomato coconut strawberry with boost=true");
//Test #607 checking search results for papaya with boost=true
yourResult = tester.search("papaya", true, 100);
TestingTools.checkSearch(yourResult, "papaya", passOut, failOut, "FruitsASearchBoostTester", "Test #607 checking search results for papaya with boost=true");
//Test #608 checking search results for pear apple with boost=true
yourResult = tester.search("pear apple", true, 100);
TestingTools.checkSearch(yourResult, "pear apple", passOut, failOut, "FruitsASearchBoostTester", "Test #608 checking search results for pear apple with boost=true");
//Test #609 checking search results for blueberry with boost=true
yourResult = tester.search("blueberry", true, 100);
TestingTools.checkSearch(yourResult, "blueberry", passOut, failOut, "FruitsASearchBoostTester", "Test #609 checking search results for blueberry with boost=true");
//Test #610 checking search results for tomato apricot pear kiwi with boost=true
yourResult = tester.search("tomato apricot pear kiwi", true, 100);
TestingTools.checkSearch(yourResult, "tomato apricot pear kiwi", passOut, failOut, "FruitsASearchBoostTester", "Test #610 checking search results for tomato apricot pear kiwi with boost=true");
//Test #611 checking search results for banana banana papaya fig with boost=true
yourResult = tester.search("banana banana papaya fig", true, 100);
TestingTools.checkSearch(yourResult, "banana banana papaya fig", passOut, failOut, "FruitsASearchBoostTester", "Test #611 checking search results for banana banana papaya fig with boost=true");
//Test #612 checking search results for papaya with boost=true
yourResult = tester.search("papaya", true, 100);
TestingTools.checkSearch(yourResult, "papaya", passOut, failOut, "FruitsASearchBoostTester", "Test #612 checking search results for papaya with boost=true");
//Test #613 checking search results for tomato peach blueberry with boost=true
yourResult = tester.search("tomato peach blueberry", true, 100);
TestingTools.checkSearch(yourResult, "tomato peach blueberry", passOut, failOut, "FruitsASearchBoostTester", "Test #613 checking search results for tomato peach blueberry with boost=true");
//Test #614 checking search results for blueberry apple with boost=true
yourResult = tester.search("blueberry apple", true, 100);
TestingTools.checkSearch(yourResult, "blueberry apple", passOut, failOut, "FruitsASearchBoostTester", "Test #614 checking search results for blueberry apple with boost=true");
//Test #615 checking search results for cherry with boost=true
yourResult = tester.search("cherry", true, 100);
TestingTools.checkSearch(yourResult, "cherry", passOut, failOut, "FruitsASearchBoostTester", "Test #615 checking search results for cherry with boost=true");
//Test #616 checking search results for blueberry strawberry with boost=true
yourResult = tester.search("blueberry strawberry", true, 100);
TestingTools.checkSearch(yourResult, "blueberry strawberry", passOut, failOut, "FruitsASearchBoostTester", "Test #616 checking search results for blueberry strawberry with boost=true");
//Test #617 checking search results for strawberry apple pear with boost=true
yourResult = tester.search("strawberry apple pear", true, 100);
TestingTools.checkSearch(yourResult, "strawberry apple pear", passOut, failOut, "FruitsASearchBoostTester", "Test #617 checking search results for strawberry apple pear with boost=true");
//Test #618 checking search results for banana tomato fig banana strawberry with boost=true
yourResult = tester.search("banana tomato fig banana strawberry", true, 100);
TestingTools.checkSearch(yourResult, "banana tomato fig banana strawberry", passOut, failOut, "FruitsASearchBoostTester", "Test #618 checking search results for banana tomato fig banana strawberry with boost=true");
//Test #619 checking search results for fig peach banana fig fig with boost=true
yourResult = tester.search("fig peach banana fig fig", true, 100);
TestingTools.checkSearch(yourResult, "fig peach banana fig fig", passOut, failOut, "FruitsASearchBoostTester", "Test #619 checking search results for fig peach banana fig fig with boost=true");
//Test #620 checking search results for tomato pear pear with boost=true
yourResult = tester.search("tomato pear pear", true, 100);
TestingTools.checkSearch(yourResult, "tomato pear pear", passOut, failOut, "FruitsASearchBoostTester", "Test #620 checking search results for tomato pear pear with boost=true");
//Test #621 checking search results for papaya kiwi apple with boost=true
yourResult = tester.search("papaya kiwi apple", true, 100);
TestingTools.checkSearch(yourResult, "papaya kiwi apple", passOut, failOut, "FruitsASearchBoostTester", "Test #621 checking search results for papaya kiwi apple with boost=true");
//Test #622 checking search results for apricot banana with boost=true
yourResult = tester.search("apricot banana", true, 100);
TestingTools.checkSearch(yourResult, "apricot banana", passOut, failOut, "FruitsASearchBoostTester", "Test #622 checking search results for apricot banana with boost=true");
//Test #623 checking search results for kiwi banana with boost=true
yourResult = tester.search("kiwi banana", true, 100);
TestingTools.checkSearch(yourResult, "kiwi banana", passOut, failOut, "FruitsASearchBoostTester", "Test #623 checking search results for kiwi banana with boost=true");
//Test #624 checking search results for apple with boost=true
yourResult = tester.search("apple", true, 100);
TestingTools.checkSearch(yourResult, "apple", passOut, failOut, "FruitsASearchBoostTester", "Test #624 checking search results for apple with boost=true");
//Test #625 checking search results for banana apple fig pear kiwi with boost=true
yourResult = tester.search("banana apple fig pear kiwi", true, 100);
TestingTools.checkSearch(yourResult, "banana apple fig pear kiwi", passOut, failOut, "FruitsASearchBoostTester", "Test #625 checking search results for banana apple fig pear kiwi with boost=true");
//Test #626 checking search results for fig with boost=true
yourResult = tester.search("fig", true, 100);
TestingTools.checkSearch(yourResult, "fig", passOut, failOut, "FruitsASearchBoostTester", "Test #626 checking search results for fig with boost=true");
//Test #627 checking search results for apple strawberry kiwi kiwi pear with boost=true
yourResult = tester.search("apple strawberry kiwi kiwi pear", true, 100);
TestingTools.checkSearch(yourResult, "apple strawberry kiwi kiwi pear", passOut, failOut, "FruitsASearchBoostTester", "Test #627 checking search results for apple strawberry kiwi kiwi pear with boost=true");
//Test #628 checking search results for coconut apple cherry peach with boost=true
yourResult = tester.search("coconut apple cherry peach", true, 100);
TestingTools.checkSearch(yourResult, "coconut apple cherry peach", passOut, failOut, "FruitsASearchBoostTester", "Test #628 checking search results for coconut apple cherry peach with boost=true");
//Test #629 checking search results for coconut with boost=true
yourResult = tester.search("coconut", true, 100);
TestingTools.checkSearch(yourResult, "coconut", passOut, failOut, "FruitsASearchBoostTester", "Test #629 checking search results for coconut with boost=true");
//Test #630 checking search results for lime with boost=true
yourResult = tester.search("lime", true, 100);
TestingTools.checkSearch(yourResult, "lime", passOut, failOut, "FruitsASearchBoostTester", "Test #630 checking search results for lime with boost=true");
//Test #631 checking search results for strawberry with boost=true
yourResult = tester.search("strawberry", true, 100);
TestingTools.checkSearch(yourResult, "strawberry", passOut, failOut, "FruitsASearchBoostTester", "Test #631 checking search results for strawberry with boost=true");
//Test #632 checking search results for papaya blueberry papaya apricot papaya with boost=true
yourResult = tester.search("papaya blueberry papaya apricot papaya", true, 100);
TestingTools.checkSearch(yourResult, "papaya blueberry papaya apricot papaya", passOut, failOut, "FruitsASearchBoostTester", "Test #632 checking search results for papaya blueberry papaya apricot papaya with boost=true");
//Test #633 checking search results for apricot with boost=true
yourResult = tester.search("apricot", true, 100);
TestingTools.checkSearch(yourResult, "apricot", passOut, failOut, "FruitsASearchBoostTester", "Test #633 checking search results for apricot with boost=true");
//Test #634 checking search results for coconut blueberry fig kiwi apricot with boost=true
yourResult = tester.search("coconut blueberry fig kiwi apricot", true, 100);
TestingTools.checkSearch(yourResult, "coconut blueberry fig kiwi apricot", passOut, failOut, "FruitsASearchBoostTester", "Test #634 checking search results for coconut blueberry fig kiwi apricot with boost=true");
//Test #635 checking search results for coconut blueberry with boost=true
yourResult = tester.search("coconut blueberry", true, 100);
TestingTools.checkSearch(yourResult, "coconut blueberry", passOut, failOut, "FruitsASearchBoostTester", "Test #635 checking search results for coconut blueberry with boost=true");
//Test #636 checking search results for papaya with boost=true
yourResult = tester.search("papaya", true, 100);
TestingTools.checkSearch(yourResult, "papaya", passOut, failOut, "FruitsASearchBoostTester", "Test #636 checking search results for papaya with boost=true");
//Test #637 checking search results for peach papaya with boost=true
yourResult = tester.search("peach papaya", true, 100);
TestingTools.checkSearch(yourResult, "peach papaya", passOut, failOut, "FruitsASearchBoostTester", "Test #637 checking search results for peach papaya with boost=true");
//Test #638 checking search results for strawberry pear pear lime with boost=true
yourResult = tester.search("strawberry pear pear lime", true, 100);
TestingTools.checkSearch(yourResult, "strawberry pear pear lime", passOut, failOut, "FruitsASearchBoostTester", "Test #638 checking search results for strawberry pear pear lime with boost=true");
//Test #639 checking search results for pear pear fig peach coconut with boost=true
yourResult = tester.search("pear pear fig peach coconut", true, 100);
TestingTools.checkSearch(yourResult, "pear pear fig peach coconut", passOut, failOut, "FruitsASearchBoostTester", "Test #639 checking search results for pear pear fig peach coconut with boost=true");
//Test #640 checking search results for blueberry with boost=true
yourResult = tester.search("blueberry", true, 100);
TestingTools.checkSearch(yourResult, "blueberry", passOut, failOut, "FruitsASearchBoostTester", "Test #640 checking search results for blueberry with boost=true");
//Test #641 checking search results for blueberry strawberry papaya fig strawberry with boost=true
yourResult = tester.search("blueberry strawberry papaya fig strawberry", true, 100);
TestingTools.checkSearch(yourResult, "blueberry strawberry papaya fig strawberry", passOut, failOut, "FruitsASearchBoostTester", "Test #641 checking search results for blueberry strawberry papaya fig strawberry with boost=true");
//Test #642 checking search results for strawberry apricot lime blueberry with boost=true
yourResult = tester.search("strawberry apricot lime blueberry", true, 100);
TestingTools.checkSearch(yourResult, "strawberry apricot lime blueberry", passOut, failOut, "FruitsASearchBoostTester", "Test #642 checking search results for strawberry apricot lime blueberry with boost=true");
//Test #643 checking search results for lime papaya fig with boost=true
yourResult = tester.search("lime papaya fig", true, 100);
TestingTools.checkSearch(yourResult, "lime papaya fig", passOut, failOut, "FruitsASearchBoostTester", "Test #643 checking search results for lime papaya fig with boost=true");
//Test #644 checking search results for papaya with boost=true
yourResult = tester.search("papaya", true, 100);
TestingTools.checkSearch(yourResult, "papaya", passOut, failOut, "FruitsASearchBoostTester", "Test #644 checking search results for papaya with boost=true");
//Test #645 checking search results for apple coconut with boost=true
yourResult = tester.search("apple coconut", true, 100);
TestingTools.checkSearch(yourResult, "apple coconut", passOut, failOut, "FruitsASearchBoostTester", "Test #645 checking search results for apple coconut with boost=true");
//Test #646 checking search results for tomato fig peach apricot with boost=true
yourResult = tester.search("tomato fig peach apricot", true, 100);
TestingTools.checkSearch(yourResult, "tomato fig peach apricot", passOut, failOut, "FruitsASearchBoostTester", "Test #646 checking search results for tomato fig peach apricot with boost=true");
//Test #647 checking search results for strawberry kiwi peach tomato with boost=true
yourResult = tester.search("strawberry kiwi peach tomato", true, 100);
TestingTools.checkSearch(yourResult, "strawberry kiwi peach tomato", passOut, failOut, "FruitsASearchBoostTester", "Test #647 checking search results for strawberry kiwi peach tomato with boost=true");
//Test #648 checking search results for cherry apple apricot lime with boost=true
yourResult = tester.search("cherry apple apricot lime", true, 100);
TestingTools.checkSearch(yourResult, "cherry apple apricot lime", passOut, failOut, "FruitsASearchBoostTester", "Test #648 checking search results for cherry apple apricot lime with boost=true");
//Test #649 checking search results for strawberry kiwi pear with boost=true
yourResult = tester.search("strawberry kiwi pear", true, 100);
TestingTools.checkSearch(yourResult, "strawberry kiwi pear", passOut, failOut, "FruitsASearchBoostTester", "Test #649 checking search results for strawberry kiwi pear with boost=true");
//Test #650 checking search results for apple apple with boost=true
yourResult = tester.search("apple apple", true, 100);
TestingTools.checkSearch(yourResult, "apple apple", passOut, failOut, "FruitsASearchBoostTester", "Test #650 checking search results for apple apple with boost=true");
//Test #651 checking search results for strawberry strawberry with boost=true
yourResult = tester.search("strawberry strawberry", true, 100);
TestingTools.checkSearch(yourResult, "strawberry strawberry", passOut, failOut, "FruitsASearchBoostTester", "Test #651 checking search results for strawberry strawberry with boost=true");
//Test #652 checking search results for apple apple cherry lime kiwi with boost=true
yourResult = tester.search("apple apple cherry lime kiwi", true, 100);
TestingTools.checkSearch(yourResult, "apple apple cherry lime kiwi", passOut, failOut, "FruitsASearchBoostTester", "Test #652 checking search results for apple apple cherry lime kiwi with boost=true");
//Test #653 checking search results for fig strawberry apple pear with boost=true
yourResult = tester.search("fig strawberry apple pear", true, 100);
TestingTools.checkSearch(yourResult, "fig strawberry apple pear", passOut, failOut, "FruitsASearchBoostTester", "Test #653 checking search results for fig strawberry apple pear with boost=true");
//Test #654 checking search results for apple apricot cherry banana lime with boost=true
yourResult = tester.search("apple apricot cherry banana lime", true, 100);
TestingTools.checkSearch(yourResult, "apple apricot cherry banana lime", passOut, failOut, "FruitsASearchBoostTester", "Test #654 checking search results for apple apricot cherry banana lime with boost=true");
//Test #655 checking search results for pear with boost=true
yourResult = tester.search("pear", true, 100);
TestingTools.checkSearch(yourResult, "pear", passOut, failOut, "FruitsASearchBoostTester", "Test #655 checking search results for pear with boost=true");
//Test #656 checking search results for tomato fig lime banana fig with boost=true
yourResult = tester.search("tomato fig lime banana fig", true, 100);
TestingTools.checkSearch(yourResult, "tomato fig lime banana fig", passOut, failOut, "FruitsASearchBoostTester", "Test #656 checking search results for tomato fig lime banana fig with boost=true");
//Test #657 checking search results for fig tomato peach pear tomato with boost=true
yourResult = tester.search("fig tomato peach pear tomato", true, 100);
TestingTools.checkSearch(yourResult, "fig tomato peach pear tomato", passOut, failOut, "FruitsASearchBoostTester", "Test #657 checking search results for fig tomato peach pear tomato with boost=true");
//Test #658 checking search results for kiwi kiwi with boost=true
yourResult = tester.search("kiwi kiwi", true, 100);
TestingTools.checkSearch(yourResult, "kiwi kiwi", passOut, failOut, "FruitsASearchBoostTester", "Test #658 checking search results for kiwi kiwi with boost=true");
failOut.close();
passOut.close();
}
}
