import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.*;
public class Fruits50SearchBoostTester {public static void main(String[] args) throws Exception{
ProjectTester tester = new ProjectTesterImp(); //Instantiate your own ProjectTester instance here
tester.initialize();
tester.crawl("https://people.scs.carleton.ca/~avamckenney/fruits50/N-0.html");
runTest(tester);}public static void runTest(ProjectTester tester) throws Exception{
PrintWriter failOut = new PrintWriter(new FileWriter("Fruits50-SearchBoost-failed.txt"));
PrintWriter passOut = new PrintWriter(new FileWriter("Fruits50-SearchBoost-passed.txt"));
List<SearchResult> yourResult; 
//Test #509 checking search results for apple tomato with boost=true
yourResult = tester.search("apple tomato", true, 50);
TestingTools.checkSearch(yourResult, "apple tomato", passOut, failOut, "Fruits50SearchBoostTester", "Test #509 checking search results for apple tomato with boost=true");
//Test #510 checking search results for tomato fig pear blueberry with boost=true
yourResult = tester.search("tomato fig pear blueberry", true, 50);
TestingTools.checkSearch(yourResult, "tomato fig pear blueberry", passOut, failOut, "Fruits50SearchBoostTester", "Test #510 checking search results for tomato fig pear blueberry with boost=true");
//Test #511 checking search results for strawberry kiwi lime cherry apple with boost=true
yourResult = tester.search("strawberry kiwi lime cherry apple", true, 50);
TestingTools.checkSearch(yourResult, "strawberry kiwi lime cherry apple", passOut, failOut, "Fruits50SearchBoostTester", "Test #511 checking search results for strawberry kiwi lime cherry apple with boost=true");
//Test #512 checking search results for apricot with boost=true
yourResult = tester.search("apricot", true, 50);
TestingTools.checkSearch(yourResult, "apricot", passOut, failOut, "Fruits50SearchBoostTester", "Test #512 checking search results for apricot with boost=true");
//Test #513 checking search results for lime banana tomato with boost=true
yourResult = tester.search("lime banana tomato", true, 50);
TestingTools.checkSearch(yourResult, "lime banana tomato", passOut, failOut, "Fruits50SearchBoostTester", "Test #513 checking search results for lime banana tomato with boost=true");
//Test #514 checking search results for cherry papaya lime banana with boost=true
yourResult = tester.search("cherry papaya lime banana", true, 50);
TestingTools.checkSearch(yourResult, "cherry papaya lime banana", passOut, failOut, "Fruits50SearchBoostTester", "Test #514 checking search results for cherry papaya lime banana with boost=true");
//Test #515 checking search results for apricot kiwi with boost=true
yourResult = tester.search("apricot kiwi", true, 50);
TestingTools.checkSearch(yourResult, "apricot kiwi", passOut, failOut, "Fruits50SearchBoostTester", "Test #515 checking search results for apricot kiwi with boost=true");
//Test #516 checking search results for apple papaya banana pear tomato with boost=true
yourResult = tester.search("apple papaya banana pear tomato", true, 50);
TestingTools.checkSearch(yourResult, "apple papaya banana pear tomato", passOut, failOut, "Fruits50SearchBoostTester", "Test #516 checking search results for apple papaya banana pear tomato with boost=true");
//Test #517 checking search results for cherry cherry lime with boost=true
yourResult = tester.search("cherry cherry lime", true, 50);
TestingTools.checkSearch(yourResult, "cherry cherry lime", passOut, failOut, "Fruits50SearchBoostTester", "Test #517 checking search results for cherry cherry lime with boost=true");
//Test #518 checking search results for pear with boost=true
yourResult = tester.search("pear", true, 50);
TestingTools.checkSearch(yourResult, "pear", passOut, failOut, "Fruits50SearchBoostTester", "Test #518 checking search results for pear with boost=true");
//Test #519 checking search results for lime with boost=true
yourResult = tester.search("lime", true, 50);
TestingTools.checkSearch(yourResult, "lime", passOut, failOut, "Fruits50SearchBoostTester", "Test #519 checking search results for lime with boost=true");
//Test #520 checking search results for lime cherry fig tomato banana with boost=true
yourResult = tester.search("lime cherry fig tomato banana", true, 50);
TestingTools.checkSearch(yourResult, "lime cherry fig tomato banana", passOut, failOut, "Fruits50SearchBoostTester", "Test #520 checking search results for lime cherry fig tomato banana with boost=true");
//Test #521 checking search results for fig apple kiwi coconut fig with boost=true
yourResult = tester.search("fig apple kiwi coconut fig", true, 50);
TestingTools.checkSearch(yourResult, "fig apple kiwi coconut fig", passOut, failOut, "Fruits50SearchBoostTester", "Test #521 checking search results for fig apple kiwi coconut fig with boost=true");
//Test #522 checking search results for lime with boost=true
yourResult = tester.search("lime", true, 50);
TestingTools.checkSearch(yourResult, "lime", passOut, failOut, "Fruits50SearchBoostTester", "Test #522 checking search results for lime with boost=true");
//Test #523 checking search results for cherry fig with boost=true
yourResult = tester.search("cherry fig", true, 50);
TestingTools.checkSearch(yourResult, "cherry fig", passOut, failOut, "Fruits50SearchBoostTester", "Test #523 checking search results for cherry fig with boost=true");
//Test #524 checking search results for pear apple coconut with boost=true
yourResult = tester.search("pear apple coconut", true, 50);
TestingTools.checkSearch(yourResult, "pear apple coconut", passOut, failOut, "Fruits50SearchBoostTester", "Test #524 checking search results for pear apple coconut with boost=true");
//Test #525 checking search results for strawberry with boost=true
yourResult = tester.search("strawberry", true, 50);
TestingTools.checkSearch(yourResult, "strawberry", passOut, failOut, "Fruits50SearchBoostTester", "Test #525 checking search results for strawberry with boost=true");
//Test #526 checking search results for papaya with boost=true
yourResult = tester.search("papaya", true, 50);
TestingTools.checkSearch(yourResult, "papaya", passOut, failOut, "Fruits50SearchBoostTester", "Test #526 checking search results for papaya with boost=true");
//Test #527 checking search results for tomato kiwi with boost=true
yourResult = tester.search("tomato kiwi", true, 50);
TestingTools.checkSearch(yourResult, "tomato kiwi", passOut, failOut, "Fruits50SearchBoostTester", "Test #527 checking search results for tomato kiwi with boost=true");
//Test #528 checking search results for tomato banana cherry coconut with boost=true
yourResult = tester.search("tomato banana cherry coconut", true, 50);
TestingTools.checkSearch(yourResult, "tomato banana cherry coconut", passOut, failOut, "Fruits50SearchBoostTester", "Test #528 checking search results for tomato banana cherry coconut with boost=true");
//Test #529 checking search results for lime peach pear apricot papaya with boost=true
yourResult = tester.search("lime peach pear apricot papaya", true, 50);
TestingTools.checkSearch(yourResult, "lime peach pear apricot papaya", passOut, failOut, "Fruits50SearchBoostTester", "Test #529 checking search results for lime peach pear apricot papaya with boost=true");
//Test #530 checking search results for pear with boost=true
yourResult = tester.search("pear", true, 50);
TestingTools.checkSearch(yourResult, "pear", passOut, failOut, "Fruits50SearchBoostTester", "Test #530 checking search results for pear with boost=true");
//Test #531 checking search results for kiwi cherry banana tomato lime with boost=true
yourResult = tester.search("kiwi cherry banana tomato lime", true, 50);
TestingTools.checkSearch(yourResult, "kiwi cherry banana tomato lime", passOut, failOut, "Fruits50SearchBoostTester", "Test #531 checking search results for kiwi cherry banana tomato lime with boost=true");
//Test #532 checking search results for cherry apple with boost=true
yourResult = tester.search("cherry apple", true, 50);
TestingTools.checkSearch(yourResult, "cherry apple", passOut, failOut, "Fruits50SearchBoostTester", "Test #532 checking search results for cherry apple with boost=true");
//Test #533 checking search results for strawberry apricot kiwi with boost=true
yourResult = tester.search("strawberry apricot kiwi", true, 50);
TestingTools.checkSearch(yourResult, "strawberry apricot kiwi", passOut, failOut, "Fruits50SearchBoostTester", "Test #533 checking search results for strawberry apricot kiwi with boost=true");
//Test #534 checking search results for cherry peach tomato with boost=true
yourResult = tester.search("cherry peach tomato", true, 50);
TestingTools.checkSearch(yourResult, "cherry peach tomato", passOut, failOut, "Fruits50SearchBoostTester", "Test #534 checking search results for cherry peach tomato with boost=true");
//Test #535 checking search results for kiwi kiwi cherry with boost=true
yourResult = tester.search("kiwi kiwi cherry", true, 50);
TestingTools.checkSearch(yourResult, "kiwi kiwi cherry", passOut, failOut, "Fruits50SearchBoostTester", "Test #535 checking search results for kiwi kiwi cherry with boost=true");
//Test #536 checking search results for lime cherry apricot pear kiwi with boost=true
yourResult = tester.search("lime cherry apricot pear kiwi", true, 50);
TestingTools.checkSearch(yourResult, "lime cherry apricot pear kiwi", passOut, failOut, "Fruits50SearchBoostTester", "Test #536 checking search results for lime cherry apricot pear kiwi with boost=true");
//Test #537 checking search results for kiwi cherry with boost=true
yourResult = tester.search("kiwi cherry", true, 50);
TestingTools.checkSearch(yourResult, "kiwi cherry", passOut, failOut, "Fruits50SearchBoostTester", "Test #537 checking search results for kiwi cherry with boost=true");
//Test #538 checking search results for fig blueberry strawberry strawberry banana with boost=true
yourResult = tester.search("fig blueberry strawberry strawberry banana", true, 50);
TestingTools.checkSearch(yourResult, "fig blueberry strawberry strawberry banana", passOut, failOut, "Fruits50SearchBoostTester", "Test #538 checking search results for fig blueberry strawberry strawberry banana with boost=true");
//Test #539 checking search results for pear coconut peach kiwi with boost=true
yourResult = tester.search("pear coconut peach kiwi", true, 50);
TestingTools.checkSearch(yourResult, "pear coconut peach kiwi", passOut, failOut, "Fruits50SearchBoostTester", "Test #539 checking search results for pear coconut peach kiwi with boost=true");
//Test #540 checking search results for lime blueberry apricot coconut with boost=true
yourResult = tester.search("lime blueberry apricot coconut", true, 50);
TestingTools.checkSearch(yourResult, "lime blueberry apricot coconut", passOut, failOut, "Fruits50SearchBoostTester", "Test #540 checking search results for lime blueberry apricot coconut with boost=true");
//Test #541 checking search results for pear strawberry lime with boost=true
yourResult = tester.search("pear strawberry lime", true, 50);
TestingTools.checkSearch(yourResult, "pear strawberry lime", passOut, failOut, "Fruits50SearchBoostTester", "Test #541 checking search results for pear strawberry lime with boost=true");
//Test #542 checking search results for apple with boost=true
yourResult = tester.search("apple", true, 50);
TestingTools.checkSearch(yourResult, "apple", passOut, failOut, "Fruits50SearchBoostTester", "Test #542 checking search results for apple with boost=true");
//Test #543 checking search results for apple pear banana lime peach with boost=true
yourResult = tester.search("apple pear banana lime peach", true, 50);
TestingTools.checkSearch(yourResult, "apple pear banana lime peach", passOut, failOut, "Fruits50SearchBoostTester", "Test #543 checking search results for apple pear banana lime peach with boost=true");
//Test #544 checking search results for peach lime apple peach with boost=true
yourResult = tester.search("peach lime apple peach", true, 50);
TestingTools.checkSearch(yourResult, "peach lime apple peach", passOut, failOut, "Fruits50SearchBoostTester", "Test #544 checking search results for peach lime apple peach with boost=true");
//Test #545 checking search results for fig with boost=true
yourResult = tester.search("fig", true, 50);
TestingTools.checkSearch(yourResult, "fig", passOut, failOut, "Fruits50SearchBoostTester", "Test #545 checking search results for fig with boost=true");
//Test #546 checking search results for coconut blueberry tomato with boost=true
yourResult = tester.search("coconut blueberry tomato", true, 50);
TestingTools.checkSearch(yourResult, "coconut blueberry tomato", passOut, failOut, "Fruits50SearchBoostTester", "Test #546 checking search results for coconut blueberry tomato with boost=true");
//Test #547 checking search results for tomato blueberry coconut peach with boost=true
yourResult = tester.search("tomato blueberry coconut peach", true, 50);
TestingTools.checkSearch(yourResult, "tomato blueberry coconut peach", passOut, failOut, "Fruits50SearchBoostTester", "Test #547 checking search results for tomato blueberry coconut peach with boost=true");
//Test #548 checking search results for strawberry with boost=true
yourResult = tester.search("strawberry", true, 50);
TestingTools.checkSearch(yourResult, "strawberry", passOut, failOut, "Fruits50SearchBoostTester", "Test #548 checking search results for strawberry with boost=true");
//Test #549 checking search results for banana pear cherry banana fig with boost=true
yourResult = tester.search("banana pear cherry banana fig", true, 50);
TestingTools.checkSearch(yourResult, "banana pear cherry banana fig", passOut, failOut, "Fruits50SearchBoostTester", "Test #549 checking search results for banana pear cherry banana fig with boost=true");
//Test #550 checking search results for blueberry papaya with boost=true
yourResult = tester.search("blueberry papaya", true, 50);
TestingTools.checkSearch(yourResult, "blueberry papaya", passOut, failOut, "Fruits50SearchBoostTester", "Test #550 checking search results for blueberry papaya with boost=true");
//Test #551 checking search results for papaya peach tomato with boost=true
yourResult = tester.search("papaya peach tomato", true, 50);
TestingTools.checkSearch(yourResult, "papaya peach tomato", passOut, failOut, "Fruits50SearchBoostTester", "Test #551 checking search results for papaya peach tomato with boost=true");
//Test #552 checking search results for kiwi lime strawberry tomato pear with boost=true
yourResult = tester.search("kiwi lime strawberry tomato pear", true, 50);
TestingTools.checkSearch(yourResult, "kiwi lime strawberry tomato pear", passOut, failOut, "Fruits50SearchBoostTester", "Test #552 checking search results for kiwi lime strawberry tomato pear with boost=true");
//Test #553 checking search results for papaya papaya peach with boost=true
yourResult = tester.search("papaya papaya peach", true, 50);
TestingTools.checkSearch(yourResult, "papaya papaya peach", passOut, failOut, "Fruits50SearchBoostTester", "Test #553 checking search results for papaya papaya peach with boost=true");
//Test #554 checking search results for cherry with boost=true
yourResult = tester.search("cherry", true, 50);
TestingTools.checkSearch(yourResult, "cherry", passOut, failOut, "Fruits50SearchBoostTester", "Test #554 checking search results for cherry with boost=true");
//Test #555 checking search results for coconut with boost=true
yourResult = tester.search("coconut", true, 50);
TestingTools.checkSearch(yourResult, "coconut", passOut, failOut, "Fruits50SearchBoostTester", "Test #555 checking search results for coconut with boost=true");
//Test #556 checking search results for strawberry blueberry with boost=true
yourResult = tester.search("strawberry blueberry", true, 50);
TestingTools.checkSearch(yourResult, "strawberry blueberry", passOut, failOut, "Fruits50SearchBoostTester", "Test #556 checking search results for strawberry blueberry with boost=true");
//Test #557 checking search results for peach cherry banana apple with boost=true
yourResult = tester.search("peach cherry banana apple", true, 50);
TestingTools.checkSearch(yourResult, "peach cherry banana apple", passOut, failOut, "Fruits50SearchBoostTester", "Test #557 checking search results for peach cherry banana apple with boost=true");
//Test #558 checking search results for tomato pear cherry strawberry tomato with boost=true
yourResult = tester.search("tomato pear cherry strawberry tomato", true, 50);
TestingTools.checkSearch(yourResult, "tomato pear cherry strawberry tomato", passOut, failOut, "Fruits50SearchBoostTester", "Test #558 checking search results for tomato pear cherry strawberry tomato with boost=true");
//Test #559 checking search results for apple pear kiwi tomato banana with boost=true
yourResult = tester.search("apple pear kiwi tomato banana", true, 50);
TestingTools.checkSearch(yourResult, "apple pear kiwi tomato banana", passOut, failOut, "Fruits50SearchBoostTester", "Test #559 checking search results for apple pear kiwi tomato banana with boost=true");
//Test #560 checking search results for blueberry fig with boost=true
yourResult = tester.search("blueberry fig", true, 50);
TestingTools.checkSearch(yourResult, "blueberry fig", passOut, failOut, "Fruits50SearchBoostTester", "Test #560 checking search results for blueberry fig with boost=true");
//Test #561 checking search results for lime with boost=true
yourResult = tester.search("lime", true, 50);
TestingTools.checkSearch(yourResult, "lime", passOut, failOut, "Fruits50SearchBoostTester", "Test #561 checking search results for lime with boost=true");
//Test #562 checking search results for kiwi lime peach peach with boost=true
yourResult = tester.search("kiwi lime peach peach", true, 50);
TestingTools.checkSearch(yourResult, "kiwi lime peach peach", passOut, failOut, "Fruits50SearchBoostTester", "Test #562 checking search results for kiwi lime peach peach with boost=true");
//Test #563 checking search results for strawberry papaya strawberry blueberry banana with boost=true
yourResult = tester.search("strawberry papaya strawberry blueberry banana", true, 50);
TestingTools.checkSearch(yourResult, "strawberry papaya strawberry blueberry banana", passOut, failOut, "Fruits50SearchBoostTester", "Test #563 checking search results for strawberry papaya strawberry blueberry banana with boost=true");
//Test #564 checking search results for cherry coconut apple tomato with boost=true
yourResult = tester.search("cherry coconut apple tomato", true, 50);
TestingTools.checkSearch(yourResult, "cherry coconut apple tomato", passOut, failOut, "Fruits50SearchBoostTester", "Test #564 checking search results for cherry coconut apple tomato with boost=true");
//Test #565 checking search results for fig fig apple tomato with boost=true
yourResult = tester.search("fig fig apple tomato", true, 50);
TestingTools.checkSearch(yourResult, "fig fig apple tomato", passOut, failOut, "Fruits50SearchBoostTester", "Test #565 checking search results for fig fig apple tomato with boost=true");
//Test #566 checking search results for peach pear papaya with boost=true
yourResult = tester.search("peach pear papaya", true, 50);
TestingTools.checkSearch(yourResult, "peach pear papaya", passOut, failOut, "Fruits50SearchBoostTester", "Test #566 checking search results for peach pear papaya with boost=true");
//Test #567 checking search results for blueberry apple strawberry banana kiwi with boost=true
yourResult = tester.search("blueberry apple strawberry banana kiwi", true, 50);
TestingTools.checkSearch(yourResult, "blueberry apple strawberry banana kiwi", passOut, failOut, "Fruits50SearchBoostTester", "Test #567 checking search results for blueberry apple strawberry banana kiwi with boost=true");
//Test #568 checking search results for pear kiwi strawberry tomato papaya with boost=true
yourResult = tester.search("pear kiwi strawberry tomato papaya", true, 50);
TestingTools.checkSearch(yourResult, "pear kiwi strawberry tomato papaya", passOut, failOut, "Fruits50SearchBoostTester", "Test #568 checking search results for pear kiwi strawberry tomato papaya with boost=true");
//Test #569 checking search results for cherry with boost=true
yourResult = tester.search("cherry", true, 50);
TestingTools.checkSearch(yourResult, "cherry", passOut, failOut, "Fruits50SearchBoostTester", "Test #569 checking search results for cherry with boost=true");
//Test #570 checking search results for apricot coconut papaya with boost=true
yourResult = tester.search("apricot coconut papaya", true, 50);
TestingTools.checkSearch(yourResult, "apricot coconut papaya", passOut, failOut, "Fruits50SearchBoostTester", "Test #570 checking search results for apricot coconut papaya with boost=true");
//Test #571 checking search results for apricot pear apricot apricot with boost=true
yourResult = tester.search("apricot pear apricot apricot", true, 50);
TestingTools.checkSearch(yourResult, "apricot pear apricot apricot", passOut, failOut, "Fruits50SearchBoostTester", "Test #571 checking search results for apricot pear apricot apricot with boost=true");
//Test #572 checking search results for cherry with boost=true
yourResult = tester.search("cherry", true, 50);
TestingTools.checkSearch(yourResult, "cherry", passOut, failOut, "Fruits50SearchBoostTester", "Test #572 checking search results for cherry with boost=true");
//Test #573 checking search results for pear apple apple papaya apple with boost=true
yourResult = tester.search("pear apple apple papaya apple", true, 50);
TestingTools.checkSearch(yourResult, "pear apple apple papaya apple", passOut, failOut, "Fruits50SearchBoostTester", "Test #573 checking search results for pear apple apple papaya apple with boost=true");
//Test #574 checking search results for kiwi with boost=true
yourResult = tester.search("kiwi", true, 50);
TestingTools.checkSearch(yourResult, "kiwi", passOut, failOut, "Fruits50SearchBoostTester", "Test #574 checking search results for kiwi with boost=true");
//Test #575 checking search results for kiwi pear with boost=true
yourResult = tester.search("kiwi pear", true, 50);
TestingTools.checkSearch(yourResult, "kiwi pear", passOut, failOut, "Fruits50SearchBoostTester", "Test #575 checking search results for kiwi pear with boost=true");
//Test #576 checking search results for kiwi blueberry cherry strawberry papaya with boost=true
yourResult = tester.search("kiwi blueberry cherry strawberry papaya", true, 50);
TestingTools.checkSearch(yourResult, "kiwi blueberry cherry strawberry papaya", passOut, failOut, "Fruits50SearchBoostTester", "Test #576 checking search results for kiwi blueberry cherry strawberry papaya with boost=true");
//Test #577 checking search results for fig apple fig kiwi strawberry with boost=true
yourResult = tester.search("fig apple fig kiwi strawberry", true, 50);
TestingTools.checkSearch(yourResult, "fig apple fig kiwi strawberry", passOut, failOut, "Fruits50SearchBoostTester", "Test #577 checking search results for fig apple fig kiwi strawberry with boost=true");
//Test #578 checking search results for peach coconut coconut with boost=true
yourResult = tester.search("peach coconut coconut", true, 50);
TestingTools.checkSearch(yourResult, "peach coconut coconut", passOut, failOut, "Fruits50SearchBoostTester", "Test #578 checking search results for peach coconut coconut with boost=true");
//Test #579 checking search results for strawberry tomato with boost=true
yourResult = tester.search("strawberry tomato", true, 50);
TestingTools.checkSearch(yourResult, "strawberry tomato", passOut, failOut, "Fruits50SearchBoostTester", "Test #579 checking search results for strawberry tomato with boost=true");
//Test #580 checking search results for papaya peach blueberry with boost=true
yourResult = tester.search("papaya peach blueberry", true, 50);
TestingTools.checkSearch(yourResult, "papaya peach blueberry", passOut, failOut, "Fruits50SearchBoostTester", "Test #580 checking search results for papaya peach blueberry with boost=true");
//Test #581 checking search results for apricot papaya tomato coconut tomato with boost=true
yourResult = tester.search("apricot papaya tomato coconut tomato", true, 50);
TestingTools.checkSearch(yourResult, "apricot papaya tomato coconut tomato", passOut, failOut, "Fruits50SearchBoostTester", "Test #581 checking search results for apricot papaya tomato coconut tomato with boost=true");
//Test #582 checking search results for blueberry strawberry apricot with boost=true
yourResult = tester.search("blueberry strawberry apricot", true, 50);
TestingTools.checkSearch(yourResult, "blueberry strawberry apricot", passOut, failOut, "Fruits50SearchBoostTester", "Test #582 checking search results for blueberry strawberry apricot with boost=true");
//Test #583 checking search results for apricot cherry papaya with boost=true
yourResult = tester.search("apricot cherry papaya", true, 50);
TestingTools.checkSearch(yourResult, "apricot cherry papaya", passOut, failOut, "Fruits50SearchBoostTester", "Test #583 checking search results for apricot cherry papaya with boost=true");
//Test #584 checking search results for pear lime peach apple with boost=true
yourResult = tester.search("pear lime peach apple", true, 50);
TestingTools.checkSearch(yourResult, "pear lime peach apple", passOut, failOut, "Fruits50SearchBoostTester", "Test #584 checking search results for pear lime peach apple with boost=true");
//Test #585 checking search results for fig tomato blueberry lime peach with boost=true
yourResult = tester.search("fig tomato blueberry lime peach", true, 50);
TestingTools.checkSearch(yourResult, "fig tomato blueberry lime peach", passOut, failOut, "Fruits50SearchBoostTester", "Test #585 checking search results for fig tomato blueberry lime peach with boost=true");
//Test #586 checking search results for strawberry cherry kiwi coconut tomato with boost=true
yourResult = tester.search("strawberry cherry kiwi coconut tomato", true, 50);
TestingTools.checkSearch(yourResult, "strawberry cherry kiwi coconut tomato", passOut, failOut, "Fruits50SearchBoostTester", "Test #586 checking search results for strawberry cherry kiwi coconut tomato with boost=true");
//Test #587 checking search results for apple lime with boost=true
yourResult = tester.search("apple lime", true, 50);
TestingTools.checkSearch(yourResult, "apple lime", passOut, failOut, "Fruits50SearchBoostTester", "Test #587 checking search results for apple lime with boost=true");
//Test #588 checking search results for pear apple apricot cherry with boost=true
yourResult = tester.search("pear apple apricot cherry", true, 50);
TestingTools.checkSearch(yourResult, "pear apple apricot cherry", passOut, failOut, "Fruits50SearchBoostTester", "Test #588 checking search results for pear apple apricot cherry with boost=true");
//Test #589 checking search results for apple coconut cherry apricot with boost=true
yourResult = tester.search("apple coconut cherry apricot", true, 50);
TestingTools.checkSearch(yourResult, "apple coconut cherry apricot", passOut, failOut, "Fruits50SearchBoostTester", "Test #589 checking search results for apple coconut cherry apricot with boost=true");
//Test #590 checking search results for apple apple peach lime with boost=true
yourResult = tester.search("apple apple peach lime", true, 50);
TestingTools.checkSearch(yourResult, "apple apple peach lime", passOut, failOut, "Fruits50SearchBoostTester", "Test #590 checking search results for apple apple peach lime with boost=true");
//Test #591 checking search results for peach tomato blueberry pear with boost=true
yourResult = tester.search("peach tomato blueberry pear", true, 50);
TestingTools.checkSearch(yourResult, "peach tomato blueberry pear", passOut, failOut, "Fruits50SearchBoostTester", "Test #591 checking search results for peach tomato blueberry pear with boost=true");
//Test #592 checking search results for banana strawberry apricot with boost=true
yourResult = tester.search("banana strawberry apricot", true, 50);
TestingTools.checkSearch(yourResult, "banana strawberry apricot", passOut, failOut, "Fruits50SearchBoostTester", "Test #592 checking search results for banana strawberry apricot with boost=true");
//Test #593 checking search results for pear with boost=true
yourResult = tester.search("pear", true, 50);
TestingTools.checkSearch(yourResult, "pear", passOut, failOut, "Fruits50SearchBoostTester", "Test #593 checking search results for pear with boost=true");
//Test #594 checking search results for lime lime with boost=true
yourResult = tester.search("lime lime", true, 50);
TestingTools.checkSearch(yourResult, "lime lime", passOut, failOut, "Fruits50SearchBoostTester", "Test #594 checking search results for lime lime with boost=true");
//Test #595 checking search results for fig cherry with boost=true
yourResult = tester.search("fig cherry", true, 50);
TestingTools.checkSearch(yourResult, "fig cherry", passOut, failOut, "Fruits50SearchBoostTester", "Test #595 checking search results for fig cherry with boost=true");
//Test #596 checking search results for apple banana with boost=true
yourResult = tester.search("apple banana", true, 50);
TestingTools.checkSearch(yourResult, "apple banana", passOut, failOut, "Fruits50SearchBoostTester", "Test #596 checking search results for apple banana with boost=true");
//Test #597 checking search results for apricot tomato tomato pear with boost=true
yourResult = tester.search("apricot tomato tomato pear", true, 50);
TestingTools.checkSearch(yourResult, "apricot tomato tomato pear", passOut, failOut, "Fruits50SearchBoostTester", "Test #597 checking search results for apricot tomato tomato pear with boost=true");
//Test #598 checking search results for papaya apple strawberry with boost=true
yourResult = tester.search("papaya apple strawberry", true, 50);
TestingTools.checkSearch(yourResult, "papaya apple strawberry", passOut, failOut, "Fruits50SearchBoostTester", "Test #598 checking search results for papaya apple strawberry with boost=true");
//Test #599 checking search results for apple lime apple kiwi kiwi with boost=true
yourResult = tester.search("apple lime apple kiwi kiwi", true, 50);
TestingTools.checkSearch(yourResult, "apple lime apple kiwi kiwi", passOut, failOut, "Fruits50SearchBoostTester", "Test #599 checking search results for apple lime apple kiwi kiwi with boost=true");
//Test #600 checking search results for fig cherry blueberry coconut with boost=true
yourResult = tester.search("fig cherry blueberry coconut", true, 50);
TestingTools.checkSearch(yourResult, "fig cherry blueberry coconut", passOut, failOut, "Fruits50SearchBoostTester", "Test #600 checking search results for fig cherry blueberry coconut with boost=true");
//Test #601 checking search results for kiwi coconut blueberry tomato blueberry with boost=true
yourResult = tester.search("kiwi coconut blueberry tomato blueberry", true, 50);
TestingTools.checkSearch(yourResult, "kiwi coconut blueberry tomato blueberry", passOut, failOut, "Fruits50SearchBoostTester", "Test #601 checking search results for kiwi coconut blueberry tomato blueberry with boost=true");
//Test #602 checking search results for cherry with boost=true
yourResult = tester.search("cherry", true, 50);
TestingTools.checkSearch(yourResult, "cherry", passOut, failOut, "Fruits50SearchBoostTester", "Test #602 checking search results for cherry with boost=true");
//Test #603 checking search results for fig kiwi fig tomato with boost=true
yourResult = tester.search("fig kiwi fig tomato", true, 50);
TestingTools.checkSearch(yourResult, "fig kiwi fig tomato", passOut, failOut, "Fruits50SearchBoostTester", "Test #603 checking search results for fig kiwi fig tomato with boost=true");
//Test #604 checking search results for strawberry apricot tomato kiwi pear with boost=true
yourResult = tester.search("strawberry apricot tomato kiwi pear", true, 50);
TestingTools.checkSearch(yourResult, "strawberry apricot tomato kiwi pear", passOut, failOut, "Fruits50SearchBoostTester", "Test #604 checking search results for strawberry apricot tomato kiwi pear with boost=true");
//Test #605 checking search results for pear blueberry with boost=true
yourResult = tester.search("pear blueberry", true, 50);
TestingTools.checkSearch(yourResult, "pear blueberry", passOut, failOut, "Fruits50SearchBoostTester", "Test #605 checking search results for pear blueberry with boost=true");
//Test #606 checking search results for blueberry with boost=true
yourResult = tester.search("blueberry", true, 50);
TestingTools.checkSearch(yourResult, "blueberry", passOut, failOut, "Fruits50SearchBoostTester", "Test #606 checking search results for blueberry with boost=true");
//Test #607 checking search results for lime kiwi with boost=true
yourResult = tester.search("lime kiwi", true, 50);
TestingTools.checkSearch(yourResult, "lime kiwi", passOut, failOut, "Fruits50SearchBoostTester", "Test #607 checking search results for lime kiwi with boost=true");
//Test #608 checking search results for lime tomato tomato papaya with boost=true
yourResult = tester.search("lime tomato tomato papaya", true, 50);
TestingTools.checkSearch(yourResult, "lime tomato tomato papaya", passOut, failOut, "Fruits50SearchBoostTester", "Test #608 checking search results for lime tomato tomato papaya with boost=true");
failOut.close();
passOut.close();
}
}
