import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.*;
public class Fruits25SearchNoBoostTester {public static void main(String[] args) throws Exception{
ProjectTester tester = new ProjectTesterImp(); //Instantiate your own ProjectTester instance here
tester.initialize();
tester.crawl("https://people.scs.carleton.ca/~avamckenney/fruits25/N-0.html");
runTest(tester);}public static void runTest(ProjectTester tester) throws Exception{
PrintWriter failOut = new PrintWriter(new FileWriter("Fruits25-SearchNoBoost-failed.txt"));
PrintWriter passOut = new PrintWriter(new FileWriter("Fruits25-SearchNoBoost-passed.txt"));
List<SearchResult> yourResult; 
//Test #334 checking search results for kiwi cherry with boost=false
yourResult = tester.search("kiwi cherry", false, 25);
TestingTools.checkSearch(yourResult, "kiwi cherry", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #334 checking search results for kiwi cherry with boost=false");
//Test #335 checking search results for kiwi papaya apricot banana kiwi with boost=false
yourResult = tester.search("kiwi papaya apricot banana kiwi", false, 25);
TestingTools.checkSearch(yourResult, "kiwi papaya apricot banana kiwi", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #335 checking search results for kiwi papaya apricot banana kiwi with boost=false");
//Test #336 checking search results for blueberry with boost=false
yourResult = tester.search("blueberry", false, 25);
TestingTools.checkSearch(yourResult, "blueberry", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #336 checking search results for blueberry with boost=false");
//Test #337 checking search results for papaya cherry apple with boost=false
yourResult = tester.search("papaya cherry apple", false, 25);
TestingTools.checkSearch(yourResult, "papaya cherry apple", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #337 checking search results for papaya cherry apple with boost=false");
//Test #338 checking search results for peach apricot papaya pear with boost=false
yourResult = tester.search("peach apricot papaya pear", false, 25);
TestingTools.checkSearch(yourResult, "peach apricot papaya pear", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #338 checking search results for peach apricot papaya pear with boost=false");
//Test #339 checking search results for blueberry pear with boost=false
yourResult = tester.search("blueberry pear", false, 25);
TestingTools.checkSearch(yourResult, "blueberry pear", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #339 checking search results for blueberry pear with boost=false");
//Test #340 checking search results for tomato apricot tomato coconut with boost=false
yourResult = tester.search("tomato apricot tomato coconut", false, 25);
TestingTools.checkSearch(yourResult, "tomato apricot tomato coconut", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #340 checking search results for tomato apricot tomato coconut with boost=false");
//Test #341 checking search results for peach tomato lime kiwi with boost=false
yourResult = tester.search("peach tomato lime kiwi", false, 25);
TestingTools.checkSearch(yourResult, "peach tomato lime kiwi", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #341 checking search results for peach tomato lime kiwi with boost=false");
//Test #342 checking search results for tomato fig with boost=false
yourResult = tester.search("tomato fig", false, 25);
TestingTools.checkSearch(yourResult, "tomato fig", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #342 checking search results for tomato fig with boost=false");
//Test #343 checking search results for apricot with boost=false
yourResult = tester.search("apricot", false, 25);
TestingTools.checkSearch(yourResult, "apricot", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #343 checking search results for apricot with boost=false");
//Test #344 checking search results for kiwi coconut with boost=false
yourResult = tester.search("kiwi coconut", false, 25);
TestingTools.checkSearch(yourResult, "kiwi coconut", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #344 checking search results for kiwi coconut with boost=false");
//Test #345 checking search results for tomato papaya apple blueberry apple with boost=false
yourResult = tester.search("tomato papaya apple blueberry apple", false, 25);
TestingTools.checkSearch(yourResult, "tomato papaya apple blueberry apple", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #345 checking search results for tomato papaya apple blueberry apple with boost=false");
//Test #346 checking search results for strawberry pear lime with boost=false
yourResult = tester.search("strawberry pear lime", false, 25);
TestingTools.checkSearch(yourResult, "strawberry pear lime", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #346 checking search results for strawberry pear lime with boost=false");
//Test #347 checking search results for fig strawberry with boost=false
yourResult = tester.search("fig strawberry", false, 25);
TestingTools.checkSearch(yourResult, "fig strawberry", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #347 checking search results for fig strawberry with boost=false");
//Test #348 checking search results for strawberry apricot blueberry banana with boost=false
yourResult = tester.search("strawberry apricot blueberry banana", false, 25);
TestingTools.checkSearch(yourResult, "strawberry apricot blueberry banana", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #348 checking search results for strawberry apricot blueberry banana with boost=false");
//Test #349 checking search results for pear blueberry coconut with boost=false
yourResult = tester.search("pear blueberry coconut", false, 25);
TestingTools.checkSearch(yourResult, "pear blueberry coconut", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #349 checking search results for pear blueberry coconut with boost=false");
//Test #350 checking search results for lime banana with boost=false
yourResult = tester.search("lime banana", false, 25);
TestingTools.checkSearch(yourResult, "lime banana", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #350 checking search results for lime banana with boost=false");
//Test #351 checking search results for kiwi cherry strawberry strawberry with boost=false
yourResult = tester.search("kiwi cherry strawberry strawberry", false, 25);
TestingTools.checkSearch(yourResult, "kiwi cherry strawberry strawberry", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #351 checking search results for kiwi cherry strawberry strawberry with boost=false");
//Test #352 checking search results for coconut kiwi pear with boost=false
yourResult = tester.search("coconut kiwi pear", false, 25);
TestingTools.checkSearch(yourResult, "coconut kiwi pear", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #352 checking search results for coconut kiwi pear with boost=false");
//Test #353 checking search results for coconut papaya kiwi apple with boost=false
yourResult = tester.search("coconut papaya kiwi apple", false, 25);
TestingTools.checkSearch(yourResult, "coconut papaya kiwi apple", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #353 checking search results for coconut papaya kiwi apple with boost=false");
//Test #354 checking search results for strawberry kiwi with boost=false
yourResult = tester.search("strawberry kiwi", false, 25);
TestingTools.checkSearch(yourResult, "strawberry kiwi", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #354 checking search results for strawberry kiwi with boost=false");
//Test #355 checking search results for apricot with boost=false
yourResult = tester.search("apricot", false, 25);
TestingTools.checkSearch(yourResult, "apricot", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #355 checking search results for apricot with boost=false");
//Test #356 checking search results for kiwi cherry papaya with boost=false
yourResult = tester.search("kiwi cherry papaya", false, 25);
TestingTools.checkSearch(yourResult, "kiwi cherry papaya", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #356 checking search results for kiwi cherry papaya with boost=false");
//Test #357 checking search results for fig apple with boost=false
yourResult = tester.search("fig apple", false, 25);
TestingTools.checkSearch(yourResult, "fig apple", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #357 checking search results for fig apple with boost=false");
//Test #358 checking search results for cherry apricot apricot pear with boost=false
yourResult = tester.search("cherry apricot apricot pear", false, 25);
TestingTools.checkSearch(yourResult, "cherry apricot apricot pear", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #358 checking search results for cherry apricot apricot pear with boost=false");
//Test #359 checking search results for banana peach papaya apricot blueberry with boost=false
yourResult = tester.search("banana peach papaya apricot blueberry", false, 25);
TestingTools.checkSearch(yourResult, "banana peach papaya apricot blueberry", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #359 checking search results for banana peach papaya apricot blueberry with boost=false");
//Test #360 checking search results for pear coconut fig with boost=false
yourResult = tester.search("pear coconut fig", false, 25);
TestingTools.checkSearch(yourResult, "pear coconut fig", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #360 checking search results for pear coconut fig with boost=false");
//Test #361 checking search results for coconut papaya kiwi with boost=false
yourResult = tester.search("coconut papaya kiwi", false, 25);
TestingTools.checkSearch(yourResult, "coconut papaya kiwi", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #361 checking search results for coconut papaya kiwi with boost=false");
//Test #362 checking search results for kiwi apple with boost=false
yourResult = tester.search("kiwi apple", false, 25);
TestingTools.checkSearch(yourResult, "kiwi apple", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #362 checking search results for kiwi apple with boost=false");
//Test #363 checking search results for pear with boost=false
yourResult = tester.search("pear", false, 25);
TestingTools.checkSearch(yourResult, "pear", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #363 checking search results for pear with boost=false");
//Test #364 checking search results for kiwi cherry lime strawberry with boost=false
yourResult = tester.search("kiwi cherry lime strawberry", false, 25);
TestingTools.checkSearch(yourResult, "kiwi cherry lime strawberry", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #364 checking search results for kiwi cherry lime strawberry with boost=false");
//Test #365 checking search results for tomato cherry kiwi with boost=false
yourResult = tester.search("tomato cherry kiwi", false, 25);
TestingTools.checkSearch(yourResult, "tomato cherry kiwi", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #365 checking search results for tomato cherry kiwi with boost=false");
//Test #366 checking search results for apricot lime strawberry with boost=false
yourResult = tester.search("apricot lime strawberry", false, 25);
TestingTools.checkSearch(yourResult, "apricot lime strawberry", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #366 checking search results for apricot lime strawberry with boost=false");
//Test #367 checking search results for pear coconut cherry apricot banana with boost=false
yourResult = tester.search("pear coconut cherry apricot banana", false, 25);
TestingTools.checkSearch(yourResult, "pear coconut cherry apricot banana", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #367 checking search results for pear coconut cherry apricot banana with boost=false");
//Test #368 checking search results for blueberry peach lime with boost=false
yourResult = tester.search("blueberry peach lime", false, 25);
TestingTools.checkSearch(yourResult, "blueberry peach lime", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #368 checking search results for blueberry peach lime with boost=false");
//Test #369 checking search results for fig with boost=false
yourResult = tester.search("fig", false, 25);
TestingTools.checkSearch(yourResult, "fig", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #369 checking search results for fig with boost=false");
//Test #370 checking search results for fig papaya blueberry with boost=false
yourResult = tester.search("fig papaya blueberry", false, 25);
TestingTools.checkSearch(yourResult, "fig papaya blueberry", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #370 checking search results for fig papaya blueberry with boost=false");
//Test #371 checking search results for blueberry with boost=false
yourResult = tester.search("blueberry", false, 25);
TestingTools.checkSearch(yourResult, "blueberry", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #371 checking search results for blueberry with boost=false");
//Test #372 checking search results for tomato apple kiwi pear peach with boost=false
yourResult = tester.search("tomato apple kiwi pear peach", false, 25);
TestingTools.checkSearch(yourResult, "tomato apple kiwi pear peach", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #372 checking search results for tomato apple kiwi pear peach with boost=false");
//Test #373 checking search results for lime apricot cherry tomato strawberry with boost=false
yourResult = tester.search("lime apricot cherry tomato strawberry", false, 25);
TestingTools.checkSearch(yourResult, "lime apricot cherry tomato strawberry", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #373 checking search results for lime apricot cherry tomato strawberry with boost=false");
//Test #374 checking search results for pear with boost=false
yourResult = tester.search("pear", false, 25);
TestingTools.checkSearch(yourResult, "pear", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #374 checking search results for pear with boost=false");
//Test #375 checking search results for strawberry coconut apple pear with boost=false
yourResult = tester.search("strawberry coconut apple pear", false, 25);
TestingTools.checkSearch(yourResult, "strawberry coconut apple pear", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #375 checking search results for strawberry coconut apple pear with boost=false");
//Test #376 checking search results for peach apricot tomato apple cherry with boost=false
yourResult = tester.search("peach apricot tomato apple cherry", false, 25);
TestingTools.checkSearch(yourResult, "peach apricot tomato apple cherry", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #376 checking search results for peach apricot tomato apple cherry with boost=false");
//Test #377 checking search results for peach kiwi cherry with boost=false
yourResult = tester.search("peach kiwi cherry", false, 25);
TestingTools.checkSearch(yourResult, "peach kiwi cherry", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #377 checking search results for peach kiwi cherry with boost=false");
//Test #378 checking search results for tomato fig tomato fig with boost=false
yourResult = tester.search("tomato fig tomato fig", false, 25);
TestingTools.checkSearch(yourResult, "tomato fig tomato fig", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #378 checking search results for tomato fig tomato fig with boost=false");
//Test #379 checking search results for peach banana coconut with boost=false
yourResult = tester.search("peach banana coconut", false, 25);
TestingTools.checkSearch(yourResult, "peach banana coconut", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #379 checking search results for peach banana coconut with boost=false");
//Test #380 checking search results for papaya peach banana with boost=false
yourResult = tester.search("papaya peach banana", false, 25);
TestingTools.checkSearch(yourResult, "papaya peach banana", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #380 checking search results for papaya peach banana with boost=false");
//Test #381 checking search results for apple papaya with boost=false
yourResult = tester.search("apple papaya", false, 25);
TestingTools.checkSearch(yourResult, "apple papaya", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #381 checking search results for apple papaya with boost=false");
//Test #382 checking search results for cherry banana with boost=false
yourResult = tester.search("cherry banana", false, 25);
TestingTools.checkSearch(yourResult, "cherry banana", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #382 checking search results for cherry banana with boost=false");
//Test #383 checking search results for kiwi pear cherry peach fig with boost=false
yourResult = tester.search("kiwi pear cherry peach fig", false, 25);
TestingTools.checkSearch(yourResult, "kiwi pear cherry peach fig", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #383 checking search results for kiwi pear cherry peach fig with boost=false");
//Test #384 checking search results for lime apple coconut with boost=false
yourResult = tester.search("lime apple coconut", false, 25);
TestingTools.checkSearch(yourResult, "lime apple coconut", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #384 checking search results for lime apple coconut with boost=false");
//Test #385 checking search results for peach apple pear tomato tomato with boost=false
yourResult = tester.search("peach apple pear tomato tomato", false, 25);
TestingTools.checkSearch(yourResult, "peach apple pear tomato tomato", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #385 checking search results for peach apple pear tomato tomato with boost=false");
//Test #386 checking search results for tomato strawberry coconut with boost=false
yourResult = tester.search("tomato strawberry coconut", false, 25);
TestingTools.checkSearch(yourResult, "tomato strawberry coconut", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #386 checking search results for tomato strawberry coconut with boost=false");
//Test #387 checking search results for tomato pear tomato pear with boost=false
yourResult = tester.search("tomato pear tomato pear", false, 25);
TestingTools.checkSearch(yourResult, "tomato pear tomato pear", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #387 checking search results for tomato pear tomato pear with boost=false");
//Test #388 checking search results for tomato papaya banana with boost=false
yourResult = tester.search("tomato papaya banana", false, 25);
TestingTools.checkSearch(yourResult, "tomato papaya banana", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #388 checking search results for tomato papaya banana with boost=false");
//Test #389 checking search results for cherry blueberry apricot cherry strawberry with boost=false
yourResult = tester.search("cherry blueberry apricot cherry strawberry", false, 25);
TestingTools.checkSearch(yourResult, "cherry blueberry apricot cherry strawberry", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #389 checking search results for cherry blueberry apricot cherry strawberry with boost=false");
//Test #390 checking search results for blueberry with boost=false
yourResult = tester.search("blueberry", false, 25);
TestingTools.checkSearch(yourResult, "blueberry", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #390 checking search results for blueberry with boost=false");
//Test #391 checking search results for tomato coconut with boost=false
yourResult = tester.search("tomato coconut", false, 25);
TestingTools.checkSearch(yourResult, "tomato coconut", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #391 checking search results for tomato coconut with boost=false");
//Test #392 checking search results for cherry apricot cherry apple peach with boost=false
yourResult = tester.search("cherry apricot cherry apple peach", false, 25);
TestingTools.checkSearch(yourResult, "cherry apricot cherry apple peach", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #392 checking search results for cherry apricot cherry apple peach with boost=false");
//Test #393 checking search results for strawberry peach apple fig cherry with boost=false
yourResult = tester.search("strawberry peach apple fig cherry", false, 25);
TestingTools.checkSearch(yourResult, "strawberry peach apple fig cherry", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #393 checking search results for strawberry peach apple fig cherry with boost=false");
//Test #394 checking search results for apricot apple kiwi cherry with boost=false
yourResult = tester.search("apricot apple kiwi cherry", false, 25);
TestingTools.checkSearch(yourResult, "apricot apple kiwi cherry", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #394 checking search results for apricot apple kiwi cherry with boost=false");
//Test #395 checking search results for apricot banana with boost=false
yourResult = tester.search("apricot banana", false, 25);
TestingTools.checkSearch(yourResult, "apricot banana", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #395 checking search results for apricot banana with boost=false");
//Test #396 checking search results for fig pear fig banana with boost=false
yourResult = tester.search("fig pear fig banana", false, 25);
TestingTools.checkSearch(yourResult, "fig pear fig banana", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #396 checking search results for fig pear fig banana with boost=false");
//Test #397 checking search results for banana blueberry peach cherry with boost=false
yourResult = tester.search("banana blueberry peach cherry", false, 25);
TestingTools.checkSearch(yourResult, "banana blueberry peach cherry", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #397 checking search results for banana blueberry peach cherry with boost=false");
//Test #398 checking search results for kiwi peach cherry with boost=false
yourResult = tester.search("kiwi peach cherry", false, 25);
TestingTools.checkSearch(yourResult, "kiwi peach cherry", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #398 checking search results for kiwi peach cherry with boost=false");
//Test #399 checking search results for fig strawberry coconut blueberry pear with boost=false
yourResult = tester.search("fig strawberry coconut blueberry pear", false, 25);
TestingTools.checkSearch(yourResult, "fig strawberry coconut blueberry pear", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #399 checking search results for fig strawberry coconut blueberry pear with boost=false");
//Test #400 checking search results for peach apple banana with boost=false
yourResult = tester.search("peach apple banana", false, 25);
TestingTools.checkSearch(yourResult, "peach apple banana", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #400 checking search results for peach apple banana with boost=false");
//Test #401 checking search results for lime apple with boost=false
yourResult = tester.search("lime apple", false, 25);
TestingTools.checkSearch(yourResult, "lime apple", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #401 checking search results for lime apple with boost=false");
//Test #402 checking search results for kiwi with boost=false
yourResult = tester.search("kiwi", false, 25);
TestingTools.checkSearch(yourResult, "kiwi", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #402 checking search results for kiwi with boost=false");
//Test #403 checking search results for strawberry apricot papaya with boost=false
yourResult = tester.search("strawberry apricot papaya", false, 25);
TestingTools.checkSearch(yourResult, "strawberry apricot papaya", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #403 checking search results for strawberry apricot papaya with boost=false");
//Test #404 checking search results for pear cherry fig papaya papaya with boost=false
yourResult = tester.search("pear cherry fig papaya papaya", false, 25);
TestingTools.checkSearch(yourResult, "pear cherry fig papaya papaya", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #404 checking search results for pear cherry fig papaya papaya with boost=false");
//Test #405 checking search results for blueberry peach blueberry cherry cherry with boost=false
yourResult = tester.search("blueberry peach blueberry cherry cherry", false, 25);
TestingTools.checkSearch(yourResult, "blueberry peach blueberry cherry cherry", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #405 checking search results for blueberry peach blueberry cherry cherry with boost=false");
//Test #406 checking search results for banana banana peach kiwi with boost=false
yourResult = tester.search("banana banana peach kiwi", false, 25);
TestingTools.checkSearch(yourResult, "banana banana peach kiwi", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #406 checking search results for banana banana peach kiwi with boost=false");
//Test #407 checking search results for coconut apricot pear coconut peach with boost=false
yourResult = tester.search("coconut apricot pear coconut peach", false, 25);
TestingTools.checkSearch(yourResult, "coconut apricot pear coconut peach", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #407 checking search results for coconut apricot pear coconut peach with boost=false");
//Test #408 checking search results for tomato tomato kiwi with boost=false
yourResult = tester.search("tomato tomato kiwi", false, 25);
TestingTools.checkSearch(yourResult, "tomato tomato kiwi", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #408 checking search results for tomato tomato kiwi with boost=false");
//Test #409 checking search results for blueberry blueberry with boost=false
yourResult = tester.search("blueberry blueberry", false, 25);
TestingTools.checkSearch(yourResult, "blueberry blueberry", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #409 checking search results for blueberry blueberry with boost=false");
//Test #410 checking search results for papaya fig kiwi peach strawberry with boost=false
yourResult = tester.search("papaya fig kiwi peach strawberry", false, 25);
TestingTools.checkSearch(yourResult, "papaya fig kiwi peach strawberry", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #410 checking search results for papaya fig kiwi peach strawberry with boost=false");
//Test #411 checking search results for pear strawberry banana tomato with boost=false
yourResult = tester.search("pear strawberry banana tomato", false, 25);
TestingTools.checkSearch(yourResult, "pear strawberry banana tomato", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #411 checking search results for pear strawberry banana tomato with boost=false");
//Test #412 checking search results for strawberry fig apple with boost=false
yourResult = tester.search("strawberry fig apple", false, 25);
TestingTools.checkSearch(yourResult, "strawberry fig apple", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #412 checking search results for strawberry fig apple with boost=false");
//Test #413 checking search results for fig peach fig with boost=false
yourResult = tester.search("fig peach fig", false, 25);
TestingTools.checkSearch(yourResult, "fig peach fig", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #413 checking search results for fig peach fig with boost=false");
//Test #414 checking search results for pear tomato kiwi coconut lime with boost=false
yourResult = tester.search("pear tomato kiwi coconut lime", false, 25);
TestingTools.checkSearch(yourResult, "pear tomato kiwi coconut lime", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #414 checking search results for pear tomato kiwi coconut lime with boost=false");
//Test #415 checking search results for pear tomato kiwi pear blueberry with boost=false
yourResult = tester.search("pear tomato kiwi pear blueberry", false, 25);
TestingTools.checkSearch(yourResult, "pear tomato kiwi pear blueberry", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #415 checking search results for pear tomato kiwi pear blueberry with boost=false");
//Test #416 checking search results for blueberry kiwi peach pear with boost=false
yourResult = tester.search("blueberry kiwi peach pear", false, 25);
TestingTools.checkSearch(yourResult, "blueberry kiwi peach pear", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #416 checking search results for blueberry kiwi peach pear with boost=false");
//Test #417 checking search results for apricot kiwi lime coconut strawberry with boost=false
yourResult = tester.search("apricot kiwi lime coconut strawberry", false, 25);
TestingTools.checkSearch(yourResult, "apricot kiwi lime coconut strawberry", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #417 checking search results for apricot kiwi lime coconut strawberry with boost=false");
//Test #418 checking search results for strawberry peach tomato apple strawberry with boost=false
yourResult = tester.search("strawberry peach tomato apple strawberry", false, 25);
TestingTools.checkSearch(yourResult, "strawberry peach tomato apple strawberry", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #418 checking search results for strawberry peach tomato apple strawberry with boost=false");
//Test #419 checking search results for pear with boost=false
yourResult = tester.search("pear", false, 25);
TestingTools.checkSearch(yourResult, "pear", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #419 checking search results for pear with boost=false");
//Test #420 checking search results for kiwi kiwi apricot strawberry kiwi with boost=false
yourResult = tester.search("kiwi kiwi apricot strawberry kiwi", false, 25);
TestingTools.checkSearch(yourResult, "kiwi kiwi apricot strawberry kiwi", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #420 checking search results for kiwi kiwi apricot strawberry kiwi with boost=false");
//Test #421 checking search results for fig blueberry strawberry apple with boost=false
yourResult = tester.search("fig blueberry strawberry apple", false, 25);
TestingTools.checkSearch(yourResult, "fig blueberry strawberry apple", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #421 checking search results for fig blueberry strawberry apple with boost=false");
//Test #422 checking search results for apricot kiwi blueberry with boost=false
yourResult = tester.search("apricot kiwi blueberry", false, 25);
TestingTools.checkSearch(yourResult, "apricot kiwi blueberry", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #422 checking search results for apricot kiwi blueberry with boost=false");
//Test #423 checking search results for cherry pear with boost=false
yourResult = tester.search("cherry pear", false, 25);
TestingTools.checkSearch(yourResult, "cherry pear", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #423 checking search results for cherry pear with boost=false");
//Test #424 checking search results for strawberry kiwi strawberry apricot with boost=false
yourResult = tester.search("strawberry kiwi strawberry apricot", false, 25);
TestingTools.checkSearch(yourResult, "strawberry kiwi strawberry apricot", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #424 checking search results for strawberry kiwi strawberry apricot with boost=false");
//Test #425 checking search results for tomato banana with boost=false
yourResult = tester.search("tomato banana", false, 25);
TestingTools.checkSearch(yourResult, "tomato banana", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #425 checking search results for tomato banana with boost=false");
//Test #426 checking search results for fig with boost=false
yourResult = tester.search("fig", false, 25);
TestingTools.checkSearch(yourResult, "fig", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #426 checking search results for fig with boost=false");
//Test #427 checking search results for fig pear apple with boost=false
yourResult = tester.search("fig pear apple", false, 25);
TestingTools.checkSearch(yourResult, "fig pear apple", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #427 checking search results for fig pear apple with boost=false");
//Test #428 checking search results for coconut apricot papaya with boost=false
yourResult = tester.search("coconut apricot papaya", false, 25);
TestingTools.checkSearch(yourResult, "coconut apricot papaya", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #428 checking search results for coconut apricot papaya with boost=false");
//Test #429 checking search results for banana with boost=false
yourResult = tester.search("banana", false, 25);
TestingTools.checkSearch(yourResult, "banana", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #429 checking search results for banana with boost=false");
//Test #430 checking search results for kiwi tomato banana with boost=false
yourResult = tester.search("kiwi tomato banana", false, 25);
TestingTools.checkSearch(yourResult, "kiwi tomato banana", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #430 checking search results for kiwi tomato banana with boost=false");
//Test #431 checking search results for coconut kiwi pear tomato with boost=false
yourResult = tester.search("coconut kiwi pear tomato", false, 25);
TestingTools.checkSearch(yourResult, "coconut kiwi pear tomato", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #431 checking search results for coconut kiwi pear tomato with boost=false");
//Test #432 checking search results for pear tomato with boost=false
yourResult = tester.search("pear tomato", false, 25);
TestingTools.checkSearch(yourResult, "pear tomato", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #432 checking search results for pear tomato with boost=false");
//Test #433 checking search results for papaya peach blueberry with boost=false
yourResult = tester.search("papaya peach blueberry", false, 25);
TestingTools.checkSearch(yourResult, "papaya peach blueberry", passOut, failOut, "Fruits25SearchNoBoostTester", "Test #433 checking search results for papaya peach blueberry with boost=false");
failOut.close();
passOut.close();
}
}
