import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.*;
public class TinyFruitsASearchNoBoostTester {public static void main(String[] args) throws Exception{
ProjectTester tester = new ProjectTesterImp(); //Instantiate your own ProjectTester instance here
tester.initialize();
tester.crawl("https://people.scs.carleton.ca/~avamckenney/tinyfruitsA/N-0.html");
runTest(tester);}public static void runTest(ProjectTester tester) throws Exception{
PrintWriter failOut = new PrintWriter(new FileWriter("TinyFruitsA-SearchNoBoost-failed.txt"));
PrintWriter passOut = new PrintWriter(new FileWriter("TinyFruitsA-SearchNoBoost-passed.txt"));
List<SearchResult> yourResult; 
//Test #289 checking search results for tomato pear with boost=false
yourResult = tester.search("tomato pear", false, 10);
TestingTools.checkSearch(yourResult, "tomato pear", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #289 checking search results for tomato pear with boost=false");
//Test #290 checking search results for lime papaya papaya with boost=false
yourResult = tester.search("lime papaya papaya", false, 10);
TestingTools.checkSearch(yourResult, "lime papaya papaya", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #290 checking search results for lime papaya papaya with boost=false");
//Test #291 checking search results for peach with boost=false
yourResult = tester.search("peach", false, 10);
TestingTools.checkSearch(yourResult, "peach", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #291 checking search results for peach with boost=false");
//Test #292 checking search results for lime peach peach with boost=false
yourResult = tester.search("lime peach peach", false, 10);
TestingTools.checkSearch(yourResult, "lime peach peach", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #292 checking search results for lime peach peach with boost=false");
//Test #293 checking search results for fig apricot with boost=false
yourResult = tester.search("fig apricot", false, 10);
TestingTools.checkSearch(yourResult, "fig apricot", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #293 checking search results for fig apricot with boost=false");
//Test #294 checking search results for banana cherry with boost=false
yourResult = tester.search("banana cherry", false, 10);
TestingTools.checkSearch(yourResult, "banana cherry", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #294 checking search results for banana cherry with boost=false");
//Test #295 checking search results for banana tomato lime pear with boost=false
yourResult = tester.search("banana tomato lime pear", false, 10);
TestingTools.checkSearch(yourResult, "banana tomato lime pear", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #295 checking search results for banana tomato lime pear with boost=false");
//Test #296 checking search results for apricot with boost=false
yourResult = tester.search("apricot", false, 10);
TestingTools.checkSearch(yourResult, "apricot", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #296 checking search results for apricot with boost=false");
//Test #297 checking search results for apricot with boost=false
yourResult = tester.search("apricot", false, 10);
TestingTools.checkSearch(yourResult, "apricot", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #297 checking search results for apricot with boost=false");
//Test #298 checking search results for lime tomato peach fig coconut with boost=false
yourResult = tester.search("lime tomato peach fig coconut", false, 10);
TestingTools.checkSearch(yourResult, "lime tomato peach fig coconut", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #298 checking search results for lime tomato peach fig coconut with boost=false");
//Test #299 checking search results for papaya papaya lime with boost=false
yourResult = tester.search("papaya papaya lime", false, 10);
TestingTools.checkSearch(yourResult, "papaya papaya lime", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #299 checking search results for papaya papaya lime with boost=false");
//Test #300 checking search results for banana apple apple fig with boost=false
yourResult = tester.search("banana apple apple fig", false, 10);
TestingTools.checkSearch(yourResult, "banana apple apple fig", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #300 checking search results for banana apple apple fig with boost=false");
//Test #301 checking search results for coconut lime banana peach with boost=false
yourResult = tester.search("coconut lime banana peach", false, 10);
TestingTools.checkSearch(yourResult, "coconut lime banana peach", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #301 checking search results for coconut lime banana peach with boost=false");
//Test #302 checking search results for fig banana with boost=false
yourResult = tester.search("fig banana", false, 10);
TestingTools.checkSearch(yourResult, "fig banana", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #302 checking search results for fig banana with boost=false");
//Test #303 checking search results for pear fig apple pear lime with boost=false
yourResult = tester.search("pear fig apple pear lime", false, 10);
TestingTools.checkSearch(yourResult, "pear fig apple pear lime", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #303 checking search results for pear fig apple pear lime with boost=false");
//Test #304 checking search results for pear kiwi kiwi peach with boost=false
yourResult = tester.search("pear kiwi kiwi peach", false, 10);
TestingTools.checkSearch(yourResult, "pear kiwi kiwi peach", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #304 checking search results for pear kiwi kiwi peach with boost=false");
//Test #305 checking search results for pear strawberry apricot with boost=false
yourResult = tester.search("pear strawberry apricot", false, 10);
TestingTools.checkSearch(yourResult, "pear strawberry apricot", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #305 checking search results for pear strawberry apricot with boost=false");
//Test #306 checking search results for cherry papaya coconut banana with boost=false
yourResult = tester.search("cherry papaya coconut banana", false, 10);
TestingTools.checkSearch(yourResult, "cherry papaya coconut banana", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #306 checking search results for cherry papaya coconut banana with boost=false");
//Test #307 checking search results for apricot with boost=false
yourResult = tester.search("apricot", false, 10);
TestingTools.checkSearch(yourResult, "apricot", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #307 checking search results for apricot with boost=false");
//Test #308 checking search results for cherry kiwi apricot blueberry tomato with boost=false
yourResult = tester.search("cherry kiwi apricot blueberry tomato", false, 10);
TestingTools.checkSearch(yourResult, "cherry kiwi apricot blueberry tomato", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #308 checking search results for cherry kiwi apricot blueberry tomato with boost=false");
//Test #309 checking search results for cherry peach strawberry kiwi with boost=false
yourResult = tester.search("cherry peach strawberry kiwi", false, 10);
TestingTools.checkSearch(yourResult, "cherry peach strawberry kiwi", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #309 checking search results for cherry peach strawberry kiwi with boost=false");
//Test #310 checking search results for strawberry banana papaya with boost=false
yourResult = tester.search("strawberry banana papaya", false, 10);
TestingTools.checkSearch(yourResult, "strawberry banana papaya", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #310 checking search results for strawberry banana papaya with boost=false");
//Test #311 checking search results for apricot with boost=false
yourResult = tester.search("apricot", false, 10);
TestingTools.checkSearch(yourResult, "apricot", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #311 checking search results for apricot with boost=false");
//Test #312 checking search results for apricot pear papaya with boost=false
yourResult = tester.search("apricot pear papaya", false, 10);
TestingTools.checkSearch(yourResult, "apricot pear papaya", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #312 checking search results for apricot pear papaya with boost=false");
//Test #313 checking search results for pear lime peach with boost=false
yourResult = tester.search("pear lime peach", false, 10);
TestingTools.checkSearch(yourResult, "pear lime peach", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #313 checking search results for pear lime peach with boost=false");
//Test #314 checking search results for peach with boost=false
yourResult = tester.search("peach", false, 10);
TestingTools.checkSearch(yourResult, "peach", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #314 checking search results for peach with boost=false");
//Test #315 checking search results for strawberry banana kiwi with boost=false
yourResult = tester.search("strawberry banana kiwi", false, 10);
TestingTools.checkSearch(yourResult, "strawberry banana kiwi", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #315 checking search results for strawberry banana kiwi with boost=false");
//Test #316 checking search results for coconut tomato with boost=false
yourResult = tester.search("coconut tomato", false, 10);
TestingTools.checkSearch(yourResult, "coconut tomato", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #316 checking search results for coconut tomato with boost=false");
//Test #317 checking search results for tomato lime coconut blueberry with boost=false
yourResult = tester.search("tomato lime coconut blueberry", false, 10);
TestingTools.checkSearch(yourResult, "tomato lime coconut blueberry", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #317 checking search results for tomato lime coconut blueberry with boost=false");
//Test #318 checking search results for strawberry fig coconut coconut with boost=false
yourResult = tester.search("strawberry fig coconut coconut", false, 10);
TestingTools.checkSearch(yourResult, "strawberry fig coconut coconut", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #318 checking search results for strawberry fig coconut coconut with boost=false");
//Test #319 checking search results for apricot pear with boost=false
yourResult = tester.search("apricot pear", false, 10);
TestingTools.checkSearch(yourResult, "apricot pear", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #319 checking search results for apricot pear with boost=false");
//Test #320 checking search results for apricot fig kiwi strawberry apple with boost=false
yourResult = tester.search("apricot fig kiwi strawberry apple", false, 10);
TestingTools.checkSearch(yourResult, "apricot fig kiwi strawberry apple", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #320 checking search results for apricot fig kiwi strawberry apple with boost=false");
//Test #321 checking search results for papaya tomato papaya with boost=false
yourResult = tester.search("papaya tomato papaya", false, 10);
TestingTools.checkSearch(yourResult, "papaya tomato papaya", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #321 checking search results for papaya tomato papaya with boost=false");
//Test #322 checking search results for blueberry peach with boost=false
yourResult = tester.search("blueberry peach", false, 10);
TestingTools.checkSearch(yourResult, "blueberry peach", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #322 checking search results for blueberry peach with boost=false");
//Test #323 checking search results for tomato coconut with boost=false
yourResult = tester.search("tomato coconut", false, 10);
TestingTools.checkSearch(yourResult, "tomato coconut", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #323 checking search results for tomato coconut with boost=false");
//Test #324 checking search results for kiwi blueberry apple strawberry peach with boost=false
yourResult = tester.search("kiwi blueberry apple strawberry peach", false, 10);
TestingTools.checkSearch(yourResult, "kiwi blueberry apple strawberry peach", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #324 checking search results for kiwi blueberry apple strawberry peach with boost=false");
//Test #325 checking search results for kiwi blueberry papaya blueberry with boost=false
yourResult = tester.search("kiwi blueberry papaya blueberry", false, 10);
TestingTools.checkSearch(yourResult, "kiwi blueberry papaya blueberry", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #325 checking search results for kiwi blueberry papaya blueberry with boost=false");
//Test #326 checking search results for kiwi coconut with boost=false
yourResult = tester.search("kiwi coconut", false, 10);
TestingTools.checkSearch(yourResult, "kiwi coconut", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #326 checking search results for kiwi coconut with boost=false");
//Test #327 checking search results for pear strawberry with boost=false
yourResult = tester.search("pear strawberry", false, 10);
TestingTools.checkSearch(yourResult, "pear strawberry", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #327 checking search results for pear strawberry with boost=false");
//Test #328 checking search results for peach coconut apricot apple with boost=false
yourResult = tester.search("peach coconut apricot apple", false, 10);
TestingTools.checkSearch(yourResult, "peach coconut apricot apple", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #328 checking search results for peach coconut apricot apple with boost=false");
//Test #329 checking search results for banana blueberry coconut with boost=false
yourResult = tester.search("banana blueberry coconut", false, 10);
TestingTools.checkSearch(yourResult, "banana blueberry coconut", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #329 checking search results for banana blueberry coconut with boost=false");
//Test #330 checking search results for apple fig apricot peach with boost=false
yourResult = tester.search("apple fig apricot peach", false, 10);
TestingTools.checkSearch(yourResult, "apple fig apricot peach", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #330 checking search results for apple fig apricot peach with boost=false");
//Test #331 checking search results for papaya apple pear with boost=false
yourResult = tester.search("papaya apple pear", false, 10);
TestingTools.checkSearch(yourResult, "papaya apple pear", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #331 checking search results for papaya apple pear with boost=false");
//Test #332 checking search results for strawberry blueberry blueberry coconut apricot with boost=false
yourResult = tester.search("strawberry blueberry blueberry coconut apricot", false, 10);
TestingTools.checkSearch(yourResult, "strawberry blueberry blueberry coconut apricot", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #332 checking search results for strawberry blueberry blueberry coconut apricot with boost=false");
//Test #333 checking search results for coconut kiwi apricot with boost=false
yourResult = tester.search("coconut kiwi apricot", false, 10);
TestingTools.checkSearch(yourResult, "coconut kiwi apricot", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #333 checking search results for coconut kiwi apricot with boost=false");
//Test #334 checking search results for pear blueberry tomato fig strawberry with boost=false
yourResult = tester.search("pear blueberry tomato fig strawberry", false, 10);
TestingTools.checkSearch(yourResult, "pear blueberry tomato fig strawberry", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #334 checking search results for pear blueberry tomato fig strawberry with boost=false");
//Test #335 checking search results for pear fig blueberry coconut banana with boost=false
yourResult = tester.search("pear fig blueberry coconut banana", false, 10);
TestingTools.checkSearch(yourResult, "pear fig blueberry coconut banana", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #335 checking search results for pear fig blueberry coconut banana with boost=false");
//Test #336 checking search results for kiwi cherry tomato lime pear with boost=false
yourResult = tester.search("kiwi cherry tomato lime pear", false, 10);
TestingTools.checkSearch(yourResult, "kiwi cherry tomato lime pear", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #336 checking search results for kiwi cherry tomato lime pear with boost=false");
//Test #337 checking search results for apricot apple tomato with boost=false
yourResult = tester.search("apricot apple tomato", false, 10);
TestingTools.checkSearch(yourResult, "apricot apple tomato", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #337 checking search results for apricot apple tomato with boost=false");
//Test #338 checking search results for peach with boost=false
yourResult = tester.search("peach", false, 10);
TestingTools.checkSearch(yourResult, "peach", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #338 checking search results for peach with boost=false");
//Test #339 checking search results for lime coconut with boost=false
yourResult = tester.search("lime coconut", false, 10);
TestingTools.checkSearch(yourResult, "lime coconut", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #339 checking search results for lime coconut with boost=false");
//Test #340 checking search results for blueberry cherry peach with boost=false
yourResult = tester.search("blueberry cherry peach", false, 10);
TestingTools.checkSearch(yourResult, "blueberry cherry peach", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #340 checking search results for blueberry cherry peach with boost=false");
//Test #341 checking search results for tomato fig apricot blueberry banana with boost=false
yourResult = tester.search("tomato fig apricot blueberry banana", false, 10);
TestingTools.checkSearch(yourResult, "tomato fig apricot blueberry banana", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #341 checking search results for tomato fig apricot blueberry banana with boost=false");
//Test #342 checking search results for strawberry coconut papaya with boost=false
yourResult = tester.search("strawberry coconut papaya", false, 10);
TestingTools.checkSearch(yourResult, "strawberry coconut papaya", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #342 checking search results for strawberry coconut papaya with boost=false");
//Test #343 checking search results for papaya fig tomato with boost=false
yourResult = tester.search("papaya fig tomato", false, 10);
TestingTools.checkSearch(yourResult, "papaya fig tomato", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #343 checking search results for papaya fig tomato with boost=false");
//Test #344 checking search results for fig coconut coconut banana with boost=false
yourResult = tester.search("fig coconut coconut banana", false, 10);
TestingTools.checkSearch(yourResult, "fig coconut coconut banana", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #344 checking search results for fig coconut coconut banana with boost=false");
//Test #345 checking search results for apple banana fig with boost=false
yourResult = tester.search("apple banana fig", false, 10);
TestingTools.checkSearch(yourResult, "apple banana fig", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #345 checking search results for apple banana fig with boost=false");
//Test #346 checking search results for apricot pear with boost=false
yourResult = tester.search("apricot pear", false, 10);
TestingTools.checkSearch(yourResult, "apricot pear", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #346 checking search results for apricot pear with boost=false");
//Test #347 checking search results for coconut fig peach apricot lime with boost=false
yourResult = tester.search("coconut fig peach apricot lime", false, 10);
TestingTools.checkSearch(yourResult, "coconut fig peach apricot lime", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #347 checking search results for coconut fig peach apricot lime with boost=false");
//Test #348 checking search results for apple apricot with boost=false
yourResult = tester.search("apple apricot", false, 10);
TestingTools.checkSearch(yourResult, "apple apricot", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #348 checking search results for apple apricot with boost=false");
//Test #349 checking search results for cherry papaya with boost=false
yourResult = tester.search("cherry papaya", false, 10);
TestingTools.checkSearch(yourResult, "cherry papaya", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #349 checking search results for cherry papaya with boost=false");
//Test #350 checking search results for apricot lime cherry fig cherry with boost=false
yourResult = tester.search("apricot lime cherry fig cherry", false, 10);
TestingTools.checkSearch(yourResult, "apricot lime cherry fig cherry", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #350 checking search results for apricot lime cherry fig cherry with boost=false");
//Test #351 checking search results for apricot cherry banana with boost=false
yourResult = tester.search("apricot cherry banana", false, 10);
TestingTools.checkSearch(yourResult, "apricot cherry banana", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #351 checking search results for apricot cherry banana with boost=false");
//Test #352 checking search results for papaya strawberry peach with boost=false
yourResult = tester.search("papaya strawberry peach", false, 10);
TestingTools.checkSearch(yourResult, "papaya strawberry peach", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #352 checking search results for papaya strawberry peach with boost=false");
//Test #353 checking search results for cherry pear pear peach with boost=false
yourResult = tester.search("cherry pear pear peach", false, 10);
TestingTools.checkSearch(yourResult, "cherry pear pear peach", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #353 checking search results for cherry pear pear peach with boost=false");
//Test #354 checking search results for strawberry tomato peach kiwi apple with boost=false
yourResult = tester.search("strawberry tomato peach kiwi apple", false, 10);
TestingTools.checkSearch(yourResult, "strawberry tomato peach kiwi apple", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #354 checking search results for strawberry tomato peach kiwi apple with boost=false");
//Test #355 checking search results for papaya tomato peach peach with boost=false
yourResult = tester.search("papaya tomato peach peach", false, 10);
TestingTools.checkSearch(yourResult, "papaya tomato peach peach", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #355 checking search results for papaya tomato peach peach with boost=false");
//Test #356 checking search results for kiwi coconut tomato blueberry lime with boost=false
yourResult = tester.search("kiwi coconut tomato blueberry lime", false, 10);
TestingTools.checkSearch(yourResult, "kiwi coconut tomato blueberry lime", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #356 checking search results for kiwi coconut tomato blueberry lime with boost=false");
//Test #357 checking search results for lime coconut banana cherry pear with boost=false
yourResult = tester.search("lime coconut banana cherry pear", false, 10);
TestingTools.checkSearch(yourResult, "lime coconut banana cherry pear", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #357 checking search results for lime coconut banana cherry pear with boost=false");
//Test #358 checking search results for apricot pear banana with boost=false
yourResult = tester.search("apricot pear banana", false, 10);
TestingTools.checkSearch(yourResult, "apricot pear banana", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #358 checking search results for apricot pear banana with boost=false");
//Test #359 checking search results for papaya papaya apricot with boost=false
yourResult = tester.search("papaya papaya apricot", false, 10);
TestingTools.checkSearch(yourResult, "papaya papaya apricot", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #359 checking search results for papaya papaya apricot with boost=false");
//Test #360 checking search results for blueberry apple papaya banana fig with boost=false
yourResult = tester.search("blueberry apple papaya banana fig", false, 10);
TestingTools.checkSearch(yourResult, "blueberry apple papaya banana fig", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #360 checking search results for blueberry apple papaya banana fig with boost=false");
//Test #361 checking search results for apricot with boost=false
yourResult = tester.search("apricot", false, 10);
TestingTools.checkSearch(yourResult, "apricot", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #361 checking search results for apricot with boost=false");
//Test #362 checking search results for pear banana coconut banana with boost=false
yourResult = tester.search("pear banana coconut banana", false, 10);
TestingTools.checkSearch(yourResult, "pear banana coconut banana", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #362 checking search results for pear banana coconut banana with boost=false");
//Test #363 checking search results for apple kiwi peach with boost=false
yourResult = tester.search("apple kiwi peach", false, 10);
TestingTools.checkSearch(yourResult, "apple kiwi peach", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #363 checking search results for apple kiwi peach with boost=false");
//Test #364 checking search results for pear fig with boost=false
yourResult = tester.search("pear fig", false, 10);
TestingTools.checkSearch(yourResult, "pear fig", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #364 checking search results for pear fig with boost=false");
//Test #365 checking search results for coconut papaya with boost=false
yourResult = tester.search("coconut papaya", false, 10);
TestingTools.checkSearch(yourResult, "coconut papaya", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #365 checking search results for coconut papaya with boost=false");
//Test #366 checking search results for tomato blueberry strawberry tomato apricot with boost=false
yourResult = tester.search("tomato blueberry strawberry tomato apricot", false, 10);
TestingTools.checkSearch(yourResult, "tomato blueberry strawberry tomato apricot", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #366 checking search results for tomato blueberry strawberry tomato apricot with boost=false");
//Test #367 checking search results for papaya lime with boost=false
yourResult = tester.search("papaya lime", false, 10);
TestingTools.checkSearch(yourResult, "papaya lime", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #367 checking search results for papaya lime with boost=false");
//Test #368 checking search results for coconut fig apple with boost=false
yourResult = tester.search("coconut fig apple", false, 10);
TestingTools.checkSearch(yourResult, "coconut fig apple", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #368 checking search results for coconut fig apple with boost=false");
//Test #369 checking search results for coconut blueberry pear with boost=false
yourResult = tester.search("coconut blueberry pear", false, 10);
TestingTools.checkSearch(yourResult, "coconut blueberry pear", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #369 checking search results for coconut blueberry pear with boost=false");
//Test #370 checking search results for apricot coconut with boost=false
yourResult = tester.search("apricot coconut", false, 10);
TestingTools.checkSearch(yourResult, "apricot coconut", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #370 checking search results for apricot coconut with boost=false");
//Test #371 checking search results for lime papaya tomato with boost=false
yourResult = tester.search("lime papaya tomato", false, 10);
TestingTools.checkSearch(yourResult, "lime papaya tomato", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #371 checking search results for lime papaya tomato with boost=false");
//Test #372 checking search results for peach cherry coconut apricot with boost=false
yourResult = tester.search("peach cherry coconut apricot", false, 10);
TestingTools.checkSearch(yourResult, "peach cherry coconut apricot", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #372 checking search results for peach cherry coconut apricot with boost=false");
//Test #373 checking search results for strawberry blueberry coconut with boost=false
yourResult = tester.search("strawberry blueberry coconut", false, 10);
TestingTools.checkSearch(yourResult, "strawberry blueberry coconut", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #373 checking search results for strawberry blueberry coconut with boost=false");
//Test #374 checking search results for pear coconut tomato with boost=false
yourResult = tester.search("pear coconut tomato", false, 10);
TestingTools.checkSearch(yourResult, "pear coconut tomato", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #374 checking search results for pear coconut tomato with boost=false");
//Test #375 checking search results for lime apricot with boost=false
yourResult = tester.search("lime apricot", false, 10);
TestingTools.checkSearch(yourResult, "lime apricot", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #375 checking search results for lime apricot with boost=false");
//Test #376 checking search results for apricot blueberry tomato with boost=false
yourResult = tester.search("apricot blueberry tomato", false, 10);
TestingTools.checkSearch(yourResult, "apricot blueberry tomato", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #376 checking search results for apricot blueberry tomato with boost=false");
//Test #377 checking search results for strawberry papaya coconut with boost=false
yourResult = tester.search("strawberry papaya coconut", false, 10);
TestingTools.checkSearch(yourResult, "strawberry papaya coconut", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #377 checking search results for strawberry papaya coconut with boost=false");
//Test #378 checking search results for strawberry cherry strawberry apricot with boost=false
yourResult = tester.search("strawberry cherry strawberry apricot", false, 10);
TestingTools.checkSearch(yourResult, "strawberry cherry strawberry apricot", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #378 checking search results for strawberry cherry strawberry apricot with boost=false");
//Test #379 checking search results for coconut strawberry banana with boost=false
yourResult = tester.search("coconut strawberry banana", false, 10);
TestingTools.checkSearch(yourResult, "coconut strawberry banana", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #379 checking search results for coconut strawberry banana with boost=false");
//Test #380 checking search results for peach apricot peach kiwi with boost=false
yourResult = tester.search("peach apricot peach kiwi", false, 10);
TestingTools.checkSearch(yourResult, "peach apricot peach kiwi", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #380 checking search results for peach apricot peach kiwi with boost=false");
//Test #381 checking search results for pear with boost=false
yourResult = tester.search("pear", false, 10);
TestingTools.checkSearch(yourResult, "pear", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #381 checking search results for pear with boost=false");
//Test #382 checking search results for peach kiwi strawberry peach with boost=false
yourResult = tester.search("peach kiwi strawberry peach", false, 10);
TestingTools.checkSearch(yourResult, "peach kiwi strawberry peach", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #382 checking search results for peach kiwi strawberry peach with boost=false");
//Test #383 checking search results for banana lime coconut apricot strawberry with boost=false
yourResult = tester.search("banana lime coconut apricot strawberry", false, 10);
TestingTools.checkSearch(yourResult, "banana lime coconut apricot strawberry", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #383 checking search results for banana lime coconut apricot strawberry with boost=false");
//Test #384 checking search results for tomato pear banana with boost=false
yourResult = tester.search("tomato pear banana", false, 10);
TestingTools.checkSearch(yourResult, "tomato pear banana", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #384 checking search results for tomato pear banana with boost=false");
//Test #385 checking search results for peach pear papaya strawberry with boost=false
yourResult = tester.search("peach pear papaya strawberry", false, 10);
TestingTools.checkSearch(yourResult, "peach pear papaya strawberry", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #385 checking search results for peach pear papaya strawberry with boost=false");
//Test #386 checking search results for papaya papaya banana blueberry with boost=false
yourResult = tester.search("papaya papaya banana blueberry", false, 10);
TestingTools.checkSearch(yourResult, "papaya papaya banana blueberry", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #386 checking search results for papaya papaya banana blueberry with boost=false");
//Test #387 checking search results for strawberry lime papaya tomato with boost=false
yourResult = tester.search("strawberry lime papaya tomato", false, 10);
TestingTools.checkSearch(yourResult, "strawberry lime papaya tomato", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #387 checking search results for strawberry lime papaya tomato with boost=false");
//Test #388 checking search results for apricot tomato banana papaya with boost=false
yourResult = tester.search("apricot tomato banana papaya", false, 10);
TestingTools.checkSearch(yourResult, "apricot tomato banana papaya", passOut, failOut, "TinyFruitsASearchNoBoostTester", "Test #388 checking search results for apricot tomato banana papaya with boost=false");
failOut.close();
passOut.close();
}
}
