import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.*;
public class TinyFruitsSearchBoostTester {public static void main(String[] args) throws Exception{
ProjectTester tester = new ProjectTesterImp(); //Instantiate your own ProjectTester instance here
tester.initialize();
tester.crawl("https://people.scs.carleton.ca/~avamckenney/tinyfruits/N-0.html");
runTest(tester);}public static void runTest(ProjectTester tester) throws Exception{
PrintWriter failOut = new PrintWriter(new FileWriter("TinyFruits-SearchBoost-failed.txt"));
PrintWriter passOut = new PrintWriter(new FileWriter("TinyFruits-SearchBoost-passed.txt"));
List<SearchResult> yourResult; 
//Test #389 checking search results for banana tomato coconut with boost=true
yourResult = tester.search("banana tomato coconut", true, 10);
TestingTools.checkSearch(yourResult, "banana tomato coconut", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #389 checking search results for banana tomato coconut with boost=true");
//Test #390 checking search results for lime orange lime with boost=true
yourResult = tester.search("lime orange lime", true, 10);
TestingTools.checkSearch(yourResult, "lime orange lime", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #390 checking search results for lime orange lime with boost=true");
//Test #391 checking search results for fig papaya papaya peach fig with boost=true
yourResult = tester.search("fig papaya papaya peach fig", true, 10);
TestingTools.checkSearch(yourResult, "fig papaya papaya peach fig", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #391 checking search results for fig papaya papaya peach fig with boost=true");
//Test #392 checking search results for kiwi fig coconut blueberry kiwi with boost=true
yourResult = tester.search("kiwi fig coconut blueberry kiwi", true, 10);
TestingTools.checkSearch(yourResult, "kiwi fig coconut blueberry kiwi", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #392 checking search results for kiwi fig coconut blueberry kiwi with boost=true");
//Test #393 checking search results for pear coconut with boost=true
yourResult = tester.search("pear coconut", true, 10);
TestingTools.checkSearch(yourResult, "pear coconut", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #393 checking search results for pear coconut with boost=true");
//Test #394 checking search results for fig lime cherry blueberry lime with boost=true
yourResult = tester.search("fig lime cherry blueberry lime", true, 10);
TestingTools.checkSearch(yourResult, "fig lime cherry blueberry lime", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #394 checking search results for fig lime cherry blueberry lime with boost=true");
//Test #395 checking search results for kiwi apricot with boost=true
yourResult = tester.search("kiwi apricot", true, 10);
TestingTools.checkSearch(yourResult, "kiwi apricot", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #395 checking search results for kiwi apricot with boost=true");
//Test #396 checking search results for pear banana with boost=true
yourResult = tester.search("pear banana", true, 10);
TestingTools.checkSearch(yourResult, "pear banana", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #396 checking search results for pear banana with boost=true");
//Test #397 checking search results for apple kiwi apricot with boost=true
yourResult = tester.search("apple kiwi apricot", true, 10);
TestingTools.checkSearch(yourResult, "apple kiwi apricot", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #397 checking search results for apple kiwi apricot with boost=true");
//Test #398 checking search results for pear apple papaya with boost=true
yourResult = tester.search("pear apple papaya", true, 10);
TestingTools.checkSearch(yourResult, "pear apple papaya", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #398 checking search results for pear apple papaya with boost=true");
//Test #399 checking search results for apple blueberry banana with boost=true
yourResult = tester.search("apple blueberry banana", true, 10);
TestingTools.checkSearch(yourResult, "apple blueberry banana", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #399 checking search results for apple blueberry banana with boost=true");
//Test #400 checking search results for peach pear lime with boost=true
yourResult = tester.search("peach pear lime", true, 10);
TestingTools.checkSearch(yourResult, "peach pear lime", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #400 checking search results for peach pear lime with boost=true");
//Test #401 checking search results for apple with boost=true
yourResult = tester.search("apple", true, 10);
TestingTools.checkSearch(yourResult, "apple", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #401 checking search results for apple with boost=true");
//Test #402 checking search results for peach coconut papaya lime with boost=true
yourResult = tester.search("peach coconut papaya lime", true, 10);
TestingTools.checkSearch(yourResult, "peach coconut papaya lime", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #402 checking search results for peach coconut papaya lime with boost=true");
//Test #403 checking search results for tomato apple papaya with boost=true
yourResult = tester.search("tomato apple papaya", true, 10);
TestingTools.checkSearch(yourResult, "tomato apple papaya", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #403 checking search results for tomato apple papaya with boost=true");
//Test #404 checking search results for pear banana blueberry lime with boost=true
yourResult = tester.search("pear banana blueberry lime", true, 10);
TestingTools.checkSearch(yourResult, "pear banana blueberry lime", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #404 checking search results for pear banana blueberry lime with boost=true");
//Test #405 checking search results for kiwi coconut banana cherry peach with boost=true
yourResult = tester.search("kiwi coconut banana cherry peach", true, 10);
TestingTools.checkSearch(yourResult, "kiwi coconut banana cherry peach", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #405 checking search results for kiwi coconut banana cherry peach with boost=true");
//Test #406 checking search results for apple blueberry blueberry apricot peach with boost=true
yourResult = tester.search("apple blueberry blueberry apricot peach", true, 10);
TestingTools.checkSearch(yourResult, "apple blueberry blueberry apricot peach", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #406 checking search results for apple blueberry blueberry apricot peach with boost=true");
//Test #407 checking search results for pear with boost=true
yourResult = tester.search("pear", true, 10);
TestingTools.checkSearch(yourResult, "pear", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #407 checking search results for pear with boost=true");
//Test #408 checking search results for apricot pear tomato with boost=true
yourResult = tester.search("apricot pear tomato", true, 10);
TestingTools.checkSearch(yourResult, "apricot pear tomato", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #408 checking search results for apricot pear tomato with boost=true");
//Test #409 checking search results for banana banana pear with boost=true
yourResult = tester.search("banana banana pear", true, 10);
TestingTools.checkSearch(yourResult, "banana banana pear", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #409 checking search results for banana banana pear with boost=true");
//Test #410 checking search results for peach blueberry kiwi apricot with boost=true
yourResult = tester.search("peach blueberry kiwi apricot", true, 10);
TestingTools.checkSearch(yourResult, "peach blueberry kiwi apricot", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #410 checking search results for peach blueberry kiwi apricot with boost=true");
//Test #411 checking search results for orange tomato with boost=true
yourResult = tester.search("orange tomato", true, 10);
TestingTools.checkSearch(yourResult, "orange tomato", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #411 checking search results for orange tomato with boost=true");
//Test #412 checking search results for banana papaya apricot cherry with boost=true
yourResult = tester.search("banana papaya apricot cherry", true, 10);
TestingTools.checkSearch(yourResult, "banana papaya apricot cherry", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #412 checking search results for banana papaya apricot cherry with boost=true");
//Test #413 checking search results for kiwi with boost=true
yourResult = tester.search("kiwi", true, 10);
TestingTools.checkSearch(yourResult, "kiwi", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #413 checking search results for kiwi with boost=true");
//Test #414 checking search results for fig lime tomato peach coconut with boost=true
yourResult = tester.search("fig lime tomato peach coconut", true, 10);
TestingTools.checkSearch(yourResult, "fig lime tomato peach coconut", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #414 checking search results for fig lime tomato peach coconut with boost=true");
//Test #415 checking search results for lime banana with boost=true
yourResult = tester.search("lime banana", true, 10);
TestingTools.checkSearch(yourResult, "lime banana", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #415 checking search results for lime banana with boost=true");
//Test #416 checking search results for tomato pear banana with boost=true
yourResult = tester.search("tomato pear banana", true, 10);
TestingTools.checkSearch(yourResult, "tomato pear banana", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #416 checking search results for tomato pear banana with boost=true");
//Test #417 checking search results for papaya banana banana orange banana with boost=true
yourResult = tester.search("papaya banana banana orange banana", true, 10);
TestingTools.checkSearch(yourResult, "papaya banana banana orange banana", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #417 checking search results for papaya banana banana orange banana with boost=true");
//Test #418 checking search results for orange cherry pear with boost=true
yourResult = tester.search("orange cherry pear", true, 10);
TestingTools.checkSearch(yourResult, "orange cherry pear", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #418 checking search results for orange cherry pear with boost=true");
//Test #419 checking search results for orange blueberry peach tomato with boost=true
yourResult = tester.search("orange blueberry peach tomato", true, 10);
TestingTools.checkSearch(yourResult, "orange blueberry peach tomato", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #419 checking search results for orange blueberry peach tomato with boost=true");
//Test #420 checking search results for lime banana with boost=true
yourResult = tester.search("lime banana", true, 10);
TestingTools.checkSearch(yourResult, "lime banana", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #420 checking search results for lime banana with boost=true");
//Test #421 checking search results for fig pear apricot cherry tomato with boost=true
yourResult = tester.search("fig pear apricot cherry tomato", true, 10);
TestingTools.checkSearch(yourResult, "fig pear apricot cherry tomato", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #421 checking search results for fig pear apricot cherry tomato with boost=true");
//Test #422 checking search results for pear coconut coconut with boost=true
yourResult = tester.search("pear coconut coconut", true, 10);
TestingTools.checkSearch(yourResult, "pear coconut coconut", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #422 checking search results for pear coconut coconut with boost=true");
//Test #423 checking search results for lime orange pear with boost=true
yourResult = tester.search("lime orange pear", true, 10);
TestingTools.checkSearch(yourResult, "lime orange pear", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #423 checking search results for lime orange pear with boost=true");
//Test #424 checking search results for orange banana fig cherry apricot with boost=true
yourResult = tester.search("orange banana fig cherry apricot", true, 10);
TestingTools.checkSearch(yourResult, "orange banana fig cherry apricot", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #424 checking search results for orange banana fig cherry apricot with boost=true");
//Test #425 checking search results for fig apricot with boost=true
yourResult = tester.search("fig apricot", true, 10);
TestingTools.checkSearch(yourResult, "fig apricot", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #425 checking search results for fig apricot with boost=true");
//Test #426 checking search results for papaya apple peach lime with boost=true
yourResult = tester.search("papaya apple peach lime", true, 10);
TestingTools.checkSearch(yourResult, "papaya apple peach lime", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #426 checking search results for papaya apple peach lime with boost=true");
//Test #427 checking search results for blueberry blueberry with boost=true
yourResult = tester.search("blueberry blueberry", true, 10);
TestingTools.checkSearch(yourResult, "blueberry blueberry", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #427 checking search results for blueberry blueberry with boost=true");
//Test #428 checking search results for lime with boost=true
yourResult = tester.search("lime", true, 10);
TestingTools.checkSearch(yourResult, "lime", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #428 checking search results for lime with boost=true");
//Test #429 checking search results for apple apricot fig with boost=true
yourResult = tester.search("apple apricot fig", true, 10);
TestingTools.checkSearch(yourResult, "apple apricot fig", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #429 checking search results for apple apricot fig with boost=true");
//Test #430 checking search results for fig fig apricot peach banana with boost=true
yourResult = tester.search("fig fig apricot peach banana", true, 10);
TestingTools.checkSearch(yourResult, "fig fig apricot peach banana", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #430 checking search results for fig fig apricot peach banana with boost=true");
//Test #431 checking search results for orange banana pear with boost=true
yourResult = tester.search("orange banana pear", true, 10);
TestingTools.checkSearch(yourResult, "orange banana pear", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #431 checking search results for orange banana pear with boost=true");
//Test #432 checking search results for papaya with boost=true
yourResult = tester.search("papaya", true, 10);
TestingTools.checkSearch(yourResult, "papaya", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #432 checking search results for papaya with boost=true");
//Test #433 checking search results for apricot lime papaya apricot with boost=true
yourResult = tester.search("apricot lime papaya apricot", true, 10);
TestingTools.checkSearch(yourResult, "apricot lime papaya apricot", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #433 checking search results for apricot lime papaya apricot with boost=true");
//Test #434 checking search results for coconut coconut with boost=true
yourResult = tester.search("coconut coconut", true, 10);
TestingTools.checkSearch(yourResult, "coconut coconut", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #434 checking search results for coconut coconut with boost=true");
//Test #435 checking search results for coconut apple orange blueberry cherry with boost=true
yourResult = tester.search("coconut apple orange blueberry cherry", true, 10);
TestingTools.checkSearch(yourResult, "coconut apple orange blueberry cherry", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #435 checking search results for coconut apple orange blueberry cherry with boost=true");
//Test #436 checking search results for coconut tomato apricot apricot peach with boost=true
yourResult = tester.search("coconut tomato apricot apricot peach", true, 10);
TestingTools.checkSearch(yourResult, "coconut tomato apricot apricot peach", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #436 checking search results for coconut tomato apricot apricot peach with boost=true");
//Test #437 checking search results for apricot blueberry with boost=true
yourResult = tester.search("apricot blueberry", true, 10);
TestingTools.checkSearch(yourResult, "apricot blueberry", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #437 checking search results for apricot blueberry with boost=true");
//Test #438 checking search results for coconut tomato apple orange kiwi with boost=true
yourResult = tester.search("coconut tomato apple orange kiwi", true, 10);
TestingTools.checkSearch(yourResult, "coconut tomato apple orange kiwi", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #438 checking search results for coconut tomato apple orange kiwi with boost=true");
//Test #439 checking search results for apricot coconut blueberry kiwi with boost=true
yourResult = tester.search("apricot coconut blueberry kiwi", true, 10);
TestingTools.checkSearch(yourResult, "apricot coconut blueberry kiwi", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #439 checking search results for apricot coconut blueberry kiwi with boost=true");
//Test #440 checking search results for peach blueberry with boost=true
yourResult = tester.search("peach blueberry", true, 10);
TestingTools.checkSearch(yourResult, "peach blueberry", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #440 checking search results for peach blueberry with boost=true");
//Test #441 checking search results for cherry with boost=true
yourResult = tester.search("cherry", true, 10);
TestingTools.checkSearch(yourResult, "cherry", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #441 checking search results for cherry with boost=true");
//Test #442 checking search results for kiwi with boost=true
yourResult = tester.search("kiwi", true, 10);
TestingTools.checkSearch(yourResult, "kiwi", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #442 checking search results for kiwi with boost=true");
//Test #443 checking search results for lime with boost=true
yourResult = tester.search("lime", true, 10);
TestingTools.checkSearch(yourResult, "lime", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #443 checking search results for lime with boost=true");
//Test #444 checking search results for tomato orange coconut papaya lime with boost=true
yourResult = tester.search("tomato orange coconut papaya lime", true, 10);
TestingTools.checkSearch(yourResult, "tomato orange coconut papaya lime", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #444 checking search results for tomato orange coconut papaya lime with boost=true");
//Test #445 checking search results for blueberry banana blueberry with boost=true
yourResult = tester.search("blueberry banana blueberry", true, 10);
TestingTools.checkSearch(yourResult, "blueberry banana blueberry", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #445 checking search results for blueberry banana blueberry with boost=true");
//Test #446 checking search results for apple kiwi with boost=true
yourResult = tester.search("apple kiwi", true, 10);
TestingTools.checkSearch(yourResult, "apple kiwi", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #446 checking search results for apple kiwi with boost=true");
//Test #447 checking search results for cherry tomato with boost=true
yourResult = tester.search("cherry tomato", true, 10);
TestingTools.checkSearch(yourResult, "cherry tomato", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #447 checking search results for cherry tomato with boost=true");
//Test #448 checking search results for cherry apple fig with boost=true
yourResult = tester.search("cherry apple fig", true, 10);
TestingTools.checkSearch(yourResult, "cherry apple fig", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #448 checking search results for cherry apple fig with boost=true");
//Test #449 checking search results for apple banana cherry with boost=true
yourResult = tester.search("apple banana cherry", true, 10);
TestingTools.checkSearch(yourResult, "apple banana cherry", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #449 checking search results for apple banana cherry with boost=true");
//Test #450 checking search results for fig orange tomato with boost=true
yourResult = tester.search("fig orange tomato", true, 10);
TestingTools.checkSearch(yourResult, "fig orange tomato", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #450 checking search results for fig orange tomato with boost=true");
//Test #451 checking search results for tomato lime with boost=true
yourResult = tester.search("tomato lime", true, 10);
TestingTools.checkSearch(yourResult, "tomato lime", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #451 checking search results for tomato lime with boost=true");
//Test #452 checking search results for lime with boost=true
yourResult = tester.search("lime", true, 10);
TestingTools.checkSearch(yourResult, "lime", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #452 checking search results for lime with boost=true");
//Test #453 checking search results for tomato lime cherry tomato with boost=true
yourResult = tester.search("tomato lime cherry tomato", true, 10);
TestingTools.checkSearch(yourResult, "tomato lime cherry tomato", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #453 checking search results for tomato lime cherry tomato with boost=true");
//Test #454 checking search results for coconut tomato lime with boost=true
yourResult = tester.search("coconut tomato lime", true, 10);
TestingTools.checkSearch(yourResult, "coconut tomato lime", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #454 checking search results for coconut tomato lime with boost=true");
//Test #455 checking search results for coconut coconut papaya apricot lime with boost=true
yourResult = tester.search("coconut coconut papaya apricot lime", true, 10);
TestingTools.checkSearch(yourResult, "coconut coconut papaya apricot lime", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #455 checking search results for coconut coconut papaya apricot lime with boost=true");
//Test #456 checking search results for banana orange with boost=true
yourResult = tester.search("banana orange", true, 10);
TestingTools.checkSearch(yourResult, "banana orange", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #456 checking search results for banana orange with boost=true");
//Test #457 checking search results for fig kiwi pear pear with boost=true
yourResult = tester.search("fig kiwi pear pear", true, 10);
TestingTools.checkSearch(yourResult, "fig kiwi pear pear", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #457 checking search results for fig kiwi pear pear with boost=true");
//Test #458 checking search results for apple cherry lime fig lime with boost=true
yourResult = tester.search("apple cherry lime fig lime", true, 10);
TestingTools.checkSearch(yourResult, "apple cherry lime fig lime", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #458 checking search results for apple cherry lime fig lime with boost=true");
//Test #459 checking search results for orange pear tomato with boost=true
yourResult = tester.search("orange pear tomato", true, 10);
TestingTools.checkSearch(yourResult, "orange pear tomato", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #459 checking search results for orange pear tomato with boost=true");
//Test #460 checking search results for lime with boost=true
yourResult = tester.search("lime", true, 10);
TestingTools.checkSearch(yourResult, "lime", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #460 checking search results for lime with boost=true");
//Test #461 checking search results for fig papaya lime with boost=true
yourResult = tester.search("fig papaya lime", true, 10);
TestingTools.checkSearch(yourResult, "fig papaya lime", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #461 checking search results for fig papaya lime with boost=true");
//Test #462 checking search results for apricot papaya with boost=true
yourResult = tester.search("apricot papaya", true, 10);
TestingTools.checkSearch(yourResult, "apricot papaya", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #462 checking search results for apricot papaya with boost=true");
//Test #463 checking search results for papaya lime coconut with boost=true
yourResult = tester.search("papaya lime coconut", true, 10);
TestingTools.checkSearch(yourResult, "papaya lime coconut", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #463 checking search results for papaya lime coconut with boost=true");
//Test #464 checking search results for apricot cherry cherry apple with boost=true
yourResult = tester.search("apricot cherry cherry apple", true, 10);
TestingTools.checkSearch(yourResult, "apricot cherry cherry apple", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #464 checking search results for apricot cherry cherry apple with boost=true");
//Test #465 checking search results for lime coconut fig with boost=true
yourResult = tester.search("lime coconut fig", true, 10);
TestingTools.checkSearch(yourResult, "lime coconut fig", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #465 checking search results for lime coconut fig with boost=true");
//Test #466 checking search results for peach banana cherry apricot with boost=true
yourResult = tester.search("peach banana cherry apricot", true, 10);
TestingTools.checkSearch(yourResult, "peach banana cherry apricot", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #466 checking search results for peach banana cherry apricot with boost=true");
//Test #467 checking search results for cherry peach banana tomato pear with boost=true
yourResult = tester.search("cherry peach banana tomato pear", true, 10);
TestingTools.checkSearch(yourResult, "cherry peach banana tomato pear", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #467 checking search results for cherry peach banana tomato pear with boost=true");
//Test #468 checking search results for kiwi apricot pear fig orange with boost=true
yourResult = tester.search("kiwi apricot pear fig orange", true, 10);
TestingTools.checkSearch(yourResult, "kiwi apricot pear fig orange", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #468 checking search results for kiwi apricot pear fig orange with boost=true");
//Test #469 checking search results for kiwi tomato pear papaya with boost=true
yourResult = tester.search("kiwi tomato pear papaya", true, 10);
TestingTools.checkSearch(yourResult, "kiwi tomato pear papaya", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #469 checking search results for kiwi tomato pear papaya with boost=true");
//Test #470 checking search results for lime with boost=true
yourResult = tester.search("lime", true, 10);
TestingTools.checkSearch(yourResult, "lime", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #470 checking search results for lime with boost=true");
//Test #471 checking search results for tomato pear with boost=true
yourResult = tester.search("tomato pear", true, 10);
TestingTools.checkSearch(yourResult, "tomato pear", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #471 checking search results for tomato pear with boost=true");
//Test #472 checking search results for tomato tomato kiwi with boost=true
yourResult = tester.search("tomato tomato kiwi", true, 10);
TestingTools.checkSearch(yourResult, "tomato tomato kiwi", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #472 checking search results for tomato tomato kiwi with boost=true");
//Test #473 checking search results for papaya apple banana cherry banana with boost=true
yourResult = tester.search("papaya apple banana cherry banana", true, 10);
TestingTools.checkSearch(yourResult, "papaya apple banana cherry banana", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #473 checking search results for papaya apple banana cherry banana with boost=true");
//Test #474 checking search results for tomato blueberry kiwi with boost=true
yourResult = tester.search("tomato blueberry kiwi", true, 10);
TestingTools.checkSearch(yourResult, "tomato blueberry kiwi", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #474 checking search results for tomato blueberry kiwi with boost=true");
//Test #475 checking search results for cherry banana lime cherry orange with boost=true
yourResult = tester.search("cherry banana lime cherry orange", true, 10);
TestingTools.checkSearch(yourResult, "cherry banana lime cherry orange", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #475 checking search results for cherry banana lime cherry orange with boost=true");
//Test #476 checking search results for peach apple lime with boost=true
yourResult = tester.search("peach apple lime", true, 10);
TestingTools.checkSearch(yourResult, "peach apple lime", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #476 checking search results for peach apple lime with boost=true");
//Test #477 checking search results for blueberry pear fig with boost=true
yourResult = tester.search("blueberry pear fig", true, 10);
TestingTools.checkSearch(yourResult, "blueberry pear fig", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #477 checking search results for blueberry pear fig with boost=true");
//Test #478 checking search results for papaya kiwi pear with boost=true
yourResult = tester.search("papaya kiwi pear", true, 10);
TestingTools.checkSearch(yourResult, "papaya kiwi pear", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #478 checking search results for papaya kiwi pear with boost=true");
//Test #479 checking search results for coconut coconut kiwi apple with boost=true
yourResult = tester.search("coconut coconut kiwi apple", true, 10);
TestingTools.checkSearch(yourResult, "coconut coconut kiwi apple", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #479 checking search results for coconut coconut kiwi apple with boost=true");
//Test #480 checking search results for apricot papaya banana fig lime with boost=true
yourResult = tester.search("apricot papaya banana fig lime", true, 10);
TestingTools.checkSearch(yourResult, "apricot papaya banana fig lime", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #480 checking search results for apricot papaya banana fig lime with boost=true");
//Test #481 checking search results for papaya kiwi blueberry kiwi apricot with boost=true
yourResult = tester.search("papaya kiwi blueberry kiwi apricot", true, 10);
TestingTools.checkSearch(yourResult, "papaya kiwi blueberry kiwi apricot", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #481 checking search results for papaya kiwi blueberry kiwi apricot with boost=true");
//Test #482 checking search results for peach papaya with boost=true
yourResult = tester.search("peach papaya", true, 10);
TestingTools.checkSearch(yourResult, "peach papaya", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #482 checking search results for peach papaya with boost=true");
//Test #483 checking search results for papaya blueberry with boost=true
yourResult = tester.search("papaya blueberry", true, 10);
TestingTools.checkSearch(yourResult, "papaya blueberry", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #483 checking search results for papaya blueberry with boost=true");
//Test #484 checking search results for lime with boost=true
yourResult = tester.search("lime", true, 10);
TestingTools.checkSearch(yourResult, "lime", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #484 checking search results for lime with boost=true");
//Test #485 checking search results for orange papaya lime apple with boost=true
yourResult = tester.search("orange papaya lime apple", true, 10);
TestingTools.checkSearch(yourResult, "orange papaya lime apple", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #485 checking search results for orange papaya lime apple with boost=true");
//Test #486 checking search results for lime coconut orange with boost=true
yourResult = tester.search("lime coconut orange", true, 10);
TestingTools.checkSearch(yourResult, "lime coconut orange", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #486 checking search results for lime coconut orange with boost=true");
//Test #487 checking search results for blueberry lime coconut banana with boost=true
yourResult = tester.search("blueberry lime coconut banana", true, 10);
TestingTools.checkSearch(yourResult, "blueberry lime coconut banana", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #487 checking search results for blueberry lime coconut banana with boost=true");
//Test #488 checking search results for papaya fig apple with boost=true
yourResult = tester.search("papaya fig apple", true, 10);
TestingTools.checkSearch(yourResult, "papaya fig apple", passOut, failOut, "TinyFruitsSearchBoostTester", "Test #488 checking search results for papaya fig apple with boost=true");
failOut.close();
passOut.close();
}
}
