import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.*;
public class TinyFruitsASearchBoostTester {public static void main(String[] args) throws Exception{
ProjectTester tester = new ProjectTesterImp(); //Instantiate your own ProjectTester instance here
tester.initialize();
tester.crawl("https://people.scs.carleton.ca/~avamckenney/tinyfruitsA/N-0.html");
runTest(tester);}public static void runTest(ProjectTester tester) throws Exception{
PrintWriter failOut = new PrintWriter(new FileWriter("TinyFruitsA-SearchBoost-failed.txt"));
PrintWriter passOut = new PrintWriter(new FileWriter("TinyFruitsA-SearchBoost-passed.txt"));
List<SearchResult> yourResult; 
//Test #389 checking search results for apricot cherry papaya papaya strawberry with boost=true
yourResult = tester.search("apricot cherry papaya papaya strawberry", true, 10);
TestingTools.checkSearch(yourResult, "apricot cherry papaya papaya strawberry", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #389 checking search results for apricot cherry papaya papaya strawberry with boost=true");
//Test #390 checking search results for apricot apricot with boost=true
yourResult = tester.search("apricot apricot", true, 10);
TestingTools.checkSearch(yourResult, "apricot apricot", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #390 checking search results for apricot apricot with boost=true");
//Test #391 checking search results for lime strawberry papaya with boost=true
yourResult = tester.search("lime strawberry papaya", true, 10);
TestingTools.checkSearch(yourResult, "lime strawberry papaya", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #391 checking search results for lime strawberry papaya with boost=true");
//Test #392 checking search results for peach blueberry cherry with boost=true
yourResult = tester.search("peach blueberry cherry", true, 10);
TestingTools.checkSearch(yourResult, "peach blueberry cherry", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #392 checking search results for peach blueberry cherry with boost=true");
//Test #393 checking search results for coconut strawberry fig strawberry kiwi with boost=true
yourResult = tester.search("coconut strawberry fig strawberry kiwi", true, 10);
TestingTools.checkSearch(yourResult, "coconut strawberry fig strawberry kiwi", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #393 checking search results for coconut strawberry fig strawberry kiwi with boost=true");
//Test #394 checking search results for apple apricot strawberry with boost=true
yourResult = tester.search("apple apricot strawberry", true, 10);
TestingTools.checkSearch(yourResult, "apple apricot strawberry", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #394 checking search results for apple apricot strawberry with boost=true");
//Test #395 checking search results for banana papaya with boost=true
yourResult = tester.search("banana papaya", true, 10);
TestingTools.checkSearch(yourResult, "banana papaya", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #395 checking search results for banana papaya with boost=true");
//Test #396 checking search results for banana tomato lime coconut tomato with boost=true
yourResult = tester.search("banana tomato lime coconut tomato", true, 10);
TestingTools.checkSearch(yourResult, "banana tomato lime coconut tomato", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #396 checking search results for banana tomato lime coconut tomato with boost=true");
//Test #397 checking search results for blueberry strawberry apple papaya lime with boost=true
yourResult = tester.search("blueberry strawberry apple papaya lime", true, 10);
TestingTools.checkSearch(yourResult, "blueberry strawberry apple papaya lime", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #397 checking search results for blueberry strawberry apple papaya lime with boost=true");
//Test #398 checking search results for lime cherry kiwi banana with boost=true
yourResult = tester.search("lime cherry kiwi banana", true, 10);
TestingTools.checkSearch(yourResult, "lime cherry kiwi banana", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #398 checking search results for lime cherry kiwi banana with boost=true");
//Test #399 checking search results for papaya papaya strawberry peach with boost=true
yourResult = tester.search("papaya papaya strawberry peach", true, 10);
TestingTools.checkSearch(yourResult, "papaya papaya strawberry peach", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #399 checking search results for papaya papaya strawberry peach with boost=true");
//Test #400 checking search results for apple pear with boost=true
yourResult = tester.search("apple pear", true, 10);
TestingTools.checkSearch(yourResult, "apple pear", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #400 checking search results for apple pear with boost=true");
//Test #401 checking search results for strawberry banana with boost=true
yourResult = tester.search("strawberry banana", true, 10);
TestingTools.checkSearch(yourResult, "strawberry banana", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #401 checking search results for strawberry banana with boost=true");
//Test #402 checking search results for peach blueberry with boost=true
yourResult = tester.search("peach blueberry", true, 10);
TestingTools.checkSearch(yourResult, "peach blueberry", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #402 checking search results for peach blueberry with boost=true");
//Test #403 checking search results for peach pear pear apple pear with boost=true
yourResult = tester.search("peach pear pear apple pear", true, 10);
TestingTools.checkSearch(yourResult, "peach pear pear apple pear", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #403 checking search results for peach pear pear apple pear with boost=true");
//Test #404 checking search results for lime strawberry banana lime coconut with boost=true
yourResult = tester.search("lime strawberry banana lime coconut", true, 10);
TestingTools.checkSearch(yourResult, "lime strawberry banana lime coconut", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #404 checking search results for lime strawberry banana lime coconut with boost=true");
//Test #405 checking search results for strawberry pear fig pear with boost=true
yourResult = tester.search("strawberry pear fig pear", true, 10);
TestingTools.checkSearch(yourResult, "strawberry pear fig pear", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #405 checking search results for strawberry pear fig pear with boost=true");
//Test #406 checking search results for coconut with boost=true
yourResult = tester.search("coconut", true, 10);
TestingTools.checkSearch(yourResult, "coconut", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #406 checking search results for coconut with boost=true");
//Test #407 checking search results for papaya with boost=true
yourResult = tester.search("papaya", true, 10);
TestingTools.checkSearch(yourResult, "papaya", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #407 checking search results for papaya with boost=true");
//Test #408 checking search results for apricot blueberry with boost=true
yourResult = tester.search("apricot blueberry", true, 10);
TestingTools.checkSearch(yourResult, "apricot blueberry", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #408 checking search results for apricot blueberry with boost=true");
//Test #409 checking search results for papaya apple peach tomato with boost=true
yourResult = tester.search("papaya apple peach tomato", true, 10);
TestingTools.checkSearch(yourResult, "papaya apple peach tomato", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #409 checking search results for papaya apple peach tomato with boost=true");
//Test #410 checking search results for apricot with boost=true
yourResult = tester.search("apricot", true, 10);
TestingTools.checkSearch(yourResult, "apricot", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #410 checking search results for apricot with boost=true");
//Test #411 checking search results for fig cherry papaya fig with boost=true
yourResult = tester.search("fig cherry papaya fig", true, 10);
TestingTools.checkSearch(yourResult, "fig cherry papaya fig", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #411 checking search results for fig cherry papaya fig with boost=true");
//Test #412 checking search results for banana blueberry with boost=true
yourResult = tester.search("banana blueberry", true, 10);
TestingTools.checkSearch(yourResult, "banana blueberry", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #412 checking search results for banana blueberry with boost=true");
//Test #413 checking search results for papaya banana blueberry blueberry with boost=true
yourResult = tester.search("papaya banana blueberry blueberry", true, 10);
TestingTools.checkSearch(yourResult, "papaya banana blueberry blueberry", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #413 checking search results for papaya banana blueberry blueberry with boost=true");
//Test #414 checking search results for papaya lime kiwi coconut apple with boost=true
yourResult = tester.search("papaya lime kiwi coconut apple", true, 10);
TestingTools.checkSearch(yourResult, "papaya lime kiwi coconut apple", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #414 checking search results for papaya lime kiwi coconut apple with boost=true");
//Test #415 checking search results for cherry strawberry blueberry coconut with boost=true
yourResult = tester.search("cherry strawberry blueberry coconut", true, 10);
TestingTools.checkSearch(yourResult, "cherry strawberry blueberry coconut", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #415 checking search results for cherry strawberry blueberry coconut with boost=true");
//Test #416 checking search results for blueberry fig apricot peach with boost=true
yourResult = tester.search("blueberry fig apricot peach", true, 10);
TestingTools.checkSearch(yourResult, "blueberry fig apricot peach", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #416 checking search results for blueberry fig apricot peach with boost=true");
//Test #417 checking search results for banana blueberry with boost=true
yourResult = tester.search("banana blueberry", true, 10);
TestingTools.checkSearch(yourResult, "banana blueberry", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #417 checking search results for banana blueberry with boost=true");
//Test #418 checking search results for coconut with boost=true
yourResult = tester.search("coconut", true, 10);
TestingTools.checkSearch(yourResult, "coconut", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #418 checking search results for coconut with boost=true");
//Test #419 checking search results for pear with boost=true
yourResult = tester.search("pear", true, 10);
TestingTools.checkSearch(yourResult, "pear", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #419 checking search results for pear with boost=true");
//Test #420 checking search results for lime apple peach apple with boost=true
yourResult = tester.search("lime apple peach apple", true, 10);
TestingTools.checkSearch(yourResult, "lime apple peach apple", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #420 checking search results for lime apple peach apple with boost=true");
//Test #421 checking search results for strawberry peach banana tomato coconut with boost=true
yourResult = tester.search("strawberry peach banana tomato coconut", true, 10);
TestingTools.checkSearch(yourResult, "strawberry peach banana tomato coconut", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #421 checking search results for strawberry peach banana tomato coconut with boost=true");
//Test #422 checking search results for kiwi fig fig papaya fig with boost=true
yourResult = tester.search("kiwi fig fig papaya fig", true, 10);
TestingTools.checkSearch(yourResult, "kiwi fig fig papaya fig", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #422 checking search results for kiwi fig fig papaya fig with boost=true");
//Test #423 checking search results for pear lime strawberry strawberry cherry with boost=true
yourResult = tester.search("pear lime strawberry strawberry cherry", true, 10);
TestingTools.checkSearch(yourResult, "pear lime strawberry strawberry cherry", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #423 checking search results for pear lime strawberry strawberry cherry with boost=true");
//Test #424 checking search results for strawberry tomato apple pear with boost=true
yourResult = tester.search("strawberry tomato apple pear", true, 10);
TestingTools.checkSearch(yourResult, "strawberry tomato apple pear", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #424 checking search results for strawberry tomato apple pear with boost=true");
//Test #425 checking search results for coconut with boost=true
yourResult = tester.search("coconut", true, 10);
TestingTools.checkSearch(yourResult, "coconut", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #425 checking search results for coconut with boost=true");
//Test #426 checking search results for tomato apricot papaya kiwi with boost=true
yourResult = tester.search("tomato apricot papaya kiwi", true, 10);
TestingTools.checkSearch(yourResult, "tomato apricot papaya kiwi", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #426 checking search results for tomato apricot papaya kiwi with boost=true");
//Test #427 checking search results for kiwi banana with boost=true
yourResult = tester.search("kiwi banana", true, 10);
TestingTools.checkSearch(yourResult, "kiwi banana", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #427 checking search results for kiwi banana with boost=true");
//Test #428 checking search results for banana apple banana strawberry with boost=true
yourResult = tester.search("banana apple banana strawberry", true, 10);
TestingTools.checkSearch(yourResult, "banana apple banana strawberry", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #428 checking search results for banana apple banana strawberry with boost=true");
//Test #429 checking search results for blueberry apple coconut with boost=true
yourResult = tester.search("blueberry apple coconut", true, 10);
TestingTools.checkSearch(yourResult, "blueberry apple coconut", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #429 checking search results for blueberry apple coconut with boost=true");
//Test #430 checking search results for blueberry papaya with boost=true
yourResult = tester.search("blueberry papaya", true, 10);
TestingTools.checkSearch(yourResult, "blueberry papaya", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #430 checking search results for blueberry papaya with boost=true");
//Test #431 checking search results for blueberry blueberry banana papaya tomato with boost=true
yourResult = tester.search("blueberry blueberry banana papaya tomato", true, 10);
TestingTools.checkSearch(yourResult, "blueberry blueberry banana papaya tomato", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #431 checking search results for blueberry blueberry banana papaya tomato with boost=true");
//Test #432 checking search results for banana with boost=true
yourResult = tester.search("banana", true, 10);
TestingTools.checkSearch(yourResult, "banana", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #432 checking search results for banana with boost=true");
//Test #433 checking search results for kiwi pear with boost=true
yourResult = tester.search("kiwi pear", true, 10);
TestingTools.checkSearch(yourResult, "kiwi pear", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #433 checking search results for kiwi pear with boost=true");
//Test #434 checking search results for kiwi coconut fig with boost=true
yourResult = tester.search("kiwi coconut fig", true, 10);
TestingTools.checkSearch(yourResult, "kiwi coconut fig", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #434 checking search results for kiwi coconut fig with boost=true");
//Test #435 checking search results for coconut tomato apple strawberry with boost=true
yourResult = tester.search("coconut tomato apple strawberry", true, 10);
TestingTools.checkSearch(yourResult, "coconut tomato apple strawberry", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #435 checking search results for coconut tomato apple strawberry with boost=true");
//Test #436 checking search results for blueberry apricot with boost=true
yourResult = tester.search("blueberry apricot", true, 10);
TestingTools.checkSearch(yourResult, "blueberry apricot", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #436 checking search results for blueberry apricot with boost=true");
//Test #437 checking search results for peach apricot fig with boost=true
yourResult = tester.search("peach apricot fig", true, 10);
TestingTools.checkSearch(yourResult, "peach apricot fig", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #437 checking search results for peach apricot fig with boost=true");
//Test #438 checking search results for papaya pear peach with boost=true
yourResult = tester.search("papaya pear peach", true, 10);
TestingTools.checkSearch(yourResult, "papaya pear peach", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #438 checking search results for papaya pear peach with boost=true");
//Test #439 checking search results for coconut papaya blueberry fig with boost=true
yourResult = tester.search("coconut papaya blueberry fig", true, 10);
TestingTools.checkSearch(yourResult, "coconut papaya blueberry fig", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #439 checking search results for coconut papaya blueberry fig with boost=true");
//Test #440 checking search results for fig pear cherry pear blueberry with boost=true
yourResult = tester.search("fig pear cherry pear blueberry", true, 10);
TestingTools.checkSearch(yourResult, "fig pear cherry pear blueberry", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #440 checking search results for fig pear cherry pear blueberry with boost=true");
//Test #441 checking search results for banana banana lime apricot papaya with boost=true
yourResult = tester.search("banana banana lime apricot papaya", true, 10);
TestingTools.checkSearch(yourResult, "banana banana lime apricot papaya", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #441 checking search results for banana banana lime apricot papaya with boost=true");
//Test #442 checking search results for tomato banana kiwi kiwi cherry with boost=true
yourResult = tester.search("tomato banana kiwi kiwi cherry", true, 10);
TestingTools.checkSearch(yourResult, "tomato banana kiwi kiwi cherry", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #442 checking search results for tomato banana kiwi kiwi cherry with boost=true");
//Test #443 checking search results for fig pear cherry pear fig with boost=true
yourResult = tester.search("fig pear cherry pear fig", true, 10);
TestingTools.checkSearch(yourResult, "fig pear cherry pear fig", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #443 checking search results for fig pear cherry pear fig with boost=true");
//Test #444 checking search results for strawberry apricot pear strawberry with boost=true
yourResult = tester.search("strawberry apricot pear strawberry", true, 10);
TestingTools.checkSearch(yourResult, "strawberry apricot pear strawberry", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #444 checking search results for strawberry apricot pear strawberry with boost=true");
//Test #445 checking search results for peach peach with boost=true
yourResult = tester.search("peach peach", true, 10);
TestingTools.checkSearch(yourResult, "peach peach", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #445 checking search results for peach peach with boost=true");
//Test #446 checking search results for peach coconut banana fig with boost=true
yourResult = tester.search("peach coconut banana fig", true, 10);
TestingTools.checkSearch(yourResult, "peach coconut banana fig", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #446 checking search results for peach coconut banana fig with boost=true");
//Test #447 checking search results for pear with boost=true
yourResult = tester.search("pear", true, 10);
TestingTools.checkSearch(yourResult, "pear", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #447 checking search results for pear with boost=true");
//Test #448 checking search results for banana with boost=true
yourResult = tester.search("banana", true, 10);
TestingTools.checkSearch(yourResult, "banana", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #448 checking search results for banana with boost=true");
//Test #449 checking search results for cherry apricot apricot fig tomato with boost=true
yourResult = tester.search("cherry apricot apricot fig tomato", true, 10);
TestingTools.checkSearch(yourResult, "cherry apricot apricot fig tomato", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #449 checking search results for cherry apricot apricot fig tomato with boost=true");
//Test #450 checking search results for tomato fig apricot apricot with boost=true
yourResult = tester.search("tomato fig apricot apricot", true, 10);
TestingTools.checkSearch(yourResult, "tomato fig apricot apricot", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #450 checking search results for tomato fig apricot apricot with boost=true");
//Test #451 checking search results for apricot cherry fig with boost=true
yourResult = tester.search("apricot cherry fig", true, 10);
TestingTools.checkSearch(yourResult, "apricot cherry fig", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #451 checking search results for apricot cherry fig with boost=true");
//Test #452 checking search results for cherry pear blueberry fig blueberry with boost=true
yourResult = tester.search("cherry pear blueberry fig blueberry", true, 10);
TestingTools.checkSearch(yourResult, "cherry pear blueberry fig blueberry", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #452 checking search results for cherry pear blueberry fig blueberry with boost=true");
//Test #453 checking search results for fig fig kiwi papaya fig with boost=true
yourResult = tester.search("fig fig kiwi papaya fig", true, 10);
TestingTools.checkSearch(yourResult, "fig fig kiwi papaya fig", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #453 checking search results for fig fig kiwi papaya fig with boost=true");
//Test #454 checking search results for tomato lime apple peach coconut with boost=true
yourResult = tester.search("tomato lime apple peach coconut", true, 10);
TestingTools.checkSearch(yourResult, "tomato lime apple peach coconut", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #454 checking search results for tomato lime apple peach coconut with boost=true");
//Test #455 checking search results for apple apricot with boost=true
yourResult = tester.search("apple apricot", true, 10);
TestingTools.checkSearch(yourResult, "apple apricot", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #455 checking search results for apple apricot with boost=true");
//Test #456 checking search results for strawberry fig apricot strawberry with boost=true
yourResult = tester.search("strawberry fig apricot strawberry", true, 10);
TestingTools.checkSearch(yourResult, "strawberry fig apricot strawberry", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #456 checking search results for strawberry fig apricot strawberry with boost=true");
//Test #457 checking search results for coconut fig coconut strawberry with boost=true
yourResult = tester.search("coconut fig coconut strawberry", true, 10);
TestingTools.checkSearch(yourResult, "coconut fig coconut strawberry", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #457 checking search results for coconut fig coconut strawberry with boost=true");
//Test #458 checking search results for peach with boost=true
yourResult = tester.search("peach", true, 10);
TestingTools.checkSearch(yourResult, "peach", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #458 checking search results for peach with boost=true");
//Test #459 checking search results for coconut banana cherry with boost=true
yourResult = tester.search("coconut banana cherry", true, 10);
TestingTools.checkSearch(yourResult, "coconut banana cherry", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #459 checking search results for coconut banana cherry with boost=true");
//Test #460 checking search results for apricot strawberry fig blueberry peach with boost=true
yourResult = tester.search("apricot strawberry fig blueberry peach", true, 10);
TestingTools.checkSearch(yourResult, "apricot strawberry fig blueberry peach", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #460 checking search results for apricot strawberry fig blueberry peach with boost=true");
//Test #461 checking search results for lime papaya apple apple fig with boost=true
yourResult = tester.search("lime papaya apple apple fig", true, 10);
TestingTools.checkSearch(yourResult, "lime papaya apple apple fig", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #461 checking search results for lime papaya apple apple fig with boost=true");
//Test #462 checking search results for blueberry banana blueberry coconut lime with boost=true
yourResult = tester.search("blueberry banana blueberry coconut lime", true, 10);
TestingTools.checkSearch(yourResult, "blueberry banana blueberry coconut lime", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #462 checking search results for blueberry banana blueberry coconut lime with boost=true");
//Test #463 checking search results for fig papaya with boost=true
yourResult = tester.search("fig papaya", true, 10);
TestingTools.checkSearch(yourResult, "fig papaya", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #463 checking search results for fig papaya with boost=true");
//Test #464 checking search results for pear kiwi with boost=true
yourResult = tester.search("pear kiwi", true, 10);
TestingTools.checkSearch(yourResult, "pear kiwi", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #464 checking search results for pear kiwi with boost=true");
//Test #465 checking search results for banana with boost=true
yourResult = tester.search("banana", true, 10);
TestingTools.checkSearch(yourResult, "banana", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #465 checking search results for banana with boost=true");
//Test #466 checking search results for apple apricot blueberry tomato with boost=true
yourResult = tester.search("apple apricot blueberry tomato", true, 10);
TestingTools.checkSearch(yourResult, "apple apricot blueberry tomato", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #466 checking search results for apple apricot blueberry tomato with boost=true");
//Test #467 checking search results for pear blueberry cherry with boost=true
yourResult = tester.search("pear blueberry cherry", true, 10);
TestingTools.checkSearch(yourResult, "pear blueberry cherry", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #467 checking search results for pear blueberry cherry with boost=true");
//Test #468 checking search results for pear pear kiwi with boost=true
yourResult = tester.search("pear pear kiwi", true, 10);
TestingTools.checkSearch(yourResult, "pear pear kiwi", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #468 checking search results for pear pear kiwi with boost=true");
//Test #469 checking search results for banana fig with boost=true
yourResult = tester.search("banana fig", true, 10);
TestingTools.checkSearch(yourResult, "banana fig", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #469 checking search results for banana fig with boost=true");
//Test #470 checking search results for strawberry apple banana with boost=true
yourResult = tester.search("strawberry apple banana", true, 10);
TestingTools.checkSearch(yourResult, "strawberry apple banana", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #470 checking search results for strawberry apple banana with boost=true");
//Test #471 checking search results for coconut fig kiwi papaya with boost=true
yourResult = tester.search("coconut fig kiwi papaya", true, 10);
TestingTools.checkSearch(yourResult, "coconut fig kiwi papaya", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #471 checking search results for coconut fig kiwi papaya with boost=true");
//Test #472 checking search results for apricot blueberry blueberry with boost=true
yourResult = tester.search("apricot blueberry blueberry", true, 10);
TestingTools.checkSearch(yourResult, "apricot blueberry blueberry", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #472 checking search results for apricot blueberry blueberry with boost=true");
//Test #473 checking search results for apricot with boost=true
yourResult = tester.search("apricot", true, 10);
TestingTools.checkSearch(yourResult, "apricot", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #473 checking search results for apricot with boost=true");
//Test #474 checking search results for blueberry apricot fig lime fig with boost=true
yourResult = tester.search("blueberry apricot fig lime fig", true, 10);
TestingTools.checkSearch(yourResult, "blueberry apricot fig lime fig", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #474 checking search results for blueberry apricot fig lime fig with boost=true");
//Test #475 checking search results for cherry banana cherry coconut apricot with boost=true
yourResult = tester.search("cherry banana cherry coconut apricot", true, 10);
TestingTools.checkSearch(yourResult, "cherry banana cherry coconut apricot", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #475 checking search results for cherry banana cherry coconut apricot with boost=true");
//Test #476 checking search results for banana with boost=true
yourResult = tester.search("banana", true, 10);
TestingTools.checkSearch(yourResult, "banana", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #476 checking search results for banana with boost=true");
//Test #477 checking search results for fig coconut with boost=true
yourResult = tester.search("fig coconut", true, 10);
TestingTools.checkSearch(yourResult, "fig coconut", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #477 checking search results for fig coconut with boost=true");
//Test #478 checking search results for papaya apricot with boost=true
yourResult = tester.search("papaya apricot", true, 10);
TestingTools.checkSearch(yourResult, "papaya apricot", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #478 checking search results for papaya apricot with boost=true");
//Test #479 checking search results for coconut with boost=true
yourResult = tester.search("coconut", true, 10);
TestingTools.checkSearch(yourResult, "coconut", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #479 checking search results for coconut with boost=true");
//Test #480 checking search results for kiwi fig coconut apple apple with boost=true
yourResult = tester.search("kiwi fig coconut apple apple", true, 10);
TestingTools.checkSearch(yourResult, "kiwi fig coconut apple apple", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #480 checking search results for kiwi fig coconut apple apple with boost=true");
//Test #481 checking search results for banana peach apple cherry with boost=true
yourResult = tester.search("banana peach apple cherry", true, 10);
TestingTools.checkSearch(yourResult, "banana peach apple cherry", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #481 checking search results for banana peach apple cherry with boost=true");
//Test #482 checking search results for apple apricot apple pear papaya with boost=true
yourResult = tester.search("apple apricot apple pear papaya", true, 10);
TestingTools.checkSearch(yourResult, "apple apricot apple pear papaya", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #482 checking search results for apple apricot apple pear papaya with boost=true");
//Test #483 checking search results for fig tomato kiwi coconut with boost=true
yourResult = tester.search("fig tomato kiwi coconut", true, 10);
TestingTools.checkSearch(yourResult, "fig tomato kiwi coconut", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #483 checking search results for fig tomato kiwi coconut with boost=true");
//Test #484 checking search results for cherry apricot strawberry banana papaya with boost=true
yourResult = tester.search("cherry apricot strawberry banana papaya", true, 10);
TestingTools.checkSearch(yourResult, "cherry apricot strawberry banana papaya", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #484 checking search results for cherry apricot strawberry banana papaya with boost=true");
//Test #485 checking search results for fig coconut fig blueberry blueberry with boost=true
yourResult = tester.search("fig coconut fig blueberry blueberry", true, 10);
TestingTools.checkSearch(yourResult, "fig coconut fig blueberry blueberry", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #485 checking search results for fig coconut fig blueberry blueberry with boost=true");
//Test #486 checking search results for banana cherry with boost=true
yourResult = tester.search("banana cherry", true, 10);
TestingTools.checkSearch(yourResult, "banana cherry", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #486 checking search results for banana cherry with boost=true");
//Test #487 checking search results for fig banana with boost=true
yourResult = tester.search("fig banana", true, 10);
TestingTools.checkSearch(yourResult, "fig banana", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #487 checking search results for fig banana with boost=true");
//Test #488 checking search results for fig papaya fig with boost=true
yourResult = tester.search("fig papaya fig", true, 10);
TestingTools.checkSearch(yourResult, "fig papaya fig", passOut, failOut, "TinyFruitsASearchBoostTester", "Test #488 checking search results for fig papaya fig with boost=true");
failOut.close();
passOut.close();
}
}
