import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.*;
public class TinyFruitsSearchNoBoostTester {public static void main(String[] args) throws Exception{
ProjectTester tester = new ProjectTesterImp(); //Instantiate your own ProjectTester instance here
tester.initialize();
tester.crawl("https://people.scs.carleton.ca/~avamckenney/tinyfruits/N-0.html");
runTest(tester);}public static void runTest(ProjectTester tester) throws Exception{
PrintWriter failOut = new PrintWriter(new FileWriter("TinyFruits-SearchNoBoost-failed.txt"));
PrintWriter passOut = new PrintWriter(new FileWriter("TinyFruits-SearchNoBoost-passed.txt"));
List<SearchResult> yourResult; 
//Test #289 checking search results for peach pear banana apricot with boost=false
yourResult = tester.search("peach pear banana apricot", false, 10);
TestingTools.checkSearch(yourResult, "peach pear banana apricot", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #289 checking search results for peach pear banana apricot with boost=false");
//Test #290 checking search results for peach coconut apple with boost=false
yourResult = tester.search("peach coconut apple", false, 10);
TestingTools.checkSearch(yourResult, "peach coconut apple", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #290 checking search results for peach coconut apple with boost=false");
//Test #291 checking search results for peach with boost=false
yourResult = tester.search("peach", false, 10);
TestingTools.checkSearch(yourResult, "peach", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #291 checking search results for peach with boost=false");
//Test #292 checking search results for cherry orange blueberry cherry with boost=false
yourResult = tester.search("cherry orange blueberry cherry", false, 10);
TestingTools.checkSearch(yourResult, "cherry orange blueberry cherry", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #292 checking search results for cherry orange blueberry cherry with boost=false");
//Test #293 checking search results for lime cherry apple with boost=false
yourResult = tester.search("lime cherry apple", false, 10);
TestingTools.checkSearch(yourResult, "lime cherry apple", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #293 checking search results for lime cherry apple with boost=false");
//Test #294 checking search results for orange coconut apple with boost=false
yourResult = tester.search("orange coconut apple", false, 10);
TestingTools.checkSearch(yourResult, "orange coconut apple", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #294 checking search results for orange coconut apple with boost=false");
//Test #295 checking search results for apple coconut fig with boost=false
yourResult = tester.search("apple coconut fig", false, 10);
TestingTools.checkSearch(yourResult, "apple coconut fig", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #295 checking search results for apple coconut fig with boost=false");
//Test #296 checking search results for orange pear pear peach pear with boost=false
yourResult = tester.search("orange pear pear peach pear", false, 10);
TestingTools.checkSearch(yourResult, "orange pear pear peach pear", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #296 checking search results for orange pear pear peach pear with boost=false");
//Test #297 checking search results for papaya lime apricot lime orange with boost=false
yourResult = tester.search("papaya lime apricot lime orange", false, 10);
TestingTools.checkSearch(yourResult, "papaya lime apricot lime orange", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #297 checking search results for papaya lime apricot lime orange with boost=false");
//Test #298 checking search results for kiwi apricot with boost=false
yourResult = tester.search("kiwi apricot", false, 10);
TestingTools.checkSearch(yourResult, "kiwi apricot", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #298 checking search results for kiwi apricot with boost=false");
//Test #299 checking search results for cherry apple apricot with boost=false
yourResult = tester.search("cherry apple apricot", false, 10);
TestingTools.checkSearch(yourResult, "cherry apple apricot", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #299 checking search results for cherry apple apricot with boost=false");
//Test #300 checking search results for apple papaya tomato banana with boost=false
yourResult = tester.search("apple papaya tomato banana", false, 10);
TestingTools.checkSearch(yourResult, "apple papaya tomato banana", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #300 checking search results for apple papaya tomato banana with boost=false");
//Test #301 checking search results for tomato apple fig with boost=false
yourResult = tester.search("tomato apple fig", false, 10);
TestingTools.checkSearch(yourResult, "tomato apple fig", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #301 checking search results for tomato apple fig with boost=false");
//Test #302 checking search results for apricot coconut lime papaya with boost=false
yourResult = tester.search("apricot coconut lime papaya", false, 10);
TestingTools.checkSearch(yourResult, "apricot coconut lime papaya", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #302 checking search results for apricot coconut lime papaya with boost=false");
//Test #303 checking search results for lime with boost=false
yourResult = tester.search("lime", false, 10);
TestingTools.checkSearch(yourResult, "lime", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #303 checking search results for lime with boost=false");
//Test #304 checking search results for cherry tomato apricot lime tomato with boost=false
yourResult = tester.search("cherry tomato apricot lime tomato", false, 10);
TestingTools.checkSearch(yourResult, "cherry tomato apricot lime tomato", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #304 checking search results for cherry tomato apricot lime tomato with boost=false");
//Test #305 checking search results for fig apricot peach papaya orange with boost=false
yourResult = tester.search("fig apricot peach papaya orange", false, 10);
TestingTools.checkSearch(yourResult, "fig apricot peach papaya orange", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #305 checking search results for fig apricot peach papaya orange with boost=false");
//Test #306 checking search results for coconut kiwi with boost=false
yourResult = tester.search("coconut kiwi", false, 10);
TestingTools.checkSearch(yourResult, "coconut kiwi", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #306 checking search results for coconut kiwi with boost=false");
//Test #307 checking search results for apple pear papaya orange papaya with boost=false
yourResult = tester.search("apple pear papaya orange papaya", false, 10);
TestingTools.checkSearch(yourResult, "apple pear papaya orange papaya", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #307 checking search results for apple pear papaya orange papaya with boost=false");
//Test #308 checking search results for apple tomato cherry with boost=false
yourResult = tester.search("apple tomato cherry", false, 10);
TestingTools.checkSearch(yourResult, "apple tomato cherry", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #308 checking search results for apple tomato cherry with boost=false");
//Test #309 checking search results for peach peach with boost=false
yourResult = tester.search("peach peach", false, 10);
TestingTools.checkSearch(yourResult, "peach peach", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #309 checking search results for peach peach with boost=false");
//Test #310 checking search results for lime coconut with boost=false
yourResult = tester.search("lime coconut", false, 10);
TestingTools.checkSearch(yourResult, "lime coconut", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #310 checking search results for lime coconut with boost=false");
//Test #311 checking search results for cherry apricot with boost=false
yourResult = tester.search("cherry apricot", false, 10);
TestingTools.checkSearch(yourResult, "cherry apricot", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #311 checking search results for cherry apricot with boost=false");
//Test #312 checking search results for tomato apricot coconut apricot fig with boost=false
yourResult = tester.search("tomato apricot coconut apricot fig", false, 10);
TestingTools.checkSearch(yourResult, "tomato apricot coconut apricot fig", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #312 checking search results for tomato apricot coconut apricot fig with boost=false");
//Test #313 checking search results for coconut fig coconut peach with boost=false
yourResult = tester.search("coconut fig coconut peach", false, 10);
TestingTools.checkSearch(yourResult, "coconut fig coconut peach", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #313 checking search results for coconut fig coconut peach with boost=false");
//Test #314 checking search results for blueberry fig coconut peach with boost=false
yourResult = tester.search("blueberry fig coconut peach", false, 10);
TestingTools.checkSearch(yourResult, "blueberry fig coconut peach", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #314 checking search results for blueberry fig coconut peach with boost=false");
//Test #315 checking search results for apple pear peach peach pear with boost=false
yourResult = tester.search("apple pear peach peach pear", false, 10);
TestingTools.checkSearch(yourResult, "apple pear peach peach pear", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #315 checking search results for apple pear peach peach pear with boost=false");
//Test #316 checking search results for kiwi kiwi cherry orange banana with boost=false
yourResult = tester.search("kiwi kiwi cherry orange banana", false, 10);
TestingTools.checkSearch(yourResult, "kiwi kiwi cherry orange banana", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #316 checking search results for kiwi kiwi cherry orange banana with boost=false");
//Test #317 checking search results for fig fig papaya with boost=false
yourResult = tester.search("fig fig papaya", false, 10);
TestingTools.checkSearch(yourResult, "fig fig papaya", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #317 checking search results for fig fig papaya with boost=false");
//Test #318 checking search results for blueberry pear pear cherry with boost=false
yourResult = tester.search("blueberry pear pear cherry", false, 10);
TestingTools.checkSearch(yourResult, "blueberry pear pear cherry", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #318 checking search results for blueberry pear pear cherry with boost=false");
//Test #319 checking search results for kiwi coconut kiwi apple kiwi with boost=false
yourResult = tester.search("kiwi coconut kiwi apple kiwi", false, 10);
TestingTools.checkSearch(yourResult, "kiwi coconut kiwi apple kiwi", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #319 checking search results for kiwi coconut kiwi apple kiwi with boost=false");
//Test #320 checking search results for tomato apricot kiwi orange with boost=false
yourResult = tester.search("tomato apricot kiwi orange", false, 10);
TestingTools.checkSearch(yourResult, "tomato apricot kiwi orange", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #320 checking search results for tomato apricot kiwi orange with boost=false");
//Test #321 checking search results for apricot lime with boost=false
yourResult = tester.search("apricot lime", false, 10);
TestingTools.checkSearch(yourResult, "apricot lime", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #321 checking search results for apricot lime with boost=false");
//Test #322 checking search results for cherry apricot tomato with boost=false
yourResult = tester.search("cherry apricot tomato", false, 10);
TestingTools.checkSearch(yourResult, "cherry apricot tomato", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #322 checking search results for cherry apricot tomato with boost=false");
//Test #323 checking search results for banana kiwi orange peach with boost=false
yourResult = tester.search("banana kiwi orange peach", false, 10);
TestingTools.checkSearch(yourResult, "banana kiwi orange peach", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #323 checking search results for banana kiwi orange peach with boost=false");
//Test #324 checking search results for peach blueberry apricot papaya banana with boost=false
yourResult = tester.search("peach blueberry apricot papaya banana", false, 10);
TestingTools.checkSearch(yourResult, "peach blueberry apricot papaya banana", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #324 checking search results for peach blueberry apricot papaya banana with boost=false");
//Test #325 checking search results for papaya papaya papaya with boost=false
yourResult = tester.search("papaya papaya papaya", false, 10);
TestingTools.checkSearch(yourResult, "papaya papaya papaya", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #325 checking search results for papaya papaya papaya with boost=false");
//Test #326 checking search results for lime apricot orange with boost=false
yourResult = tester.search("lime apricot orange", false, 10);
TestingTools.checkSearch(yourResult, "lime apricot orange", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #326 checking search results for lime apricot orange with boost=false");
//Test #327 checking search results for cherry with boost=false
yourResult = tester.search("cherry", false, 10);
TestingTools.checkSearch(yourResult, "cherry", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #327 checking search results for cherry with boost=false");
//Test #328 checking search results for banana fig with boost=false
yourResult = tester.search("banana fig", false, 10);
TestingTools.checkSearch(yourResult, "banana fig", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #328 checking search results for banana fig with boost=false");
//Test #329 checking search results for banana coconut blueberry apple with boost=false
yourResult = tester.search("banana coconut blueberry apple", false, 10);
TestingTools.checkSearch(yourResult, "banana coconut blueberry apple", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #329 checking search results for banana coconut blueberry apple with boost=false");
//Test #330 checking search results for peach apricot pear tomato peach with boost=false
yourResult = tester.search("peach apricot pear tomato peach", false, 10);
TestingTools.checkSearch(yourResult, "peach apricot pear tomato peach", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #330 checking search results for peach apricot pear tomato peach with boost=false");
//Test #331 checking search results for fig with boost=false
yourResult = tester.search("fig", false, 10);
TestingTools.checkSearch(yourResult, "fig", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #331 checking search results for fig with boost=false");
//Test #332 checking search results for apricot lime peach with boost=false
yourResult = tester.search("apricot lime peach", false, 10);
TestingTools.checkSearch(yourResult, "apricot lime peach", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #332 checking search results for apricot lime peach with boost=false");
//Test #333 checking search results for kiwi coconut with boost=false
yourResult = tester.search("kiwi coconut", false, 10);
TestingTools.checkSearch(yourResult, "kiwi coconut", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #333 checking search results for kiwi coconut with boost=false");
//Test #334 checking search results for pear banana blueberry fig cherry with boost=false
yourResult = tester.search("pear banana blueberry fig cherry", false, 10);
TestingTools.checkSearch(yourResult, "pear banana blueberry fig cherry", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #334 checking search results for pear banana blueberry fig cherry with boost=false");
//Test #335 checking search results for coconut tomato fig with boost=false
yourResult = tester.search("coconut tomato fig", false, 10);
TestingTools.checkSearch(yourResult, "coconut tomato fig", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #335 checking search results for coconut tomato fig with boost=false");
//Test #336 checking search results for coconut with boost=false
yourResult = tester.search("coconut", false, 10);
TestingTools.checkSearch(yourResult, "coconut", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #336 checking search results for coconut with boost=false");
//Test #337 checking search results for orange apple with boost=false
yourResult = tester.search("orange apple", false, 10);
TestingTools.checkSearch(yourResult, "orange apple", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #337 checking search results for orange apple with boost=false");
//Test #338 checking search results for lime lime with boost=false
yourResult = tester.search("lime lime", false, 10);
TestingTools.checkSearch(yourResult, "lime lime", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #338 checking search results for lime lime with boost=false");
//Test #339 checking search results for kiwi cherry orange with boost=false
yourResult = tester.search("kiwi cherry orange", false, 10);
TestingTools.checkSearch(yourResult, "kiwi cherry orange", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #339 checking search results for kiwi cherry orange with boost=false");
//Test #340 checking search results for kiwi banana apple pear coconut with boost=false
yourResult = tester.search("kiwi banana apple pear coconut", false, 10);
TestingTools.checkSearch(yourResult, "kiwi banana apple pear coconut", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #340 checking search results for kiwi banana apple pear coconut with boost=false");
//Test #341 checking search results for apricot coconut with boost=false
yourResult = tester.search("apricot coconut", false, 10);
TestingTools.checkSearch(yourResult, "apricot coconut", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #341 checking search results for apricot coconut with boost=false");
//Test #342 checking search results for blueberry coconut with boost=false
yourResult = tester.search("blueberry coconut", false, 10);
TestingTools.checkSearch(yourResult, "blueberry coconut", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #342 checking search results for blueberry coconut with boost=false");
//Test #343 checking search results for peach fig blueberry blueberry apricot with boost=false
yourResult = tester.search("peach fig blueberry blueberry apricot", false, 10);
TestingTools.checkSearch(yourResult, "peach fig blueberry blueberry apricot", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #343 checking search results for peach fig blueberry blueberry apricot with boost=false");
//Test #344 checking search results for lime cherry fig cherry with boost=false
yourResult = tester.search("lime cherry fig cherry", false, 10);
TestingTools.checkSearch(yourResult, "lime cherry fig cherry", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #344 checking search results for lime cherry fig cherry with boost=false");
//Test #345 checking search results for fig with boost=false
yourResult = tester.search("fig", false, 10);
TestingTools.checkSearch(yourResult, "fig", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #345 checking search results for fig with boost=false");
//Test #346 checking search results for coconut coconut with boost=false
yourResult = tester.search("coconut coconut", false, 10);
TestingTools.checkSearch(yourResult, "coconut coconut", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #346 checking search results for coconut coconut with boost=false");
//Test #347 checking search results for fig papaya papaya with boost=false
yourResult = tester.search("fig papaya papaya", false, 10);
TestingTools.checkSearch(yourResult, "fig papaya papaya", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #347 checking search results for fig papaya papaya with boost=false");
//Test #348 checking search results for papaya orange cherry coconut papaya with boost=false
yourResult = tester.search("papaya orange cherry coconut papaya", false, 10);
TestingTools.checkSearch(yourResult, "papaya orange cherry coconut papaya", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #348 checking search results for papaya orange cherry coconut papaya with boost=false");
//Test #349 checking search results for orange fig apple with boost=false
yourResult = tester.search("orange fig apple", false, 10);
TestingTools.checkSearch(yourResult, "orange fig apple", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #349 checking search results for orange fig apple with boost=false");
//Test #350 checking search results for papaya blueberry kiwi with boost=false
yourResult = tester.search("papaya blueberry kiwi", false, 10);
TestingTools.checkSearch(yourResult, "papaya blueberry kiwi", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #350 checking search results for papaya blueberry kiwi with boost=false");
//Test #351 checking search results for papaya papaya apricot fig with boost=false
yourResult = tester.search("papaya papaya apricot fig", false, 10);
TestingTools.checkSearch(yourResult, "papaya papaya apricot fig", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #351 checking search results for papaya papaya apricot fig with boost=false");
//Test #352 checking search results for banana blueberry with boost=false
yourResult = tester.search("banana blueberry", false, 10);
TestingTools.checkSearch(yourResult, "banana blueberry", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #352 checking search results for banana blueberry with boost=false");
//Test #353 checking search results for papaya banana with boost=false
yourResult = tester.search("papaya banana", false, 10);
TestingTools.checkSearch(yourResult, "papaya banana", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #353 checking search results for papaya banana with boost=false");
//Test #354 checking search results for coconut cherry with boost=false
yourResult = tester.search("coconut cherry", false, 10);
TestingTools.checkSearch(yourResult, "coconut cherry", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #354 checking search results for coconut cherry with boost=false");
//Test #355 checking search results for fig peach kiwi with boost=false
yourResult = tester.search("fig peach kiwi", false, 10);
TestingTools.checkSearch(yourResult, "fig peach kiwi", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #355 checking search results for fig peach kiwi with boost=false");
//Test #356 checking search results for peach with boost=false
yourResult = tester.search("peach", false, 10);
TestingTools.checkSearch(yourResult, "peach", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #356 checking search results for peach with boost=false");
//Test #357 checking search results for fig orange fig papaya with boost=false
yourResult = tester.search("fig orange fig papaya", false, 10);
TestingTools.checkSearch(yourResult, "fig orange fig papaya", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #357 checking search results for fig orange fig papaya with boost=false");
//Test #358 checking search results for pear lime kiwi with boost=false
yourResult = tester.search("pear lime kiwi", false, 10);
TestingTools.checkSearch(yourResult, "pear lime kiwi", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #358 checking search results for pear lime kiwi with boost=false");
//Test #359 checking search results for papaya with boost=false
yourResult = tester.search("papaya", false, 10);
TestingTools.checkSearch(yourResult, "papaya", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #359 checking search results for papaya with boost=false");
//Test #360 checking search results for blueberry cherry tomato pear with boost=false
yourResult = tester.search("blueberry cherry tomato pear", false, 10);
TestingTools.checkSearch(yourResult, "blueberry cherry tomato pear", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #360 checking search results for blueberry cherry tomato pear with boost=false");
//Test #361 checking search results for orange orange tomato coconut banana with boost=false
yourResult = tester.search("orange orange tomato coconut banana", false, 10);
TestingTools.checkSearch(yourResult, "orange orange tomato coconut banana", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #361 checking search results for orange orange tomato coconut banana with boost=false");
//Test #362 checking search results for apple with boost=false
yourResult = tester.search("apple", false, 10);
TestingTools.checkSearch(yourResult, "apple", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #362 checking search results for apple with boost=false");
//Test #363 checking search results for papaya apple with boost=false
yourResult = tester.search("papaya apple", false, 10);
TestingTools.checkSearch(yourResult, "papaya apple", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #363 checking search results for papaya apple with boost=false");
//Test #364 checking search results for blueberry apricot with boost=false
yourResult = tester.search("blueberry apricot", false, 10);
TestingTools.checkSearch(yourResult, "blueberry apricot", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #364 checking search results for blueberry apricot with boost=false");
//Test #365 checking search results for pear with boost=false
yourResult = tester.search("pear", false, 10);
TestingTools.checkSearch(yourResult, "pear", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #365 checking search results for pear with boost=false");
//Test #366 checking search results for apple tomato apricot with boost=false
yourResult = tester.search("apple tomato apricot", false, 10);
TestingTools.checkSearch(yourResult, "apple tomato apricot", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #366 checking search results for apple tomato apricot with boost=false");
//Test #367 checking search results for apple with boost=false
yourResult = tester.search("apple", false, 10);
TestingTools.checkSearch(yourResult, "apple", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #367 checking search results for apple with boost=false");
//Test #368 checking search results for kiwi papaya with boost=false
yourResult = tester.search("kiwi papaya", false, 10);
TestingTools.checkSearch(yourResult, "kiwi papaya", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #368 checking search results for kiwi papaya with boost=false");
//Test #369 checking search results for apple kiwi with boost=false
yourResult = tester.search("apple kiwi", false, 10);
TestingTools.checkSearch(yourResult, "apple kiwi", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #369 checking search results for apple kiwi with boost=false");
//Test #370 checking search results for blueberry kiwi pear with boost=false
yourResult = tester.search("blueberry kiwi pear", false, 10);
TestingTools.checkSearch(yourResult, "blueberry kiwi pear", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #370 checking search results for blueberry kiwi pear with boost=false");
//Test #371 checking search results for apricot papaya coconut banana with boost=false
yourResult = tester.search("apricot papaya coconut banana", false, 10);
TestingTools.checkSearch(yourResult, "apricot papaya coconut banana", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #371 checking search results for apricot papaya coconut banana with boost=false");
//Test #372 checking search results for papaya pear cherry with boost=false
yourResult = tester.search("papaya pear cherry", false, 10);
TestingTools.checkSearch(yourResult, "papaya pear cherry", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #372 checking search results for papaya pear cherry with boost=false");
//Test #373 checking search results for banana blueberry with boost=false
yourResult = tester.search("banana blueberry", false, 10);
TestingTools.checkSearch(yourResult, "banana blueberry", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #373 checking search results for banana blueberry with boost=false");
//Test #374 checking search results for coconut fig papaya banana with boost=false
yourResult = tester.search("coconut fig papaya banana", false, 10);
TestingTools.checkSearch(yourResult, "coconut fig papaya banana", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #374 checking search results for coconut fig papaya banana with boost=false");
//Test #375 checking search results for apple orange papaya with boost=false
yourResult = tester.search("apple orange papaya", false, 10);
TestingTools.checkSearch(yourResult, "apple orange papaya", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #375 checking search results for apple orange papaya with boost=false");
//Test #376 checking search results for coconut orange pear papaya with boost=false
yourResult = tester.search("coconut orange pear papaya", false, 10);
TestingTools.checkSearch(yourResult, "coconut orange pear papaya", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #376 checking search results for coconut orange pear papaya with boost=false");
//Test #377 checking search results for cherry papaya blueberry with boost=false
yourResult = tester.search("cherry papaya blueberry", false, 10);
TestingTools.checkSearch(yourResult, "cherry papaya blueberry", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #377 checking search results for cherry papaya blueberry with boost=false");
//Test #378 checking search results for orange with boost=false
yourResult = tester.search("orange", false, 10);
TestingTools.checkSearch(yourResult, "orange", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #378 checking search results for orange with boost=false");
//Test #379 checking search results for fig with boost=false
yourResult = tester.search("fig", false, 10);
TestingTools.checkSearch(yourResult, "fig", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #379 checking search results for fig with boost=false");
//Test #380 checking search results for blueberry with boost=false
yourResult = tester.search("blueberry", false, 10);
TestingTools.checkSearch(yourResult, "blueberry", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #380 checking search results for blueberry with boost=false");
//Test #381 checking search results for papaya apple with boost=false
yourResult = tester.search("papaya apple", false, 10);
TestingTools.checkSearch(yourResult, "papaya apple", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #381 checking search results for papaya apple with boost=false");
//Test #382 checking search results for fig coconut fig tomato with boost=false
yourResult = tester.search("fig coconut fig tomato", false, 10);
TestingTools.checkSearch(yourResult, "fig coconut fig tomato", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #382 checking search results for fig coconut fig tomato with boost=false");
//Test #383 checking search results for coconut apple banana lime apple with boost=false
yourResult = tester.search("coconut apple banana lime apple", false, 10);
TestingTools.checkSearch(yourResult, "coconut apple banana lime apple", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #383 checking search results for coconut apple banana lime apple with boost=false");
//Test #384 checking search results for banana orange cherry apple with boost=false
yourResult = tester.search("banana orange cherry apple", false, 10);
TestingTools.checkSearch(yourResult, "banana orange cherry apple", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #384 checking search results for banana orange cherry apple with boost=false");
//Test #385 checking search results for papaya with boost=false
yourResult = tester.search("papaya", false, 10);
TestingTools.checkSearch(yourResult, "papaya", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #385 checking search results for papaya with boost=false");
//Test #386 checking search results for pear with boost=false
yourResult = tester.search("pear", false, 10);
TestingTools.checkSearch(yourResult, "pear", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #386 checking search results for pear with boost=false");
//Test #387 checking search results for apple papaya banana with boost=false
yourResult = tester.search("apple papaya banana", false, 10);
TestingTools.checkSearch(yourResult, "apple papaya banana", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #387 checking search results for apple papaya banana with boost=false");
//Test #388 checking search results for fig peach coconut peach blueberry with boost=false
yourResult = tester.search("fig peach coconut peach blueberry", false, 10);
TestingTools.checkSearch(yourResult, "fig peach coconut peach blueberry", passOut, failOut, "TinyFruitsSearchNoBoostTester", "Test #388 checking search results for fig peach coconut peach blueberry with boost=false");
failOut.close();
passOut.close();
}
}
